### ISSUE TITLE
[Bug]: Version 2.7.0 extra75 reports default SecurityGroups as unused

### ISSUE THREAD

**Issue by jansepke** [toniblyx/prowler#1001]
**What happened?**  
After upgrading to prowler 2.7.0 existing default SecurityGroups that are not being used are now a failure in extra75 check. Before this version it was only an INFO.

**Expected behavior**  
7.5 [extra75] Ensure there are no Security Groups not being used - ec2 [Informational]
       INFO! eu-central-1: sg-XYZ is not being used - default security group 

**Actual behavior**  
7.5 [extra75] Ensure there are no Security Groups not being used - ec2 [Informational]
       FAIL! eu-central-1: sg-XYZ is not being used!

**From where are you running Prowler?**  
Please, complete the following information:
 - Resource: EC2 instance
 - OS: Amazon Linux 2
 - AWS-CLI Version [`aws --version`]: 1.22.42
 - Prowler Version [`./prowler -V`]: 2.7.0
 - Shell and version: bash
 - Others:

**Comment by toniblyx** [comment]
I think there is a misunderstanding here, this check has worked that way since it was written. If a SG is not in use it is a FAIL.

**Comment by jansepke** [comment]
OK I found the bug: this commit 2b2814723ffc84495f7af928a5f381bed978dd6d changed the content of the variables, I will create a PR to fix it.
