### ISSUE TITLE
[Bug]: Version 2.7.0 extra793 fails for network LBs

### ISSUE THREAD

**Issue by jansepke** [toniblyx/prowler#1002]
**What happened?**  
After upgrading to prowler 2.7.0 existing network LBs are now reported aus failure from extra793. Network LBs where skipped before this version. This was introduced by a copy past mistake in https://github.com/prowler-cloud/prowler/commit/7b848c04c417b44b5fa7db8e4ee9a6e8af79e686#diff-b1664cb40c3cbbbda77c412cc03924209c78e46bbb71967b64701b079f902b71

**Expected behavior**  
7.93 [extra793] Check if Elastic Load Balancers have SSL listeners  - elb [Medium]

**Actual behavior**  
7.93 [extra793] Check if Elastic Load Balancers have SSL listeners  - elb [Medium]
       FAIL! eu-central-1:  has non-encrypted listeners 

**From where are you running Prowler?**  
Please, complete the following information:
 - Resource: EC2 instance
 - OS: Amazon Linux 2
 - AWS-CLI Version [`aws --version`]: 1.22.42
 - Prowler Version [`./prowler -V`]: 2.7.0
 - Shell and version: bash
 - Others:

**Comment by toniblyx** [comment]
It is now fixed in master. Thanks for the heads up.

**Comment by jansepke** [comment]
@toniblyx sorry, I noticed a different line and created another PR to fix this

**Comment by toniblyx** [comment]
I see, thanks!

**Comment by jansepke** [comment]
@toniblyx is there any planned release date for a 2.7.1 version? I don't want to use master...

**Comment by toniblyx** [comment]
Let´s see if we can fix some more issues and we make the minor release. We will check it out later this week.
