### ISSUE TITLE
[Bug]: Failing to send check output to AWS Security Hub due to wrong region

### ISSUE THREAD

**Issue by dlorch** [toniblyx/prowler#1011]
**What happened?**  
A clear and concise description of what the bug is or what is not working as expected

Given a SecurityHub enabled in `eu-central-1` and the prower command line `./prowler/prowler -R "$ROLE" -A "$accountId" -r eu-central-1 -f eu-central-1 -g cislevel -w whitelist.txt -M json-asff -q -S`, some checks fail to upload their results to Security Hub, as they send it to the wrong region.

Two reasons could be found:
* in some checks, the region is hardcoded to `us-east-1` (e.g. `check_extra764`)
* in other checks, the region of the resource is considered and the check results are sent to Security Hub of that given region

**How to reproduce it**  
1. What command are you running?

SecurityHub enabled in `eu-central-1` and the prower command line `./prowler/prowler -R "$ROLE" -A "$accountId" -r eu-central-1 -f eu-central-1 -g healthcare-kickstarter -w whitelist.txt -M json-asff -q -S`

2. Environment you have, like single account, multi-account, organizations, etc.

Multi-account, serverless setup using CodeBuild.

3. See error

Various errors, e.g.

```
7.64 [extra764] Check if S3 buckets have secure transport policy  - s3 [Medium]

An error occurred (AccessDeniedException) when calling the BatchImportFindings operation: User: arn:aws:sts::1234567890:assumed-role/ProwlerXA-CBRole/ProwlerAssessmentSession is not authorized to perform: securityhub:BatchImportFindings on resource: arn:aws:securityhub:us-east-1::product/prowler/prowler

ERROR! Failed to send check output to AWS Security Hub

FAIL! Bucket stackset-customcontroltower-stno-hub-6-logsbucket-kdwod1kqel6z allows requests over insecure transport
```

or

```
7.34 [extra734] Check if S3 buckets have default encryption (SSE) enabled or use a bucket policy to enforce it - s3 [Medium]

Provided region_name '
An error occurred (AccessDenied) when calling the GetBucketLocation operation: Access Denied' doesn't match a supported format.
 ERROR! Failed to send check output to AWS Security Hub
       FAIL!
An error occurred (AccessDenied) when calling the GetBucketLocation operation: Access Denied Access Denied Trying to Get Bucket Location for aws-controltower-logs-1234567890-eu-central-1
Provided region_name '
An error occurred (AccessDenied) when calling the GetBucketLocation operation: Access Denied' doesn't match a supported format.
 ERROR! Failed to send check output to AWS Security Hub
       FAIL!
An error occurred (AccessDenied) when calling the GetBucketLocation operation: Access Denied Access Denied Trying to Get Bucket Location for aws-controltower-s3-access-logs-1234567890-eu-central-1
```

or

```
7.64 [extra764] Check if S3 buckets have secure transport policy  - s3 [Medium]
       FAIL! Access Denied Trying to Get Bucket Location for aws-controltower-logs-1234567890-eu-central-1
       FAIL! Access Denied Trying to Get Bucket Location for aws-controltower-s3-access-logs-1234567890-eu-central-1
An error occurred (AccessDeniedException) when calling the BatchImportFindings operation: User: arn:aws:sts::1234567890:assumed-role/ProwlerXA-CBRole/ProwlerAssessmentSession is not authorized to perform: securityhub:BatchImportFindings on resource: arn:aws:securityhub:us-east-1::product/prowler/prowler
 ERROR! Failed to send check output to AWS Security Hub
       FAIL! No bucket policy for cf-templates-ferfvert4h8s8o-eu-central-1
```

Note: some identifiers (Account ID etc.) have been anonymized in the excerpts above.

**Expected behavior**  

Results sent to Security Hub in home region `eu-central-1`.

**Screenshots or Logs**  

See errors above.

**From where are you running Prowler?**  
Please, complete the following information:
 - Resource: CodeBuild
 - OS: Amazon Linux 2
 - AWS-CLI Version [`aws --version`]:
 - Prowler Version `Prowler 2.7.0-24January2022`
 - Shell and version:
 - Others:

**Additional context**

I started preparing a pull-request and replaced some of the hardcoded values, but then realized that I did not have the full picture of how regions are intended to be used in the prowler code: is it the resource region that goes into the report, or does it have some other meaning? It's probably best if you review that, having the full understanding of the code.

**Comment by n4ch04** [comment]
Hi @dlorch  we are going to review it and give you a solution asap!!
Thank you for your contribution

**Comment by n4ch04** [comment]
Hi @dlorch we have been reviewed the content of the check extra764 and made a few changes, please check it out at #1089 .
Regarding the SecurityHub issues, we think you need to check the configuration you have in your AWS account.
Prowler's Security Hub integration works if you have enabled Security Hub with Prowler integration in each region you want to ingest findings from. 
Security Hub auto populates the region automatically for each finding (https://docs.aws.amazon.com/cli/latest/reference/securityhub/batch-import-findings.html) so, even if you are dealing with a global service (like s3) Security Hub assigns the region for the s3 bucket finding.
If you don't have Security Hub enabled in that region with Prowler integration prowler is going to return an error.
Regarding the examples of check extra764 you provided, you would need to enable Security Hub with the Prowler integration in region `us-east-1` to solve that issue.

I'am seeing right now the errors in check extra734 right now, I'am going to review it and let you know, in the meantime, please, could you test the above solution?

**Comment by n4ch04** [comment]
Check extra74 does not generate errors for me, please check the above solution regarding security hub ingestion and let us know if everything is ok

**Comment by n4ch04** [comment]
We are going to close this one, please @dlorch  feel free to open if you experiment any new issues.
Thanks for your contribution !!!

**Comment by lorchda** [comment]
Thank you @n4ch04! The issue was resolved with this commit:

https://github.com/prowler-cloud/prowler/commit/198c7f48ca0df6cb82107315a3771a680dcf3abe

In the previous code, the region was hard-coded to `us-east-1`, see here:

```
           textFail "Bucket $bucket allows requests over insecure transport" "us-east-1" "$bucket"
```

The region parameter (here `us-east-1`) is passed down to the function `textFail` https://github.com/prowler-cloud/prowler/blob/03b1c10d13dddcd572d49fe9098e70732bd7616e/include/outputs#L234-L239

which in turn passes it down to `general_output` https://github.com/prowler-cloud/prowler/blob/03b1c10d13dddcd572d49fe9098e70732bd7616e/include/outputs#L127-L132

which in turns then sends it to SecurityHub in the line:

```
sendToSecurityHub "${JSON_ASFF_OUTPUT}" "${REGION_FROM_CHECK}"
```

In `sendToSecurityHub`: https://github.com/prowler-cloud/prowler/blob/03b1c10d13dddcd572d49fe9098e70732bd7616e/include/securityhub_integration#L89-L92

This then sends it to SecurityHub in the region `us-east-1`, independent of the actual region of the S3 resource:

```
  BATCH_IMPORT_RESULT=$($AWSCLI securityhub --region "$region" $PROFILE_OPT batch-import-findings --findings "${findings}" 2>&1)
```
