### ISSUE TITLE
[Bug]: [extra7141] Find secrets in SSM Documents - ssm - AccessDeniedException

### ISSUE THREAD

**Issue by lazize** [toniblyx/prowler#1016]
**What happened?**  
On stdout file it shows this error message below. Just after the error it says the check PASS, so it is a false positive.  
Also, which permission is missing?

```shell
7.141 [extra7141] Find secrets in SSM Documents - ssm [Critical]
       INFO! eu-north-1: No SSM Document found.
       INFO! ap-south-1: No SSM Document found.
       INFO! eu-west-3: No SSM Document found.
       INFO! eu-west-2: No SSM Document found.
       INFO! eu-west-1: No SSM Document found.
       INFO! ap-northeast-3: No SSM Document found.
       INFO! ap-northeast-2: No SSM Document found.
       INFO! ap-northeast-1: No SSM Document found.

An error occurred (AccessDeniedException) when calling the GetDocument operation: User: arn:aws:sts::123412341234:assumed-role/ProwlerExecRole/ProwlerAssessmentSession is not authorized to perform: ssm:GetDocument on resource: arn:aws:ssm:sa-east-1:123412341234:document/AWSQuickSetup-CreateAndAttachIAMToInstance-5v3z8 because no identity-based policy allows the ssm:GetDocument action
       PASS! sa-east-1: No secrets found in SSM Document AWSQuickSetup-CreateAndAttachIAMToInstance-5v3z8
```

A clear and concise description of what the bug is or what is not working as expected

**How to reproduce it**  
1. What command are you running? : `-R ProwlerExecRole -A 123412341234 -M csv,html -T 43200`
2. Environment you have, like single account, multi-account, organizations, etc. : `organizations`
3. See error above

**Expected behavior**  

**Screenshots or Logs**  
Also, you can add logs (anonymize them first!). Here a command that may help to share a log
`bash -x ./prowler -options > debug.log 2>&1` then attach here `debug.log`

**From where are you running Prowler?**  
Please, complete the following information:
 - Resource: EC2 instance 
 - OS: Amazon Linux 2
 - AWS-CLI Version [`aws --version`]: `aws-cli/2.4.15 Python/3.8.8 Linux/4.14.256-197.484.amzn2.x86_64 exe/x86_64.amzn.2 prompt/off`
 - Prowler Version [`./prowler -V`]: `v2.7.0-24January2022`
 - Shell and version: `GNU bash, version 4.2.46(2)-release (x86_64-koji-linux-gnu)`
 - Others:

**Additional context**

**Comment by lazize** [comment]
Action `ssm:GetDocument` is not available in any managed or inline policy defined on role `ProwlerExecRole`

**Comment by jfagoagas** [comment]
Thank you @lazize
