### ISSUE TITLE
[Bug]: [extra7148] Check if EFS File systems have backup enabled - efs - AccessDeniedException

### ISSUE THREAD

**Issue by lazize** [toniblyx/prowler#1017]
**What happened?**  
Missing permission for `ProwlerExecRole`. Action `elasticfilesystem:DescribeBackupPolicy` is not available on any managed or inline policy.  
Check PASS after an exception, which is a false positive.

```shell
7.148 [extra7148] Check if EFS File systems have backup enabled - efs [Medium]
       INFO! eu-north-1: No EFS File systems found
       INFO! ap-south-1: No EFS File systems found
       INFO! eu-west-3: No EFS File systems found
       INFO! eu-west-2: No EFS File systems found
       INFO! eu-west-1: No EFS File systems found
       INFO! ap-northeast-3: No EFS File systems found
       INFO! ap-northeast-2: No EFS File systems found
       INFO! ap-northeast-1: No EFS File systems found

An error occurred (AccessDeniedException) when calling the DescribeBackupPolicy operation: User: arn:aws:sts::123412341234:assumed-role/ProwlerExecRole/ProwlerAssessmentSession is not authorized to perform: elasticfilesystem:DescribeBackupPolicy on the specified resource
       PASS! sa-east-1: EFS File system fs-abcdef12345 has backup enabled
```

**How to reproduce it**  
1. What command are you running? : `-R ProwlerExecRole -A 123412341234 -M csv,html -T 43200`
2. Environment you have, like single account, multi-account, organizations, etc. : `organizations`
3. See error above

**Expected behavior**  

**Screenshots or Logs**  
Also, you can add logs (anonymize them first!). Here a command that may help to share a log
`bash -x ./prowler -options > debug.log 2>&1` then attach here `debug.log`

**From where are you running Prowler?**  
Please, complete the following information:
 - Resource: EC2 instance
 - OS: Amazon Linux 2
 - AWS-CLI Version [`aws --version`]: `aws-cli/2.4.15 Python/3.8.8 Linux/4.14.256-197.484.amzn2.x86_64 exe/x86_64.amzn.2 prompt/off`
 - Prowler Version [`./prowler -V`]: `v2.7.0-24January2022`
 - Shell and version: `GNU bash, version 4.2.46(2)-release (x86_64-koji-linux-gnu)`
 - Others:

**Additional context**

**Comment by toniblyx** [comment]
arn:aws:iam::aws:policy/SecurityAudit does not include `elasticfilesystem:DescribeBackupPolicy` so it has to be included in the prowler required references. Also additional error handling has to be included in the check
