### ISSUE TITLE
[Bug]: [extra771] Generates CSV file with multiple-lines

### ISSUE THREAD

**Issue by lazize** [toniblyx/prowler#1019]
**What happened?**  
CSV file generated with bucket policy in multiple-lines

```
,123412341234,us-east-1,7.71,FAIL,,Extra,[extra771] Check if S3 buckets have policies which allow WRITE access ,Bucket REDACTED-BUCKET-NAME allows public write: {
  "Sid": "Stmt1591730693753",
  "Effect": "Allow",
  "Principal": "*",
  "Action": "s3:*",
  "Resource": "arn:aws:s3:::REDACTED-BUCKET-NAME/*"
},Software and Configuration Checks,Critical,s3,AwsS3Bucket,Software and Configuration Checks,Non intended users can put objects in a given bucket.,Ensure proper bucket policy is in place with the least privilege principle applied.,https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_s3_rw-bucket.html,IAM,REDACTED-BUCKET-NAME,2022-02-01T15:07:39+0000
```

**How to reproduce it**  
1. What command are you running? `-R ProwlerExecRole -A 123412341234 -M csv,html -T 43200`
2. Environment you have, like single account, multi-account, organizations, etc. `organizations`
3. See error above

**Expected behavior**  

**Screenshots or Logs**  
Also, you can add logs (anonymize them first!). Here a command that may help to share a log
`bash -x ./prowler -options > debug.log 2>&1` then attach here `debug.log`

**From where are you running Prowler?**  
Please, complete the following information:
 - Resource: EC2 instance
 - OS: Amazon Linux 2
 - AWS-CLI Version [`aws --version`]: `aws-cli/2.4.15 Python/3.8.8 Linux/4.14.256-197.484.amzn2.x86_64 exe/x86_64.amzn.2 prompt/off`
 - Prowler Version [`./prowler -V`]: `v2.7.0-24January2022`
 - Shell and version: `GNU bash, version 4.2.46(2)-release (x86_64-koji-linux-gnu)`
 - Others:

**Additional context**

**Comment by lazize** [comment]
Also notice that comma inside json policy will break CSV format.

**Comment by lazize** [comment]
Should this check have hard-coded `us-east-1` region?

https://github.com/prowler-cloud/prowler/blob/dcd55dbb8f8451fe05489a048183c9c61312c2f7/checks/check_extra771#L36

**Comment by lazize** [comment]
Let me know if the changes below are a good fit to fix this. If so I can create a PR.

`jq --compact-output` to remove `\n` (new line char). It gives a better view of policy in one line.

Replace character `,` by word `[comma]`

`BUCKET_POLICY_BAD_STATEMENTS=$(echo "${BUCKET_POLICY_BAD_STATEMENTS}" | sed 's|,|[comma]|g')`

It will gives the output like below. (I changed `jq` filter to force it FAIL)

```shell
FAIL! sa-east-1: Bucket xxxx allows public write: {"Sid":"xxxx"[comma]"Effect":"Allow"[comma]"Principal":"*"[comma]"Action":["s3:GetObject"[comma]"s3:PutObject"[comma]"s3:ListBucket"][comma]"Resource":["arn:aws:s3:::xxxx"[comma]"arn:aws:s3:::xxxx/*"][comma]"Condition":{"StringEquals":{"aws:PrincipalOrgID":"o-abc123"}}}
```

**Comment by lazize** [comment]
This check uses the `if` condition below to check if bucket policy exists or not.

```shell
if [[ $BUCKET_POLICY_STATEMENTS == *GetBucketPolicy* ]]; then
```

But it will be true to any exception CLI generated, like the one below:

> An error occurred (AccessDenied) when calling the GetBucketPolicy operation: Access Denied

Wouldn't be better to check for word `NoSuchBucketPolicy` instead of `GetBucketPolicy`?

> An error occurred (NoSuchBucketPolicy) when calling the GetBucketPolicy operation: The bucket policy does not exist

Also wouldn't be better to use the same pattern using `grep` to performs those checks?  
Probably the performance will not be better, but at least the code will have the same standard.

Like:

```shell
if [[ $(echo "$BUCKET_POLICY_STATEMENTS" | grep 'NoSuchBucketPolicy') ]]; then
```

**Comment by toniblyx** [comment]
Fixed by https://github.com/prowler-cloud/prowler/pull/1031

**Comment by toniblyx** [comment]
Thanks @lazize for your help here!
