### ISSUE TITLE
[Bug]: [extra771] jq: error (at <stdin>:1): startswith() requires string inputs

### ISSUE THREAD

**Issue by lazize** [toniblyx/prowler#1026]
**What happened?**  
S3 bucket policy breaks `jq` command when policy action is an array, not an string.

```
jq: error (at <stdin>:1): startswith() requires string inputs
       PASS! Bucket xxxxxxx has S3 bucket policy which does not allow public write access
```

Bucket policy:
```json
{
  "Sid": "xxxxxxxx",
  "Effect": "Allow",
  "Principal": "*",
  "Action": [
    "s3:GetObject",
    "s3:PutObject",
    "s3:ListBucket"
  ],
  "Resource": [
    "arn:aws:s3:::xxxx",
    "arn:aws:s3:::xxxx/*"
  ],
  "Condition": {
    "StringEquals": {
      "aws:PrincipalOrgID": "o-abc123"
    }
  }
}
```

**How to reproduce it**  
1. What command are you running? `./prowler -p default -f sa-east-1 -c extra771`
2. Environment you have, like single account, multi-account, organizations, etc. `single account`
3. See error above

**Expected behavior**  

**Screenshots or Logs**  
Also, you can add logs (anonymize them first!). Here a command that may help to share a log
`bash -x ./prowler -options > debug.log 2>&1` then attach here `debug.log`

**From where are you running Prowler?**  
Please, complete the following information:
 - Resource: Local computer
 - OS: MacOS
 - AWS-CLI Version [`aws --version`]: `aws-cli/2.3.3 Python/3.8.8 Darwin/19.6.0 exe/x86_64 prompt/off`
 - Prowler Version [`./prowler -V`]: `v2.7.0-24January2022`
 - Shell and version: `GNU bash, version 5.1.8(1)-release (x86_64-apple-darwin19.6.0)`
 - Others:
```shell
jq --version
jq-1.6
```

**Additional context**

**Comment by KAKU1234567** [comment]
<h1>Hello</h1>

**Comment by toniblyx** [comment]
Fixed in https://github.com/prowler-cloud/prowler/pull/1031
