### ISSUE TITLE
[Bug]: whitelist parsing broken

### ISSUE THREAD

**Issue by jansepke** [toniblyx/prowler#1034]
**What happened?**  
Commit 30ce25300f1f07a54ac889b1bfe4856adb84f42c does not work with arn values in whitelist. Before the commit it was sufficient to include a part of the resource in the whitelist, e.g. only the role name and not the complete role arn. After this commit the exact resource name is required, but as the whitelist resource name is split by ":" and only the second occurrence is used, an arn will also not work. How should one now whitelist for example IAM roles.

**How to reproduce it**  
`/prowler/prowler -f eu-central-1 -r eu-central-1 -s -w "prowler-whitelist.txt"`

prowler-whitelist.txt contains:
check122:my_admin_role
check122:arn:aws:iam::ACCOUNTID:policy/my_admin_role

**Expected behavior**  
check122 does not fail for arn:aws:iam::ACCOUNTID:policy/my_admin_role

**Actual behavior**  
check122 fails for arn:aws:iam::ACCOUNTID:policy/my_admin_role :
````
1.22 [check122] Ensure IAM policies that allow full "*:*" administrative privileges are not created - iam [Medium]
       FAIL! eu-central-1: Policy arn:aws:iam::ACCOUNTID:policy/my_admin_role allows "*:*
```

**From where are you running Prowler?**  
Please, complete the following information:
 - Resource: Docker  
 - OS: Alpine
 - AWS-CLI Version: aws-cli/1.22.50
 - Prowler Version [`./prowler -V`]: cloned from github
 - Shell and version: bash
 - Others:


**Additional context**
Add any other context about the problem here.

**Comment by jfagoagas** [comment]
Hi @jansepke, this bug is being analysed at https://github.com/prowler-cloud/prowler/issues/961

I close this issue.

Thank you!
