### ISSUE TITLE
[Bug]: Trused advisor checks fail if the default region in the profile is not the one expected

### ISSUE THREAD

**Issue by prmarino1m** [toniblyx/prowler#1050]
Depending on the partition ( US gov cloud, standard or china) a different region must be used for trusted advisor checks.
that said the checks for trusted advisor use whatever is set as the default in the profile. this can cause the following errors

For standard AWS the endpoint should be /support.us-east-1.amazonaws.com
For US Gov Cloud the endpoint it should be support.us-gov-west-1.amazonaws.com

The partition can be determined vi a the get_partition_for_region call in boto3 https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/session.html using the default region in the profile then making the calls to the correct endpoint for that partition. unfortunately this API call does not seem to be present in any other versions of the AWS API's or from the  CLI so to use it a wrapper script may be required. 

7.26 [extra726] Check Trusted Advisor for errors and warnings - trustedadvisor [Medium]

Could not connect to the endpoint URL: "https://support.us-east-2.amazonaws.com/"

Could not connect to the endpoint URL: "https://support.us-east-2.amazonaws.com/"

Could not connect to the endpoint URL: "https://support.us-east-2.amazonaws.com/"

Could not connect to the endpoint URL: "https://support.us-east-2.amazonaws.com/"

Could not connect to the endpoint URL: "https://support.us-east-2.amazonaws.com/"

Could not connect to the endpoint URL: "https://support.us-east-2.amazonaws.com/"

Could not connect to the endpoint URL: "https://support.us-east-2.amazonaws.com/"

Could not connect to the endpoint URL: "https://support.us-east-2.amazonaws.com/"

Could not connect to the endpoint URL: "https://support.us-east-2.amazonaws.com/"

Could not connect to the endpoint URL: "https://support.us-east-2.amazonaws.com/"

Could not connect to the endpoint URL: "https://support.us-east-2.amazonaws.com/"

Could not connect to the endpoint URL: "https://support.us-east-2.amazonaws.com/"

Could not connect to the endpoint URL: "https://support.us-east-2.amazonaws.com/"

Could not connect to the endpoint URL: "https://support.us-east-2.amazonaws.com/"

Could not connect to the endpoint URL: "https://support.us-east-2.amazonaws.com/"

Could not connect to the endpoint URL: "https://support.us-east-2.amazonaws.com/"

This output was produced running prowler with the following options
"-M html,csv,text -p \<ProfileName\> -r us-gov-west-1"

**Comment by prmarino1m** [comment]
@jfagoagas ^^

**Comment by jfagoagas** [comment]
We are closing this issue, it's duplicated at https://github.com/prowler-cloud/prowler/issues/967

Thank you!
