### ISSUE TITLE
[Bug]: Integration to security hub

### ISSUE THREAD

**Issue by sottlmarek** [toniblyx/prowler#1052]
Currently I cannot fined Prowler in the security hub integrations. IS there any workaround what is not documented. I tested also the cli integration and received following message: 

```
aws securityhub enable-import-findings-for-product --region us-east-1 --product-arn arn:aws:securityhub:us-east-1::product/prowler/prowler

An error occurred (ResourceNotFoundException) when calling the EnableImportFindingsForProduct operation: {"productArn":"arn:aws:securityhub:us-east-1::product/prowler/prowler"}
```

**Comment by sottlmarek** [comment]
Already Talked to AWS as it looks like the problem is on AWS side.

**Comment by toniblyx** [comment]
Please keep us posted with whatever the issue is. And thanks for let us know @sottlmarek!

**Comment by sottlmarek** [comment]
Currently testing it. I spoke with AWS guys in Community builders slack to report it. Yesterday was not possible to approve ASFF ingestion in AWS Security hub integrations. Now, I am testing if it works for more regions.

**Comment by toniblyx** [comment]
I have done a test in us-east-1 and worked properly for me.

**Comment by sottlmarek** [comment]
Now it works, yesterday not. When I searched prowler in integrations it was not there. AWS folks confirmed that bug. Now it looks good. We can close the issue. I can reopen it when the problem will appear again.

**Comment by jfagoagas** [comment]
Sounds great!! Thank you @sottlmarek
