### ISSUE TITLE
S3 checks - checks global region instead of the region the S3 bucket is created in - this is for control tower type accounts

### ISSUE THREAD

**Issue by RoxyR44** [toniblyx/prowler#1075]
[check29] Ensure VPC Flow Logging is Enabled in all VPCs

[extra764] Check if S3 buckets have secure transport policy - checks Global region instead of the region our S3 buckets are actually created in, the report then reports the global region when the bucket is actually sitting in a specific region like EU WEST 1

**Comment by MrCloudSec** [comment]
Hi @RoxyR44, please, for being able to solve the issue correctly, it is needed to fulfill the provided issue template. Could you reopen it with that information? Thank you.
