### ISSUE TITLE
[Bug]: check extra764 doesn't handle bucket region properly

### ISSUE THREAD

**Issue by RoxyR44** [toniblyx/prowler#1076]
**What happened?**  
When running the checks for S3 it picks up the global region instead of the region the bucket is created in

**How to reproduce it**  
1. What command are you running? Check 7.64 [extra764] Check if S3 buckets have secure transport policy enabled
2. Running in Control tower multi-account environment, running as administrator in specific account 
3. Error - Picks up us-east-1 but our region is not this region

**Expected behavior**  
I would expect it to return the correct region as it has done for the following S3 checks :
[extra73] Ensure there are no S3 buckets open to Everyone or Any AWS use
[extra734] Check if S3 buckets have default encryption (SSE) enabled or use a bucket policy to enforce it

**Screenshots or Logs**  
<img width="598" alt="Screenshot 2022-03-17 at 13 50 59" src="https://user-images.githubusercontent.com/91897071/158803012-f9854990-a3fb-4aed-9551-2a0f8a01aa56.png">

**From where are you running Prowler?**  
 - Resource: Workstation
 - OS: Mac OS Monteray 12.2.1 (21D62)
 - AWS-CLI Version: aws-cli/2.4.13 Python/3.8.8 Darwin/21.3.0
 - Prowler Version: Prowler 2.7.0-24January2022
 - Shell and version:
 - Others:

**Additional context**
 I picked it up by going to the finding and then going to the S3 instance, only to find it in the correct region and not the US EAST 1 region.

**Comment by MrCloudSec** [comment]
Hi @RoxyR44 , good catch! We have open a Pull Request on behalf of this issue: https://github.com/prowler-cloud/prowler/pull/1077
Please, test it to see if that works for you 😄

**Comment by toniblyx** [comment]
This is now fixed from PR https://github.com/prowler-cloud/prowler/pull/1077. Available in master branch now. It will be part of the next fix release in a week. Thanks!
