### ISSUE TITLE
[Bug]: aws prowler integration references old repo location

### ISSUE THREAD

**Issue by spazm** [toniblyx/prowler#1087]
**What happened?**  

The `ActivationUrl` in the Prowler integration in aws points to a repository location `toniblyx/prowler` rather than `prowler-cloud/prowler`.

**How to reproduce** 

The ActivationUrl can be seen by querying aws v2 api:

```
% aws securityhub describe-products | jq '.Products[]|select(.ProductName=="Prowler")|.' 

{
  "ProductArn": "arn:aws:securityhub:us-west-2::product/prowler/prowler",
  "ProductName": "Prowler",
  "CompanyName": "Prowler",
  "Description": "Prowler is an Open Source security tool to perform AWS checks related to security best practices, hardening and continuous monitoring. Includes all CIS controls plus more than 160 additional checks.",
  "Categories": [
    "Cloud Compliance and Best Practices Checks",
    "Governance, Risk, and Compliance (GRC)"
  ],
  "IntegrationTypes": [
    "SEND_FINDINGS_TO_SECURITY_HUB"
  ],
  "ActivationUrl": "https://github.com/toniblyx/prowler/#security-hub-integration",
  "ProductSubscriptionResourcePolicy": "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"AWS\":\"371988892900\"},\"Action\":[\"securityhub:BatchImportFindings\"],\"Resource\":\"arn:aws:securityhub:us-west-2::product/prowler/prowler\",\"Condition\":{\"StringEquals\":{\"securityhub:TargetAccount\":\"371988892900\"}}}]}"
}
 

**Expected behavior**  

I would expect the `ActivattionUrl` to be `https://github.com/prowler-online/prowler/#security-hub-integration`

**Comment by jfagoagas** [comment]
Hi @spazm, are you experiencing any issue with that?

You're right and we need to modify Prowler repository URL but Github performs automatic redirection from the old repository to the new one.
```
➜  ~ curl https://github.com/toniblyx/prowler
<html><body>You are being <a href="https://github.com/prowler-cloud/prowler">redirected</a>.</body></html>%
```

**Comment by jfagoagas** [comment]
We are closing this issue. Please @spazm, feel free to reopen it if you experience any issue or if you can provide us more information about it.

We've opened a new support case to modify this URL at the Prowler's Security Hub integration.

Thank you.

**Comment by spazm** [comment]
> Hi @spazm, are you experiencing any issue with that?


No issue, just wanted to report as a lowest-priority item to get tracked somewhere. :)

**Comment by jfagoagas** [comment]
> > Hi @spazm, are you experiencing any issue with that?
> 
> 
> No issue, just wanted to report as a lowest-priority item to get tracked somewhere. :)

Yes!! Thank you 🙌
