### ISSUE TITLE
[Bug]: Check7.92- if Elastic Load Balancers have insecure SSL ciphers gives false +ve

### ISSUE THREAD

**Issue by ankitloud** [toniblyx/prowler#1088]
<html>
<body>

Problem:
=======
If someone uses security policy like **ELBSecurityPolicy-TLS13-1-2-2021-06** then prowler says  Load Balancers is using insecure SSL ciphers which is wrong. This check need to be updated with latest TLS policies.

<br class="Apple-interchange-newline">
</body>
</html>

**Comment by jfagoagas** [comment]
Hi @ankitloud, please fulfil the [Issue Template](https://github.com/prowler-cloud/prowler/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) to provide us the required information to triage this issue.

Thanks!

**Comment by MrCloudSec** [comment]
Hi @ankitloud , good catch! We have open a Pull Request on behalf of this issue: https://github.com/prowler-cloud/prowler/pull/1091
As it was fixed, we close this issue. Please, test it and let us know if that works for you!
