### ISSUE TITLE
Can you add CIS Benchmark Version 1.4 related test cases ?

### ISSUE THREAD

**Issue by ankitloud** [toniblyx/prowler#1096]
**Is your feature request related to a problem? Please describe.**
Current version  of Prowler is CIS benchmark is 1.2  which is outdated. Can we have a plan to integrate 1.4 ?
**Describe the solution you'd like**
Update new test cases as part of CIS Foundation benchmark version 1.4.

**Describe alternatives you've considered**

**Additional context**

**Comment by jfagoagas** [comment]
Hi @ankitloud, actually Prowler covers CIS v1.3 but we don't have updated our documentation yet.

The only change I've noticed in CIS v1.4  is that `1.12 Ensure credentials unused for 45 days or greater are disabled` has changed from 90 days to 45 days. We are going to modify this in Prowler soon.

Do you have noticed any other CIS check that is not included in Prowler?

[CIS_Amazon_Web_Services_Foundations_Benchmark_v1.4.0.pdf](https://github.com/prowler-cloud/prowler/files/8470392/CIS_Amazon_Web_Services_Foundations_Benchmark_v1.4.0.pdf)

**Comment by jfagoagas** [comment]
We are closing this issue. We've included support for CIS v1.4 in our roadmap.

Please, reopen this issue if you can provide us more information.
