### ISSUE TITLE
[Bug]: JSON format returns invalid json

### ISSUE THREAD

**Issue by michaelsegal21** [toniblyx/prowler#1097]
**What happened?**  
I've run Prowler V2.8.1 on my AWS account, I've requested it to save the result in JSON format. 
After the run, I've accessed the file but the result wasn't in a valid JSON format. 
I've received multiple findings, but they returned in the following format:
```
{
    "Profile":"ENV",
    "Control":"[extra73] Ensure there are no S3 buckets open to Everyone or Any AWS user",
    "Status":"FAIL",
    "Control ID":"7.3",
    ...
}
{
    "Profile":"ENV",
    "Control":"[extra73] Ensure there are no S3 buckets open to Everyone or Any AWS user",
    "Status":"FAIL",
    "Control ID":"7.3",
    ...
}
```

Two valid JSON's, but in an invalid format.

**How to reproduce it**  
`docker run -v /tmp/prowler:/tmp/prowler -ti --rm --name prowler --env AWS_ACCESS_KEY_ID --env AWS_SECRET_ACCESS_KEY --env AWS_SESSION_TOKEN toniblyx/prowler:2.8.1 -q -b -c extra742 -f us-east-1 -M json -o /tmp/prowler -F output`
2. I've ran on specific account that is part of an org
3. enter output.json and see that it isn't valid (could also try json.load(file)

**Expected behavior**  
I expected to receive a file in a valid JSON format.

**From where are you running Prowler?**  
Please, complete the following information:
 - Resource: Local machine via docker
 - OS: Mac
 - AWS-CLI Version [`aws --version`]: aws-cli/2.4.5 Python/3.9.9 Darwin/21.1.0 source/x86_64 prompt/off
 - Prowler Version [`./prowler -V`]: 2.8.1
 - Shell and version:
 - Others:

Thank you so much for the assistance.

**Comment by toniblyx** [comment]
Hi @michaelsegal21, can you take a look here? https://github.com/prowler-cloud/prowler/issues/190#issuecomment-426273542

**Comment by MrHassanMurtaza** [comment]
Temporary fix using Python for a static file name: 

Also it could be feature request to be able to specify the output file name in Prowler. 

```
filepath = "prowler-output.json"
with open(filepath) as f:
    lines = f.read().splitlines()

with open(filepath, "w") as f:
    last = lines[-1]
    f.write("[")
    for line in lines:
        if line is not last:
            f.write(line + ",\n")
        else:
            f.write(line)
    f.write("]")
```

**Comment by michaelsegal21** [comment]
Thanks for the help.
In the end I've done something very similar to the code you've suggested (thanks!).

**Comment by jfagoagas** [comment]
Hi @michaelsegal21, thank you for all the information provided. 

We're closing this issue but we've included this in our roadmap in order to build a valid `json` object with all the security findings.
