### ISSUE TITLE
Updated multi account deployment

### ISSUE THREAD

**Issue by MorlaxAR** [toniblyx/prowler#1110]
**Is your feature request related to a problem? Please describe.**
I have been tasked with deploying Prowler on our AWS Organizations accounts. There is an excellent example deployment at [org-multi-account](https://github.com/prowler-cloud/prowler/tree/master/util/org-multi-account), but it generates HTML reports and uploads them to a bucket. With the addition of the SecurityHub integration, I believe it is much easier to just use that.

**Describe the solution you'd like**
I started working with the example deployment provided, and modified to use SecurityHub instead. It also uses a Fargate container with an EventBridge Rule instead of an EC2 instance with a cronjob. Several other performance and security improvements have been made, so my solution ended up being quite different than the one currently in the prowler repo.

What I have been working in can be found in my fork at [multi-acc-sechub](https://github.com/MorlaxAR/prowler/tree/multi-acc-sechub). 

I don't want to make a PR to update the current solution, because the architectures are quite different. I would like to merge my example solution into the main repo in a different directory, as it is currently on my fork.

Feel free to take a look at it, and tell me if you would like me to proceed with the PR :)

**Comment by n4ch04** [comment]
Hi @MorlaxAR thanks for your contribution!!
That approach (deploy prowler into AWS organizations) is one of the use cases  covered by the Pro version of Prowler  including:
- DASHBOARDS FOR COMPLIANCE AND SECURITY
- ENHANCED MONITORING OPTIONS
- ENTERPRISE-GRADE SUPPORT

and much more ...
Please check it out here [Prowler Pro](https://prowler.pro)

Regarding your contribution, could you please make a PR including your solution in a new folder to let us check it?

Thanks !!

**Comment by jfagoagas** [comment]
Thank you for your contribution @MorlaxAR, we're closing this issue because your PR has been merged.
