### ISSUE TITLE
[Bug]: An error occurred (InvalidAccessException) when calling the GetFindings operation: Account xxxx is not subscribed to AWS Security Hub

### ISSUE THREAD

**Issue by gvasquez95** [toniblyx/prowler#1143]
**What happened?**  
When trying to push only failed checks (with the `-q` flag) to AWS Security Hub, unexpected behaviour appears.

Trying `-q` or `-M json-asff -S` separately works perfect, but when adding all of them makes it crash

**How to reproduce it**  
1. What command are you running? `./prowler -q -M json-asff -S `
2. Environment you have, like single account, multi-account, organizations, etc.
3. See error: the error msg is exactly the this isss subject, minus the account number, that has been replaced for security concerns.

**Expected behavior**  
Prowler should tolerate these 3 flags combined as it's the recommended mix as per Note 1 for uploading only failed checks to AWS Security Hub.

**Screenshots or Logs**  
Also, you can add logs (anonymize them first!). Here a command that may help to share a log
`bash -x ./prowler -options > debug.log 2>&1` then attach here `debug.log`

**From where are you running Prowler?**  
Please, complete the following information:
 - Resource: [e.g. EC2 instance, Fargate task, Docker container manually, EKS, Cloud9, CodeBuild, workstation, etc.) : workstatuin
 - OS: [e.g. Amazon Linux 2, Mac, Alpine, Windows, etc. ] OSX
 - AWS-CLI Version [`aws --version`]:aws-cli/2.7.0 Python/3.9.11 Darwin/21.3.0 exe/x86_64 prompt/off
 - Prowler Version [`./prowler -V`]: Prowler 2.9.0-13April2022
 - Shell and version: /bin/bash  GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin21)
 - Others: -

**Additional context**

**Comment by toniblyx** [comment]
Hi @gvasquez95, remember that Security Hub is a region based AWS service so you have to make sure whatever region you are sending Prowler findings has Security Hub enabled with Prowler integration enabled as well. Then run Prowler based on those regions using also `-f region` or `-f region1,region2`. All details here https://github.com/prowler-cloud/prowler#security-hub-integration

**Comment by gvasquez95** [comment]
Re-run it yesterday with ` ./prowler -M json-asff -S -q -f us-east-1` and the same problem appeared for some of the first checks, but not with all of them...running them today shows no problems.

What I'm thinking of is that yesterday I interrupted the run because I forgot to add the `-q` flag so even PASSED checks were being reported as findings in Security Hub, so it was kind of damaging our metrics. After interrupting I flagged as RESOLVED all Prowler findings with PASSED status and, I'm guessing that this might have caused some kind of conflict

**Comment by toniblyx** [comment]
Not sure if I understand what you mean, do you mean it is solved now? @gvasquez95

**Comment by gvasquez95** [comment]
It works now, I did nothing at all, but it shows no problems now. Could have been just a timing issue back then.

**Comment by jfagoagas** [comment]
> It works now, I did nothing at all, but it shows no problems now. Could have been just a timing issue back then.

Thank you!
