### ISSUE TITLE
[Bug]: Minor typo

### ISSUE THREAD

**Issue by gvasquez95** [toniblyx/prowler#1144]
[Here](https://github.com/prowler-cloud/prowler/blob/a18b18e530438921c306631d0080629ef38fd7d0/util/codebuild/codebuild-prowler-audit-account-cfn.yaml#L134) it says `Prower`, should be `Prowler` IMHO

**Comment by jfagoagas** [comment]
Thank you @gvasquez95, the PR [here](https://github.com/prowler-cloud/prowler/pull/1145/files) fixes it.

**Comment by gvasquez95** [comment]
Great, thanks!
