### ISSUE TITLE
[Bug]: AllowList Documentation Error

### ISSUE THREAD

**Issue by JonathanTranter-nasstar** [toniblyx/prowler#1146]
**What happened?**  
This is more a documentation issue than a problem with Prowler

When using DynamoDB to store an allowlist, the readme.md states "Make sure that the table has account_id as partition key and rule as sort key, and that the used credentials have dynamodb:Scan permissions in the table."

I found that the permissions also required  dynamodb:PartiQLSelect in the servicerole for CodeBuild to be able to read the allowlist from DynamoDB

Prowler generated an access denied error, when trying to read from DynamoDB until dynamodb:PartiQLSelect permission was added to the CodeBuild service role

**How to reproduce it**  
1. Run Prowler via AWS CodeBuild
2. See error

**Expected behavior**  

**Screenshots or Logs**  
Running Prowler as ./prowler -r eu-west-1 -f eu-west-1 -M text,junit-xml,html,csv,json -w arn:aws:dynamodb:eu-west-1:XXXXXXXXX:table/AFProwlerAllowList
54 |  
55 | [Container] 2022/05/16 22:02:24 Running command ./prowler $PROWLER_OPTIONS
56 | Getting allowlist from DynamoDB table arn:aws:dynamodb:eu-west-1:XXXXXXXXX:table/AFProwlerAllowList ...
57 | FAIL! Access Denied trying to get allowlist from the DynamoDB, please make sure it is correct and/or you have permissions to scan the table AFProwlerAllowList.

**From where are you running Prowler?**  
Please, complete the following information:
 - Resource: CodeBuild
  - OS:  Amazon Linux 2
 - AWS-CLI Version; 2 aws/codebuild/amazonlinux2-x86_64-standard:3.0
 - Prowler Version: v2.9.0-13April2022

**Additional context**

**Comment by MrCloudSec** [comment]
Good catch @JonathanTranter-nasstar !! 
The readme was changed in this [PR](https://github.com/prowler-cloud/prowler/pull/1147), thank you for the contribution.
