### ISSUE TITLE
[Bug]: extra730 - gdate: invalid date ‘@2022-07-27T11:18:29-04:00’

### ISSUE THREAD

**Issue by gvasquez95** [toniblyx/prowler#1152]
**What happened?**  
I'm guessing that there might be a timestamp format issue here, as it could be related to [this issue](https://github.com/prowler-cloud/prowler/issues/1150) too.

**How to reproduce it**  
1. What command are you running? `./prowler -M json-asff -S -q -f us-east-1,eu-west-1 -c extra730`

**Expected behavior**  
It should accept the shown date or reformat it to be compliant.

**Screenshots or Logs**  
Screenshot: 
![Screen Shot 2022-05-18 at 13 11 52](https://user-images.githubusercontent.com/14003078/169102261-aa5c561e-5d8e-46aa-bbba-5808b157eb20.png)

Log: 
[debug.log](https://github.com/prowler-cloud/prowler/files/8718572/debug.log)

**From where are you running Prowler?**  
From where are you running Prowler?
Please, complete the following information:
Resource: [e.g. EC2 instance, Fargate task, Docker container manually, EKS, Cloud9, CodeBuild, workstation, etc.) : workstation
OS: [e.g. Amazon Linux 2, Mac, Alpine, Windows, etc. ] OSX
AWS-CLI Version [aws --version]:aws-cli/2.7.0 Python/3.9.11 Darwin/21.3.0 exe/x86_64 prompt/off
Prowler Version [./prowler -V]: Prowler 2.9.0-13April2022
Shell and version: /bin/bash GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin21)

**Comment by jfagoagas** [comment]
Hi @gvasquez95, how did you install `gdate` on your workstation? Did you installed it through `coreutils` package using `brew`?

Please, paste here the output of the following command:
`gdate --version`

Thank you!

**Comment by gvasquez95** [comment]
I can't tell how / when I installed `gdate`, as I didn't have to add it to run prowler.

The output is:

```
date (GNU coreutils) 9.0
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by David MacKenzie.
```

**Comment by jfagoagas** [comment]
> I can't tell how / when I installed `gdate`, as I didn't have to add it to run prowler.
> 
> The output is:
> 
> ```
> date (GNU coreutils) 9.0
> Copyright (C) 2021 Free Software Foundation, Inc.
> License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
> This is free software: you are free to change and redistribute it.
> There is NO WARRANTY, to the extent permitted by law.
> 
> Written by David MacKenzie.
> ```

Thank you, it help us to reproduce your issue.

**Comment by n4ch04** [comment]
Hi @gvasquez95 please check it out the solution we propose in #1154 and let us know if everything is ok

**Comment by gvasquez95** [comment]
I just downloaded the `PRWLR-492-bug-syntax-error-operand-expected-error-token-is-60-60-24` branch, tested and works fine. Thanks a lot!

**Comment by n4ch04** [comment]
Thanks for your contribution !! Closing this
