### ISSUE TITLE
[Bug]: extra728 doesn't check for SqsManagedSseEnabled

### ISSUE THREAD

**Issue by ghost** [toniblyx/prowler#1173]
**What happened?**  
When an SQS queue has AWS managed encryption set it fails the check.

**How to reproduce it**  
Set:
"SqsManagedSseEnabled": "true"

**Expected behavior**  
Check should pass

**Screenshots or Logs**  
```<REGION>: SQS queue https://sqs.<region>.amazonaws.com/<account-id>/<queue-name> is not using Server Side Encryption```

**From where are you running Prowler?**  
EC2

**Additional context**
Script only checks for KMS encryption - 
```
$AWSCLI sqs get-queue-attributes ...--query Attributes.KmsMaster.KeyId
```

Should also check 
```
$AWSCLI sqs get-queue-attributes ...--query Attributes.SqsManagedSseEnabled
```

**Comment by MrCloudSec** [comment]
Thank you @wobblesprout, good catch!
We will fix it asap and let you know.

**Comment by MrCloudSec** [comment]
@wobblesprout you have the PR fixing this issue [here](https://github.com/prowler-cloud/prowler/pull/1175), try it and let us know if it works!

**Comment by ghost** [comment]
@sergargar  - I ran #1175 against my account and it now passed. Thanks.
