### ISSUE TITLE
[Bug]: extra762 flagging out all version of nodejs

### ISSUE THREAD

**Issue by NMuee** [toniblyx/prowler#1174]
According to "https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtime-support-policy"
The identifier for node.js 0.10 is "nodejs"
however, i believe probably due to the above identifier, all my lambda that are running on nodejs14.x and nodejs12.x are all being flagged out. 
Will need the team help to take a look, thank you.

**Comment by MrCloudSec** [comment]
Thank you @NMuee for reaching out! 
We will solve this issue shortly and let you know.

**Comment by MrCloudSec** [comment]
We have created this [PR](https://github.com/prowler-cloud/prowler/pull/1177) to solve this issue, please check it out.

**Comment by MxxxxxF** [comment]
Looks good, thank you so much

**Comment by NMuee** [comment]
Looks good, thank you so much
