### ISSUE TITLE
[Bug]: Codebuild COMMAND_EXECUTION_ERROR

### ISSUE THREAD

**Issue by SecOp187** [toniblyx/prowler#1182]
**What happened?**  
I followed exactly the instructions to run Prowler in a CodeBuild environment https://github.com/prowler-cloud/prowler#codebuild-deployment by deploying the CloudFormation template. After running for 33 minutes, the build fails with the error message: "Command did not exit successfully ./prowler $PROWLER_OPTIONS exit status 3". These are the environment variables:
![image](https://user-images.githubusercontent.com/82619023/172215638-b4c672ea-784d-4634-9067-5c913366dc4b.png)

**How to reproduce it**  
1. What command are you running? 
![image](https://user-images.githubusercontent.com/82619023/172215916-1c25dea6-2a58-4f90-8783-52a6958d879c.png)
2. Environment you have, like single account, multi-account, organizations, etc. Single AWS account
3. See error
![image](https://user-images.githubusercontent.com/82619023/172216167-29a7b3b6-2f7f-44d7-a28a-0bd1017c156a.png)

**Screenshots or Logs**  
See above

**From where are you running Prowler?**  
 - Resource: [e.g. EC2 instance, Fargate task, Docker container manually, EKS, Cloud9, CodeBuild, workstation, etc.)  CodeBuild
 - OS: [e.g. Amazon Linux 2, Mac, Alpine, Windows, etc. ] aws/codebuild/amazonlinux2-x86_64-standard:3.0
 - AWS-CLI Version [`aws --version`]: v2
 - Prowler Version [`./prowler -V`]: 2.5.0

**Comment by MrCloudSec** [comment]
Hi @SecOp187, thank you for reaching out!
We'll take a look at it and get back to you.

**Comment by MrCloudSec** [comment]
How did you include the PROWLER_BRANCH variable?

**Comment by MrCloudSec** [comment]
We have solve some issues in this [PR](https://github.com/prowler-cloud/prowler/pull/1183) , please try it again and let us know if that fix your errors.

**Comment by SecOp187** [comment]
> How did you include the PROWLER_BRANCH variable?

I modified the PROWLER_BRANCH attribute (default value) by changing 2.5 to 2.5.0 in the yaml file (https://static.us-east-1.prod.workshops.aws/public/ba7ded10-50ba-4afc-9932-4e168003e650/static/templates/3-Deploy-Run-Prowler-CodeBuild.yaml). Because I was getting error due to the non-existent branch 2.5.
![image](https://user-images.githubusercontent.com/82619023/172452236-b9315bdb-6239-4917-9429-ec6d9170c81f.png)

**Comment by MrCloudSec** [comment]
Can you try it with this [original cloudformation template](https://github.com/prowler-cloud/prowler/blob/master/util/codebuild/codebuild-prowler-audit-account-cfn.yaml)?

**Comment by SecOp187** [comment]
> Can you try it with this [original cloudformation template](https://github.com/prowler-cloud/prowler/blob/master/util/codebuild/codebuild-prowler-audit-account-cfn.yaml)?

I used that template yesterday after you updated it. I still got the same error message after running for 4 hours:
![image](https://user-images.githubusercontent.com/82619023/172675810-ade3125a-c8eb-43c5-ae4d-51c1a2365fa3.png)

These are the options I used for the prowler command
![image](https://user-images.githubusercontent.com/82619023/172676166-3a52e504-a7d3-4af8-8b75-e15da486d920.png)

**Comment by MrCloudSec** [comment]
We have realized what the problem was, please add `-z` to PROWLER_OPTIONS and let us know if that works.
This flag makes failed checks not to trigger exit code 3.

**Comment by SecOp187** [comment]
> We have realized what the problem was, please add `-z` to PROWLER_OPTIONS and let us know if that works. This flag makes failed checks not to trigger exit code 3.

Hello @sergargar, the -z argument fixed the exit code 3 error but after running for 5 hours, the build failed because it timed out. 
![image](https://user-images.githubusercontent.com/82619023/173117471-33f4ad4c-a387-4b15-afa3-276984d6e2e4.png)
Is it a codebuild issue or should I use different prowler options such as reporting only failed checks to reduce the run time? These are the options I used for prowler.
![image](https://user-images.githubusercontent.com/82619023/173117630-3ff61e2e-b600-44e3-b88a-2c27e5a863b2.png)

**Comment by MrCloudSec** [comment]
Hi @SecOp187, try the last version of the [cloudformation template](https://github.com/prowler-cloud/prowler/blob/master/util/codebuild/codebuild-prowler-audit-account-cfn.yaml). We have incremented the timeout to the maximum supported by codebuild which is 8 hours. Let us know if that works.

**Comment by SecOp187** [comment]
> 

Hi @sergargar I just re-created the cloudformation stack with your updated template and the build timed out again after running for 8 hours. Can I run an assessment with a set of selected groups (e.g. -g group1, group2) or should I just run with reporting only failed checks to reduce the build time?

**Comment by MrCloudSec** [comment]
Hello @SecOp187, exactly, try to divide assessments by selecting groups and/or running with only failed checks with `-q`. Let's see if that save time to last less than 8 hours.

**Comment by SecOp187** [comment]
> Hello @SecOp187, exactly, try to divide assessments by selecting groups and/or running with only failed checks with `-q`. Let's see if that save time to last less than 8 hours.

Hi @sergargar  I ran a prowler assessment with one group (-g group1) only and the build completed but it failed with the errors below:
![image](https://user-images.githubusercontent.com/82619023/173639711-b2181bed-1b6d-4f10-a7a9-0148565cd4f4.png)
I checked the policy permissions for codebuild in the cloudformation template and everything looks good.
![image](https://user-images.githubusercontent.com/82619023/173639997-943dc05a-be5a-4acc-8d58-b8484e301294.png)

By the way, can I include multiple groups (e.g. -g group1, group2, group3) as a prowler option or it requires only one group?

**Comment by MrCloudSec** [comment]
HI @SecOp187 , what is the command you are inputing? 

> By the way, can I include multiple groups (e.g. -g group1, group2, group3) as a prowler option or it requires only one group?

No, at the moment, you can only include one group at once.

**Comment by SecOp187** [comment]
> HI @SecOp187 , what is the command you are inputing?
> 
> > By the way, can I include multiple groups (e.g. -g group1, group2, group3) as a prowler option or it requires only one group?
> 
> No, at the moment, you can only include one group at once.

Hi @sergargar the command was `-r us-west-1 -f us-west-1 -M junit-xml,json-asff -S -z -g group1`

**Comment by SecOp187** [comment]
> HI @SecOp187 , what is the command you are inputing?
> 
> > By the way, can I include multiple groups (e.g. -g group1, group2, group3) as a prowler option or it requires only one group?
> 
> No, at the moment, you can only include one group at once.

I added the branch 2.10.0 to codebuild source and the build was completed successfully without errors below:
![image](https://user-images.githubusercontent.com/82619023/174199964-b13b4225-2cb7-41eb-971e-666b7e0d6184.png)

but I am getting the following error: 
![image](https://user-images.githubusercontent.com/82619023/174200046-13ef1be4-b55c-490f-a77a-2ced8bac8b58.png)

The Codebuild service role policy has the Security Hub Full Access permissions and us-west-2 has the region aggregation enabled. The command I inputted was `-r us-west-2 -f us-west-2 -M junit-xml,json-asff -S -z -g hipaa`

**Comment by MrCloudSec** [comment]
Hi @SecOp187, we have solve the junit_xml error in this [PR](https://github.com/prowler-cloud/prowler/pull/1210). Let us know if with the latest version works for you in Codebuild.

**Comment by SecOp187** [comment]
> Hi @SecOp187, we have solve the junit_xml error in this [PR](https://github.com/prowler-cloud/prowler/pull/1210). Let us know if with the latest version works for you in Codebuild.

Hi @sergargar, the latest version works and I am not getting the junit_xml error anymore. However, I still get the error message 'ERROR! Failed to send check output to AWS Security Hub' when running prowler for the us-west-2 region with us-west-2 as the API endpoint. The runs with other regions (us-east-1 and us-west-1) are not producing errors.

**Comment by MrCloudSec** [comment]
Hi @SecOp187, verify if you have enabled SecurityHub in the regions where you are getting those errors (or maybe you have deactivated some regions via SCP).

**Comment by SecOp187** [comment]
> Hi @SecOp187, verify if you have enabled SecurityHub in the regions where you are getting those errors (or maybe you have deactivated some regions via SCP).

Hi @sergargar I do have Security Hub enabled for the regions I am running prowler assessment against. I also ran into another issue related to an expired security token.
![image](https://user-images.githubusercontent.com/82619023/175433322-3578a281-18eb-4ad1-9147-05fce0b9244c.png)

**Comment by MrCloudSec** [comment]
Hi @SecOp187, are you using the latest version? Please, send us the command you are using and the logs with `bash -x`.

**Comment by SecOp187** [comment]
> Hi @SecOp187, are you using the latest version? Please, send us the command you are using and the logs with `bash -x`.

Hi @sergargar I am running the latest version, I used the most updated cloudformation template for codebuild. This is the command I ran:
![image](https://user-images.githubusercontent.com/82619023/176751939-1558a3a3-db03-4547-80cc-8ae5da99dc0f.png)

How can I send the logs with Codebuild?

**Comment by MrCloudSec** [comment]
Hi @SecOp187, change the Buildspec file by adding `bash -x` to the following line:
![image](https://user-images.githubusercontent.com/38561120/177140980-d3c7ad83-6e75-4910-904f-09b052a87d8a.png)

Please, insert here the build logs to analyze it.

**Comment by SecOp187** [comment]
> Hi @SecOp187, change the Buildspec file by adding `bash -x` to the following line: ![image](https://user-images.githubusercontent.com/38561120/177140980-d3c7ad83-6e75-4910-904f-09b052a87d8a.png)
> 
> Please, insert here the build logs to analyze it.

[Link](https://drive.google.com/file/d/16o0QxO1TDCAJHx1_md7mLBfyavfAAzEc/view?usp=sharing) to access the build logs.

**Comment by MrCloudSec** [comment]
@SecOp187 did the build fail this time? I don't see the `ExpiredToken` error.

**Comment by SecOp187** [comment]
> @SecOp187 did the build fail this time? I don't see the `ExpiredToken` error.

Hi @sergargar, it failed to send some security findings to AWS Security Hub. Didn't  you see the error message "Failed to send check output to AWS Security Hub" in the build logs. I don't think it is related to an `ExpiredToken` error but a permission issue. But the service role policy has full access to Security Hub.

**Comment by MrCloudSec** [comment]
@SecOp187 pls, insert here the permissions of your role `prowler-reinforce-3-CodeBuildServiceRole-15QCR9TV1GUAV`.

**Comment by SecOp187** [comment]
> @SecOp187 pls, insert here the permissions of your role `prowler-reinforce-3-CodeBuildServiceRole-15QCR9TV1GUAV`.

Here are the role permission policies (automatically assigned when the role was created with the CloudFormation template):
![image](https://user-images.githubusercontent.com/82619023/177834597-d98131dd-8b10-4d65-a072-05d918c63d5f.png)

I only modified is the SecurityHubBatchImportFindings policy to update findings as well:
`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "securityhub:BatchImportFindings",
                "securityhub:BatchUpdateFindings",
                "securityhub:GetFindings"
            ],
            "Effect": "Allow",
            "Resource": "*"
        }
    ]
}`

**Comment by sergargar** [comment]
@SecOp187 please dm me to schedule a call and try to resolve this in real time, because we cannot reproduce this issue in our environment.

**Comment by MrCloudSec** [comment]
Please, try it again with the latest version. We have fix the error with the above PR.

**Comment by SecOp187** [comment]
> Please, try it again with the latest version. We have fix the error with the above PR.

I ran the build with the latest version by inputting 'master' as the source version but I am still getting the expired token error message. 
![image](https://user-images.githubusercontent.com/82619023/178622232-337f4026-453c-4f1f-a092-28856a91a477.png)

![image](https://user-images.githubusercontent.com/82619023/178621350-f5648cf9-34ab-416f-a065-d3da6cafeb66.png)

**Comment by jfagoagas** [comment]
Hi @SecOp187, please test it again using branch expired-token-codebuild from this PR https://github.com/prowler-cloud/prowler/pull/1265.

You can do it by putting the branch `expired-token-codebuild` in the source version of the Codebuild project.
Let us know if everything is fixed.

**Comment by SecOp187** [comment]
> Hi @SecOp187, please test it again using branch expired-token-codebuild from this PR #1265.
> 
> Let us know if everything is fixed.

I restarted another build with the branch expired-token-codebuild as the source version an hour ago and I still got the expired token exception:
![image](https://user-images.githubusercontent.com/82619023/178793744-9c57f80e-4e15-4964-8086-c3c3d44d8323.png)
![image](https://user-images.githubusercontent.com/82619023/178794908-1cd8274a-7cf3-412d-8013-5a41ca4aeab9.png)

Prowler Options:
![image](https://user-images.githubusercontent.com/82619023/178797108-f68a7df0-b5af-4197-a905-71ede9226fdc.png)

**Comment by jfagoagas** [comment]
> 
> I restarted another build with the branch expired-token-codebuild as the source version an hour ago and I still got the expired token exception:
> 
> ![image](https://user-images.githubusercontent.com/82619023/178793744-9c57f80e-4e15-4964-8086-c3c3d44d8323.png)
> 
> ![image](https://user-images.githubusercontent.com/82619023/178794908-1cd8274a-7cf3-412d-8013-5a41ca4aeab9.png)
> 
> 
> 
> Prowler Options:
> 
> ![image](https://user-images.githubusercontent.com/82619023/178797108-f68a7df0-b5af-4197-a905-71ede9226fdc.png)
> 
> 

Please @SecOp187, send us the execution log appending `bash -x` like the other day. Thanks!!
Make sure you are not retrying the build but creating a new one.

**Comment by MrCloudSec** [comment]
@SecOp187 as we cannot reproduce your problem we close this issue. Please, feel free to reopen it if you are still having these problems by attaching more info.

**Comment by SecOp187** [comment]
Hi @sergargar,

My build is now failing at the "UPLOAD_ARTIFACTS" phase (as shown below)
![image](https://user-images.githubusercontent.com/82619023/187519660-8ccb263f-0b3c-4d52-a58e-9d5148ffac4f.png)
This is the command I run: 
![image](https://user-images.githubusercontent.com/82619023/187519785-c96c6a8a-cddf-4622-84db-b153dd4edb3c.png)

Am I getting this error because I don't specify `-M junit-xml` and the JunitXml reports don't exist?

**Comment by MrCloudSec** [comment]
Hi @SecOp187, try it with adding `junit-xml` to -M please.

**Comment by SecOp187** [comment]
Hi @sergargar 

I added `junit-xml` and the build completed successfully.
![image](https://user-images.githubusercontent.com/82619023/188757392-aeee1f12-6e37-4dda-8512-4cc46edfdee6.png)

For the error message "Failed to send check output to AWS Security hub", should I run prowler build in each respective region? For example, Oregon: `-r us-west-2 -f us-west-2 -M junit-xml,json-asff -S -z -q`

**Comment by MrCloudSec** [comment]
Hi @SecOp187, glad to see that the build was successful. 
For the SHub error, try to do the command that you mentioned since this service is regional.
Feel free to reopen the issue if you have any problem, thank you!
