### ISSUE TITLE
Outdated CIS checks

### ISSUE THREAD

**Issue by antoniomml** [toniblyx/prowler#1191]
Hi! I have searched about Prowler to see the CIS check compliance on some AWS accounts. But I have seen that the latest CIS version you are using is 1.2.0 from 2018. The latest current version is 1.4.0 from 2021. This includes the "Storage" group of checks and changes other checks. It would be great if you could update it in a future version with all these new checks. Thanks!

**Comment by n4ch04** [comment]
Hi @antoniomml, currently we cover CIS 1.3 (we need to update some doc I think), version 1.4 is intended to be covered in Prowler 3.0.
Of course, if you want to contribute adding some CIS 1.4 new checks, that contribution will be welcomed!!

Thanks for all !!
