### ISSUE TITLE
Severity not populated

### ISSUE THREAD

**Issue by dritz-ecloud** [toniblyx/prowler#1206]
<p dir="auto"><strong>What happened?</strong><br>
When running the latest version of Prowler on EC2, Severity is not included in any outputs.  </p>
<p dir="auto"><strong>How to reproduce it</strong><br>
Steps to reproduce the behavior:</p>
<ol dir="auto">
<li>What command are you running?</li>

`./prowler -n -M html,json,csv -p aws-profile`

<li>Environment you have, like single account, multi-account, organizations, etc.</li>
running in single account mode
<li>See output</li>
</ol>
<p dir="auto"><strong>Expected behavior</strong><br>
Severity should be populated in all outputs.</p>

<p dir="auto"><strong>Screenshots or Logs</strong><br>

```<tr class="table-danger">
  <td>FAIL</td>
  <td></td>            <---- This field is always empty
  <td>123456789012</td>
  <td>us-east-1</td>
  <td>ens-op.acc.3.aws.iam.1</td>
  <td>iam</td>
  <td>1.16</td>
  <td>[check116] Ensure IAM policies are attached only to groups or roles</td>
  <td>us-east-1: xxxxxxxx_xxx has inline policy directly attached</td>
  <td>CIS Level 1</td>
  <td>IAM</td>
  <td><p class="show-read-more">By default IAM users; groups; and roles have no access to AWS resources. IAM policies are the means by which privileges are granted to users; groups; or roles. It is recommended that IAM policies be applied directly to groups and roles but not users. Assigning privileges at the group or role level reduces the complexity of access management as the number of users grow. Reducing access management complexity may in-turn reduce opportunity for a principal to inadvertently receive or retain excessive privileges.</p></td>
  <td><p class="show-read-more">Remove any policy attached directly to the user. Use groups or roles instead.</p></td>
  <td><a class="read-more" href="https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html"><i class="fas fa-external-link-alt"></i></a></td>
  <td>xxxxxxxx_xxx</td>
</tr>
```

</p>

<p dir="auto"><strong>From where are you running Prowler?</strong><br>
Please, complete the following information:</p>
<ul dir="auto">
<li>Resource: [e.g. EC2 instance, Fargate task, Docker container manually, EKS, Cloud9, CodeBuild, workstation, etc.)</li>
EC2
<li>OS: [e.g. Amazon Linux 2, Mac, Alpine, Windows, etc. ]</li>
Amazon Linux 2
<li>AWS-CLI Version [<code>aws --version</code>]:</li>

`aws-cli/2.3.0 Python/3.8.8 Linux/4.14.281-212.502.amzn2.x86_64 exe/x86_64.amzn.2`

<li>Prowler Version [<code>./prowler -V</code>]:</li>

`Prowler 2.10.0-25May2022`

<li>Shell and version:</li>
bash
<li>Others:</li>
</ul>
<p dir="auto"><strong>Additional context</strong>
Add any other context about the problem here.</p>

**Comment by toniblyx** [comment]
Thanks for your feedback @dritz-ecloud, we'd really appreciate if you could have used the issue template and we can help you better and faster.

**Comment by dritz-ecloud** [comment]
This works on a brand new instance of EC2, so must be environment related.

**Comment by n4ch04** [comment]
Hi @dritz-ecloud, what do you mean?  it is solved?

**Comment by MrCloudSec** [comment]
Hi @dritz-ecloud, we have reproduce the issue with the above information but it works fine from our side. Feel free to reopen the issue if you still encounter with this problem.
