### ISSUE TITLE
[Bug]: Failed findings in Security Hub treated like Passed

### ISSUE THREAD

**Issue by martingolisdfx5** [toniblyx/prowler#1218]
Hello guys, I just want to ask if the new version of prowler works correctly. Today I implemented Prowler into AWS account, but all findings that are in SecurityHub have Compliance status “PASSED” instead of “FAILED”.  I am using  “-q” flag for only failed findings. Previous version worked correctly with the same parameters which I used today. 
![Prowler](https://user-images.githubusercontent.com/85734946/175018682-3ff128a0-dfff-45e8-8750-d05b0a6ad980.png)

**Comment by MrCloudSec** [comment]
Hi @martingolis-dfx5, thank you for reaching out, good catch! https://github.com/prowler-cloud/prowler/pull/1219 solves this issue.
