### ISSUE TITLE
[Bug]: extra7162 error in filter retentionInDays = 365 

### ISSUE THREAD

**Issue by bcarranza** [toniblyx/prowler#1229]
Record screen

https://user-images.githubusercontent.com/19688747/175463302-54e5c809-a9d4-44d8-98e3-78118aa52b69.mov

**What happened?**  
We need to overcome the vulnerability reported by the prowler

Result | Severity | AccountID | Region | Compliance | Service | CheckID | Check Title | Check Output | CIS Level | CAF Epic | Risk | Remediation | Docs | Resource ID
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
FAIL | Medium | xxxxxxx | us-west-2 | Software and Configuration Checks | cloudwatch | 7.162 | [extra7162] Check if CloudWatch Log Groups have a retention policy of 365 days | us-west-2: x2-ops-cloudtrail-cloudwatch-alarms Log Group does not have 365 days retention period! | Extra | Data Retention | If log groups have a low reten read more... | Add Log Retention policy of 36 read more... |   | x2-ops-cloudtrail-cloudwatch-alarms

However, even though we have a 365 day retention bucket in the filter it is behaving strangely.
When we used ` !=` works.
When `==` failure. 
seems to be the opposite behavior.

**How to reproduce it**  
- Create a cloudwatch log group with 365-day retention.
- Run a traditional prowler scan and you will get the previously reported vulnerability.

**Expected behavior**  
Obtain a PASS for this vulnerability since the log group is correct.

**From where are you running Prowler?**  
Please, complete the following information:
 - Resource: [EKS)  
 - Image: [https://hub.docker.com/r/toniblyx/prowler ]
 - AWS-CLI Version [`aws-cli/2.4.10 Python/3.9.9 `]:
 - Prowler Version [`latest`]:
 
**Extra
It seems to be a direct problem with awscli and not prowler, however I wanted to report it to see if it can be mitigated in another way.

**Comment by jfagoagas** [comment]
Hi @bcarranza, thank you for reporting this issue.

We'll take a look at it and get back to you.

**Comment by jfagoagas** [comment]
Please @bcarranza test it again using the following branch `1229-bug-extra7162-error-in-filter-retentionindays`.

We've identified an issue using `jmespath` and the `LOG_GROUP_RETENTION_PERIOD_DAYS` variable. 

The problem was that `LOG_GROUP_RETENTION_PERIOD_DAYS` was declared as an integer and not as a string and when you want to use shell variables in `jmespath` you need to write it this way ```--query "logGroups[?retentionInDays==\`${LOG_GROUP_RETENTION_PERIOD_DAYS}\`].[logGroupName]"```

This is the PR with the fix: https://github.com/prowler-cloud/prowler/pull/1232

**Comment by bcarranza** [comment]
Hi @jfagoagas  It worked for me, thank you so much!!!, 
quick question: Approximately when can we have it in the latest image from https://hub.docker.com/r/toniblyx/prowler?
This is an automatic process following the merge of the pr?

**Comment by jfagoagas** [comment]
> Hi @jfagoagas It worked for me, thank you so much!!!

Perfect! I'm going to merge this PR. 

>  quick question: Approximately when can we have it in the latest image from https://hub.docker.com/r/toniblyx/prowler? This is an automatic process following the merge of the pr?

It is automated in our CI, so you'll see the latest one in a few minutes once it gets approved.
