### ISSUE TITLE
[Bug]: Prowler failing on CI

### ISSUE THREAD

**Issue by asthasrivastava48** [toniblyx/prowler#1242]
**What happened?**  
We are trying to run prowler from CI, After the scanning completes it returns **Process completed with exit code 3.**
![image](https://user-images.githubusercontent.com/83942480/176593984-9dea1ec5-c71d-4cb7-ade8-c3028d29094e.png)

**How to reproduce it**  
Attaching the workflow file for reference
<img width="542" alt="Screenshot 2022-06-30 at 10 10 28 AM" src="https://user-images.githubusercontent.com/83942480/176594264-bff2ad30-a411-4351-8230-5d7201c9f53d.png">

**Expected behavior**  
The process should gracefully exit and workflow should complete successfully

**From where are you running Prowler?**  
 - Github actions
 - Prowler Version [`./prowler -V`]: Prowler 2.10.0-25May2022

**Comment by jfagoagas** [comment]
Hi @asthasrivastava48 you need to set the `-z` when runnning Prowler on a CI. This flag do not trigger exit code 3 when a FAIL occurs. https://github.com/prowler-cloud/prowler/blob/821083639a745b7d115a222c1832efbb653591e4/prowler#L120

If you need more information use `./prowler -h` to see details of `-z` and `-Z`.

Please, test it and let us know if that works for you.

Thanks!

**Comment by asthasrivastava48** [comment]
@jfagoagas, Thanks it worked.
