### ISSUE TITLE
Python library detect-secrets not found in latest Docker image

### ISSUE THREAD

**Issue by nielsvn92** [toniblyx/prowler#1249]
Hi,

When running the latest Docker image, I see for the detect secrets checks there's an error stating the `detect-secrets` Python library isn't installed.
When I run the Docker image with version 2.10.0, it does work. Looks like a regression issue in the latest commit https://github.com/prowler-cloud/prowler/commit/172484cf08018768ba139b02fce16b2c74381a53 ?

Command that doesn't work:
`docker run -ti --rm --name prowler -v /path/to/local/prowler-output:/prowler/output --env AWS_ACCESS_KEY_ID --env AWS_SECRET_ACCESS_KEY --env AWS_SESSION_TOKEN toniblyx/prowler:latest -M html -r eu-central-1 -f eu-central-1 -c extra7141`

It gives the error:
`7.141 [extra7141] Find secrets in SSM Documents - ssm [Critical]
       INFO! eu-central-1: python library detect-secrets not found. Make sure it is installed correctly.`

Command that does work:
`docker run -ti --rm --name prowler -v /path/to/local/prowler-output:/prowler/output --env AWS_ACCESS_KEY_ID --env AWS_SECRET_ACCESS_KEY --env AWS_SESSION_TOKEN toniblyx/prowler:2.10.0 -M html -r eu-central-1 -f eu-central-1 -c extra7141`

Kind regards,

Niels

**Comment by jfagoagas** [comment]
Hi @nielsvn92 thank you for notifying this. We have a fix in progress.

We'll let you know when the PR is available.

**Comment by jfagoagas** [comment]
Please @nielsvn92 check the above PR and test it building with that Dockerfile.

Let us know if `detect-secrets` works well on your environment using it. 

Thanks!

**Comment by jfagoagas** [comment]
Hi, FYI @nielsvn92 the fix is now merged in master so the Docker image `toniblyx/prowler:latest` is available with that fix.

**Comment by nielsvn92** [comment]
Awesome, thank you for the very fast fix! 💪 
I just confirmed it is working again with the latest Docker image.

**Comment by nielsvn92** [comment]
@jfagoagas it seems there might be a regression with this fix.
I don't seem to be getting the output files anymore in /prowler/output.
Could it be due to the change in workdir on this line https://github.com/prowler-cloud/prowler/pull/1250/files#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R55?

**EDIT:** the output path is now `/home/prowler/output`.

**Comment by jfagoagas** [comment]
Hi @nielsvn92, my bad. Please, test it using this PR https://github.com/prowler-cloud/prowler/pull/1254, I've reset the original path.

**Comment by nielsvn92** [comment]
The PR is confirmed to be working correctly. Thank you very much for your swift response!

**Comment by jfagoagas** [comment]
Thank you!! Merging it!!
