### ISSUE TITLE
[Bug]: CodeBuild jobs running > 60 minutes use expired AWS credentials

### ISSUE THREAD

**Issue by jameswarren** [toniblyx/prowler#1259]
**What happened?**  
After deploying Prowler to run from AWS CodeBuild, jobs running for > 60 minutes use expired credentials and cannot further execute checks.

**How to reproduce it**  
1. What command are you running? `prowler -r us-west-2 -g iso27001 -M html -z`
2. Environment you have, like single account, multi-account, organizations, etc. `single account`
3. See error: `screenshot attached below`

**Expected behavior**  
Prowler runs using CodeBuild taking > 60 minutes should successfully execute all checks using valid AWS credentials.

**Screenshots or Logs**  
At the 60-minute mark (maximum session time used by CodeBuild), checks start using expired credentials
![Screen Shot 2022-07-08 at 5 05 43 PM](https://user-images.githubusercontent.com/260910/178084494-291402af-6022-454d-af46-ebfff2e1b5ed.png)

**From where are you running Prowler?**  
 - Resource: CodeBuild
 - OS: Amazon Linux 2
 - AWS-CLI Version [`aws --version`]: aws-cli/2.7.14
 - Prowler Version [`./prowler -V`]: v2.10.0-25May2022
 - Shell and version: bash

**Additional context**
I've identified the issue that [credentials are extracted from the container metadata at the beginning of the run and exported as environment variables](https://github.com/prowler-cloud/prowler/blob/ff33f426e5314ea24e248dcd4826d6b17679eac8/include/aws_profile_loader#L35-L40). While CodeBuild will refresh the automatically refresh the container credentials, they are not made accessible to prowler.

For our immediate needs, commenting out the `EXPORT` statements ensures prowler uses credentials from the container and executions > 60 minutes can run successfully. It is unclear to me how the specific code is used in other contexts (e.g. for organization-wide checks), but given additional guidance, I'm happy to work towards submitting a patch.

**Comment by MrCloudSec** [comment]
Hi @jameswarren, thank you for reaching out!
We'll take a look at it and get back to you.

**Comment by sergargar** [comment]
Please, try it again with the latest version. We have fix the error with the above PR.

**Comment by jfagoagas** [comment]
Hi @jameswarren, please test it again using branch `expired-token-codebuild` from this PR https://github.com/prowler-cloud/prowler/pull/1265. 

Let us know if everything is fixed.

**Comment by jameswarren** [comment]
Hi @jfagoagas and @sergargar - I can confirm the `expired-token-codebuild` branch works! Looking forward to having it merged into `master` :grin:

**Comment by jfagoagas** [comment]
Thank you @jameswarren, we're closing this issue.
