### ISSUE TITLE
[Bug]: Extra check 7.173 is listed as 'check' instead of 'extra'

### ISSUE THREAD

**Issue by mitcharoo** [toniblyx/prowler#1269]
**What happened?**  
When I list Prowler checks with `./prowler -l`, extra check 7.173 returns as `check7173` instead of `extra7173`. This obviously leads to a failure if you use that ID `./prowler -c check7173`.

**How to reproduce it**  
1. `./prowler -l`
2. `./prowler -c check7173`

**Expected behavior**  
The list of checks should return 7.173 as `[extra7173] Security Groups created by EC2 Launch Wizard`

**Screenshots or Logs**  
![2022-07-19_17-27-40](https://user-images.githubusercontent.com/44173271/179865451-59660e5b-572d-448e-a1df-15b0170ee17d.jpg)
![2022-07-19_17-23-41](https://user-images.githubusercontent.com/44173271/179865466-cf4e3fa6-acb6-4090-8a7f-f9a90c8c4a67.jpg)

**From where are you running Prowler?**  
 - Resource: Workstation VM
 - OS: Ubuntu 20.04
 - AWS-CLI Version [`aws --version`]: aws-cli/2.4.11
 - Prowler Version [`./prowler -V`]: Prowler 2.10.0-25May2022

**Additional context**
The value of `CHECK_TITLE_extra7173` should be changed to `[extra7173] Security Groups created by EC2 Launch Wizard` to avoid confusion.

**Comment by jfagoagas** [comment]
Hi @vigah, thank you for notifying this. We're going to review it!
