### ISSUE TITLE
[Bug]: Missing API permission in prowler-additions-policy.json

### ISSUE THREAD

**Issue by mikevirgilio** [toniblyx/prowler#1277]
When validating the latest 2.11 version, I noticed the scan hang while assessing appstream until it timed out.  Access Denied errors were generated at the console, as well as within CloudTrail.
The API call which was missing is: appstream:DescribeFleets

It is not part the AWS managed policies ViewOnlyAccess nor SecurityAudit.  
It is also not included in the prowler-additions-policy.json policy listed in the prowler-cloud repo.

I have added it to my IAM Role and have validated that the issue is resolved.

stdout:
7.190 [extra7190] Ensure user maximum session duration is no longer than 10 hours. - [1;35mappstream[0;39m [0;33m[Medium][0;39m
      [1;33m INFO![0;39m eu-north-1: Access Denied trying to describe appstream fleet(s)
      [1;33m INFO![0;39m ap-south-1: Access Denied trying to describe appstream fleet(s)

CloudTrail:
    "userAgent": "aws-cli/2.7.17 Python/3.9.11 Linux/4.14.287-215.504.amzn2.x86_64 exe/x86_64.amzn.2 prompt/off command/appstream.describe-fleets",
    "errorCode": "AccessDenied",
    "errorMessage": "User: arn:aws:sts::XXXXXXXXX:assumed-role/ProwlerExecRole/ProwlerAssessmentSession is not authorized to perform: appstream:DescribeFleets on resource: arn:aws:appstream:us-east-1:XXXXXXXXXXXXX:fleet/* because no identity-based policy allows the appstream:DescribeFleets action"

**Comment by jfagoagas** [comment]
Hi @micvirgi, thank you for notifying this. Please, check it again using the following branch https://github.com/prowler-cloud/prowler/pull/1278

Thanks!
