### ISSUE TITLE
check712: improved Macie detection option

### ISSUE THREAD

**Issue by williambrady** [toniblyx/prowler#1279]
I was looking at check_extra712 where the tool is looking for a Macie role instead of evaluating the status of the service. Via AWS CLI you can determine is Macie is enabled by making an innocuous call.

**With Macie Enabled**
```
will@fluffy:~/development/prowler$ aws macie2 list-findings
{
    "findingIds": []
}
```

**With Macie disabled**

```
will@fluffy:~/development/prowler$ aws macie2 list-findings

An error occurred (AccessDeniedException) when calling the ListFindings operation: Macie is not enabled.
```

**With bad credentials**
```
will@fluffy:~/development/prowler$ aws macie2 list-findings --profile cleaner

An error occurred (UnrecognizedClientException) when calling the ListFindings operation: The security token included in the request is invalid.
```

This seems like a more direct method than counting roles and recommending the user / admin manually verify. Please let me know if this type of request is valuable and if the content was sufficient.

**Comment by jfagoagas** [comment]
Hi @williambrady, thank you for catching this.

You're absolutely right, could you make a PR to update this check?

That way to check if Macie is enabled was for Macie V1, but like you said, it is no longer needed.

**Comment by williambrady** [comment]
I have the changes written and tested locally. Turns out there's a better way to check status that also includes when Macie is Enabled but Suspended (not processing new results). 

Do you want me to merge to main or can I have permissions to create a branch?

**Comment by jfagoagas** [comment]
Hi @williambrad, you can open a new PR to Prowler master branch from whatever branch you have.

If you have a Prowler fork is as simple as PR to prowler:master.

Thank you again for your contribution!

**Comment by williambrady** [comment]
PR submitted.

**Comment by MrCloudSec** [comment]
Thank you again @williambrady! Feel free to reopen the issue if you have any comments, your PR is now merged.
