### ISSUE TITLE
[Bug]: CHECK_REMEDIATION_check12

### ISSUE THREAD

**Issue by gregorschulz** [toniblyx/prowler#1280]
**What happened?**  
Findings with check12 show a remediation of

CHECK_REMEDIATION_check12='Enable MFA for root account. MFA is a simple best practice that adds an extra layer of protection on top of your user name and password. Recommended to use hardware keys over virtual MFA.'

**How to reproduce it**  
prowler run of version 2.11.0-21July2022

**Expected behavior**  
Don't propose remediating this check by enabling MFA for root as this is wrong.

**Comment by jfagoagas** [comment]
Hi @gregorschulz, we are going to review this. 

Thank you for notifying this!

**Comment by jfagoagas** [comment]
Hi @gregorschulz, we've modified it in this PR https://github.com/prowler-cloud/prowler/pull/1281
