### ISSUE TITLE
extra7190, 7191, 7192, 7193 appstream regions

### ISSUE THREAD

**Issue by williambrady** [toniblyx/prowler#1293]
**Is your feature request related to a problem? Please describe.**

Currently appstream is not available in all regions, so when the scans happen for `sa-east-1` for example, they generate errors which result in a Fail state. It's also not available in `eu-north-1` but AWS returns a different error, making the check overall unreliable.

**Describe the solution you'd like**

Unless you already have a service-specific region list, I would like to generate one by adding a check-specific REGIONS value:

`curl -s https://api.regional-table.region-services.aws.a2z.com/index.json | jq -r '.prices[].attributes|select(."aws:serviceName" == "Amazon AppStream 2.0") | ."aws:region"'`

This will return a current list of regions for the specific service. This could also be done at a higher level of code logic (like globally generate lists for all the services and have the checks call back) but embedding this in the affected modules doesn't seem to add excessive overhead.

**Describe alternatives you've considered**

Another option would be to populate a map of services to regions that  is populated at run-time, and allow each module to call their respective REGION list. This could be better long term, but would take more planning since I don't know all the inner workings of the scripts yet. Additionally, we'd likely load up all the regions for all services even if we are only checking 1-2 services, so there could be unexpected latency in execution.

**Comment by williambrady** [comment]
Submitted PR for potential improvement to these scans.

**Comment by jfagoagas** [comment]
Hi @williambrady, thank you for your contribution, we are going to include this map of regions and services for Prowler v3. 

Regarding your issue and the related PR, we are not being able to reproduce your issue because these checks correctly handle errors in the event that the audited region does not support the AppStream service. Please, take a look here:
- `extra7190`: https://github.com/prowler-cloud/prowler/blob/c1d60054e996ed50bb33024077e1344fc1fb9643/checks/check_extra7190#L31
- `extra7191`: https://github.com/prowler-cloud/prowler/blob/c1d60054e996ed50bb33024077e1344fc1fb9643/checks/check_extra7191#L31
- `extra7192`: https://github.com/prowler-cloud/prowler/blob/c1d60054e996ed50bb33024077e1344fc1fb9643/checks/check_extra7192#L31
- `extra7193`: https://github.com/prowler-cloud/prowler/blob/c1d60054e996ed50bb33024077e1344fc1fb9643/checks/check_extra7193#L31

Thanks!

**Comment by jfagoagas** [comment]
Hi @williambrady, I've seen the problem.

For the AWS region `sa-east-1` the CLI is returning the following error which is not being handled correctly: `Connect timeout on endpoint URL: "https://appstream2.sa-east-1.amazonaws.com/"'`

I'm going to close your PR and open a new one to handle this type of error.

**Comment by jfagoagas** [comment]
Please @williambrady, test it again with the following branch `PRWLR-747-fix-extra-7190-7191-7192-7193-app-stream-regions` and let us know if everything works fine. 

Thanks!

**Comment by williambrady** [comment]
I did notice the other service-region related issues that had been filed over the weekend, so I think the larger service map is the better approach. I will test the branch listed and hold off on future comments about regions until I get to play with v.3!

Thank you!

**Comment by williambrady** [comment]
I think `PRWLR-747-fix-extra-7190-7191-7192-7193-app-stream-regions` was cleared when merged with `Master`, but testing against the current `Master` works as expected, except for the long pause for `sa-east-1` to timeout. 

The service map work will fix this. 

Thanks again!

**Comment by jfagoagas** [comment]
> I did notice the other service-region related issues that had been filed over the weekend, so I think the larger service map is the better approach. I will test the branch listed and hold off on future comments about regions until I get to play with v.3!
> 
> Thank you!

Yes, the service-region map is the best approach especially to avoid unnecessary API calls to AWS.

> I think `PRWLR-747-fix-extra-7190-7191-7192-7193-app-stream-regions` was cleared when merged with `Master`, but testing against the current `Master` works as expected, except for the long pause for `sa-east-1` to timeout.
> 
> The service map work will fix this.
> 
> Thanks again!

Sorry for that, we merged it before you test. Thank you again for your contribution!
