### ISSUE TITLE
[Bug]: check_extra747 detects AWS Neptune instances (no CloudWatch exports) and reports a false-positive

### ISSUE THREAD

**Issue by analytically** [toniblyx/prowler#1348]
The check_extra747 check includes AWS Neptune instances in it's query response, creating false positives for CloudWatch exports being 'disabled' for this instance. CW exports are only used for MySQL and Postgres RDS.

**Comment by n4ch04** [comment]
Hi @analytically, please, to help us to triage the issue, could you fill the issue template to provide more information ?

**Comment by n4ch04** [comment]
Hi @analytically, since we do not get feedback from your side we are going to close the issue.
Please feel free to reopen the issue providing more details if the error persists.
