### ISSUE TITLE
[Bug]: Error while getting credentials

### ISSUE THREAD

**Issue by RenukaMane** [toniblyx/prowler#1369]
**What happened?**  
Failing to get the credentials(Have set the AWS credentials in the environment variables as well as in the credentials file)

**How to reproduce it**  
1. I am using the docker command to run prowler on windows
2. I am using my organizations AWS account to test the tool
3. See error

**Expected behavior**  

**Screenshots or Logs**  
<img width="796" alt="Screenshot 2022-09-15 150631" src="https://user-images.githubusercontent.com/53396422/190372026-d9d96cac-9d4d-4387-b175-c06d53490c6e.png">

**From where are you running Prowler?**  
Please, complete the following information:
 - Resource: Docker container manually  
 - OS: Windows
 - AWS-CLI Version [2.5.4]:
 - Prowler Version [`./prowler -V`]:
 - Shell and version:
 - Others:

**Additional context**

**Comment by n4ch04** [comment]
Hi @RenukaMane, we are reviewing it, in the meantime, could you check if those env variables are filled with its proper values to log against AWS?

**Comment by RenukaMane** [comment]
Thanks for your response changed some permission settings on the AWS account. Got it working.
