### ISSUE TITLE
[Bug]: AWS CloudShell close the shell connection before prowler can finish the checks

### ISSUE THREAD

**Issue by ldina** [toniblyx/prowler#1377]
**What happened?**  
I run prowler as configured in [shortcut.sh](https://github.com/prowler-cloud/prowler/blob/master/util/cloudshell/shortcut.sh), prowler can't finish the checks because it takes longer than the shell session maximum time. AWS CloudShell disconnect the shell and prowler stop without completing the scan.

**How to reproduce it**  

1. What command are you running? screen -dmS prowler sh -c "./prowler -M csv,html;cd ~;zip -r ${account}-results/prowler-${account}.zip /home/cloudshell-user/prowler/output"

2. Environment:  I'm connected to an account that is a member of an organization
3. See error: connection closed on the AWS Cloudshell while prowler still running

**Expected behavior**  
I see different option here:

- A reference on the documentation that AWS Cloud Shell can be used to run prowler just for a quicker scan versus full check
- A workaround to trick or configure the shell session length in AWS Cloud Shell
- A change in prowler so that can resume an interrupted scan caused by AWS Cloud shell session closing  without starting from scratch

**Screenshots or Logs**  
N/A

**From where are you running Prowler?**  
Resource: AWS CloudShell
OS: Linux/4.14.291-218.527.amzn2.x86_64
AWS-CLI Version [aws --version]: aws-cli/2.7.34 Python/3.9.11 Linux/4.14.291-218.527.amzn2.x86_64 exec-env/CloudShell exe/x86_64.amzn.2 prompt/off
Prowler Version [./prowler -V]: Prowler 2.11.0-21July2022
Shell and version: GNU bash, version 4.2.46(2)-release (x86_64-koji-linux-gnu) - Others:

**Additional context**
I guess that probably nothing can be done on the AWS Cloud Shell because is interactive by design
https://docs.aws.amazon.com/cloudshell/latest/userguide/limits.html#session-lifecycle-limitations

**Comment by MrCloudSec** [comment]
Hi @ldina, thank you for reaching out! Please, can you try this command instead?
`./prowler -M csv,html;cd ~;zip -r ${account}-results/prowler-${account}.zip /home/cloudshell-user/prowler/output`

**Comment by ldina** [comment]
Hi @sergargar , thanks for the help and the suggestion. I run it again with your command:

Started at Date: Thu Sep 29 14:55:46 UTC 2022 --> Stopped at 15:51

**See error:**
![Schermata 2022-09-29 alle 18 11 00](https://user-images.githubusercontent.com/43407568/193083876-3cd467d3-712b-41a1-b8b0-7fe9fc93e972.png)

**See last checks:**
7.32 [extra732] Check if Geo restrictions are enabled in CloudFront distributions - cloudfront [Low]
       INFO! eu-west-1: No CloudFront distributions found
7.33 [extra733] Check if there are SAML Providers then STS can be used - iam [Low]
       FAIL! eu-west-1: No SAML Provider found. Add one and use STS
7.34 [extra734] Check if S3 buckets have default encryption (SSE) enabled or use a bucket policy to enforce it - s3 [Medium]
       PASS! eu-west-1: Bucket cf-templates-lrjv5tidwkyl-eu-west-1 is enabled for default encryption with AES256
7.35 [extra735] Check if RDS instances storage is encrypted - rds [Medium]
Lost your connection to the environment.
Press any key to reconnect and continue using AWS CloudShell

**Restarting the CludShell I see the partial output files:**

-rw-rw-r-- 1 cloudshell-user cloudshell-user 1230203 Sep 29 15:51 prowler-output-xxx-20220929145546.csv
-rw-rw-r-- 1 cloudshell-user cloudshell-user 1682377 Sep 29 15:51 prowler-output-xxx-20220929145546.html

**Comment by MrCloudSec** [comment]
Hi @ldina, with the commands on section 6 in this [[link](https://github.com/prowler-cloud/prowler/tree/master/util/cloudshell)](url), you can force user interaction in CloudShell.
Let us know if that works!

**Comment by ldina** [comment]
@sergargar unfortunately the command does not help. It keeps closing the connection before finishing

![image](https://user-images.githubusercontent.com/43407568/194330054-e38fd751-533b-4dd7-aec8-ac6a2347b6d1.png)

**Comment by jfagoagas** [comment]
Hi @ldina we need to dig in more because there are some CloudShell timeouts involved:

![Screenshot 2022-10-06 at 16 44 33](https://user-images.githubusercontent.com/16007882/194343807-bd2188a9-8a0d-46dd-a6f7-55864e4dffc2.png)
![Screenshot 2022-10-06 at 16 44 27](https://user-images.githubusercontent.com/16007882/194343847-5e6de889-6aa4-4592-8400-c652eecfd9d4.png)

**Comment by ldina** [comment]
@jfagoagas yes, I agree with you. I'm available for testing

**Comment by jfagoagas** [comment]
@ldina I don't know if we can do more from our side because the CloudShell needs user interaction to keep running. The good thing is that with Prowler v3 we are going to address all the speed and efficiency issues.

**Comment by ldina** [comment]
@jfagoagas since the use-case of the CloudShell make a lot of sense to me, I did some more testing and I discovered that analyzing just one region reduces the processing time enough to keep the session happy. So my workaround is to run it like -f eu-west-1. My suggestion is to collect this parameter on the script execution.

**Comment by jfagoagas** [comment]
> @jfagoagas since the use-case of the CloudShell make a lot of sense to me, I did some more testing and I discovered that analyzing just one region reduces the processing time enough to keep the session happy. So my workaround is to run it like -f eu-west-1. My suggestion is to collect this parameter on the script execution.

Hi @ldina this is a good workaround, also you can run Prowler in parallel by region using:
`cat regions.txt | parallel -j <Number of workers> -I {} ./prowler -f {} -M csv -o $(date +%F)_{}`

I'm closing this issue, please feel free to reopen it if you need it. 

Thanks!
