### ISSUE TITLE
[Bug]: check21 Reports Failed If Second Trail is Off

### ISSUE THREAD

**Issue by jasonwadsworth** [toniblyx/prowler#1391]
**What happened?**  
Running check21 returned a failure for one of the trails in my account that is turned off.

**How to reproduce it**  
Include multiple trails in your account and turn one off.

**Expected behavior**  
The risk is that you don't have cloud trail turned on in a region, not that an individual trail is not on. I would expect this check to look for the existence of at least one active trail and return a passing state if there is one. There isn't a reason to check the status of each trail for this check, as that's not what the check purports to do.

**Screenshots or Logs**  
Also, you can add logs (anonymize them first!). Here a command that may help to share a log
`bash -x ./prowler -options > debug.log 2>&1` then attach here `debug.log`

**From where are you running Prowler?**  
Please, complete the following information:
 - Resource: Lambda
 - OS: Lambda
 - AWS-CLI Version [`aws --version`]: Not sure, though it doesn't really matter for this bug
 - Prowler Version [`./prowler -V`]: Not sure, but the code was pulled on September 14th
 - Shell and version:
 - Others:

**Additional context**

**Comment by MrCloudSec** [comment]
Hi @jasonwadsworth, thank you for reaching us out!
Good catch, considering this use case we think that the best option for you would be to whitelist the check since the check logic would have an important change.
For the next version, we will have your issue in mind and reformulate the check in a better way.

**Comment by MrCloudSec** [comment]
@jasonwadsworth check my above comment, reopen the issue if you need anything else!

**Comment by jasonwadsworth** [comment]
> @jasonwadsworth check my above comment, reopen the issue if you need anything else!

Any thoughts on a new check that does it correctly? I understand the issue with a change in behavior (big believer in [Hyrum's Law](https://www.hyrumslaw.com/)). It would be nice to be able to have a solution to this.
