### ISSUE TITLE
[Bug]: Invalid Data Structure Prowler CSV Report 

### ISSUE THREAD

**Issue by ykaiboussi** [toniblyx/prowler#1393]
There is discrepancy of the data structure of CVS file output vs expected JSON [format](https://github.com/prowler-cloud/prowler#json). 
Command:
`./prowler -b -n -f EDIT_AWS_REGION -g cislevel1 -M csv > prowler_report.csv`

<img width="1043" alt="Screen Shot 2022-10-08 at 5 06 33 PM" src="https://user-images.githubusercontent.com/10117389/194729637-5c0defe0-c01e-4f98-92d1-ba8d20af044c.png">

Here is another image as JSON output.

<img width="1047" alt="Screen Shot 2022-10-08 at 6 01 09 PM" src="https://user-images.githubusercontent.com/10117389/194730638-c121c08a-2bff-4de8-8dc0-136ac828e069.png">

**Comment by n4ch04** [comment]
Hi @ykaiboussi, first of all thanks for using Prowler !!
To export the results in `.csv` format you don't need to redirect the tool output to a file, the tool itself generates a `.csv` file.
Right now you are storing all the info that the tool shows in your screen into a file.
To get the results in different formats:
```
./prowler -b -n -f EDIT_AWS_REGION -g cislevel1 -M csv
./prowler -b -n -f EDIT_AWS_REGION -g cislevel1 -M json
```
Please check it and let us know it the issue persists

**Comment by ykaiboussi** [comment]
@n4ch04 Thank you for the insight helped resolve my issue. I updated the script to read the report from `output` as CSV format and parsed the file to generate a JSON to load data Dynamodb table.

**Comment by ykaiboussi** [comment]
I'm closing the issue since no action is needed.
