### ISSUE TITLE
[Bug]: Inventory option does not list RDS instances

### ISSUE THREAD

**Issue by ldina** [toniblyx/prowler#1396]
**What happened?**  
running prowler with inventory option does not list RDS instances in the inventory output

**How to reproduce it**  
1. What command are you running? ./prowler -i on AWS Cloudshell
2. Environment :I'm connected to an account that is a member of an organization
3. See error:  List of type of resources per service for AWS Account xxx -=-

-=- cloudformation service -=-
      1 stack
      2 stackset
-=- ec2 service -=-
      3 instance
      1 snapshot
      5 vpc-endpoint
-=- events service -=-
      1 rule
-=- iam service -=-
      1 group
      1 policy
     17 role
      1 user
-=- lambda service -=-
      2 function
-=- ssm service -=-
      4 document

Total resources found: 39

**Expected behavior**  
The RDS instances should be included in the inventory as they are covered by the checks.
Running  ./prowler -g rds can perform checks on RDS instances and shows existing ones

**Screenshots or Logs**  
prowler -i
![image](https://user-images.githubusercontent.com/43407568/194896825-e4c0aa85-88bf-4ee6-ab42-2c9f65b4ac91.png)
./prowler -g rds
![image](https://user-images.githubusercontent.com/43407568/194897038-04f379e7-a92c-43a1-985a-1477ffed4309.png)

**From where are you running Prowler?**  
Resource: AWS CloudShell
OS: Linux/4.14.291-218.527.amzn2.x86_64
AWS-CLI Version [aws --version]: aws-cli/2.7.34 Python/3.9.11 Linux/4.14.291-218.527.amzn2.x86_64 exec-env/CloudShell exe/x86_64.amzn.2 prompt/off
Prowler Version [./prowler -V]: Prowler 2.11.0-21July2022
Shell and version: GNU bash, version 4.2.46(2)-release (x86_64-koji-linux-gnu) - Others:

**Additional context**
I understand that the inventory option is beta so that may be an expected behaviour

**Comment by ldina** [comment]
Generally speaking, RDS should be in scope as mentioned here https://github.com/prowler-cloud/prowler/discussions/1398

**Comment by jfagoagas** [comment]
Hi @ldina the services covered by checks and by the quick inventory are not related because the latter is using the `resourcegroupstaggingapi` from AWS and at this moment it doesn't cover RDS. For that reason you are not seeing the RDS resources or some others because that API doesn't include all AWS services.


https://docs.aws.amazon.com/resourcegroupstagging/latest/APIReference/overview.html

Thanks!

**Comment by ldina** [comment]
@jfagoagas thanks for clarifying that the two options are relying on different APIs but it seems that the API you mention support it.
https://docs.aws.amazon.com/resourcegroupstagging/latest/APIReference/supported-services.html

![Schermata 2022-10-11 alle 09 52 04](https://user-images.githubusercontent.com/43407568/195030847-f4b86817-8be7-4472-9128-b4b0b375802e.png)

From the user's perspective, it's confusing if the scope of the checks and of the quick inventory is different.

**Comment by jfagoagas** [comment]
Yes @ldina my bad, this service covers RDS. 

I'm testing it in our environment and the execution using `./prowler -i` outputs the number of RDS resources. 

Prowler runs the following command underneath, can you execute it and paste the output here?
`aws resourcegroupstaggingapi get-resources --region<YOUR-REGION> --query ResourceTagMappingList[].ResourceARN --output json 2>&1)`

Please redact sensitive information.

Thanks!

**Comment by ldina** [comment]
hi @jfagoagas , no worries
I run the command you provided and the result seems comparable to what I got from prowler. So it seems that is not specific to prowler, maybe permissions related or cloudshell specific?

![image](https://user-images.githubusercontent.com/43407568/195553043-a2f66f31-54b1-4445-b285-d0de4141559c.png)

**Comment by jfagoagas** [comment]
Hi @ldina, do you have any SCPs restricting the usage of service? 

I think you need to talk with your AWS support because for some reason the Resource Groups and Tagging API is not returning your RDS instance.

Thanks!

**Comment by ldina** [comment]
Hi @jfagoagas thanks for the suggestion, I looked in the Organization SCP and is disabled. I'll talk with the AWS support and I'll let you know.
![Schermata 2022-10-14 alle 09 45 34](https://user-images.githubusercontent.com/43407568/195791395-1137ec29-51e1-43dc-8ee7-49da73ee60d0.png)

**Comment by jfagoagas** [comment]
@ldina we're closing this issue because there is no possible solution from our side. Feel free to reopen it if you need it.

Thanks for using Prowler!
