### ISSUE TITLE
[BUG]: [extra740] Resources more than max items

### ISSUE THREAD

**Issue by jfagoagas** [toniblyx/prowler#1400]
### Discussed in https://github.com/prowler-cloud/prowler/discussions/1399

<div type='discussions-op-text'>

<sup>Originally posted by **MxxxxxF** October 11, 2022</sup>
Hi Prowler, 

Regarding to this check rule [extra740] Check if EBS snapshots are encrypted, I have about 500+ EBS snapshots. 
However, based on my output, the scan only report my first 100 snapshots. 
Is this a limitation?
How can I have prowler to scan all of my snapshots? 

Current the output display as below
PASS - 99. snapshot_99 is encrypted 
PASS - 100.snapshot_100 is encrypted
PASS - 101. 500 encrypted snapshots out of 500 snapshots found. Only the first 100 encrypted snapshots are reported.
INFO  - 102. 0 unencrypted EBS volume snapshots out of 500 total snapshots

Thank you</div>

**Comment by ifduyue** [comment]
> -m <maxitems>       Specify the maximum number of items to return for long-running requests (default: 100).

**Comment by jfagoagas** [comment]
Hi @MxxxxxF we fix it refactoring the logic to show one line per resource and getting rid of the % value because it doesn't follow Prowler's checks pattern.

With that you can use the `-m` option to set the `MAX_ITEMS` value for long-running requests.

Feel free to reopen it if you face more problems regarding that issue.

Thank you for you contribution.

**Comment by MxxxxxF** [comment]
Thank you so much for fixing this. 
Would like to check, if I just run ./prowler across my entire account. I will still have to state the max item with -m right? else it will only run the default item which will be 100?
E.g: ./prowler -m 500?

**Comment by jfagoagas** [comment]
> 

Yes, you're right, you have to set the `-m <MAX_ITEMS>` value. By default the value is 100.

**Comment by jfagoagas** [comment]
> Thank you so much for fixing this. Would like to check, if I just run ./prowler across my entire account. I will still have to state the max item with -m right? else it will only run the default item which will be 100? E.g: ./prowler -m 500?

You're right @MxxxxxF, you have to set the `-m <MAX_ITEMS>` value. By default the value is 100.
