### ISSUE TITLE
feature: Add a docker tag for the latest stable release

### ISSUE THREAD

**Issue by jansepke** [toniblyx/prowler#1412]
Currently the latest tag on docker hub points to the latest commit on master. This can result in broken prowler executions if one is using this tag. Could you either change the latest tag to point to the latest release or add a new tag e.g. "stable" that points to the latest release?

**Comment by n4ch04** [comment]
Hi @jansepke thanks for using Prowler!!

Regarding your question, we use the `master` branch as the latest version of Prowler. For stable releases you can check them here https://github.com/prowler-cloud/prowler/releases

Also, for every release we have the container image, check the v2.11.0 [here](https://hub.docker.com/layers/toniblyx/prowler/2.11.0/images/sha256-4ef5bd8bd5c9118058fa1714107c56dfc16c49418472539e8e0b42accae1743b?context=explore)

We are considering to point the stable tag to the latest stable release (which is v2.11.0 right now).

If you need more help, please let us know.

**Comment by jansepke** [comment]
Thank you. A stable tag pointing to the latest released version would help us

**Comment by n4ch04** [comment]
@jansepke we have included that feature here #1419 and we will publish a new release soon.
If you need something else, please let us know.
Thanks!!
