### ISSUE TITLE
[Bug]: Does not see organization cloudtrail

### ISSUE THREAD

**Issue by zfLQ2qx2** [toniblyx/prowler#1427]
We just rebuilt our Prowler image and it looks like something changed, it looks like checks 21-27 no longer see organization cloudtrails in other regions. I think these are also called "shadow" cloudtrails sometimes, the cloudtrail exists in the organization master account and receives events for all regions. They are visible in the child accounts but do not belong to the account. I'll see if I can spot the change.

**Comment by n4ch04** [comment]
Hi @zfLQ2qx2, we made some changes on those checks here #1390 to remove duplicates.
What is exactly what you would like the checks to show and it is no longer showing?
Please check it out the PR and if you provide more details we will be able to help you  with the troubleshooting.
Thanks for using Prowler !!

**Comment by zfLQ2qx2** [comment]
@n4ch04 Hmm, I don't immediately see why https://github.com/prowler-cloud/prowler/pull/1390 would have caused the issue, I need to step through it. I believe that if a shadow trail (organization trail) is present then that should satisfy the requirement - even if the trail does not "belong" to that count. Shadow trails will be visible from the account but the arn will reflect the account where they were created. We only rebuild our prowler image every few months so there might be an earlier change also. I'll take a look as soon as my morning meetings are done.

**Comment by n4ch04** [comment]
From the docs, https://docs.aws.amazon.com/cli/latest/reference/cloudtrail/describe-trails.html the flag `--include-shadow-trails` is by default set to `True`, since we do not set that flag in the API calls it should return the shadow trails

**Comment by zfLQ2qx2** [comment]
@n4ch04 I found one problem here - https://github.com/prowler-cloud/prowler/blob/master/checks/check21#L41 

It disregards any cloudtrail not created in the same region as being queried. That is not valid in the case of a multi-region cloudtrail because it "exists" in a single region and then receives events for all regions. The check on line 41 might be valid in the case of a single-region cloudtrail but it would have to be done much later in the function after the cloudtrail is described.

**Comment by zfLQ2qx2** [comment]
@n4ch04 So I guess it was 1390 after all, moving those checks inside the region loops is what broke those seven checks. So the "duplication" output you were trying to suppress there wasn't actually duplicate, it was listing the multi-region and organization trails that satisfied the conditions of the check in each region. An alternate way to remove the "duplicate" text would be to look for multi-region trails and only look for individual regional trails is no multi-region trail exists. In the mean time can we back out the changes for checks21-27 in 1390?

**Comment by n4ch04** [comment]
@zfLQ2qx2 Reviewing the changes in the check it seems that we changed something else since that line it had not been changed since two years https://github.com/prowler-cloud/prowler/blame/5a43ec951a1c600ca4551a5a0dd467caff13ab52/checks/check21#L41
At this point I think that it would be better if we solve the issue rewriting some parts of the check.
Since we are looking for at least one trail enabled and logging in each region I would iterate over the trails returned in each region, if one of the trails (including shadow trails) is enabled and logging in that region, set as `PASS` and move to the next one.
I'm going to correct that in a new branch, you can test it, and if it works I can do the same changes in the other 6 checks affected to solve the issue.
I'll post here the branch link once I have it

**Comment by n4ch04** [comment]
A workaround for the issue is here https://github.com/prowler-cloud/prowler/tree/PRWLR-973-prowler-2-x-check-21, @zfLQ2qx2 please check it out and let us know if it works right now, if so we can propagate the same logic for the checks 22-27

**Comment by zfLQ2qx2** [comment]
@n4ch04 Seems to work well, we need the same thing for checks 22-27 also.

**Comment by n4ch04** [comment]
Nice, we will propagate the changes

**Comment by n4ch04** [comment]
Changes have been merged here https://github.com/prowler-cloud/prowler/pull/1433, please test it and feel free to reopen this issue if something goes wrong.
Thanks for all !!
