### ISSUE TITLE
[Bug]:  Wrong remediation (`'Ensure this repository and its contents should be publicly accessible.'`) for check extra 71

### ISSUE THREAD

**Issue by ifduyue** [toniblyx/prowler#1430]
**What happened?**  

https://github.com/prowler-cloud/prowler/blob/5a43ec951a1c600ca4551a5a0dd467caff13ab52/checks/check_extra71#L13-L27

Remediation for [check extra 71 ](https://github.com/prowler-cloud/prowler/blob/master/checks/check_extra71), `'Ensure this repository and its contents should be publicly accessible.'`, was likely copied & pasted from [check extra 77](https://github.com/prowler-cloud/prowler/blob/master/checks/check_extra77).

It doesn't make sense since this check is `"[extra71] Ensure users of groups with AdministratorAccess policy have MFA tokens enabled"`

**Comment by n4ch04** [comment]
Hi @ifduyue, we'll check this out and let you know, thanks for using Prowler !!

**Comment by ifduyue** [comment]
@n4ch04 Thank you
