### ISSUE TITLE
[Bug]: KMS keys and allowlist

### ISSUE THREAD

**Issue by erkwish** [toniblyx/prowler#1458]
**What happened?**  **How to reproduce it** 
I tried to whitelist a KMS key with the help of the allowlist. I used the check:resource format as stated in the exemple file. I didn't work I was still given a fail. I read something in a discussion in your gh that you used the (n)th record for match for the allowlist. So I figured that the "-" in the key may work as a whitespace so I tried to match on the part before the "-" and it worked. 

**Expected behavior**  
check:2345435-235251-52635734-23465 should work and not only check:2345435

**From where are you running Prowler?**  
 - Resource: ESK
 - OS: Amazon Linux 2 or Ubunto
 - AWS-CLI Version [`aws --version`]:latest
 - Prowler Version [`./prowler -V`]: 2.11.0
 - Shell and version: bash

**Comment by toniblyx** [comment]
Hi @erkwish, can you share the exact allow list file with mock data to make sure the syntax is correct and try to reproduce it with the proper check? Thanks in advance!

**Comment by erkwish** [comment]
As now I only have one entry in my allowlist file:
extra8001:abcabcab
This generates this:
WARNING! eu-central-1: Key abcabcab-abca-abca-abca-abcabcabcabc is not managed in Thales
Doing this:
extra8001:abcabcab-abca-abca-abca-abcabcabcabc
This generates this:
FAIL! eu-central-1: Key abcabcab-abca-abca-abca-abcabcabcabc is not managed in Thales

**Comment by MrCloudSec** [comment]
Hi @erkwish, thank you for reaching us out!
Could you try to escape the "-" character with `\-`?

**Comment by n4ch04** [comment]
Hi @erkwish since we do not receive feedback from you we assume that the issue is solved, please feel free to reopen of create a new one if the issue still persists
