### ISSUE TITLE
[Bug]: extra7133 Fails on Aurora

### ISSUE THREAD

**Issue by jasonwadsworth** [toniblyx/prowler#1459]
**What happened?**  
When running this check on an account with an Aurora database the check fails. This is because the Aurora cluster is multi-az, not the instances in the cluster. For Aurora the cluster should be checked instead.

**How to reproduce it**  
Create an Aurora RDS instance with multi-az on. The check will fail. You can also run the command that this check is running and see the issue.
```
aws rds describe-db-instances
```

**Expected behavior**  
It should pass because the cluster is multi-az.

**Screenshots or Logs**  

**From where are you running Prowler?**  

**Additional context**
Running `aws rds describe-db-clusters` instead for Aurora would address the issue.

**Comment by MrCloudSec** [comment]
Hi @jasonwadsworth, thank you for reaching us out!
We will review this issue shortly and let you know.

**Comment by MrCloudSec** [comment]
Hi @jasonwadsworth, sorry for the late response. 
This use case would be for a different check and it will be included in the new version 3.
Stay tuned for the release!
Thank you for your feedback 😄

**Comment by jasonwadsworth** [comment]
> Hi @jasonwadsworth, sorry for the late response. 
> 
> This use case would be for a different check and it will be included in the new version 3.
> 
> Stay tuned for the release!
> 
> Thank you for your feedback 😄  

I think it's fine for this to be a different check, so long as the existing check doesn't fail.
