### ISSUE TITLE
[Bug]: -M text,... -o ... fails validation of -o with -M arg containing 'text'

### ISSUE THREAD

**Issue by ghost** [toniblyx/prowler#1464]
**What happened?**  

When using `-M` with multiple modes, one of which being 'text', validation of the custom output directory fails. The order of the modes does not matter, so long as one of them is 'text'.

```
$ AWS_PROFILE=my-profile prowler -M html,text -o prowler/output -F extra714.my-profile -c extra714
 ...
 ERROR! - When using custom directory output Mode (-M) has to be set as well. Use -h for help.
```

(the -F and -c are extraneous)

**Expected behavior**  

I expect output to be sent to the terminal, as well as an HTML output saved to prowler/output/extra714.my-profile.html

**From where are you running Prowler?**  
Please, complete the following information:
 - OS: Ubuntu 20.04
 - Prowler Version [`./prowler -V`]: v2.12.0-27October2022
 - Shell and version: GNU bash, version 5.1.16(1) on

**Workaround**

Instead of using 'text' mode, use 'mono'; so for example:

```
$ AWS_PROFILE=my-profile prowler -M html,mono -o prowler/output -F extra714.my-profile -c extra714
 ...
```

**Patch**  

Looking at the code, the problem stems from include/validate_options. Here's a patch 

```
-- prowler/include/validate_options.bak        2022-11-11 01:02:47.523433013 +0000
+++ prowler/include/validate_options    2022-11-11 01:04:12.764855011 +0000
@@ -147,7 +147,7 @@
     if [ -n "${OUTPUT_DIR_CUSTOM}" ]
     then
         # If dir custom, mode has to be enabled (if you provide a custom directory it's because you want to store something)
-        if [[ ! "${MODE}" =~ 'text' ]]
+        if [[ "${MODE}" != 'text' ]]
         then
             # Check if custom folder exists
             if [ ! -d "${OUTPUT_DIR_CUSTOM}" ]
```

Which can be applied a command such as:

```
patch -u prowler/include/validate_options /components/prowler/issue-1464.patch
```

With this in place, the following command runs to completion:

```
AWS_PROFILE=my-profile prowler -M html,text -o prowler/output -F extra714.my-profile -c extra714
```

Thanks for creating Prowler!

**Comment by n4ch04** [comment]
Hi @pythiankerr thanks for your feedback, we'll check this out and let you know

**Comment by n4ch04** [comment]
@pythiankerr The mode `text` is the default mode, you don't need to set it, that's why it is tested in that logic.
To get the results in a "plain text" format you need to set the mode csv, since the text mode only shows the results in your screen.

**Comment by n4ch04** [comment]
Can we help you with something else?

**Comment by ghost** [comment]
@n4ch04 Thanks for replying. I can confirm that running with `-M html` outputs both HTML and Text.

Would be good to clarify this in Prowler 3 (if applicable). I was expecting `-M html` to turn off 'text' mode.

Thanks,
Cameron
