### ISSUE TITLE
[Bug]: AWS_DEFAULT_OUTPUT is becoming unset, failing checks when output=yaml set in ~/.aws/config

### ISSUE THREAD

**Issue by ghost** [toniblyx/prowler#1472]
**What happened?**  

I find YAML much easier to read than JSON, so I set `output = yaml` in my ~/.aws/config file. The few checks I've run so far mostly worked okay (eg. extra773) work fine, but others (eg. check3x) will fail because they attempt to parse output with `jq` and assume `aws` will output in its default JSON.

**How to reproduce it**  

In ~/.aws/config

```
[profile accountN]
...
output = yaml
```

```
AWS_PROFILE=accountN prowler -c check35
...
3.5 [check35] Ensure a log metric filter and alarm exist for CloudTrail configuration changes - cloudtrail [Medium]
parse error: Invalid numeric literal at line 1, column 2
```

**Expected behavior**  

Prowler should not assume output format and should set it explicitly to json when piped to `jq`, output should be identical to the case where user has not set preferred output format.

**Screenshots or Logs**  

Running prowler with `bash -x` only showed debugging options at the startup, and then not after. I modified `check3x` adding `set -x` at the beginning of the function, which then illustrated the following:

```
++ jq -r -c '.[] |@base64'
++ echo - CloudWatchLogsLogGroupArn: 'arn:aws:logs:us-east-1:REDACTED:log-group:aws-controltower/CloudTrailLogs:*' ...REDACTED
parse error: Invalid numeric literal at line 1, column 2
```

`parse error` is being reported by `jq` because the input (`echo - ...` is not JSON but instead YAML (with newlines removed))

**From where are you running Prowler?**  
Please, complete the following information:
 - Resource: Docker container
 - OS: Ubuntu 20.04
 - AWS-CLI Version [`aws --version`]: aws-cli/2.8.11 Python/3.9.11 Linux/5.15.49-linuxkit exe/aarch64.ubuntu.22 prompt/off
 - Prowler Version [`./prowler -V`]: Prowler 2.12.0-27October2022
 - Shell and version: GNU bash, version 5.1.16(1)-release (aarch64-unknown-linux-gnu)
 - Others:

**Additional context**

Given the number of places this would need to change, I found that using the environment variable `AWS_DEFAULT_OUTPUT=json` is enough to override the `output = yaml` in my ~/.aws/config, but will still be overridden by an explicit `--output text`, so setting this in the prowler script should be a good way to implement this fix.

But looking at the prowler script, there is a function `set_aws_default_output`, so I set about tracing its effect after `set_aws_default_output` is run inside `prowler`, and inside `check3x()`, with the following observation:

```
DEBUG: AWS_DEFAULT_OUTPUT=json
DEBUG: within check3x AWS_DEFAULT_OUTPUT=
```

This seems to be because of the following later in prowler AWS_DEFAULT_OUTPUT is explicitly and unconditionally unset.

```bash
# Environment variable takes precedence over command line
unset AWS_DEFAULT_OUTPUT
```

Commenting out this line makes the problem go away:

```
$ git diff prowler 
diff --git a/prowler b/prowler
index 6f77b73..8a7a3e6 100755
--- a/prowler
+++ b/prowler
@@ -298,7 +298,7 @@ trap clean_up EXIT
 trap handle_ctrl_c INT
 
 # Environment variable takes precedence over command line
-unset AWS_DEFAULT_OUTPUT
+# unset AWS_DEFAULT_OUTPUT
 
 # Check OS
 os_detector

```

**Comment by n4ch04** [comment]
Hi @pythiankerr we'll check this out and let you know asap.
Thanks for using prowler!!

**Comment by n4ch04** [comment]
@pythiankerr Yes, as you said prowler 2.X strongly relies on the aws cli output format, right now most of the checks parse the output in `json` format. Such kind on dependences are going to be solved on version 3, until then I recommend you to keep using the json format (maybe setting a profile only with json output for prowler).

Can we help you with something else?

**Comment by ghost** [comment]
Will close as won't-fix with workaround. Thanks.
