### ISSUE TITLE
[Bug]: False positive in check_extra764

### ISSUE THREAD

**Issue by sw-krodi** [toniblyx/prowler#1481]
**What happened?**  
I guess there is a false positive in check_extra764.
I have the following Permission attached to a S3 bucket:
```
{  
    "Version": "2012-10-17",  
    "Statement": [  
        {  
            "Sid": "HttpsOnly",  
            "Effect": "Deny",  
            "Principal": "*",  
            "Action": "*",  
            "Resource": "arn:aws:s3:::[redacted]/*",  
            "Condition": {  
                "Bool": {  
                    "aws:SecureTransport": "false"  
                }  
            }  
        }  
    ]  
}  
```
Prowler gives me a "FAIL" regarding the check for using a secure transport policy for this bucket.

**How to reproduce it**  
1. prowler -p <accountname>
2. multi-account
3.  [extra764] Check if S3 buckets have secure transport policy  - s3 [Medium]
  FAIL! No bucket policy for [redacted]

**Expected behavior**  
I would expect this policy to allow only secure requests. So why does prowler report it as unsafe?  
If that is intended and i missed something i am really sorry for the inconvenience.

**From where are you running Prowler?**  
 - Resource: locally
 - OS: Linux
 - AWS-CLI Version [`aws --version`]: 2.5.7
 - Prowler Version [`./prowler -V`]: Prowler 2.9.0-13April2022

**Comment by MrCloudSec** [comment]
Hi @sw-krodi, thank you for reaching us out!
We will review this issue shortly and let you know.

**Comment by n4ch04** [comment]
Hi @sw-krodi sorry for the delay,
We've been reviewing this issue, and your policy should retrieve a FAIL when executing the check `extra_764`. 
The reason behind is that, according with AWS documentation, is recommended to include in the resource block the bucket itself and its contents (https://aws.amazon.com/premiumsupport/knowledge-center/s3-bucket-policy-for-config-rule/)
So the correct policy should be: 
```
{  
    "Version": "2012-10-17",  
    "Statement": [  
        {  
            "Sid": "HttpsOnly",  
            "Effect": "Deny",  
            "Principal": "*",  
            "Action": "*",  
            "Resource": [
        "arn:aws:s3:::test-bucket,
        "arn:aws:s3:::test-bucket/*"
      ],
            "Condition": {  
                "Bool": {  
                    "aws:SecureTransport": "false"  
                }  
            }  
        }  
    ]  
}  
```
Please check it out and let us know if everything is ok to close the issue

**Comment by sw-krodi** [comment]
Hi, no worries and thanks for your answer.
Actually in [this blog post of AWS](https://aws.amazon.com/blogs/security/how-to-use-bucket-policies-and-apply-defense-in-depth-to-help-secure-your-amazon-s3-data/) is also just the objects of buckets in the resource block and not the bucket as well:
```
{
    "Version": "2012-10-17",
    "Id": "Policy1504640911349",
    "Statement": [
        {
            "Sid": "Stmt1504640908907",
            "Effect": "Deny",
            "Principal": "*",
            "Action": "s3:GetObject",
            "Resource": "arn:aws:s3:::/*",
            "Condition": 
                "Bool": {
                    "aws:SecureTransport": "false"
                }
            }
        }
    ]
}
```
Thus, i still think my policy should retrieve a PASS. since according to this blog post all objects within this bucket are only  accessible via HTTPS.

**Comment by n4ch04** [comment]
Hi @sw-krodi, yep, it should be considered as PASS as well, since we are working right now in releasing Prowler v3 asap we will include this change in the check `s3_bucket_secure_transport_policy`.

Can we help you with something else?

**Comment by n4ch04** [comment]
Since we did not receive any other feedback from you @sw-krodi we are going to close this issue, please feel free to reopen if the problem persists.

Thanks for using Prowler
