### ISSUE TITLE
Wazuh Integration - string indices must be integers, not str

### ISSUE THREAD

**Issue by syedez** [toniblyx/prowler#1510]
I am trying to integrate The prowler with the Latest version of the Wazuh, But when I try to run the below cmd I am getting the following error.

cmd : /var/ossec/integrations/prowler-wrapper.py --aws_profile default --aws_account_alias default --debug 2

Error : [root@ip-172-16-3-4 output]# /var/ossec/integrations/prowler-wrapper.py --aws_profile default --aws_account_alias default --debug 2
DEBUG-1: +++ Debug mode on - Level: 2
DEBUG-1: +++ Get Prowler Version
DEBUG-1: Running prowler with args: -p default -V
DEBUG-2: Running command: /var/ossec/integrations/prowler/prowler -p default -V
DEBUG-1: +++ Get Prowler Results - check11
DEBUG-1: Running prowler with args: -b -c check11 -p default -M json
DEBUG-2: Running command: /var/ossec/integrations/prowler/prowler -b -c check11 -p default -M json

DEBUG-1: +++ Send Prowler Results
DEBUG-2: RESULT MSG ---  This report is being generated using credentials below:
DEBUG-1: INVALID JSON ---
{
  "integration": "prowler",
  "prowler":  This report is being generated using credentials below:
}

Unknown error: string indices must be integers, not str
Traceback (most recent call last):
  File "/var/ossec/integrations/prowler-wrapper.py", line 236, in <module>
    main(sys.argv[1:])
  File "/var/ossec/integrations/prowler-wrapper.py", line 227, in main
    _send_prowler_results(_prowler_results, _prowler_version, _options)
  File "/var/ossec/integrations/prowler-wrapper.py", line 196, in _send_prowler_results
    _check_result['prowler']['prowler_version'] = _prowler_version
TypeError: string indices must be integers, not str

**Comment by toniblyx** [comment]
With the release of Prowler v3 next week (full rewritten in python) we need to think a better and newer way to perform this integration but probably the best way is sending the prowler output json file to Wazuh from a bucket using a lambda function... Ideas? In any case we won't support that wrapper but a native or third party integration if it comes. In Prowler v3 folder structure this will go to `contrib`. Closing this issue, we are happy to assist you and help on the integration for v3 if you like.
