### ISSUE TITLE
allow running of multiple groups via -g group1,group2

### ISSUE THREAD

**Issue by rofreytag** [toniblyx/prowler#1515]
**Is your feature request related to a problem? Please describe.**
I don't want to run prowler multiple times, as some of these checks overlap (like soc2 and the group1,group2 checks).

I want to be able to run multiple test-groups all at once. 
Right now, if I specify a group using `-g`, I can only run the tests of that group.

When I enter multiple groups `-g group1 -g group2` it will run the last group's checks.
When I enter the command like this:
```
./prowler -f us-east-1,us-east-2,us-west-1,us-west-2 -g group1,group2
```
it will fail with: `WARNING! Group group1,group2 does not exist. `

**Describe the solution you'd like**
Following the existing CLI argument pattern, I would like 
```
./prowler -f us-east-1,us-east-2,us-west-1,us-west-2 -g group1,group2
```
to run all checks for the group1 and group2.

Likewise, the CLI commands to list checks should follow suit and list all checks that would run, i.e.

```
./prowler -l -g group1,group2
```

**Describe alternatives you've considered**
I am currently running `./prowler -l -g groupname` for each group, put the output in a text file and create a checklist from that to be able to run all the checks at once.

**Additional context**
We like to target multiple groups to cast a wider net on our compliance reports. 
Really appreciate the work you guys are doing on this project, it is an amazing tool!

**Comment by jfagoagas** [comment]
Hi @rofreytag, you're totally right, this is a known issue we have with Prowler v2. The good news is that we're close to release Prowler v3 and we've solved this issue with this new version. 

You can check it here https://github.com/prowler-cloud/prowler/tree/prowler-3.0-dev and test it with the following:
- List groups (in v3 are called categories): `./prowler --list-categories`
- Run checks by categories: `./prowler --categories secrets internet-exposed`

Thanks for using and contributing to Prowler!

**Comment by n4ch04** [comment]
Hi @rofreytag since this issue is addressed in Prowler v3 which is already in a functional beta version, we are going to close this issue, please let us know if the problem still persists and feel free to reopen or to create a new issue

**Comment by rofreytag** [comment]
@n4ch04 / @jfagoagas Thank you, will check it out!
