### ISSUE TITLE
[Bug]: ERROR Getting credentials to run Prowler - EXITING! 

### ISSUE THREAD

**Issue by umarhyatt00** [toniblyx/prowler#1535]
After the installation of Prowler as described in the wiki when I tried running it it gives the below error:

"ERROR Getting credentials to run Prowler - EXITING! "

I am running scout successfully with same aws credentials so I doubt if there is anything wrong there. The command that I am running is ./prowler

My environment is I have installed prowler on:
M1 Mac running
Kali linux "kali-linux-2022.3-installer-arm64" using UTM

Other details:

aws-cli/1.24.8 Python/3.10.8 Linux/5.18.0-kali5-arm64 botocore/1.26.8
Prowler 2.12.0-27October2022 

SC is below:

<img width="852" alt="Screenshot 2022-12-09 at 6 27 43 PM" src="https://user-images.githubusercontent.com/52189569/206712859-222a976c-3f86-4dee-a659-d09b068c56ae.png">

**Comment by n4ch04** [comment]
Hi @umarhyatt00, 

Prowler relies in AWS cli binary to launch AWS api calls, from your screenshot it seems that either you don't have AWS cli installed or what you have installed is not the binary that your system can execute (`cannot execute binary file: Exec format error`).  Test if AWS CLI is installed properly launching for example ` aws --version`, if not uninstall what you have or install AWS cli using official docs https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html.

Once aws cli is properly installed and working Prowler will work, please refer to another requirements here https://github.com/prowler-cloud/prowler#requirements-and-installation

Thanks for using Prowler

**Comment by umarhyatt00** [comment]
> Hi @umarhyatt00,
> 
> Prowler relies in AWS cli binary to launch AWS api calls, from your screenshot it seems that either you don't have AWS cli installed or what you have installed is not the binary that your system can execute (`cannot execute binary file: Exec format error`). Test if AWS CLI is installed properly launching for example ` aws --version`, if not uninstall what you have or install AWS cli using official docs https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html.
> 
> Once aws cli is properly installed and working Prowler will work, please refer to another requirements here https://github.com/prowler-cloud/prowler#requirements-and-installation
> 
> Thanks for using Prowler

output of "aws --version" is below:
aws-cli/1.24.8 Python/3.10.8 Linux/5.18.0-kali5-arm64 botocore/1.26.8

I have got prowler successfully running on MAC OS but Kali is till giving the same error.

**Comment by n4ch04** [comment]
This seems to be a issue related with the architecture of the Kali and the aws binary, the binary is for ARM arch, the Kali has the same architecture or it is amd64 ?

**Comment by umarhyatt00** [comment]
> This seems to be a issue related with the architecture of the Kali and the aws binary, the binary is for ARM arch, the Kali has the same architecture or it is amd64 ?

already added this info in my 1st post

My environment is I have installed prowler on:
M1 Mac running
Kali linux "kali-linux-2022.3-installer-arm64" running as a VM using UTM

More details:

 Static hostname: kali
       Icon name: computer
      Machine ID: 
         Boot ID: 
  Virtualization: qemu
Operating System: Kali GNU/Linux Rolling          
          Kernel: Linux 5.18.0-kali5-arm64
    Architecture: arm64
 Hardware Vendor: QEMU
  Hardware Model: QEMU Virtual Machine
Firmware Version: 0.0.0

**Comment by n4ch04** [comment]
Try to execute directly `/usr/local/bin/aws` to check which binary is that does not match the needed format

**Comment by n4ch04** [comment]
Hi @umarhyatt00 did you get any progress?

**Comment by umarhyatt00** [comment]
Unfortunately I got busy with something, I will try and get back to you
tomorrow.

**Comment by n4ch04** [comment]
Hi @umarhyatt00 we have just released the version 3 with huuuge improvements, instead of spending time on figure it out what is wrong, which seems a system issue , give it a try  and let us know if something goes wrong

Thanks for using Prowler!!

**Comment by umarhyatt00** [comment]
> Try to execute directly `/usr/local/bin/aws` to check which binary is that does not match the needed format

it says not a directory although aws directory exists in that path
