### ISSUE TITLE
[Bug]: Extra73 check generates wrong report in case of expired token

### ISSUE THREAD

**Issue by daftkid** [toniblyx/prowler#1558]
**What happened?**  
I was running a prowler scan against a Chinese AWS account from within the EC2 instance deployed within this account. In the final report, I can see strange lines related to S3 bucket checks - it seems that prowler caught an unhandled error response from the AWS API on `list buckets` (https://github.com/prowler-cloud/prowler/blob/master/checks/check_extra73#L69) and then iterated through each word in the error response treating it as a bucket name.

**How to reproduce it**  
1. What command are you running? 
`./prowler -r cn-north-1 -M csv,html `
3. Environment you have, like single account, multi-account, organizations, etc.
Single account
5. See error

```
An error occurred (InvalidBucketName) when calling the GetBucketLocation operation: The specified bucket is not valid
```

and then the following errors in the report (I have stripped them a bit):
```
An error occurred (NoSuchBucket) when calling the GetBucketLocation operation: The specified bucket does not exist: error bucket is Public! <..stripped...>
An error occurred (NoSuchBucket) when calling the GetBucketLocation operation: The specified bucket does not exist: occurred bucket is Public! <..stripped...>
An error occurred (NoSuchBucket) when calling the GetBucketLocation operation: The specified bucket does not exist: when bucket is Public! <..stripped...>
An error occurred (NoSuchBucket) when calling the GetBucketLocation operation: The specified bucket does not exist: calling bucket is Public! <..stripped...>
An error occurred (NoSuchBucket) when calling the GetBucketLocation operation: The specified bucket does not exist: the bucket is Public! <..stripped...>
An error occurred (NoSuchBucket) when calling the GetBucketLocation operation: The specified bucket does not exist: ListBuckets bucket is Public! <..stripped...>
An error occurred (NoSuchBucket) when calling the GetBucketLocation operation: The specified bucket does not exist: The bucket is Public! <..stripped...>
An error occurred (NoSuchBucket) when calling the GetBucketLocation operation: The specified bucket does not exist: provided bucket is Public! <..stripped...>
An error occurred (NoSuchBucket) when calling the GetBucketLocation operation: The specified bucket does not exist: token bucket is Public! <..stripped...>
An error occurred (NoSuchBucket) when calling the GetBucketLocation operation: The specified bucket does not exist: malformed bucket is Public! <..stripped...>
An error occurred (NoSuchBucket) when calling the GetBucketLocation operation: The specified bucket does not exist: otherwise bucket is Public! <..stripped...>
An error occurred (NoSuchBucket) when calling the GetBucketLocation operation: The specified bucket does not exist: invalid. bucket is Public! <..stripped...>
```

If I collect all of the "failed" bucket names, I'll get this initial error that has not been properly handled by the tool:

```
An error occurred (InvalidToken) when calling the ListBuckets operation: The provided token is malformed or otherwise invalid.
```

**Expected behavior**  
The tool is able to handle `InvalidToken` error before iterating through the list of buckets.

**Screenshots or Logs**  
Also, you can add logs (anonymize them first!). Here a command that may help to share a log
`bash -x ./prowler -options > debug.log 2>&1` then attach here `debug.log`

**From where are you running Prowler?**  
Please, complete the following information:
 - Resource: EC2 instance
 - OS: Amazon Linux 2
 - AWS-CLI Version [`aws --version`]:
 - Prowler Version [`./prowler -V`]: `2.12.0-27October2022`
 - Shell and version: bash
 - Others:

**Additional context**

**Comment by jfagoagas** [comment]
Hi @daftkid, first of all thank you for using Prowler. 

The issue is caused because we are not handling right the possible errors returned by the AWS CLI  as you mentioned. We are going to fix this in Prowler v2 as soon as possible.

Have you had the opportunity to test Prowler v3? Right now are are really close to the release and this kind of errors are solved because we correctly handle this kind of errors. You can test it in the following branch https://github.com/prowler-cloud/prowler/tree/prowler-3.0-dev

Also there is a new Prowler community in Slack, join us using the following link https://join.slack.com/t/prowler-workspace/shared_invite/zt-1khcj2c41-owhVxRhuNHQwZoDTKcnVlQ

Thanks!

**Comment by daftkid** [comment]
Hi @jfagoagas. I have testes a new version today and I really like it and the fact that it is Python-based right now instead of pure bash! 🚀 

However, it's hard to reproduce the issue as it depends on some timings. I think you can close the issue as I'm not going to use the second version of the tool and will use new one instead.

**Comment by jfagoagas** [comment]
Thanks a lot @daftkid !! 

If you can please join the new Prowler Slack community here https://join.slack.com/t/prowler-workspace/shared_invite/zt-1khcj2c41-owhVxRhuNHQwZoDTKcnVlQ

Please, reach us if you need anything.
