### ISSUE TITLE
[Bug]: CloudFormation stack has incorrect exec command for prowler

### ISSUE THREAD

**Issue by siarheirdn** [toniblyx/prowler#1572]
**What happened?**
CloudFormation stack has incorrect exec command for latest 2.12.1 build

**How to reproduce it**
Create cloudformation stack and check Codebuild

**Screenshots or Logs**
CodeBuild Error
```/codebuild/output/tmp/script.sh: line 4: ./prowler: Is a directory```
![image](https://user-images.githubusercontent.com/91063359/208918634-1366c22d-dfc8-45e2-94b2-4d3861316807.png)

**From where are you running Prowler?**
Please, complete the following information:
 - Resource: CodeBuild
 - Prowler Version 2.12.1

**Additional context**
thanks!

**Comment by toniblyx** [comment]
Thanks @siarheirdn, that CFN tamplate is using the master branch that now is Prowler 3, you can adapt it for v3 or make sure you get the proper v2 branch, which is now prowler-v2 `git clone --branch prowler-v2 https://github.com/prowler-cloud/prowler`. Please, if you make those changes feel free to send back a pull request to contribute.

**Comment by toniblyx** [comment]
Hey @siarheirdn, we have updated the template in master branch to still use v2 so you can use this file to make it work on CodeBuild with Prowler v2  https://github.com/prowler-cloud/prowler/blob/master/contrib/codebuild/codebuild-prowlerv2-audit-account-cfn.yaml
