### ISSUE TITLE
[Bug]: --list-services option fails to run

### ISSUE THREAD

**Issue by thewriteway** [toniblyx/prowler#1578]
**What happened?**
ran a prowler command against azure and it failed with a traceback error.

**How to reproduce it**
1. What command are you running?
ran the command prowler azure --az-cli-auth --list-services or prowler azure --list-services

2. Environment you have, like single account, multi-account, organizations, etc.
Azure environment - single account pay as you go

3. See error:
Traceback (most recent call last):

  File "/home/user/.local/bin/prowler", line 8, in <module>

    sys.exit(prowler())

  File "/home/user/.local/lib/python3.10/site-packages/prowler/__main__.py", line 69, in prowler

    print_services(list_services(provider))

  File "/home/user/.local/lib/python3.10/site-packages/prowler/lib/check/check.py", line 114, in list_services

    service_name = check_name[0].split(".")[3]

IndexError: list index out of range

**Expected behavior**
expected it to list the services available to scan from Azure

**Screenshots or Logs**
Also, you can add logs (anonymize them first!). Here a command that may help to share a log
`bash -x ./prowler -options > debug.log 2>&1` then attach here `debug.log`
N/A

**From where are you running Prowler?**
Please, complete the following information:
 - Resource: Locally hosted virtual machine
 - OS: [ubuntu]
 - Prowler Version [`./prowler -V`]: 3.0.0
 - Shell and version: Linux ubunt1 5.15.0-56-generic -Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**

**Comment by n4ch04** [comment]
Hi @thewriteway we are solving this issue right now, we'll let you know when it is done

**Comment by n4ch04** [comment]
Hi @thewriteway please check the workaround here https://github.com/prowler-cloud/prowler/pull/1587 and let us know if it is ok

**Comment by thewriteway** [comment]
ok i manually edited check.py and it works but all it shows is:

_ __  _ __ _____      _| | ___ _ __

| '_ \| '__/ _ \ \ /\ / / |/ _ \ '__|

| |_) | | | (_) \ V  V /| |  __/ |

| .__/|_|  \___/ \_/\_/ |_|\___|_|v3.0.0

|_| the handy cloud security tool


Date: 2022-12-22 14:08:19
            

There are 1 available services: 
- 


with no actual services listed.

Is this meant to be all it can display?

**Comment by n4ch04** [comment]
I think that you missed something, we are going to release a new version today with that solved, please check it out upgrading the pip package and feel free to reopen if the issue persists

**Comment by thewriteway** [comment]
its resolved. thanks.
