### ISSUE TITLE
[Bug]: Report to AWS S3 Bucket

### ISSUE THREAD

**Issue by Riqardos** [toniblyx/prowler#1593]
**What happened?**
Prowler configured to upload the report to s3 bucket. Did work with previous version (no problem with permissions, ...). When running it with `-B` or `-D` option, I am getting this issue: 
`[File: outputs.py:198]  [Module: outputs]        CRITICAL: UnboundLocalError[191] -- local variable 'filename' referenced before assignment`.

The report is not uploaded.

**How to reproduce it**
1. `prowler aws --profile <PROFILE> --verbose -f <REGION> -M html -B <S3_BUCKET_NAME> -s iam`

**Expected behavior**
Output uploaded to s3 bucket

**Screenshots or Logs**
logtail:
```
-> Scan completed! |▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉| 27/27 [100%] in 14.5s 
2022-12-22 15:57:21,982 [File: outputs.py:198]  [Module: outputs]        CRITICAL: UnboundLocalError[191] -- local variable 'filename' referenced before assignment
```

**From where are you running Prowler?**
 - Resource: docker: toniblyx/prowler:3.0.0
 - OS: Mac
 - Prowler Version [`./prowler --version`]: Prowler 3.0.0

**Comment by n4ch04** [comment]
Hi @Riqardos we are going to check it and let you know, thanks !!!

**Comment by n4ch04** [comment]
Hi @Riqardos we have solved the issue here https://github.com/prowler-cloud/prowler/pull/1599, please check it out

**Comment by n4ch04** [comment]
We are going to release a new version with this issue solved today, please check it out and feel free to reopen the issue if the problem persists.

Thanks !!
