### ISSUE TITLE
[Bug]: Prowler3.0.0 shows sqs encryption FAIL while real state should be PASS

### ISSUE THREAD

**Issue by siarheirdn** [toniblyx/prowler#1595]
**What happened?**
Prowler v3 shows different from Prowler v2 results. For example, Prowler3 fails on SQS SSE encryption check. But SQS has SSE encryption. Checked manually. At the same time, Prowler v2 shows this step as PASS (as it should be).

**How to reproduce it**
1. run Prowler v2
2. run Prowler v3
3. Compare results.

**Expected behavior**
1. Prowler 3 and Prowler 2 has same results
2. Prowler 3 shows real state

**Screenshots or Logs**
![image](https://user-images.githubusercontent.com/91063359/209179780-c69820d1-fa8c-49cd-a3d3-924c78d1ce75.png)
while Prowler2 says PASS
![image](https://user-images.githubusercontent.com/91063359/209180261-fc043c5d-e559-47dd-8b11-7723b75683ce.png)

**From where are you running Prowler?**
Please, complete the following information:
 - Resource: AWS SQS, Security groups
 - OS: Linux (local)
 - Prowler Version: 2.12.1 and 3.0.0

**Comment by MrCloudSec** [comment]
Good catch @siarheirdn !! 
You are right, we will solve this issue shortly 👍🏼

**Comment by MrCloudSec** [comment]
This is the PR that solves this issue: https://github.com/prowler-cloud/prowler/pull/1596
