### ISSUE TITLE
[Bug]: AttributeError: 'Aws_Output_Options' object has no attribute 'output_filename'

### ISSUE THREAD

**Issue by ichasco-heytrade** [toniblyx/prowler#1602]
I can't save the report if I add a custom name
```
prowler aws -f eu-west-1 -M html -q --output-filename prowler-pro.html
```

Error:
```
-> Scan completed! |▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉| 244/244 [100%] in 58.1s 
Traceback (most recent call last):
  File "/home/prowler/.local/bin/prowler", line 8, in <module>
    sys.exit(prowler())
  File "/home/prowler/.local/lib/python3.9/site-packages/prowler/__main__.py", line 178, in prowler
    audit_output_options.output_filename, args.output_directory
AttributeError: 'Aws_Output_Options' object has no attribute 'output_filename'
```

I am using the last version of the dockerfile

**Comment by n4ch04** [comment]
Hi @ichasco-heytrade we are going to check this out and let you know

**Comment by ichasco-heytrade** [comment]
And also `-q` option I think that is not working properly.  The description is: 
`-q, --quiet           Show only Prowler failed findings` 
And it also shows the `PASS` status

**Comment by MrCloudSec** [comment]
Hi @ichasco-heytrade, thank you for the info.
Could send us screenshots of your `-q` behavior? We cannot reproduce the error of showing some PASS status.

**Comment by ichasco-heytrade** [comment]
Here you have, and then in the reports the successful checks appears.

![image](https://user-images.githubusercontent.com/77392885/209338774-d3b6ff7c-232b-4bb2-9fee-869f622fa931.png)

![image](https://user-images.githubusercontent.com/77392885/209339229-a2a88720-a2ab-439d-8926-7b3a501431ea.png)

**Comment by MrCloudSec** [comment]
Hi @ichasco-heytrade, the original issue has been solved in https://github.com/prowler-cloud/prowler/pull/1604
Regarding the `--quiet` option, this argument was designed to show only FAIL findings in the verbose mode (in the output files and tables every finding is shown, for example, in the html you can filter the findings by its status)
