### ISSUE TITLE
[Bug]: Wrong default file naming: None.format

### ISSUE THREAD

**Issue by sol-malisani** [toniblyx/prowler#1616]
**From where are you running Prowler?**
 - Resource: Docker container manually
 - OS: Mac
 - Prowler Version: 3.0.1
 - Parameters: -M html -B my-s3-bucket -o cis-benchmark

**What happened?**
As showed below, documentation says if custom output report name is not specified, filename will use default output/prowler-output-ACCOUNT_NUM-OUTPUT_DATE.format (-F flag), but instead of that, default name is None.format

<img width="988" alt="image" src="https://user-images.githubusercontent.com/66799118/209565517-0d65a06a-9053-4193-8710-cfb335959d25.png">

**How to reproduce it**
As I'm using docker
`docker run --rm --name prowler --env AWS_ACCESS_KEY_ID --env AWS_SECRET_ACCESS_KEY --env AWS_SESSION_TOKEN toniblyx/prowler:3.0.1 -M html -B my-s3-bucket -o cis-benchmark`

<img width="690" alt="image" src="https://user-images.githubusercontent.com/66799118/209565859-c1400f37-6fdc-4878-97ae-13551cd7fd07.png">
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/66799118/209566016-1af68ced-804a-4398-847a-f28d8455702d.png">

Note: I also tried without -o and -M flag and same behaviour.

**Expected behavior**
Get a file with expected file naming: output/prowler-output-ACCOUNT_NUM-OUTPUT_DATE.format
In my case: html/prowler-output-xxxxx-20221226133115.html

**Comment by toniblyx** [comment]
Good catch @sol-malisani, thank you. We will look at this and let you know.

**Comment by daftkid** [comment]
I can see the next error related to the output module:
```
{"timestamp": "2022-12-28 17:05:14,890", "filename": "models.py:72", "level": "ERROR", "module": "models", "message": "ValidationError[46]: 1 validation error for Aws_Check_Output_CSV
profile
  none is not an allowed value (type=type_error.none.not_allowed)"}
{"timestamp": "2022-12-28 17:05:14,890", "filename": "outputs.py:157", "level": "ERROR", "module": "outputs", "message": "TypeError[121]: cannot unpack non-iterable NoneType object"}
```

**Comment by jfagoagas** [comment]
@daftkid @sol-malisani these issues has been solved in this branch `PRWLR-1211-bug-wrong-default-file-naming-none-format-issue-1616`

Please, test it and let us know if everything works well.

Thanks
