### ISSUE TITLE
[Bug]: Prowler v3 integration to AWS Security Hub and usage of -q flag to send only FAILs

### ISSUE THREAD

**Issue by toniblyx** [toniblyx/prowler#1624]
### Discussed in https://github.com/prowler-cloud/prowler/discussions/1623

<div type='discussions-op-text'>

<sup>Originally posted by **am-avios** December 28, 2022</sup>
Hello All

With previous version of prowler i was able to send only failed checks to security hub with flag -q, however it seems v3 sends both passed and failed checks to security hub even with -q flag. Is this intentional?  </div>

**Comment by MrCloudSec** [comment]
You are totally right @am-avios, you have the PR above solving this issue.

Thank you!!
