### ISSUE TITLE
[Bug]: Prowler auto archives Security Hub findings from previous prowler scan

### ISSUE THREAD

**Issue by toniblyx** [toniblyx/prowler#1626]
### Discussed in https://github.com/prowler-cloud/prowler/discussions/1625

<div type='discussions-op-text'>

<sup>Originally posted by **am-avios** December 28, 2022</sup>
Hi @toniblyx 

Say for example i run 
#prowler aws --categories secrets -S
and then 
#prowler aws --categories internet-exposed -S

I noticed that after running the second prowler scan the security hub findings from previous scan get auto archived in security hub (Security hub Record State goes from Active to Archived).

Can this behaviour be changed?</div>

**Comment by MrCloudSec** [comment]
Hi @toniblyx @am-avios,
Prowler archives all Security Hub findings from previous executions of Prowler that have not appear in the new execution.
May I get your feedback on what behavior you would like?

Thank you!

**Comment by MrCloudSec** [comment]
PD: @am-avios, we recommend you to always run the same execution in Prowler to have the same history of findings in Security Hub.

**Comment by am-avios** [comment]
Thanks @sergargar.

In terms of feedback.
Just a bit of background we have hundreds of aws accounts which need to be scanned. I plan to run prowler in a container. One approach was to split the scans into daily, weekly and monthly scans. With daily scans including critical checks being run more frequently. We want to build some automated ticketing for the most critical findings. I guess for this to work we could have a flag to preserve findings from previous execution of prowler. Your thoughts?

The other approach as you mentioned is to run all checks daily.

**Comment by MrCloudSec** [comment]
Thanks for the information @am-avios !
I see... Out of curiosity, how much time does Prowler spend on average in your accounts running all the checks vs. just the critical ones?
A flag to preserve findings in Security Hub is a great idea though.

**Comment by MrCloudSec** [comment]
@am-avios pls, reopen the issue if you need more information.
Thank you!
