### ISSUE TITLE
[Bug]: Check 'storage_blob_public_access_level_is_disabled' was not found for the AZURE provider.

### ISSUE THREAD

**Issue by jfagoagas** [toniblyx/prowler#1633]
### Discussed in https://github.com/prowler-cloud/prowler/discussions/1608

<div type='discussions-op-text'>

<sup>Originally posted by **Rodasa** December 24, 2022</sup>
Hi, could someone help me in the correct configuration to run prowler with Azure? I get the following error: [File: check.py:341] [Module: check] CRITICAL: Check 'storage_blob_public_access_level_is_disabled' was not found for the AZURE provider.
Regards!</div>

**Comment by jfagoagas** [comment]
Hi @Rodasa, how did you installed Prowler in your environment?

We need more information because we are not being able to reproduce it in our test environments. Please, if you can fill the issue template to give us more details about your setup.

Thanks!

**Comment by jfagoagas** [comment]
Hi @Rodasa we're closing this issue, if you notice this again please feel free to reopen this issue and give us more information about it.

Thanks for using Prowler.

**Comment by mayankmehra11** [comment]
i am facing this same error

**Comment by mayankmehra11** [comment]
CRITICAL: Check 'storage_blob_public_access_level_is_disabled' was not found for the AZURE provider

**Comment by jfagoagas** [comment]
Hi @mayankmehra11, how did you installed Prowler in your environment?

We need more information because we are not being able to reproduce it in our test environments. Please, if you can fill the issue template to give us more details about your setup.

I'm getting no error with the latest version, please check if you are using the same one

```
(prowler-py3.11) ➜  prowler git:(master) ./prowler.py azure --list-checks --service storage 
                         _
 _ __  _ __ _____      _| | ___ _ __
| '_ \| '__/ _ \ \ /\ / / |/ _ \ '__|
| |_) | | | (_) \ V  V /| |  __/ |
| .__/|_|  \___/ \_/\_/ |_|\___|_|v3.7.1
|_| the handy cloud security tool

Date: 2023-07-23 18:26:43

[storage_blob_public_access_level_is_disabled] Ensure that the 'Public access level' is set to 'Private (no anonymous access)' for all blob containers in your storage account - storage [medium]
[storage_default_network_access_rule_is_denied] Ensure Default Network Access Rule for Storage Accounts is Set to Deny - storage [medium]
[storage_ensure_azure_services_are_trusted_to_access_is_enabled] Ensure that 'Allow trusted Microsoft services to access this storage account' is enabled for storage accounts - storage [medium]
[storage_ensure_encryption_with_customer_managed_keys] Ensure that your Microsoft Azure Storage accounts are using Customer Managed Keys (CMKs) instead of Microsoft Managed Keys - storage [high]
[storage_ensure_minimum_tls_version_12] Ensure the 'Minimum TLS version' for storage accounts is set to 'Version 1.2' - storage [medium]
[storage_infrastructure_encryption_is_enabled] Ensure that 'Enable Infrastructure Encryption' for Each Storage Account in Azure Storage is Set to 'enabled'  - storage [low]
[storage_secure_transfer_required_is_enabled] Ensure that all data transferred between clients and your Azure Storage account is encrypted using the HTTPS protocol. - storage [medium]

There are 7 available checks.
```

As you can see in the above output the first check displayed is the one you are seeing as missed.

**Comment by mayankmehra11** [comment]
I installed in Parrot OS. I ran scoutsuite, it worked perfectly fine but when i ran prowler via browser auth and tenant id , it shows the error.

Executing 20 checks, please wait...

2023-07-23 22:01:30,526 [File: check.py:508]    [Module: check]  CRITICAL: Check 'storage_blob_public_access_level_is_disabled' was not found for the AZURE provider
-> Scan was aborted! |▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉⚠︎             | (!) 13/20 [65%] in 4.3s 
┌─[✗]─[mmehra@parrot]─[~]
└──╼ $

**Comment by jfagoagas** [comment]
@mayankmehra11 Could you execute it with `--log-level ERROR` and paste the output here?

**Comment by jfagoagas** [comment]
Hi @mayankmehra11, we cannot reproduce it using `v3.7.2` which is the latest release published.

Since we did not receive any response from your side we are going to close this issue. Please feel free to reopen it if you notice this issue again.

Thanks for using Prowler 🚀
