### ISSUE TITLE
feat(installation): Make provider dependencies optional for pip installation

### ISSUE THREAD

**Issue by mathiaHT** [toniblyx/prowler#1647]
I use only aws as a cloud provider. So I dont perform test against azure but still the dependencies are all installed

Use of poetry extra feature to make azure and boto3 dependencies optional. 

Then to install prowler it would be possible to do either
```bash
pip install prowler-cloud[all]
pip install prowler-cloud[aws]
pip install prowler-cloud[azure]
```

**Comment by jfagoagas** [comment]
Hi @mathiaHT thanks for the suggestion. We have in our roadmap the migration to use poetry and this is a really good idea.

**Comment by toniblyx** [comment]
Hi @mathiaHT, as you can see, we have done some tests with Poetry extras and it didn't convince us, at the end of the day now we install aws or azure dependencies on every installation, that is not that much in terms of size so it is not a big deal. We will continue using the installer as it is so `pip install prowler` will install all needed dependencies for any supported provider (so far AWS and Azure). For better dependency management we are moving to Poetry to use only `pyproject.toml`. Thanks for your suggestion, we are closing this feature request.

**Comment by jfagoagas** [comment]
Hello @mathiaHT we have created this feature request to keep track of it https://github.com/prowler-cloud/prowler/issues/4696. Thanks!
