### ISSUE TITLE
[Bug]: Connection reset when running Prowler using remote session in Ubuntu

### ISSUE THREAD

**Issue by toniblyx** [toniblyx/prowler#1659]
I realized that I haven't shared what I see as an outcome in my earlier comment.  So, the attachment is from earlier attempt that confirms my creds and config is correct. I attempted this on 2 ubuntu boxes and every time scan hangs at 48% and it messes up connectivity to my box. I would have to restart the EC2 to retry again. I am assuming this may be conflicting or changing firewall config of the machine preventing host resolution or port 22 connectivity.

![image](https://user-images.githubusercontent.com/110049394/210637784-0e0118fd-9d50-472a-9ad7-1b4e76ce59aa.png)

![image](https://user-images.githubusercontent.com/110049394/210639698-a72189ca-e502-4949-a31b-dc26e9f74fcf.png)

_Originally posted by @SrikanthREEF in https://github.com/prowler-cloud/prowler/issues/1654#issuecomment-1371355197_

**Comment by toniblyx** [comment]
From @n4ch04: 

Hi @SrikanthREEF since the scan get hanged and you loose connectivity every time, it seems that you have a low ulimit set on your ubuntu ec2 instances. In Unix the ulimit sets the maximum file descriptors open at the same time, and the system treat as file descriptor almost everything (from sockets to proper files). Prowler uses Python paginators, which creates intermediate files to process large API responses.
Give a try to the ulimit change setting, first check the current value with ulimit -a and then change it with ulimit -n <value>

**Comment by SrikanthREEF** [comment]
Hi @toniblyx 
                     I tried increasing ulimit from 1k to 40k. but scan still ended up hanging at 48%

![image](https://user-images.githubusercontent.com/110049394/210804911-c1c50f2b-1b26-4e1f-9cc5-d874d801a5af.png)

![image](https://user-images.githubusercontent.com/110049394/210816854-3e3c94c2-c3de-4fd2-88b7-3247786cfa4c.png)


![image](https://user-images.githubusercontent.com/110049394/210807241-d50d0ef5-0fa9-4df3-9a45-ab4f3cfbb3a0.png)

**Comment by n4ch04** [comment]
Hi @SrikanthREEF 
 The scanning is still hanging, but did you loose again the connectivity to the remote host?
Looking at your screenshot it seems that something went wrong can you relaunch the scanning with the flag `--log-level ERROR` appended to the end of the command and share the logs?

**Comment by n4ch04** [comment]
Hi @SrikanthREEF did this workaround work for you?

**Comment by SrikanthREEF** [comment]
Hi @n4ch04 ,
                      Sorry, I didn't get a chance to respond yesterday. Last Friday, I have upgraded size of my EC2 instance to t2.medium from t2.micro. Since then scan started to progress to 95% & completes with a failure in creating a output file. I did also run it with logs enabled please take a look at attached text file.
Prowler scan is modifying something in none.html file but it doesn't contain latest scan info as in the header section the file. 

![image](https://user-images.githubusercontent.com/110049394/211592963-660fca6c-7e23-46c6-8ed0-161ac9b9a7d3.png)

[prowler error logs.txt](https://github.com/prowler-cloud/prowler/files/10384128/prowler.error.logs.txt)

![image](https://user-images.githubusercontent.com/110049394/211594149-a2132a7c-f0f2-41c0-af80-08c5f977f22d.png)

**Comment by n4ch04** [comment]
Hi @SrikanthREEF no worries, yep we have deal with that issue and it has solved on version `3.0.2`, from your logs it seems that you are not using the latest version (you can check it with `prowler -v`). 
Please update it and launch it again, it should be solved.
Regarding the system requirements Prowler v3 parallelise and stores information in memory to improve performance so that memory requirement may be true in your case.

**Comment by SrikanthREEF** [comment]
Hello @n4ch04, 
                         new version did generate the output files. I would say this issue can be closed now.
My suggestion would be to call out recommended memory requirements on Prowler documentation. so, other users can avoid this issue .

**Comment by n4ch04** [comment]
Thanks so much @SrikanthREEF,  we'll take it into account and update the docs.

Thank you for using Prowler!!
