### ISSUE TITLE
[Bug]: ASFF Resources['Id'] using resource_id instead of resource_arn

### ISSUE THREAD

**Issue by gabrielsoltz** [toniblyx/prowler#1661]
Hi Prowler Team! 

**What happened?**

After reviewing the integration between Security Hub and Prowler, I found that ASFF output for field Resources['Id'] it's being filled by resource_id instead of resource_arn as it should be. As I see it, this is a big deal. If you need to correlate findings from different scanners/sources based on affected resource, you can't because the Resources['Id'] being reported by Prowler is not the ARN as it is supposed to be (when correlating findings is not the same `i-0123456789` than `arn:ec2:..../i-0123456789`)

Here is what I found:

- ASFF Reosource['Id'] field must be the ARN of the affected resource ([ASFF](https://docs.aws.amazon.com/securityhub/latest/userguide/asff-resources.html))
- Prowler is using the resource_id instead of the resource_arn ([Id](https://github.com/prowler-cloud/prowler/blob/master/prowler/lib/outputs/json.py#L35))
- Looks like AWS is not validating this field, as it's working this way... 
- I found that Prowler is not generating the ResourceArn for all the scanned resource types. This could explain why it is sending the resource_id (available for every resource).
- I already started [here](https://github.com/prowler-cloud/prowler/pull/1649) adding the missing ResourceArn. Having the ResourceArn for each finding is key for any good integration, as it is the unique identifier for an AWS resource (not the resource_id).
- What I wanted to propose is modifying the ASFF generator to start using resource_arn only when it's available, and when not, use the resource_id like we are doing now, so something like this [here:](https://github.com/prowler-cloud/prowler/blob/master/prowler/lib/outputs/json.py#L15):

```
    if finding.resource_id == "":
        finding.resource_id = "NONE_PROVIDED"
    if finding.resource_arn == "":
        finding.resource_arn = finding.resource_id
    ...
    ...
    finding_output.Resources = [
        Resource(
            Id=finding.resource_arn,
            Type=finding.check_metadata.ResourceType,
            Partition=audit_info.audited_partition,
            Region=finding.region,
        )
    ]
```

- Last but not least important: the Finding Id for each finding is generated based on the [resource_id](https://github.com/prowler-cloud/prowler/blob/master/prowler/lib/outputs/json.py#L19), so we can keep that to avoid making this a breaking change in terms of integration as far as I understand based on AWS Documentation. Findings are unique based on this Id, so when this change, it's deployed. The id will continue being the same; the only field that will be updated is the Resources['Id']

**Expected behavior**

Having ResourceArn for each affected resource and generating the Resoucers['Id'] field for ASFF output based on that field.

`Id=finding.resource_arn`

**Comment by MrCloudSec** [comment]
Good catch @gabrielsoltz !
The PR has been made with the required changes, thank you 🔝
