### ISSUE TITLE
[Bug]: Prowler CSV output format doesn't covert correctly

### ISSUE THREAD

**Issue by chronospaulh** [toniblyx/prowler#1679]
Hi, the CSV output file seems having issue with delimiter with excess of ";". The columns aren't separated by semicolon and the result shown in one single cell. As we can see in the following screenshot that shows all columns are under Column A.
![2023-01-09_16-30-39](https://user-images.githubusercontent.com/90489174/211435828-809c727c-adcc-4b87-ae41-c1492be016f5.png)

**Comment by jfagoagas** [comment]
Hi @chronospaulh tin Prowler v3 the CSV delimiter is the `;`. Did you set it as the field separator in the program you are using?

Please, for the next time fill the issue template because we need that information to triage the issues.

Thanks for using Prowler!

**Comment by jfagoagas** [comment]
Hi @tayivan-sg, we're closing this issue. Please feel free to reopen it if you experience the same again.

Thanks!

**Comment by jfagoagas** [comment]
@chronospaulh, we're closing this issue. Please feel free to reopen it if you experience the same again.

Thanks!
