### ISSUE TITLE
[Bug]: check_extra79 does not check WAF settings

### ISSUE THREAD

**Issue by tayivan-sg** [toniblyx/prowler#1683]
**What happened?**
The remediation for rule extra 79 is "Ensure the load balancer should be publicly accessible. If publicly exposed ensure a WAF ACL is implemented" 
How ever it does not seem to check for WAF ACL implementation

**How to reproduce it**
run rule

**Expected behavior**
Load balancer that implemented WAF ACL should pass this rule

**Comment by jfagoagas** [comment]
Hi @tayivan-sg, did you tried with Prowler v3? Right now v3 is available either `pip install prowler-cloud` or using `master` branch in thew Github repository.

Please, test it and let us know.

Thanks for using Prowler!

**Comment by jfagoagas** [comment]
Hi @tayivan-sg, we've reviewed the Prowler v2 `check_extra79` and the recommendation is right. This check looks for Public ELBs and raises a FAIL if it's publicly exposed.

The recommendation for this check is that if your ELB has to be Public it is recommended to put a WAF ACL in front of it.

Thanks for using Prowler!
