### ISSUE TITLE
[Bug]: aws_regions_by_service.json: FileNotFoundError[13]

### ISSUE THREAD

**Issue by ah-jota** [toniblyx/prowler#1687]
Unable to run Prowler as of the most recent version in master branch on Mac OS Ventura as a fresh install. Getting the following error: 

(local-path)/prowler/providers/aws/aws_regions_by_service.json: FileNotFoundError[13]

After looking at the true installed path for aws_regions_by_service.json, it appears to be missing an additional /prowler/ directory. Please confirm this issue. 

True path as installed: 
(local-path)/prowler/prowler/providers/aws/aws_regions_by_service.json

Is it by design that prowler should only be executed if your current directory is the prowler parent directory? Using relative paths worked in the past. 

Possibly related to the following issue: https://github.com/prowler-cloud/prowler/issues/1669 as I have this issue once upgraded to prowler 3.0.2, specifically this change: https://github.com/prowler-cloud/prowler/blob/master/prowler/config/config.py#L65

Workaround:
Ensure you execute from the installed /prowler/directory. 

Example works: 
`cd /prowler/ && python3.9 prowler.py aws -h`

Example doesn't work:
`cd /literally-anywhere-else/ && python3.9 /prowler/prowler.py aws -h`

**Comment by MrCloudSec** [comment]
Thank you for letting us now @ah-jota ! We'll fix it shortly.
