### ISSUE TITLE
[Bug]: Report contains wrong value for a region field when running for the Chinese AWS accounts

### ISSUE THREAD

**Issue by daftkid** [toniblyx/prowler#1691]
**What happened?**
Hi all, just noticed in the report for Chinese AWS accounts that a value for the region field is set to `us-east-1` for some checks, I think it’s made by mistake in the code (e.g. here [https://github.com/prowler-cloud/prowler/blob/master/prowler/providers/aws/service[…]ilter_and_alarm_for_cloudtrail_configuration_changes_enabled.py](https://github.com/prowler-cloud/prowler/blob/master/prowler/providers/aws/services/cloudwatch/cloudwatch_log_metric_filter_and_alarm_for_cloudtrail_configuration_changes_enabled/cloudwatch_log_metric_filter_and_alarm_for_cloudtrail_configuration_changes_enabled.py#L24)). `us-east-1` is set as the default value and it’s not changed to the `cn-north-1` for some reason later

**How to reproduce it**
1. What command are you running?
```
for accountId in $ACCOUNTS_IN_ORG; do
    echo $accountId
    test "$(jobs | wc -l)" -ge $PARALLEL_ACCOUNTS && wait || true
    {
        ./prowler.py aws --role arn:aws-cn:iam::$accountId:role/$ROLE_TO_ASSUME \
        --organizations-role arn:aws-cn:iam::$MGMT_ACCOUNT_ID:role/$ROLE_TO_ASSUME \
	-M html csv -F prowler-output-2023-01-11 
    } &
done
```
2. Cloud provider you are launching - `aws`
3. Environment you have like single account, multi-account, organizations, multi or single subsctiption, etc. - multi-account within the organization

**Expected behavior**
Region for the finding is set to Chinese one (actual one).

**Screenshots or Logs**
I have filtered logs to show you which of the checks have this issue. Please see below (only CHECK_ID, STATUS, SEVERITY and REGION fields are shown):
```
🌱 > cat prowler-output-2023-01-11.csv | grep ';us-east-1;' | awk -F ';' '{ if (!seen[$4]++) print $4, $7, $11, $35}' | column -t

cloudwatch_changes_to_network_acls_alarm_configured                                  FAIL  medium  us-east-1
cloudwatch_changes_to_network_gateways_alarm_configured                              FAIL  medium  us-east-1
cloudwatch_changes_to_network_route_tables_alarm_configured                          FAIL  medium  us-east-1
cloudwatch_changes_to_vpcs_alarm_configured                                          FAIL  medium  us-east-1
cloudwatch_log_metric_filter_and_alarm_for_aws_config_configuration_changes_enabled  FAIL  medium  us-east-1
cloudwatch_log_metric_filter_and_alarm_for_cloudtrail_configuration_changes_enabled  FAIL  medium  us-east-1
cloudwatch_log_metric_filter_authentication_failures                                 FAIL  medium  us-east-1
cloudwatch_log_metric_filter_aws_organizations_changes                               FAIL  medium  us-east-1
cloudwatch_log_metric_filter_disable_or_scheduled_deletion_of_kms_cmk                FAIL  medium  us-east-1
cloudwatch_log_metric_filter_for_s3_bucket_policy_changes                            FAIL  medium  us-east-1
cloudwatch_log_metric_filter_policy_changes                                          FAIL  medium  us-east-1
cloudwatch_log_metric_filter_root_usage                                              FAIL  medium  us-east-1
cloudwatch_log_metric_filter_security_group_changes                                  FAIL  medium  us-east-1
cloudwatch_log_metric_filter_sign_in_without_mfa                                     FAIL  medium  us-east-1
cloudwatch_log_metric_filter_unauthorized_api_calls                                  FAIL  medium  us-east-1
```

**From where are you running Prowler?**
Please, complete the following information:
 - Resource: (e.g. EC2 instance, Fargate task, Docker container manually, EKS, Cloud9, CodeBuild, workstation, etc.) - `workstation`
 - OS: [e.g. Amazon Linux 2, Mac, Alpine, Windows, etc. ] - `MacOS`
 - Prowler Version [`./prowler --version`]: `Prowler 3.0.1`
 - Python version [`python --version`]: `Python 3.9.12`
 - Pip version [`pip --version`]: `pip 22.3.1 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)`
 - Installation method (Are you running it from pip package or cloning the github repo?): running from the master branch in the cloned repo
 - Others:

**Additional context**

**Comment by n4ch04** [comment]
Hi @daftkid we are going to review it and let you know. 
Thank you for all the details of the issue, this helps us a lot to trace it and solve it.

**Comment by MrCloudSec** [comment]
@daftkid you have above the PR solving this issue, pls try it out and let us know if that works for you.
