### ISSUE TITLE
[Bug]: Component status shows FAIL though the gaps are addressed

### ISSUE THREAD

**Issue by venky1982** [toniblyx/prowler#1700]
Prowler shows the status of some of the components as FAIL though some of the gaps are addressed such as below

PFA screenshots for your reference where the tool reported the gap on enabling object monitoring on CloudTrail for S3 objects read/write.
<img width="1625" alt="Prowler-report-sample" src="https://user-images.githubusercontent.com/113198582/212265246-e5fecab7-2285-4805-bfc4-f06c947fb99b.png">

However, the gap has been addressed long time ago. PFA evidence regarding the same
<img width="1088" alt="Evidence" src="https://user-images.githubusercontent.com/113198582/212265352-9af33d42-43d1-45b5-b858-53423ff6e4a1.png">

Please let me know how such false positves can be avoided

**Comment by venky1982** [comment]
Similarly there are other gaps that have been addressed on EC2, CloudWatch alarms, etc, But the tool still shows them as FAIL. Is there any cache / state maintained somewhere with some default TTLs. If yes, can those be flushed to generate proper report everytime?

**Comment by MrCloudSec** [comment]
Hi @venky1982, thank you for reaching us out!
The html report is showing you that there are no Cloudtrail Trails in us-east-1 region recording all S3 object-level API operation.
For which trail is the second screenshot that you are showing to us? In which region is it?

**Comment by venky1982** [comment]
@sergargar It is from us-east-1 region.

**Comment by MrCloudSec** [comment]
So prowler is not detecting that trail, right? @venky1982

**Comment by venky1982** [comment]
@sergargar Seems to me that it is loading from some form of cache instead of making the API call to get the updated trails. May be I am wrong but the observation was results are not getting updated when prowler was executed multiple times

**Comment by MrCloudSec** [comment]
Could you execute it again with `prowler aws --log-level ERROR` and send us the logs pls? Maybe some error occurring.

**Comment by n4ch04** [comment]
Hi @venky1982 did the above workaround solve your issue?

**Comment by n4ch04** [comment]
Hi @venky1982 since we do not receive feedback we assume that the issue is solved.
Feel free to reopen if the problem persists
