### ISSUE TITLE
[Bug]: /providers/aws/aws_regions_by_service.json: FileNotFoundError[13]

### ISSUE THREAD

**Issue by ghost** [toniblyx/prowler#1726]
Environment:
Windows 10
Python 3.9 

Installation Method:
Used the command "pip install prowler-cloud"

Issue found:
Error message "/providers/aws/aws_regions_by_service.json: FileNotFoundError[13]"
Issue identified in the file C:\Users\USERNAME\AppData\Local\Programs\Python\Python39\Lib\site-packages\prowler\config\config.py
In the routine get_aws_available_regions(): the variable actual_directory is not being set to anything. I used a print statement and the output was blank
My fix was to set the variable to os.path.dirname(os.path.dirname(os.path.realpath(__file__))) and this resolved the issue. 

actual_directory = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))

Note that I used os.path.dirname twice. This was done to go up a level, equivalent to going up a directory level with "cd .." . It corrects the relative path for the next command  f = open_file(f"{actual_directory}/providers/aws/{aws_services_json_file}") . Without going up a directory the file open was failing due to the context being in the subdirectory "config" . 

Setting the path using the os.path.dirname function above worked for me and corrected the file not found error. This has only been tested on Windows 10 and not on any other platform.

**Comment by MrCloudSec** [comment]
Hello @hhjd-ph, thank you for reaching us out!
What version of Prowler are you using?

**Comment by ghost** [comment]
prowler -v reports version 3.0.2

**Comment by MrCloudSec** [comment]
@hhjd-ph could you upgrade to the version 3.1.0? That issue should be fixed now.

**Comment by ghost** [comment]
I upgraded. Yes it looks to be fixed.

**Comment by MrCloudSec** [comment]
Awesome, I close this issue then.
Let us know if you have any problem, thank you!
