### ISSUE TITLE
[Bug]: [AWS] rds_instance_deletion_protection on DocumentDB

### ISSUE THREAD

**Issue by ichasco-heytrade** [toniblyx/prowler#1729]
The check `rds_instance_deletion_protection` is marked as failed when the deletion protection is enabled

It complains about the instance (the deletion protection is set in the cluster). I don't know if it is related.

Example:
```
docdb    <-- Cluster
|
|--> docdb-1 <-- Instance
```

The deletion protection is set in the docdb and prowler is complaining about docdb-1

**Comment by MrCloudSec** [comment]
Thank you for reaching us out @ichasco-heytrade!
We'll take a look a this use case shortly.

**Comment by MrCloudSec** [comment]
@ichasco-heytrade, as far as I know, the RDS Instances does not inherit the delete protection attribute.
If a RDS Cluster has deletion protection, you will have to enable it too in the instance.
Is that the case you mean?

**Comment by ichasco-heytrade** [comment]
This is not an rds as such it is a documentDB, but prowler catalogs it as RDS.
And you are right in the documentdb, the deletion protection can't be applied to the instance, it has to be applied to the cluster. 

This is the bug I think, prowler complains about the instance, and here is not possible to enable deletion protection. In the cluster, I have enabled.

**Comment by MrCloudSec** [comment]
Good point @ichasco-heytrade, let me investigate how can we fix this.

**Comment by MrCloudSec** [comment]
@ichasco-heytrade, I think the best option would be to remove DocumentDB Resources to appear in RDS checks and add a DocumentDB Service in Prowler in the future.
