### ISSUE TITLE
[Bug]: Allowlist (seemingly) Does Not Work

### ISSUE THREAD

**Issue by sinkr** [toniblyx/prowler#1733]
I'm trying the simplest case I can--am I doing something wrong here, or is this a bug?

```Allowlist:
Accounts:
   "*":
    Checks:
      "iam_avoid_root_usage":
        Regions:
          - "*"
        Resources:
          - "*"  
 ```

```
 python3.11 ./prowler.py aws --log-level ERROR -b -w ../allowlist.yaml -c iam_avoid_root_usage

This report is being generated using credentials below:

AWS-CLI Profile: [default] AWS Filter Region: [all]
AWS Account: [<redacted>] UserId: [<redacted>]
Caller Identity ARN: [arn:aws:iam::<redacted>:user/<redacted>]

Executing 1 checks, please wait...

-> Scan completed! |▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉| 1/1 [100%] in 2.8s

Overview Results:
╭───────────────────┬─────────────────╮
│ 100.0% (1) Failed │ 0.0% (0) Passed │
╰───────────────────┴─────────────────╯

Account <redacted> Scan Results (severity columns are for fails only):
╭────────────┬───────────┬──────────┬────────────┬────────┬──────────┬───────╮
│ Provider   │ Service   │ Status   │   Critical │   High │   Medium │   Low │
├────────────┼───────────┼──────────┼────────────┼────────┼──────────┼───────┤
│ aws        │ iam       │ FAIL (1) │          0 │      1 │        0 │     0 │
╰────────────┴───────────┴──────────┴────────────┴────────┴──────────┴───────╯
```
Please, complete the following information:
 - Resource: (e.g. EC2 instance, Fargate task, Docker container manually, EKS, Cloud9, CodeBuild, workstation, etc.)
 - OS: [e.g. Amazon Linux 2, Mac, Alpine, Windows, etc. ]

Mac

 - Prowler Version [`./prowler --version`]:
3.1.0

 - Python version [`python --version`]:
3.11

 - Pip version [`pip --version`]:

22.3.1
 - Installation method (Are you running it from pip package or cloning the github repo?):

pip

**Comment by MrCloudSec** [comment]
Thank you for reaching us out @sinkr !
Could you execute it with `--verbose` to see the findings pls?

**Comment by sinkr** [comment]
@sergargar thank you for the response, with ```--verbose```, the output is this:
```        
FAIL us-west-2: Root user in the account was last accessed 29 days ago.
```

**Comment by MrCloudSec** [comment]
Thank for the info @sinkr, the resources value admit only regex expressions (* is not a valid one), you can try with the following allowlist for this case:
```
Accounts:
   "*":
    Checks:
      "iam_avoid_root_usage":
        Regions:
          - "*"
        Resources:
          - "root"  
```
However, we discovered that for example  `.*` is currently not accepted as a regex expression right now. We'll fix it shortly.

**Comment by sinkr** [comment]
Hi @sergargar, this above does not work for me, nor does the fully-qualified ARN of the root account, either.

I will wait for your regex `.*` fix--thank you for your help and Prowler!

**Comment by MrCloudSec** [comment]
The ARN won't work since the resource is called <root_account> (you can see it in the output files).
https://github.com/prowler-cloud/prowler/pull/1734 will solve the regex `.*` issue.
Thank you @sinkr !

**Comment by sinkr** [comment]
Thank you @sergargar when I check out the branch _remove-re.escape_ and have the `Resources` regex as `.*`, it still fails.
```
Allowlist:
Accounts:
   "*":
    Checks:
      "iam_avoid_root_usage":
        Regions:
          - "*"
        Resources:
          - ".*"               
```

```
git branch                                                                 
  master
* remove-re.escape 
                                                                                                           
$ python3.11 ./prowler.py aws --log-level ERROR -b -w ../allowlist.yaml -c iam_avoid_root_usage --verbose

This report is being generated using credentials below:

AWS-CLI Profile: [default] AWS Filter Region: [all]
AWS Account: [<redacted>] UserId: [<redacted>]
Caller Identity ARN: [arn:aws:iam::<redacted>:user/<redacted>]

Executing 1 checks, please wait...


Check ID: iam_avoid_root_usage - iam [high]
        FAIL us-west-2: Root user in the account was last accessed 29 days ago.

-> Scan completed! |▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉| 1/1 [100%] in 2.6s

Overview Results:
╭───────────────────┬─────────────────╮
│ 100.0% (1) Failed │ 0.0% (0) Passed │
╰───────────────────┴─────────────────╯

Account <redacted> Scan Results (severity columns are for fails only):
╭────────────┬───────────┬──────────┬────────────┬────────┬──────────┬───────╮
│ Provider   │ Service   │ Status   │   Critical │   High │   Medium │   Low │
├────────────┼───────────┼──────────┼────────────┼────────┼──────────┼───────┤
│ aws        │ iam       │ FAIL (1) │          0 │      1 │        0 │     0 │
╰────────────┴───────────┴──────────┴────────────┴────────┴──────────┴───────╯
```

**Comment by MrCloudSec** [comment]
I think that is not working because you have a malformed yaml, try to add an indentation to the Accounts key like this:
```
Allowlist:
  Accounts:
    "*":
      Checks:
        "iam_avoid_root_usage":
          Regions:
            - "*"
          Resources:
            - "root"  
```
Let us know if that's the issue @sinkr, we will add a validator of that YAML to prevent this type of errors.

**Comment by sinkr** [comment]
@sergargar thank you--that fixed it.  I was going by what is [here in the documentation](https://docs.prowler.cloud/en/latest/tutorials/allowlist/).
<img width="1219" alt="image" src="https://user-images.githubusercontent.com/696374/213231894-46b70b03-08d2-4ee3-bc48-4e8371ae3cf9.png">

**Comment by MrCloudSec** [comment]
Good catch, thank you @sinkr !!
https://github.com/prowler-cloud/prowler/pull/1735 solves the documentation and add the validator.
Feel free to reopen the issue if you have any problems.
