### ISSUE TITLE
[Bug]: Moving to V3 CloudBuild

### ISSUE THREAD

**Issue by Macb3th** [toniblyx/prowler#1754]
Hi, 

We are trying to migrate from V2 to V3 by editing CloudBuild from V2. Main goal is to push results to S3 and security hub.

We made minor changes to run V3, but got this error:

> '''
> Executing 247 checks, please wait...
> --
> 977 |  
> 978 | -> Scan completed! \|⚠︎                                       \| (!) 0/247 [0%] in 2:14.9
> 979 | Traceback (most recent call last):
> 980 | File "/root/.pyenv/versions/3.9.12/bin/prowler", line 8, in <module>
> 981 | sys.exit(prowler())
> 982 | File "/root/.pyenv/versions/3.9.12/lib/python3.9/site-packages/prowler/__main__.py", line 200, in prowler
> 983 | resolve_security_hub_previous_findings(args.output_directory, audit_info)
> 984 | File "/root/.pyenv/versions/3.9.12/lib/python3.9/site-packages/prowler/providers/aws/lib/security_hub/security_hub.py", line 70, in resolve_security_hub_previous_findings
> 985 | with open(
> 986 | FileNotFoundError: [Errno 2] No such file or directory: '/codebuild/output/src474672006/src/output/prowler-output-547188551695-20230123123928.asff.json'
> '''

Build looks like this:
> '''
> version: 0.2
> phases:
>   install:
>     runtime-versions:
>       python: 3.9
>     commands:
>       - echo "Installing Prowler and dependencies..."
>       - pip3 install detect-secrets
>       - yum -y install jq
>       - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
>       - unzip awscliv2.zip
>       - ./aws/install
>       - pip3 install prowler-cloud
> 
>   build:
>     commands:
>       - echo "Running Prowler as prowler $PROWLER_OPTIONS"
>       - prowler aws $PROWLER_OPTIONS
>       - aws s3 cp --sse AES256 output/ s3://$BUCKET_REPORT/ --recursive
>  '''

PROWLER_OPTIONS | -q -M json-asff -S -f eu-west-1

Any idea what we are missing?

**Comment by MrCloudSec** [comment]
Hi @Macb3th, thank you for reaching us out!
We'll review it shortly and let you know.

**Comment by artfulbodger** [comment]
@sergargar , this is the same bug I reported under #1663  , looks like a possible bug regression from v3.0.2 where the compliance flag was fixed but the file name error has crept back?

**Comment by artfulbodger** [comment]
@sergargar I don't get this error if I omit -S (Security Hub Integration).  Looks like the Security Hub integration isn't using the same asff path as the output.

**Comment by MrCloudSec** [comment]
That's interesting @artfulbodger but I cannot reproduce the Security Hub error, are you using the latest version (3.1.1)?

**Comment by Macb3th** [comment]
Removed -S, get 0 findings(V2 version found a lot of them):


> Executing 247 checks, please wait...
> --
> 990 |  
> 991 | -> Scan completed! \|⚠︎                                       \| (!) 0/247 [0%] in 2:05.7
> 992 |  
> 993 | There are no findings in Account 547188551695
> 994 |  
> 995 |  
> 996 | [Container] 2023/01/24 09:07:05 Phase complete: BUILD State: SUCCEEDED
> 997 | [Container] 2023/01/24 09:07:05 Phase context status code:  Message:
> 998 | [Container] 2023/01/24 09:07:05 Entering phase POST_BUILD
> 999 | [Container] 2023/01/24 09:07:05 Phase complete: POST_BUILD State: SUCCEEDED
> 1000 | [Container] 2023/01/24 09:07:05 Phase context status code:  Message:

**Comment by MrCloudSec** [comment]
@Macb3th I'm going to create a new CloudFormation template of CodeBuild for version 3. I'll let you know when I do the PR so you can test it.

**Comment by MrCloudSec** [comment]
@Macb3th can you try the template of this PR https://github.com/prowler-cloud/prowler/pull/1764?

**Comment by Macb3th** [comment]
@sergargar  Is this correct:

"- pip3 install ."

**Comment by MrCloudSec** [comment]
Yes @Macb3th , since we are selecting Prowler GitHub repository as the Source of the project, you can install the package in the actual directory.

**Comment by Macb3th** [comment]
@sergargar just to clarify do I need to use CloudFormation to rebuild everything or can I just do edits in CodeBuild?

**Comment by MrCloudSec** [comment]
@Macb3th CloudFormation would be the easy way, but you can edit your BuildSpec with:

> version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing Prowler and dependencies..."
      - pip3 install .
  build:
    commands:
      - echo "Running Prowler as ./prowler $PROWLER_OPTIONS"
      - prowler $PROWLER_OPTIONS
  post_build:
    commands:
      - echo "Uploading reports to S3..."
      - aws s3 cp --sse AES256 output/ s3://$BUCKET_REPORT/ --recursive
      - echo "Done!"

and put Prowler repository as a GitHub source.

**Comment by Macb3th** [comment]
I did it this way:

```
version: 0.2
Location: https://github.com/prowler-cloud/prowler
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing Prowler and dependencies..."
      - pip3 install .
  build:
    commands:
      - echo "Running Prowler as ./prowler $PROWLER_OPTIONS"
      - prowler $PROWLER_OPTIONS --log-level ERROR
  post_build:
    commands:
      - echo "Uploading reports to S3..."
      - aws s3 cp --sse AES256 output/ s3://$BUCKET_REPORT/ --recursive
      - echo "Done!"
```

Started scanning and giving results to s3, but still had to remove "-S" otherwise failing.

**Comment by Macb3th** [comment]
Btw, with V3 changed output json formatting. Do you know how to restore it? I think that is the problem with the security hub
in V2 it was a one-liner.
In V3 it became a "real" json with correct formatting. (objects, parameters split into multiple lines):

```
    "Types": [
        "IAM"
    ],
    "FirstObservedAt": "2023-01-24T14:06:27Z",
    "UpdatedAt": "2023-01-24T14:06:27Z",
    "CreatedAt": "2023-01-24T14:06:27Z",
    "Severity": {
        "Label": "LOW"
```

**Comment by MrCloudSec** [comment]
Thank you for the info @Macb3th ! We will release version 3.1.2 soon that will let you use -S in CodeBuild.
Regarding json formatting, do you need the old formatting for any purpose or just as an idea to fix this issue?

**Comment by Macb3th** [comment]
@sergargar I need the old format, we use Athena to move results and the new format is not supported by Athena. And also it was an idea why with -S build fails.

**Comment by MrCloudSec** [comment]
@Macb3th could you create an issue requesting this change to the json format please? It would be interesting to take it a look.

**Comment by Macb3th** [comment]
sure
