### ISSUE TITLE
[Bug]: Checks iam_disable_NN_days_credentials do not append to output report

### ISSUE THREAD

**Issue by acknosyn** [toniblyx/prowler#1757]
**What happened?**
None of the three `iam_disable_NN_days_credentials` checks appear in the output report. When running Prowler with a set of checks which includes these, it's missing from the output. It also produces a blank report where the CSV only contains the column headers when the checks are run on their own.

* [iam_disable_30_days_credentials](https://github.com/prowler-cloud/prowler/tree/4e34040e62bc3e254ccd971add1e9bec858ca469/prowler/providers/aws/services/iam/iam_disable_30_days_credentials)
* [iam_disable_45_days_credentials](https://github.com/prowler-cloud/prowler/tree/4e34040e62bc3e254ccd971add1e9bec858ca469/prowler/providers/aws/services/iam/iam_disable_45_days_credentials)
* [iam_disable_90_days_credentials](https://github.com/prowler-cloud/prowler/tree/4e34040e62bc3e254ccd971add1e9bec858ca469/prowler/providers/aws/services/iam/iam_disable_90_days_credentials)

**How to reproduce it**
1. Run the following command:
```
prowler aws --checks iam_disable_45_days_credentials --output-mode csv
```
2. Observe that the CSV file only contains the header row and the check is missing.

**Expected behavior**
These checks should be included in any output file.

**Screenshots or Logs**
![check_terminal_output](https://user-images.githubusercontent.com/8602276/214142707-ccbbcdfb-ff05-401f-beac-8463492cff57.png)

![CleanShot 2023-01-24 at 09 31 10](https://user-images.githubusercontent.com/8602276/214143647-7fdface6-e82f-4a5e-ac07-668033d1be29.png)

**From where are you running Prowler?**
 - macOS `12.6.2`
 - Prowler Version [`./prowler --version`]: `Prowler 3.0.2`
 - Python version [`python --version`]: `Python 3.10.8`
 - Pip version [`pip --version`]: `pip 22.3.1`
 - Installation method (Are you running it from pip package or cloning the github repo?): pip package
 - Others:

**Additional context**
N/A

**Comment by acknosyn** [comment]
The account I'm trying does not have any IAM users. However, I'd still expect to see the check in the report as a PASS, as the other IAM user checks are still included in the report with no users because it still looks at the root user.

Just tried with an account that has users in it and the checks are included in the report. So looks like this only happens for accounts with no users.

**Comment by n4ch04** [comment]
Hi @acknosyn, this is an expected behaviour, in Prowler v3 if there are no resources to be checked the check is not launched. The FAIL and PASS results are associated with a resource.
In your case Prowler detects there are no users, so it moves forward to the next check.

**Comment by acknosyn** [comment]
Hey @n4ch04, that makes sense, but the thing that's confusing is that other IAM checks which look at users are showing up in the report, when there are no IAM users. If checks shouldn't show up when there are none of the resources, why are they showing and these checks aren't?

For example, the following checks are included in the report because of the root user:
* iam_user_mfa_enabled_console_access
* iam_user_no_setup_initial_access_key
* iam_user_two_active_access_key

So I would expect these iam_disable_30_days_credentials checks to also be included

**Comment by n4ch04** [comment]
Hi @acknosyn depends on the check, those four checks are kind of "binary".
Since there always exists a root user and the root user can or can't have mfa enabled, initial access key or two access keys there will always generate a record, on the other hand, there are checks that only will be launched if exists resources to be checked.

We do not include the root user in the other checks because exists a concrete check for the root user usage `iam_avoid_root_usage`

**Comment by acknosyn** [comment]
Ah cool, thanks for that explanation

As an aside, would be nice to have a record somewhere which shows all of the check IDs that were not included because there were no relevant resources. It would help a ton with piece of mind and reassurance, because otherwise it's kind of silently excluded which can cause doubt
