### ISSUE TITLE
[Bug]: prowler does not exit with exit code <> 0 if allowlist not found

### ISSUE THREAD

**Issue by jansepke** [toniblyx/prowler#1759]
**What happened?**
If prowler is executed with a non existing allowlist file it exists with an error but with exit code 0.

**How to reproduce it**
```prowler aws --allowlist-file does-not-existyaml```

Output:
```2023-01-24 06:12:50,718 [File: allowlist.py:73] 	[Module: allowlist]	 CRITICAL: FileNotFoundError -- [Errno 2] No such file or directory: 'prowler-allowlist.yaml'[62]```
Exit code 0

**Expected behavior**
Exit code not 0

**From where are you running Prowler?**
Please, complete the following information:
 - Resource: (e.g. EC2 instance, Fargate task, Docker container manually, EKS, Cloud9, CodeBuild, workstation, etc.) Docker
 - OS: [e.g. Amazon Linux 2, Mac, Alpine, Windows, etc. ] Alpine
 - Prowler Version [`./prowler --version`]: 3.1.1
 - Python version [`python --version`]:
 - Pip version [`pip --version`]:
 - Installation method (Are you running it from pip package or cloning the github repo?): pip
 - Others:

**Additional context**

**Comment by n4ch04** [comment]
Hi @jansepke we are going to check this out and let you know asap.

Thanks for using Prowler !!!

**Comment by toniblyx** [comment]
We will add a flag to give exit 1 when a FAIL is found like in v2. Coming in the next weeks.
