### ISSUE TITLE
[Bug]: json-asff format changed in V3

### ISSUE THREAD

**Issue by Macb3th** [toniblyx/prowler#1766]
Hi,

In V2 version json-asff format was oneliner, but in V3 it changed and AWS Athena doesn't accept the new format.

From AWS documentation example how in V2 json-asff is formatted correctly:

Use one line per record
The following JSON records are formatted correctly:

```
{ "id" : 50, "name":"John" }
{ "id" : 51, "name":"Jane" }
{ "id" : 53, "name":"Jill" }
```

The following JSON records are formatted incorrectly:
How it looks like in V3
```
{
  "id" : 50,
  "name":"John"
},
{
  "id" : 51,
  "name":"Jane"
}
{
  "id" : 53,
  "name":"Jill"
}
```

Any ideas on how to return json-asff to old formatting?

**UPDATE**: changed to -M csf file and created a new Athena table.

**Comment by toniblyx** [comment]
Hi @Macb3th, json-asff format in Prowler was built just to inject the findings to Security Hub, not to be actually used to parse anything, if you need to do so, I would  parse our own json that actually comes with more metadata per finding than json-asff. In any case,  feel free to parse and modify the given json file to meet your needs. Cheers!

**Comment by Macb3th** [comment]
@toniblyx with V2 everything worked perfectly. Now if you try to run json-asff format with "-S" the scan crashes because Security Hub doesn't approve "new" json-asff format. This was history about "-S" and other problems [https://github.com/prowler-cloud/prowler/issues/1754]

**Comment by MrCloudSec** [comment]
@Macb3th the previous issue is not related with this problem, could you try again to use `-S` in CodeBuild with the latest version (3.1.2)?

**Comment by MrCloudSec** [comment]
@Macb3th with the new version of Prowler, Codebuild is working in my environment. Please feel free to reopen the issue if you encounter any problem. Thanks for using Prowler!
