### ISSUE TITLE
[Bug]: Looks like a copy paste error in the API Gateway V2 - Access logging enabled check

### ISSUE THREAD

**Issue by congon4tor** [toniblyx/prowler#1767]
**What happened?**
The metadata file talks about API Gateway authorizers not being configured but this issue checks for access logging enabled. Looks like a copy paste error

**How to reproduce it**
1. https://github.com/prowler-cloud/prowler/blob/master/prowler/providers/aws/services/apigatewayv2/apigatewayv2_access_logging_enabled/apigatewayv2_access_logging_enabled.metadata.json#L4

**Expected behavior**
This metadata should describe the access logging not enabled issue

**Comment by MrCloudSec** [comment]
Good catch @congon4tor, thank you for letting us know!
Above you have the PR with the changes.
