### ISSUE TITLE
[Bug]: v3 does not exit with exit code <> 0 if any check fails (like in v2)

### ISSUE THREAD

**Issue by jansepke** [toniblyx/prowler#1770]
**What happened?**
If a prowler check fails the prowler executable still returns a exit code of 0. Prowler v2 was returning a different exit code in that case. This is very important to use be able to use prowler in pipelines.

**How to reproduce it**
```prowler aws --allowlist-file prowler-allowlist.yaml --region eu-central-1 --excluded-checks accessanalyzer_enabled_without_findings```
exit code = 0

**Expected behavior**
exit code <> 0

**From where are you running Prowler?**
Please, complete the following information:
 - Resource: workstation and docker
 - OS: Ubuntu / Alpine
 - Prowler Version [`./prowler --version`]: 3.1.1
 - Python version [`python --version`]: Python 3.10.6
 - Pip version [`pip --version`]:  pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)
 - Installation method (Are you running it from pip package or cloning the github repo?): pip
 - Others:

**Additional context**

**Comment by n4ch04** [comment]
Hi @jansepke we are going to review this take in to account https://github.com/prowler-cloud/prowler/issues/1759
Thanks for using Prowler !!

**Comment by toniblyx** [comment]
We will add a flag to give exit 1 when a FAIL is found like in v2. Coming in the next weeks.
