### ISSUE TITLE
[Bug]: json report is invalid if no findings written

### ISSUE THREAD

**Issue by jansepke** [toniblyx/prowler#1771]
**What happened?**
If prowler is executed with the `--quiet` flag it will only write failed checks to the report files. In case no finding was found the JSON report will end up with an invalid content o `]`

**How to reproduce it**
```
prowler aws \
      --verbose --quiet \
      --output-modes json \
      --allowlist-file prowler-allowlist.yaml \
      --region eu-central-1 \
      --excluded-services trustedadvisor macie \
      --excluded-checks accessanalyzer_enabled_without_findings
```

**Expected behavior**
a JSON report file with `[]` content

**From where are you running Prowler?**
Please, complete the following information:
 - Resource: workstation and docker
 - OS: Ubuntu / Alpine
 - Prowler Version [`./prowler --version`]: 3.1.1
 - Python version [`python --version`]: Python 3.10.6
 - Pip version [`pip --version`]:  pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)
 - Installation method (Are you running it from pip package or cloning the github repo?): pip
 - Others:

**Comment by n4ch04** [comment]
Hi @jansepke we are going to review this and let you know.

Thanks for using Prowler !!
