### ISSUE TITLE
[Bug]: script not running

### ISSUE THREAD

**Issue by rajarammohan0203** [toniblyx/prowler#1782]
prowler v2
I'll follow all the steps in prowler v2 to install 
os version: Canonical, Ubuntu, 20.04 LTS, amd64 focal image build on 2023-01-12
ami-0778521d914d23bc1

**Additional context**
![image](https://user-images.githubusercontent.com/52132926/214901858-f7532fbe-7cb2-4433-94fd-1e070226bf17.png)

**Comment by toniblyx** [comment]
Hello @rajarammohan0203 by default you are trying to execute prowler v3, for v2 switch to the proper branch, it is called prowler-2 (`git checkout prowler-2`) then it should work as you expect. For anything related to prowler v3 you don't even need to clone the repo, just see doc here https://docs.prowler.cloud/en/latest/. `pip install prowler` will make the trick.

**Comment by toniblyx** [comment]
I'm gonna proceed to close this ticket, please feel free to reopen it if you need further assistance. Thanks for using Prowler!
