### ISSUE TITLE
[Bug]: cloudtrail_s3_dataevents_write_enabled check does not work in AWS GovCloud in v3

### ISSUE THREAD

**Issue by mhamill2** [toniblyx/prowler#1784]
**What happened?**
We are in the process of upgrading to Prowler v3 and we are seeing some checks fail in the new version that we were not seeing in version 2. One of which is cloudtrail_s3_dataevents_write_enabled (previously extra725).

It looks like the python implementation of the check does not account for AWS GovCloud, as it is only checking for resource values of arn:aws:s3 and arn:aws:s3:::*/* and not including arn:aws-us-gov:s3: https://github.com/prowler-cloud/prowler/blob/master/prowler/providers/aws/services/cloudtrail/cloudtrail_s3_dataevents_write_enabled/cloudtrail_s3_dataevents_write_enabled.py#L24-L27

The previous check was using a templated string for the resource value: https://github.com/prowler-cloud/prowler/blob/2.12.1/checks/check_extra725#L46

**How to reproduce it**
1. Run the following in an AWS GovCloud enviornment that contains a CloudTrail with a data event to record all S3 operations: prowler aws -c cloudtrail_s3_dataevents_write_enabled
2. The check will fail when it shouldn't

**Expected behavior**
The check should have the same behavior as the version 2 check and pass in GovCloud

**From where are you running Prowler?**
 - Resource: Docker container manually
 - OS: Alpine Linux v3.16
 - Prowler Version: 3.1.2
 - Python version: 3.9.15
 - Pip version: 22.3.1
 - Installation method: pip3 install prowler-cloud

**Comment by n4ch04** [comment]
Hi @mhamill2 we are going to review this and let you know asap.

Thanks for using Prowler !!

**Comment by MrCloudSec** [comment]
Hi @mhamill2, thanks for reaching us out!
Can you try the above PR to see if it works in your environment?

**Comment by mhamill2** [comment]
@sergargar This fix is working for us. Thank you!
