### ISSUE TITLE
[Bug]: kms_cmk_rotation_enabled check fails for key types that don't have the automatic rotation option in v3

### ISSUE THREAD

**Issue by mhamill2** [toniblyx/prowler#1785]
**What happened?**
When upgrading to version 3 the kms_cmk_rotation_enabled (previously check28) started failing for us when it wasn't in version 2. 

I see in version 2 that this check used to grep for SYMMETRIC so that only Symmetric encryption KMS keys would be checked: https://github.com/prowler-cloud/prowler/blob/2.12.1/checks/check28#L39

Version 3 does not appear to do this and does a check against all KMS keys, even if automatic rotation is not available for that type of key. For example we have RSA_4096 keys and we are failing this check because automatic rotation is not enabled for them, even though automatic rotation isn't even an option for that key type. 

I believe this check needs to be updated to ensure only symmetric encryption keys are checked against. 

**How to reproduce it**
1. Create an RSA_4096 KMS key in AWS and run the following check: prowler aws -c kms_cmk_rotation_enabled
2. The check fails

**Expected behavior**
Prowler should skip these keys since automatic rotation is not available for them. 

**From where are you running Prowler?**
 - Resource: Docker container manually
 - OS: Alpine Linux v3.16
 - Prowler Version: 3.1.2
 - Python version: 3.9.15
 - Pip version: 22.3.1
 - Installation method: pip3 install prowler-cloud

**Comment by n4ch04** [comment]
Hi @mhamill2 we are going to check this out and let you know 

Thanks for using Prowler !!

**Comment by MrCloudSec** [comment]
Hi @mhamill2, thanks for reaching us out!
Can you try the above PR to see if it works in your environment?

**Comment by mhamill2** [comment]
@sergargar Yep that fix seems to work for us. Thank you!
