### ISSUE TITLE
Grafana integration

### ISSUE THREAD

**Issue by rajarammohan0203** [toniblyx/prowler#1791]
**Is it possible to integrate the prowler in grafana**
 because your prowler-cloud UI looks like a grafana dashboard, that's why I am asking 
 - is it possible means,  let me know, how to do that 
 

**client doesn't want another UI**
 the customer asks a question to DevOps engineers 
 - I'm already using grafana prometheus to see the logs and status in the grafana dashboard, so I don't want another UI to see the prowler logs

**Comment by toniblyx** [comment]
Hi @rajarammohan0203, you can inject all CSV output from Prowler into you favorite SQL database and use Grafana to query it. We don't provide that directly to you but feel free to use ProwerPro at https://prowler.pro.

**Comment by rajarammohan0203** [comment]
thanks
