### ISSUE TITLE
[Bug]: some cloudtrail checks are failing

### ISSUE THREAD

**Issue by ichasco-heytrade** [toniblyx/prowler#1795]
It seems like some of the cloudtrail checks are failing

The check `cloudtrail_logs_s3_bucket_access_logging_enabled` is marked as an error when the s3 bucket has the logs enabled. 

![image](https://user-images.githubusercontent.com/77392885/215343133-5907b7e3-1951-463b-bb72-e5f79fe2ee1d.png)

The checks `cloudtrail_s3_dataevents_read_enabled` and `cloudtrail_s3_dataevents_write_enabled` are failing and the cloudtrail config is ok

CloudTrail data events config:
```
[
  {
    "name": "S3 Read Events",
    "fieldSelectors": [
      {
        "field": "eventCategory",
        "equals": [
          "Data"
        ]
      },
      {
        "field": "resources.type",
        "equals": [
          "AWS::S3::Object"
        ]
      },
      {
        "field": "readOnly",
        "equals": [
          "true"
        ]
      }
    ]
  },
  {
    "name": "S3 Write Events",
    "fieldSelectors": [
      {
        "field": "eventCategory",
        "equals": [
          "Data"
        ]
      },
      {
        "field": "resources.type",
        "equals": [
          "AWS::S3::Object"
        ]
      },
      {
        "field": "readOnly",
        "equals": [
          "false"
        ]
      }
    ]
  }
]
```

![image](https://user-images.githubusercontent.com/77392885/215345297-2c30b1a8-e32c-445a-aa30-423b92baf080.png)

![image](https://user-images.githubusercontent.com/77392885/215345368-1598c8c5-dd6d-41f1-bdcf-d296d57ea969.png)

Prowler version: `3.1.2`

**Comment by n4ch04** [comment]
Hi @ichasco-heytrade regarding check `cloudtrail_logs_s3_bucket_access_logging_enabled` we can't reproduce the behaviour you describe.
To ensure everything is well configured, please check that the trail bucket policy  includes an statement like the following:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "S3ServerAccessLogsPolicy",
            "Effect": "Allow",
            "Principal": {
                "Service": "logging.s3.amazonaws.com"
            },
            "Action": [
                "s3:PutObject"
            ],
            "Resource": "arn:aws:s3:::DOC-EXAMPLE-BUCKET/EXAMPLE-LOGGING-PREFIX*",
            "Condition": {
                "ArnLike": {
                    "aws:SourceArn": "arn:aws:s3:::SOURCE-BUCKET-NAME"
                },
                "StringEquals": {
                    "aws:SourceAccount": "SOURCE-ACCOUNT-ID"
                }
            }
        }
    ]
}	
```

For the other two checks we have realised that we were only checking for old data events selectors not included the advanced ones.  We are going to include it asap, thanks for pointing this out

**Comment by ichasco-heytrade** [comment]
I don't have that policy in cloudtrail bucket. It only has the `Server access logging` enabled (this is how is created by aws terraform module)

**Comment by n4ch04** [comment]
Hi @ichasco-heytrade can you check this again with the latest version code please?

**Comment by ichasco-heytrade** [comment]
Hi @n4ch04 the part of the `cloudtrail_s3_dataevents_read_enabled` and `cloudtrail_s3_dataevents_write_enabled` is fixed. But `cloudtrail_logs_s3_bucket_access_logging_enabled` is still failing
