### ISSUE TITLE
[Bug]: accessanalyzer_enabled_without_findings check fails

### ISSUE THREAD

**Issue by ichasco-heytrade** [toniblyx/prowler#1796]
The check `accessanalyzer_enabled_without_findings` shows that there are active findings but I have archived all of them. If they are archived, should it mark as failed?

![image](https://user-images.githubusercontent.com/77392885/215345689-4c7b926d-15d9-48aa-8222-ff2c225f8853.png)

**Comment by n4ch04** [comment]
Hi @ichasco-heytrade we are going to check this out and let you know, thanks for using Prowler !!

**Comment by n4ch04** [comment]
Hi @ichasco-heytrade we have included a workaround here https://github.com/prowler-cloud/prowler/pull/1799 to solve this issue, please check it out and let us know if everything is working

**Comment by ichasco-heytrade** [comment]
Hi @n4ch04  It works perfectly now. 
Thank you!
