### ISSUE TITLE
[Bug]: Check `ecr_repositories_lifecycle_policy_enabled` is failing

### ISSUE THREAD

**Issue by ichasco-heytrade** [toniblyx/prowler#1797]
The check `ecr_repositories_lifecycle_policy_enabled` is marked as failed but the lifecycle policy exists

![image](https://user-images.githubusercontent.com/77392885/215346401-ef2f67c1-df9d-40b0-9ddd-d10e7aef6098.png)

![image](https://user-images.githubusercontent.com/77392885/215346546-1ea75a76-a30c-405e-8bb9-571ae3dddb92.png)

Thanks

**Comment by n4ch04** [comment]
Hi @ichasco-heytrade we are going to check this out and let you know, thanks for using Prowler !!

**Comment by n4ch04** [comment]
Hi @ichasco-heytrade we can't reproduce the behaviour you describe in our test environments, can you provide more details executing the same check with `--log-level ERROR` and `--verbose` flags and share the logs?

**Comment by n4ch04** [comment]
Hi @ichasco-heytrade have you made any progress on this issue?

**Comment by ichasco-heytrade** [comment]
I have run the next command:

```
prowler aws -q -b -f eu-west-1 -c ecr_repositories_lifecycle_policy_enabled --log-level ERROR --verbose --log-file prowler.log
```

and this is the output:

![image](https://user-images.githubusercontent.com/77392885/216046991-75cc4831-f843-4179-b838-3302a8f10f31.png)

the file `prowler.log` is empty

**Comment by n4ch04** [comment]
Hi @ichasco-heytrade this is really weird, we can't reproduce the issue.
I am testing it right now in a repo with the following lifecycle policy configuration and it is working fine
<img width="1373" alt="Screenshot 2023-02-09 at 08 20 10" src="https://user-images.githubusercontent.com/59198746/217744596-1bf384fd-471d-4b25-8449-87f9b99ca5db.png">

Can you ensure you have the latest version of Prowler? It would be helpful also if you provide the info included in the PR template

**Comment by n4ch04** [comment]
Hi @ichasco-heytrade since we don't receive feedback from you, we consider that this is solved.
If the issue persists please feel free to reopen or open a new issue.

Thanks for using Prowler !!
