### ISSUE TITLE
need clarification for eks-cis

### ISSUE THREAD

**Issue by rajarammohan0203** [toniblyx/prowler#1810]
**can you please explain the EKS-CIS checklist**
 - it only checks whether the eks cluster endpoint is private or not 
 - can you describe the checks what are all the security scan has done in EKS-CIS

**did you provide eks full vulnerability compliance  scan report**
- because why I am asking compare to Trivy  with prowler,  The Trivy tool gives a more detailed report of the EKS Cluster vulnerability 
   and misconfiguration 

**About Prowler-ui**
- In prowler-ui I will only give the view-only and security audit credentials to access and audit my aws account, but our customer has fear about this because you will store the entire security audit logs in your server, how do I know it securely stores into your server, 
   is any encryption you will maintain for the data to be securely transferred through the internet....?

**Comment by toniblyx** [comment]
Hi @rajarammohan0203 as you may know, we support the following checks for EKS (`prowler -l | grep eks`):
```
[eks_cluster_kms_cmk_encryption_in_secrets_enabled] Ensure Kubernetes Secrets are encrypted using Customer Master Keys (CMKs) - eks [medium]
[eks_control_plane_endpoint_access_restricted] Restrict Access to the EKS Control Plane Endpoint - eks [medium]
[eks_control_plane_logging_all_types_enabled] Ensure EKS Control Plane Audit Logging is enabled for all log types - eks [medium]
[eks_endpoints_not_publicly_accessible] Ensure EKS Clusters are created with Private Endpoint Enabled and Public Access Disabled - eks [high]
``` 

Those checks are part of the CIS benchmark for EKS and those checks are the ones that can be performed directly using the AWS API endpoint for EKS, we don't perform any check that requires access to the K8s API itself (as other K8s tools do). At this point we don't plan to pair Prowler with any other specific K8s tool.

If you refer to ProwlerPro with Prowler-ui and you have questions about its security please visit https://docs.prowler.pro/en/latest/security/#encryption or reach out to us via `help@prowler.pro` for more details.

**Comment by rajarammohan0203** [comment]
thanks for the information
