### ISSUE TITLE
[Bug]: Prowler fails on 3 AWS checks

### ISSUE THREAD

**Issue by jchandramouli** [toniblyx/prowler#1811]
**What happened?**
We are getting error on 3 checks when trying to run prowler against the AWS cloud. Those are `efs_not_publicly_accessible`, `s3_bucket_public_access` and ` vpc_endpoint_connections_trust_boundaries`

**How to reproduce it**
1. What command are you running?
`prowler aws -c efs_not_publicly_accessible s3_bucket_public_access vpc_endpoint_connections_trust_boundaries -M csv -o . -F prowler_test_run_output4 -f us-east-1 --log-level ERROR -b -q`
2. Cloud provider you are launching
AWS
3. Environment you have like single account, multi-account, organizations, multi or single subsctiption, etc.
Single account

**Expected behavior**
The checks should show results as to whether it passed or failed 

**Screenshots or Logs**

![image](https://user-images.githubusercontent.com/71663363/215906071-3ff9ba88-3150-4bfa-84c8-a95112db902d.png)

**From where are you running Prowler?**
Please, complete the following information:
 - Resource: Workstation (MacBook)
 - OS: Mac OS v13.1
 - Prowler Version [`./prowler --version`]: Prowler 3.1.1
 - Python version [`python --version`]: Python 3.9.10
 - Pip version [`pip --version`]: pip 21.3.1
 - Installation method (Are you running it from pip package or cloning the github repo?): running it from pip package
 - Others:

**Additional context**
The user running the above command has full access to the AWS account.

**Comment by n4ch04** [comment]
Hi @jchandramouli we are going to review this and let you know asap.
Since the las version is `3.1.2` can you update Prowler with `pip install prowler --upgrade` ?

**Comment by jchandramouli** [comment]
@n4ch04  Updated prowler to 3.1.2 and still seeing same error

**Comment by Maitriporwal16** [comment]
Prowler version 3.1.2 fails to check against GDPR, HIPPA compliance checks, it's showing scanning aborted, how to solve this issue?

**Comment by MrCloudSec** [comment]
Hi @jchandramouli, could you update Prowler to the new 3.1.3 version and send us the new logs?

**Comment by MrCloudSec** [comment]
Hi @Maitriporwal16, thank you for reaching us out! Could you create an issue with that problem please?

**Comment by jchandramouli** [comment]
@sergargar  tried with 3.1.3 and still same error. 
```
Executing 3 checks, please wait...

Something went wrong in efs_not_publicly_accessible, please use --log-level ERROR
2023-02-03 15:23:23,143 [File: check.py:307] 	[Module: check]	 ERROR: efs_not_publicly_accessible -- TypeError[21]: string indices must be integers
Something went wrong in s3_bucket_public_access, please use --log-level ERROR
2023-02-03 15:23:42,923 [File: check.py:307] 	[Module: check]	 ERROR: s3_bucket_public_access -- KeyError[56]: 'Principal'
Something went wrong in vpc_endpoint_connections_trust_boundaries, please use --log-level ERROR
2023-02-03 15:23:51,619 [File: check.py:307] 	[Module: check]	 ERROR: vpc_endpoint_connections_trust_boundaries -- IndexError[29]: list index out of range
```

**Comment by Maitriporwal16** [comment]
It's showing error while checking against GDPR, SOC 2, HIPPA & checks numbers also, how can we solve this issue with version 3.1.2?


<img width="1440" alt="Screenshot 2023-02-05 at 10 11 59 PM" src="https://user-images.githubusercontent.com/63542734/216832287-363daba4-dcb7-4969-8df2-5c798fde54aa.png">

**Comment by MrCloudSec** [comment]
Thanks for the info @jchandramouli. What is the pattern that you are using for the policies of your EFS?

**Comment by jchandramouli** [comment]
@sergargar  Most of the EFS instances dont have policy. 
```
aws efs describe-file-system-policy --file-system-id fs-xxxx 

An error occurred (PolicyNotFound) when calling the DescribeFileSystemPolicy operation: None
```
Only 1 have policy and thats following this pattern and it follows the style mentioned [here](https://docs.aws.amazon.com/efs/latest/ug/create-file-system-policy.html):

**Comment by MrCloudSec** [comment]
Thank you for the info @jchandramouli, I have detect the error. The above PR solves your issues.

**Comment by jchandramouli** [comment]
Thank you so much.
