### ISSUE TITLE
[Bug]: cloudtrail_logs_s3_bucket_access_logging_enabled reports failed when access logging is enabled

### ISSUE THREAD

**Issue by kovaxur** [toniblyx/prowler#1820]
Hi,

**What happened?**
The cloudtrail_logs_s3_bucket_access_logging_enabled check fails, when we have a trail, which is logging to a remote account's s3 bucket. The access logging is enabled on the bucket.

On the bucket:
![image](https://user-images.githubusercontent.com/9846259/216302735-ff0e7519-9fbf-41ba-a5f8-b7a21257483e.png)

Prowler output:
![image](https://user-images.githubusercontent.com/9846259/216303538-630cbb7c-d212-4e80-bb0c-fb75f1fc1660.png)

**How to reproduce it**
1. Set up trail to log to a remote account's s3 bucket
2. enable access logging on the bucket
3. run the check

**Expected behavior**
The check should mark this as passed.

**Screenshots or Logs**
```
prowler aws \
  --output-directory public \
  --output-filename "${CI_ENVIRONMENT_NAME}" \
  --output-modes html \
  --role "${ROLE_ARN}" \
  --excluded-checks \
      securityhub_enabled \
      config_recorder_all_regions_enabled \
      macie_is_enabled \
      accessanalyzer_enabled_without_findings \
      iam_root_mfa_enabled \
      iam_root_hardware_mfa_enabled \
      iam_avoid_root_usage \
  --log-level ERROR \
  --checks cloudtrail_logs_s3_bucket_access_logging_enabled
```

There are no error logs for this check.

**From where are you running Prowler?**
Please, complete the following information:
 - Resource: EC2
 - OS: Amazon Linux 2
Prowler Version [./prowler --version]: 3.1.2
Python version [python --version]: 3.11.1
Pip version [pip --version]: 22.3.1
 - Installation method (Are you running it from pip package or cloning the github repo?): pip

**Additional context**
N/A

**Comment by MrCloudSec** [comment]
Hi @kovaxur, thanks for reaching us out!
Could you test it again in the new version 3.1.3?

**Comment by n4ch04** [comment]
Hi @kovaxur this is fixed in the related PR, please check it out
