### ISSUE TITLE
[Bug]: Link in the Prowler output for the SecurityHub forwards to nowhere

### ISSUE THREAD

**Issue by daftkid** [toniblyx/prowler#1825]
**What happened?**
I tried to run Prowler with posting findings to SecurityHub and I can see the following message in the Prowler outputs:
```
2023-02-02 17:51:21,502 [File: security_hub.py:40] 	[Module: security_hub]	 ERROR: Security Hub is enabled in cn-northwest-1 but Prowler integration does not accept findings. More info: https://github.com/prowler-cloud/prowler/#security-hub-integration
```
As I can see it's defined here: https://github.com/prowler-cloud/prowler/blob/master/prowler/providers/aws/lib/security_hub/security_hub.py#L41

**How to reproduce it**
1. What command are you running? `prowler aws -M html csv -S`
2. Cloud provider you are launching `aws`
3. Environment you have like single account, multi-account, organizations, multi or single subsctiption, etc. 
```
2023-02-02 17:51:21,502 [File: security_hub.py:40] 	[Module: security_hub]	 ERROR: Security Hub is enabled in cn-northwest-1 but Prowler integration does not accept findings. More info: https://github.com/prowler-cloud/prowler/#security-hub-integration
```

**Expected behavior**
Link forwards to the correct section with the SecurityHub related docs.

**Screenshots or Logs**
Also, you can add logs (anonymize them first!). Here a command that may help to share a log
`prowler <your arguments> --log-level DEBUG --log-file $(date +%F)_debug.log` then attach here the log file.

**From where are you running Prowler?**
Please, complete the following information:
 - Resource: (e.g. EC2 instance, Fargate task, Docker container manually, EKS, Cloud9, CodeBuild, workstation, etc.)
 - OS: [e.g. Amazon Linux 2, Mac, Alpine, Windows, etc. ]
 - Prowler Version [`./prowler --version`]:
 - Python version [`python --version`]:
 - Pip version [`pip --version`]:
 - Installation method (Are you running it from pip package or cloning the github repo?):
 - Others:

**Additional context**
Also, I can see the same link is referenced within the AWS SecurityHub integration for the Prowler product. I think it should be fixed too.

**Comment by MrCloudSec** [comment]
Hi @daftkid, thank you for reaching us out!
This error is related to the integration of Prowler in Security Hub, please, make sure that you have activated the integration. You can see it in the Step 2 in the [documentation](https://docs.prowler.cloud/en/latest/tutorials/aws/securityhub/).

**Comment by daftkid** [comment]
Hi @sergargar yeah, I already found this document and was able to integrate sechub, my initial concern was related to the fact that URL provided in the error message (and even more - in the SecHub product for Prowler) forwards to the old github readme section (https://github.com/prowler-cloud/prowler/#security-hub-integration) that is not in place anymore. I think it should be changed to the one you shared with me (https://docs.prowler.cloud/en/latest/tutorials/aws/securityhub/)

**Comment by MrCloudSec** [comment]
Totally right @daftkid, good catch!
Above you have the PR with the changes.
