### ISSUE TITLE
[Bug]: CIS 1.5 benchmark 1.20 fails when access analyzer findings are present in account

### ISSUE THREAD

**Issue by addefisher** [toniblyx/prowler#1827]
**What happened?**
As shown below, when running prowler with the `--compliance cis_1.5_aws` option, Prowler reports failures for CIS benchmark `1.20` (Ensure that IAM Access Analyzer is enabled for all regions) when access analyzer is enabled but has open findings. While the underlying check (`accessanalyzer_enabled_without_findings`) is performing as expected based on its name, it is not appropriate for testing benchmark `1.20`, as this benchmark only specifies that access analyzer should be enabled, regardless of open findings.
![image](https://user-images.githubusercontent.com/97761488/216456292-d49a37c8-d60f-4498-9447-b4e95c86964e.png)

**How to reproduce it**
Run the following command in any AWS account / region where access analyzer is enabled and has at least one open finding:
`prowler aws --compliance cis_1.5_aws`

**Expected behavior**
Running prowler with the `--compliance cis_1.5_aws` option should not execute the check `accessanalyzer_enabled_without_findings`. Instead, a different check should be executed (i.e. `accessanalyzer_enabled`) which only reports failure if access analyzer is disabled in an AWS account / region

**Screenshots or Logs**
![image](https://user-images.githubusercontent.com/97761488/216456292-d49a37c8-d60f-4498-9447-b4e95c86964e.png)

**From where are you running Prowler?**
Please, complete the following information:
 - Resource: ECS Fargate task (reproduced behavior on local workstation)
 - OS: MacOS (local)
 - Prowler Version [`./prowler --version`]: 3.1.1
 - Python version [`python --version`]: 3.10
 - Pip version [`pip --version`]:
 - Installation method (Are you running it from pip package or cloning the github repo?): pip package
 - Others:

**Additional context**

**Comment by MrCloudSec** [comment]
Thank you for reaching us out @addefisher !
I totally agree with you, we will create a new check called `accessanalyzer_enabled` to address this issue.
