### ISSUE TITLE
[Bug]: Prowler does not log error messages when security hub uploads fail

### ISSUE THREAD

**Issue by addefisher** [toniblyx/prowler#1828]
**What happened?**
When running prowler with the `-S` option, no error messages are shown when sending findings to AWS SecurityHub via the `BatchUpdateFindings` API fails

**How to reproduce it**
Run a prowler scan with the `-S` option while using an IAM role or user which does not have permission to call `securityhub:BatchUpdateFindings`

**Expected behavior**
An error log is generated indicating the security upload failed.

**Screenshots or Logs**
Also, you can add logs (anonymize them first!). Here a command that may help to share a log
`prowler <your arguments> --log-level DEBUG --log-file $(date +%F)_debug.log` then attach here the log file.

**From where are you running Prowler?**
Please, complete the following information:
- Resource: ECS Fargate task (reproduced behavior on local workstation)
- OS: MacOS (local)
- Prowler Version [./prowler --version]: 3.1.1
- Python version [python --version]: 3.10
- Pip version [pip --version]:
- Installation method (Are you running it from pip package or cloning the github repo?): pip package (reproduced via repo cloning as well)

**Additional context**
This behavior is particularly problematic because it can cause Prowler to archive valid security findings which were uploaded on scan N-1 and then failed to upload on scan N.

**Comment by MrCloudSec** [comment]
Hi @addefisher, thank you for reaching us out!
Error logs are only displayed when you use the flag `--log-level ERROR`. By default, Prowler will only show CRITICAL logs.

**Comment by addefisher** [comment]
thanks for clarifying @sergargar , closing this out
