### ISSUE TITLE
[Bug]: kms_cmk_rotation_enabled check fails for AWS managed KMS keys used by ACM

### ISSUE THREAD

**Issue by addefisher** [toniblyx/prowler#1838]
**What happened?**
The `kms_cmk_rotation_enabled` appears to be scanning Amazon managed KMS keys in addition to customer managed CMKs for key rotation. This behavior is unnecessary since AWS customers are not able to enable or disable key rotation for AWS managed KMS keys.

Furthermore, AWS customers do not have the ability to modify the resource policy (i.e. key policy) on AWS managed KMS keys. For certain types of AWS managed KMS keys, such as those used by the ACM service, the resource policies on these keys do not allow any principal to call `kms:GetKeyRotationStatus` against the key, causing Prowler to error.

**How to reproduce it**
run `prowler aws --checks kms_cmk_rotation_enabled` in an AWS account / region with at least one ACM certificate present. Ensure that a KMS key with alias `aws/acm` is present as well.

**Expected behavior**
The `kms_cmk_rotation_enabled` check should not scan any AWS managed KMS keys. The check should not raise any errors unless the customer has configured an under-permissive key policy on a customer managed KMS key.

**Screenshots or Logs**
2023-02-03 15:35:54,753 [File: kms_service.py:75]       [Module: kms_service]    ERROR: us-west-2 -- ClientError:71 -- An error occurred (AccessDeniedException) when calling the GetKeyRotationStatus operation: User: [redacted] is not authorized to perform: kms:GetKeyRotationStatus on resource: [redacted] because no resource-based policy allows the kms:GetKeyRotationStatus action

**From where are you running Prowler?**
Please, complete the following information:
 - Resource: workstation
 - OS: MacOs
 - Prowler Version [`./prowler --version`]: 3.1.1
 - Python version [`python --version`]: 3.1.0
 - Pip version [`pip --version`]: 22.3.1
 - Installation method (Are you running it from pip package or cloning the github repo?): pip package
 - Others:

**Additional context**

**Comment by MrCloudSec** [comment]
Thanks for reaching us out @addefisher  ! 
You're right, we are calling `kms:GetKeyRotationStatus ` to AWS Managed keys, the above PR solves the issue.
