### ISSUE TITLE
[Bug]: cis_1.5_aws benchmark scan shows failures when security hub is enabled without standards

### ISSUE THREAD

**Issue by addefisher** [toniblyx/prowler#1839]
**What happened?**
When running prowler with the `--compliance cis_1.5_aws` option, failures are shown for the `securityhub_enabled` check when Security Hub is enabled, but does not have standards subscriptions enabled. This is reported as a failure of CIS AWS foundations v1.5 benchmark 4.16, even though the this benchmark only calls for the SecurityHub service (as opposed to the standards) to be enabled.

**How to reproduce it**
1. Confirm security hub is enabled in an AWS account / region: `aws securityhub describe-hub`
2. Confirm security hub standards are not enabled: `aws securityhub get-enabled-standards`
3. Run `prowler aws --compliance cis_1.5_aws`

**Expected behavior**
No failures reported if security hub is enabled without standards.

**Screenshots or Logs**
`aws securityhub describe-hub` output:
{
    "HubArn": "[redacted],
    "SubscribedAt": "[redacted]",
    "AutoEnableControls": [redacted]
}

`aws securityhub get-enabled-standards` output:
{
    "StandardsSubscriptions": []
}

Prowler output: 
https://github.com/prowler-cloud/prowler/issues/1838

**From where are you running Prowler?**
Please, complete the following information:
 - Resource: workstation
 - OS: MacOS
 - Prowler Version [`./prowler --version`]: 3.1.1
 - Python version [`python --version`]: 3.10
 - Pip version [`pip --version`]: 22.3.1
 - Installation method (Are you running it from pip package or cloning the github repo?): pip package
 - Others:

**Additional context**
Security team who opt to use Prowler for CIS compliance will often want to disable SecurityHub standards in order to reduce noise in security hub. Also, SecurityHub standards currently do not include the CIS AWS foundations benchmark version 1.5

**Comment by MrCloudSec** [comment]
Thank you for reaching us out @addefisher !
I totally agree with you, we will change the behavior of the check to address this issue.

**Comment by MrCloudSec** [comment]
The problem is that once you activate SecurityHub, `aws securityhub describe-hub` will always say that it is active, even if you have it disabled at that moment.
That is why we check the standards, if you don't have any of them, SecurityHub is disabled.

**Comment by toniblyx** [comment]
Hi @addefisher, we'd like to know more about your use case, if you have Security Hub on but without any standard enabled, do you have instead integrations only? I mean, we can improve the check looking for enabled standards and/or integrations otherwise, having Security Hub enabled without standards or integrations (hence findings) would deserve a FAIL, what do you think?

**Comment by addefisher** [comment]
@toniblyx I think your approach would work for me, we currently have security hub enabled without standards because we want to use Prowler as our source of truth for CIS 1.5 compliance, and do not wish to receive findings for any other compliance frameworks at this time.
