### ISSUE TITLE
[Bug]: iam_root_hardware_mfa_enabled fails even if hardware mfa is present

### ISSUE THREAD

**Issue by ldina** [toniblyx/prowler#1855]
**What happened?**
Check iam_root_hardware_mfa_enabled fails when multiple MFA are enabled and  hardware mfa is present in the root account

**How to reproduce it**
1. What command are you running? aws -f eu-west-1 -M html
2. Cloud provider you are launching aws
3. Environment you have: organizations

**Expected behavior**
Detect that at least one hardware MFA is enabled

**Screenshots or Logs**
Error
![Schermata 2023-02-07 alle 17 00 58](https://user-images.githubusercontent.com/43407568/217298157-92a8740c-d190-4fa3-ae2c-3daca9a279ae.png)

IAM configuration with 2 MFA enabled one virtual and one hardware fido
![Schermata 2023-02-07 alle 17 05 53](https://user-images.githubusercontent.com/43407568/217298524-3fbcd1d1-de4e-4efc-b2bf-a11fc9c3d452.png)

**From where are you running Prowler?**
Please, complete the following information:
 - Resource: EC2 instance,
 - OS: Amazon Linux 2
 - Prowler Version [`prowler --version`]:3.1.3
 - Python version [`python --version`]:3.11.1
 - Pip version [`pip --version`]:pip 23
 - Installation method (Are you running it from pip package or cloning the github repo?): pip package

**Comment by n4ch04** [comment]
Hi @ldina we are going to review this and let you know, thanks for using Prowler !!

**Comment by n4ch04** [comment]
Hi @ldina the check detects if you have anything other than a hardware mfa enabled for the root user. If you have a virtual and a hardware mfa configured the check detects the virtual one and fails since the root user should have only the hardware one

**Comment by ldina** [comment]
Hi @n4ch04 I see your point so if you plan to keep the check that way I suggest that the Check Description, Status Extended and Recommendation reflects that.
LIke "Ensure hardware MFA is enabled for the root account" -->Ensure **only** hardware MFA is enabled for the root account"
"Root account has a virtual MFA instead of a hardware MFA device enabled." --> "Root account has a virtual MFA instead **of having only** a hardware MFA device enabled."
"The root account is the most privileged user in an AWS account. MFA adds an extra layer of protection on top of a user name and password. With MFA enabled when a user signs in to an AWS website they will be prompted for their user name and password as well as for an authentication code from their AWS MFA device. For Level 2 it is recommended that the root account be protected with a hardware MFA." --> "The root account is the most privileged user in an AWS account. MFA adds an extra layer of protection on top of a user name and password. With MFA enabled when a user signs in to an AWS website they will be prompted for their user name and password as well as for an authentication code from their AWS MFA device. For Level 2 it is recommended that the root account be protected with **only** a hardware MFA."

**Comment by n4ch04** [comment]
Hi @ldina , you are right,  we are going to update it and let you know when it is done.
