### ISSUE TITLE
Add command line argument(s) to set max retries for AWS checks

### ISSUE THREAD

**Issue by addefisher** [toniblyx/prowler#1856]
**Is your feature request related to a problem? Please describe.**
I see intermittent failures on automated Prowler scans due to errors like the one below:
`[File: ec2_service.py:209] [Module: ec2_service] ERROR: us-east-2 -- ClientError[195]: An error occurred (RequestLimitExceeded) when calling the DescribeNetworkInterfaces operation (reached max retries: 4): Request limit exceeded.`

**Describe the solution you'd like**
The following functionality would help me address these errors:
- all `boto3` clients created by Prowler should use the `standard` retry mode as opposed to `legacy`, this retry mode covers more exception types, including the `RequestLimitExceeded` error shown above
- add a command line argument (like `--aws-max-attempts`) to allow users to override the default number of max attempts used in the boto3 clients retry mode

**Comment by jfagoagas** [comment]
Hi @addefisher, first of all thank you for using Prowler!

We are working on this right now, we'll keep you posted.

**Comment by jfagoagas** [comment]
Hi @addefisher, can you check the above PR, we have included the `standard` boto3 retrier with the new argument you suggest.

Thanks!

**Comment by addefisher** [comment]
@jfagoagas PR looks good, thanks!!
