### ISSUE TITLE
[Bug]: iam_no_custom_policy_permissive_role_assumption check produces false positive results for some policy statements

### ISSUE THREAD

**Issue by pmastrovito** [toniblyx/prowler#1866]
**What happened?**
The `iam_no_custom_policy_permissive_role_assumption` check produces false positive results for some policy statements.

**How to reproduce it**

1. Create an IAM policy that contains the following:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": "s3:*",
            "Effect": "Allow",
            "Resource": "*"
        }
    ]
}
```
2. run prowler `python3.10 ./prowler/prowler.py aws --services iam`
3. The policy fails the check.

**Expected behavior**
The example policy above does not contain statements that would allow permissive role assumption; it should not fail the test.

The problem appears to be in this [if statement](https://github.com/prowler-cloud/prowler/blob/master/prowler/providers/aws/services/iam/iam_no_custom_policy_permissive_role_assumption/iam_no_custom_policy_permissive_role_assumption.py#L23-L27). The conditions are not handling the fact that `statement["Action"]` could be a string or a list.

When the `statement["Action"]` is a list, the code behaves as expected. 
When the `statement["Action"]` is a string, the conditions are evaluated incorrectly.

```python
>>> "*" in ["s3:*"]
False
>>> "*" in "s3:*"
True
```

**From where are you running Prowler?**
Please, complete the following information:
 - Resource: IAM policy
 - OS: WSL Ubuntu
 - Prowler Version [`prowler --version`]: Prowler 3.1.4
 - Python version [`python --version`]: Python 3.10.9
 - Pip version [`pip --version`]: pip 23.0
 - Installation method (Are you running it from pip package or cloning the github repo?): cloned git repo

**Comment by n4ch04** [comment]
Hi @pmastrovito we are going to review this and let you know, thanks for using Prowler !!!

**Comment by n4ch04** [comment]
Hi @pmastrovito we have included a workaround here https://github.com/prowler-cloud/prowler/pull/1869 please check it out to ensure everything is working fine now
