### ISSUE TITLE
Skip SecurityHub updates when scanning failures occur

### ISSUE THREAD

**Issue by addefisher** [toniblyx/prowler#1867]
**Is your feature request related to a problem? Please describe.**
Based on my understanding of the code in https://github.com/prowler-cloud/prowler/blob/master/prowler/providers/aws/lib/security_hub/security_hub.py, Prowler uses the following logic to archive SecurityHub findings:

1. Create a list of finding IDs for findings generated by the scan performed (i.e. current findings) from local ASFF data.
2. Call `securityhub:GetFindings` to retrieve all ACTIVE Prowler findings for the AWS account and region that was scanned.
3. Archive any ACTIVE findings whose IDs are not in the list of current findings.

The issue with this logic is that if a scanning error occurs, valid findings can be missing from the generated list of "current" findings. These missing findings would then result in SecurityHub findings being archived even though the underlying issues associated with these findings are still present, essentially creating a false negative in SecurityHub.

**Describe the solution you'd like**
I see two potential solutions to this issue:

1. (Easier) Add a command line option such as `--skip-sh-update-on-error` which will cause Prowler to skip the SecurityHub update process (or at least the call to `resolve_security_hub_previous_findings()`) when any scanning errors occur.
2. (Harder) Add logic to track which checks or services failed, and have Prowler only avoid resolving the impacted finding types.

**Additional context**
This is primarily an issue in environments where Prowler is used for continuous scanning, since stale data with potential false positives is preferable to data containing false negatives.

**Comment by MrCloudSec** [comment]
This is a great idea @addefisher , thank you! I've included this feature in our roadmap

Just out of curiosity, what types of errors are you encountering? We would appreciate if you send us the error logs so we can solve them and improve Prowler.

**Comment by addefisher** [comment]
Thanks @sergargar! 

To answer your question, this is primarily an issue with transient errors such as rate limiting. 

The feature added as part of https://github.com/prowler-cloud/prowler/issues/1856 does a great job helping to address this by allowing us to override `boto3`'s max retry count. However, it is still possible that a scan can be run with an insufficient retry count, as AWS rate limiting is somewhat un-predictable. 

In addition, a scenario where 1 or more AWS services are impaired in an AWS region could cause similar issues. While this scenario is much more rare, the impact on visibility is much higher and is unlikely to be solved using retry logic.

**Comment by MrCloudSec** [comment]
Thank you for the information @addefisher ! Above you have the PR with this new feature.
