### ISSUE TITLE
Spelling correction in service check description needed

### ISSUE THREAD

**Issue by rustic** [toniblyx/prowler#1874]
Spelling correction is needed on the word "lesss". It shows with the -l list of checks.

https://github.com/prowler-cloud/prowler/blob/d6bbf8b7cc05bbb935e81588e8213115a512e0a1/prowler/providers/aws/services/appstream/appstream_fleet_session_disconnect_timeout/appstream_fleet_session_disconnect_timeout.metadata.json#L4

**Comment by MrCloudSec** [comment]
Good catch @rustic, I've creating the PR solving this typo. Thanks for using Prowler!
