### ISSUE TITLE
[Bug]: cloudtrail_multi_region_enabled check fails when disabled CloudTrails are present

### ISSUE THREAD

**Issue by addefisher** [toniblyx/prowler#1876]
**What happened?**
When running `prowler aws --checks cloudtrail_multi_region_enabled` in an AWS account / region with a disabled CloudTrail, Prowler will fail the check even if an enabled, multi-region CloudTrail is also present. Specifying the resource ARN of the enabled multi-region CloudTrail prevents Prowler from showing this failure.

**How to reproduce it**
1. Create an enabled multi-region CloudTrail and a disabled CloudTrail in the same AWS account / region. Make sure the disabled CloudTrail is alphabetically earlier than the enabled CloudTrail.
2. Run `prowler aws --checks cloudtrail_multi_region_enabled`, this should produce a finding.
3. run `prowler aws --checks cloudtrail_multi_region_enabled --resource-arn {ARN of the enabled CloudTrail}`, this should not produce a finding.

**Expected behavior**
Prowler does not fail the `cloudtrail_multi_region_enabled` check when an enabled, multi-region CloudTrail is present.

**From where are you running Prowler?**
Please, complete the following information:
 - Resource: workstation
 - OS: MacOS
 - Prowler Version [`prowler --version`]: 3.1.4
 - Python version [`python --version`]: 3.1.0
 - Pip version [`pip --version`]: 22.3.1
 - Installation method (Are you running it from pip package or cloning the github repo?): saw this with pip and source code versions
 - Others:

**Additional context**
Based on my understanding of the code in https://github.com/prowler-cloud/prowler/blob/master/prowler/providers/aws/services/cloudtrail/cloudtrail_multi_region_enabled/cloudtrail_multi_region_enabled.py, this behavior is dependent on the order of the CloudTrails stored in `cloudtrail_client.trails` which may make this bug more difficult to re-produce.

**Comment by n4ch04** [comment]
Hi @addefisher we are going to review this and let you know, thanks for using Prowler !!

**Comment by n4ch04** [comment]
Hi @addefisher we have reformatted the check code to take into account that case, please check it here #1880 and let us know if works fine

**Comment by addefisher** [comment]
@sergargar checked my scan output on version `3.2.0` and this is working as expected, thank you! (code changes look good as well)
