### ISSUE TITLE
[Bug]: AttributeError: 'Azure_Audit_Info' object has no attribute 'audit_resources'    

### ISSUE THREAD

**Issue by MathCarv** [toniblyx/prowler#1888]
Hi, I'm trying to run the script and it's generating this error. Can anyone tell me what it could be?

![Issue](https://user-images.githubusercontent.com/96321313/218457958-fb29eaa9-8dd2-447c-85e5-4640d61379e1.png)

**Comment by n4ch04** [comment]
Hi @MathCarv  we are going to review this and let you know asap.

Thanks for using prowler !!!

**Comment by n4ch04** [comment]
Hi @MathCarv we have included a workaround here for this issue, please check it out.
https://github.com/prowler-cloud/prowler/pull/1891
