### ISSUE TITLE
[Bug]: cloudtrail_logs_s3_bucket_access_logging_enabled fails when cross account delivery is used

### ISSUE THREAD

**Issue by addefisher** [toniblyx/prowler#1895]
**What happened?**
The `cloudtrail_logs_s3_bucket_access_logging_enabled` check fails for any CloudTrail which is configured to deliver logs to an AWS S3 bucket in another account. No error logs are shown when this occurs, but Prowler reports the checks as failing as shown below:

![prowler-ct-s3-access-logs-issue](https://user-images.githubusercontent.com/97761488/218560651-f987f458-a309-431d-8f69-1ccb40294a24.png)

**How to reproduce it**
1. Create a CloudTrail with cross account S3 delivery delivered.
2. `prowler aws -f us-west-2 --checks cloudtrail_logs_s3_bucket_access_logging_enabled --output-modes html --log-level ERROR`

**Expected behavior**
The check should show as passing.

**Screenshots or Logs**
![prowler-ct-s3-access-logs-issue](https://user-images.githubusercontent.com/97761488/218560651-f987f458-a309-431d-8f69-1ccb40294a24.png)

**From where are you running Prowler?**
Please, complete the following information:
 - Resource: workstation
 - OS: MacOS
 - Prowler Version [`prowler --version`]: `3.2.0`
 - Python version [`python --version`]: `3.10.9`
 - Pip version [`pip --version`]: `22.3.1`
 - Installation method (Are you running it from pip package or cloning the github repo?): pip

**Additional context**
I see two potential solutions to this issue:
1. When a CloudTrail with cross account S3 delivery is being evaluated, use cross account role assumption to audit the destination bucket in the destination AWS account. This is a significantly more complex approach.
2. When a CloudTrail with cross account S3 delivery is being evaluated, always mark this check is passing. This is a much simpler approach, but requires the external account to be scanned in order to avoid a potential visibility gap. 

When prowler is being used to scan every account in an organization, option 2 is completely viable as the destination account will almost always be scanned anyways.

A similar issue was raised about this by @kovaxur on an older Prowler version: https://github.com/prowler-cloud/prowler/issues/1820

**Comment by n4ch04** [comment]
Hi @addefisher this is fixed in the related PR, please check it out.
Since we can't access the cross account we are setting the check as FAIL but changing the `status_extended`  field pointing that in this case you should check it manually

**Comment by addefisher** [comment]
@n4ch04 I still think this is an issue when using Prowler with AWS SecurityHub as we don't get `status_extended` in the SH findings, making this condition difficult to filter for.

**Comment by toniblyx** [comment]
Ok, so the issue now is with Security Hub integration, that´s another one we have to look at. Closing this one.

**Comment by toniblyx** [comment]
could you please open another issue telling us your experience with SH?
