### ISSUE TITLE
Add StatusExtended field to SecurityHub findings

### ISSUE THREAD

**Issue by addefisher** [toniblyx/prowler#1905]
**Is your feature request related to a problem? Please describe.**
The `StatusExtended` field of a Prowler finding can sometimes be useful for filtration / suppression purposes. An example of such scenario can be found in https://github.com/prowler-cloud/prowler/issues/1895. However, this field is not uploaded to SecurityHub when a scan is run with the `-S`. This makes the aforementioned filtration / suppression impossible to do via SecurityHub.

**Describe the solution you'd like**
Add the `StatusExtended` fields from Prowler findings to SecurityHub findings when the `-S` option is used. The logical location for this field within a SecurityHub finding is likely the `ProductFields` dictionary (see https://docs.aws.amazon.com/securityhub/1.0/APIReference/API_AwsSecurityFinding.html)

**Describe alternatives you've considered**
N/A

**Additional context**
As per my comments on https://github.com/prowler-cloud/prowler/issues/1895, we are not interested in raising `cloudtrail_logs_s3_bucket_access_logging_enabled` findings for CloudTrails with external S3 destinations configured. The reason for this is because we are already scanning the "destination account" containing the external S3 bucket, so we would see findings for this check in the destination account anyways.

**Comment by MrCloudSec** [comment]
Hi @addefisher, thank you for the idea!
We have added in the above PR the status extended as the description of SHub findings.
