### ISSUE TITLE
[Bug]: Quick inventory not reporting the correct resource types

### ISSUE THREAD

**Issue by Fennerr** [toniblyx/prowler#1912]
**What happened?**
I ran the quick inventory option, and some of the resource type fields aren't producing the correct values.

**How to reproduce it**
1. Run `prowler aws -i` in an account with some SQS queues, SNS topics, and an API gateway

**Expected behavior**
SQS queues should list the resource types as 'queues' or similar instead of the queue names
One of the SNS topics is being used as the resource type for all the SNS topics
API Gateway is listing 2 resources, but it doesn't specify the resource type

Edit: 
I took a look at the CSV output and can see that for a resource that is correctly categorized by type it looks like this:
`ACCOUNTID,eu-west-1,aws,secretsmanager,secret,[secretname],arn:aws:secretsmanager:eu-west-1:ACCOUNTID:secret:[prefix]/[secretname]`
SNS topics:
`ACCOUNTID,us-east-1,aws,sns,TOPICNAME,,arn:aws:sns:us-east-1:ACCOUNTID:TOPICNAME`
SQS queues:
`ACCOUNTID,eu-west-1,QUEUENAME,,arn:aws:sqs:eu-west-1:ACCOUNTID:QUEUENAME`
API gateway:
`ACCOUNTID,eu-west-1,aws,apigateway,,ID,arn:aws:apigateway:eu-west-1::/restapis/ID`
It seems like the type is being overwritten for SNS and SQS (the topic/queue names should be one column to the right when compared to the other resources)
The API resources just don't have a type, and the resource name/ID is in the correct column - not sure what is going on here. 

**Screenshots or Logs**
![quick-inventory](https://user-images.githubusercontent.com/41741346/219029659-aa0580ea-1a1f-4cbf-be2e-d5daa27c96ed.png)

**From where are you running Prowler?**
Please, complete the following information:

 - Resource: Workstation
 - OS: Kali (debian based)
 - Prowler Version [`prowler --version`]: Prowler 3.1.1 
 - Python version [`python --version`]: Python 3.10.9
 - Pip version [`pip --version`]: pip 23.0 from /usr/lib/python3/dist-packages/pip (python 3.10)
 - Installation method (Are you running it from pip package or cloning the github repo?): pip package

**Additional context**
None

**Comment by Fennerr** [comment]
I also noticed that when I ran it in an account it only showed 1 ELB when there were 2. I checked out the one that wasn't report on and noticed that it did not have any tags - might be worth caveating the output sent to the terminal with a line saying that this inventory is based off of resources that have been tagged - and it might not detected untagged resources.

**Comment by MrCloudSec** [comment]
Hi @Fennerr, thank you for reaching us out! Could you try it again with the version 3.2.0? It should be fixed now.
