### ISSUE TITLE
[Bug]: cloudwatch_metric_filter_unauthorized_api_calls fails when metric filter and alarm are present

### ISSUE THREAD

**Issue by addefisher** [toniblyx/prowler#1914]
**What happened?**
I have a multi-region CloudTrail logging to CloudWatch logs. This CloudTrail has a metric filter with the following pattern:
`{ ($.errorCode = "*UnauthorizedOperation") || ($.errorCode = "AccessDenied*") }`

However, the `cloudwatch_metric_filter_unauthorized_api_calls` check still fails when I scan this account

**How to reproduce it**
1. prowler aws --checks cloudwatch_metric_filter_unauthorized_api_calls --log-level ERROR

**Expected behavior**
The check is shown as passing.

**Screenshots or Logs**
![image](https://user-images.githubusercontent.com/97761488/219107502-37e7b0f3-a290-4c5a-a82b-442e14c98f23.png)

**From where are you running Prowler?**
Please, complete the following information:
 - Resource: Workstation
 - OS: MacOS
 -  - Prowler Version [`prowler --version`]: `3.2.0`
 - Python version [`python --version`]: `3.10.9`
 - Pip version [`pip --version`]: `22.3.1`
 - Installation method (Are you running it from pip package or cloning the github repo?): pip (also re-produced from source)
 - Others:

**Additional context**
From what I can tell when re-producing this issue locally, this is likely an issue with the regex matching performed here: https://github.com/prowler-cloud/prowler/blob/7008d2a953f94dcca21432fa89a77522967dfc98/prowler/providers/aws/services/cloudwatch/cloudwatch_log_metric_filter_unauthorized_api_calls/cloudwatch_log_metric_filter_unauthorized_api_calls.py#L32

This means this same issue likely exists for many of the other CloudWatch metric filter related checks.

**Comment by MrCloudSec** [comment]
Good catch @addefisher, thank you!
Right now, Prowler only supports metric filters without `"`, in the case of this check, it would be:
 `{ ($.errorCode = *UnauthorizedOperation) || ($.errorCode = AccessDenied*) }`
 We will improve the regex to admit `"` in the filter patterns.

**Comment by aeroflowdev** [comment]
I think this issue with not supporting `"` in metric filters is also affecting the `cloudwatch_log_metric_filter_root_usage` check. The previously recommended remediation from prowler v2 is no longer working in prowler v3.

We were able to resolve the issue in prowler v3 by modifying the metric filter from:
```
{ $.userIdentity.type = "Root" && $.userIdentity.invokedBy NOT EXISTS && $.eventType != "AwsServiceEvent" }
```
to:
```
{ $.userIdentity.type = Root && $.userIdentity.invokedBy NOT EXISTS && $.eventType != AwsServiceEvent }
```
Unfortunately now prowler v2 is failing.
