### ISSUE TITLE
Update iam_disable_45_days_credentials to check for unused access keys

### ISSUE THREAD

**Issue by addefisher** [toniblyx/prowler#1915]
**Is your feature request related to a problem? Please describe.**
Based on my understanding of the code in https://github.com/prowler-cloud/prowler/blob/master/prowler/providers/aws/services/iam/iam_disable_45_days_credentials/iam_disable_45_days_credentials.py, the `iam_disable_45_days_credentials` check only looks for passwords that have been un-used for 45 days, as opposed to access keys.

**Describe the solution you'd like**
The check should also look for access keys which have been un-used for 45 days.

**Describe alternatives you've considered**
None

**Additional context**
The CIS AWS Foundations 1.5 Benchmark `1.12` specifies that both access keys and passwords should be disabled if they haven't been used for 45 days.

**Comment by MrCloudSec** [comment]
Hi @addefisher, thank you for reaching us out!
Could you try this check with the above PR and let us now if those changes work for you?

**Comment by addefisher** [comment]
@sergargar I'll test this out today and get back to you shortly

**Comment by addefisher** [comment]
@sergargar when access keys have not been used for 45 days, can this be reported as a finding on the access key resource (`AwsIamAccessKey`) instead of a finding on the IAM user?

This way, if a user has a password and 2 access keys, all of which are un-used for 2 days, we would see 3 separate findings. During testing this scenario just produced one finding for me.

**Comment by addefisher** [comment]
also left a minor comment about a print statement

**Comment by MrCloudSec** [comment]
@addefisher I'm afraid it is not possible to have different resource types for the same check. Thank you for testing it though.
