### ISSUE TITLE
Make iam_policy_no_administrative_privileges check configurable to scan AWS managed policies

### ISSUE THREAD

**Issue by addefisher** [toniblyx/prowler#1917]
**Is your feature request related to a problem? Please describe.**
Due to the way `iam_service.py` retrieves policies using the `Local` scope (https://github.com/prowler-cloud/prowler/blob/7008d2a953f94dcca21432fa89a77522967dfc98/prowler/providers/aws/services/iam/iam_service.py#L344), the `iam_policy_no_administrative_privileges` check only raises findings if a customer managed policy with "*:*" permissions is attached to an IAM principal, as opposed to an AWS managed policy such as `arn:aws:iam::aws:policy/AdministratorAccess`.

While this behavior can be useful in many scenarios, the CIS 1.5 benchmark specifies that no "*:*" policies should be attached to any IAM principals, regardless of whether they are AWS managed. 

**Describe the solution you'd like**
Make the iam_policy_no_administrative_privileges check configurable so that a user can specify that AWS managed policies should be scanned by this check as well.

**Describe alternatives you've considered**

**Additional context**
While scanning AWS managed policies is useful for compliance enforcement, it is not necessarily desirable default behavior as it can result in a large number of inactionable findings.

**Comment by MrCloudSec** [comment]
Hi @addefisher, thank you for reaching us out!
Good idea, we will adjust to CIS regarding the attachment of the policies and make a configurable option for the scope.

**Comment by addefisher** [comment]
@sergargar any updates on this?

**Comment by MrCloudSec** [comment]
Sorry for the delay, I just created the PR with the changes.
As CISv1.5 control 1.16 requires to check attaches policies for both custom or AWS managed, it did not make sense to make it configurable.
Let me know if it works for you, thank you!

**Comment by MrCloudSec** [comment]
FYI @addefisher we did the dollowing:
- Renamed current check `iam_policy_no_administrative_privileges` to `iam_customer_unattached_policy_no_administrative_privileges`.
- Add new check `iam_customer_attached_policy_no_administrative_privileges`: that checks only customer managed policies attached. HIGH, to fix it is changing it.
- Add new check `iam_aws_attached_policy_no_administrative_privileges`: that checks only AWS managed IAM policies attached. HIGH, to fix it is detaching it.
