### ISSUE TITLE
[Bug]: I can still see wrong region being mentioned for some checks

### ISSUE THREAD

**Issue by daftkid** [toniblyx/prowler#1944]
**What happened?**
I'm running scans for the Chinese AWS regions and noticed that `us-east-1` region name is used within the remediation steps for some checks (https://github.com/prowler-cloud/prowler/blob/master/prowler/providers/aws/services/cloudformation/cloudformation_stacks_termination_protection_enabled/cloudformation_stacks_termination_protection_enabled.metadata.json#L16)

It seems that it does not break any functionality, I just was asked by the security team if it can be fixed.

**How to reproduce it**
1. What command are you running?
2. Cloud provider you are launching
3. Environment you have like single account, multi-account, organizations, multi or single subsctiption, etc.

**Expected behavior**

**Screenshots or Logs**
Also, you can add logs (anonymize them first!). Here a command that may help to share a log
`prowler <your arguments> --log-level DEBUG --log-file $(date +%F)_debug.log` then attach here the log file.

**From where are you running Prowler?**
Please, complete the following information:
 - Resource: (e.g. EC2 instance, Fargate task, Docker container manually, EKS, Cloud9, CodeBuild, workstation, etc.)
 - OS: [e.g. Amazon Linux 2, Mac, Alpine, Windows, etc. ]
 - Prowler Version [`prowler --version`]: 3.2.0
 - Python version [`python --version`]:
 - Pip version [`pip --version`]:
 - Installation method (Are you running it from pip package or cloning the github repo?):
 - Others:

**Additional context**

**Comment by MrCloudSec** [comment]
Good catch @daftkid, thank you! I saw that `us-east-1` region name is only used in the metadata of the mentioned check.
