### ISSUE TITLE
Implement a new check for RDS to require encrypted connections

### ISSUE THREAD

**Issue by Fennerr** [toniblyx/prowler#1951]
**Is your feature request related to a problem? Please describe.**
The default DB parameter groups for RDS has the rds.force_ssl parameter set to 0. This parameter can be set to 1 for MSSQL and PostgreSQL to require that connections made to the database are protected by SSL.

**Describe the solution you'd like**
Implement a new check to ensure that the DB parameter group enforces SSL. Rather than just checking if the default parameter group is in use, the check should determine if the rds.force_ssl parameter is set to 1.

This check could also raise an informational risk finding advising users to check if SSL connections are required for Oracle DB, MySQL, and MariaDB. These checks need to be performed within the DB.

**Describe alternatives you've considered**
None

**Additional context**
[None](https://aws.amazon.com/premiumsupport/knowledge-center/rds-connect-ssl-connection/)

**Comment by MrCloudSec** [comment]
Good idea, thanks @Fennerr !!
