### ISSUE TITLE
[Bug]: awslambda_function_invoke_api_operations_cloudtrail_logging_enabled fails even after turning on cloud trail logs for all lambda events

### ISSUE THREAD

**Issue by akunap2** [toniblyx/prowler#1973]
**What happened?**
We have enabled cloud trail logging for all lambda events but the check awslambda_function_invoke_api_operations_cloudtrail_logging_enabled continues to fail. Prowler seems to report a Lambda function as not being monitored by a CloudTrail trail if you are using the CloudTrail event selector arn:aws:lambda which tells the trail to monitor all Lambdas.

![Screenshot 2023-02-24 at 4 10 37 AM](https://user-images.githubusercontent.com/1134432/221138653-0e25b364-8e1c-412c-8e8a-d0d83b73a87d.png)

**How to reproduce it**
1. What command are you running?
prowler aws --checks awslambda_function_invoke_api_operations_cloudtrail_logging_enabled

2. Cloud provider you are launching
AWS

**Expected behavior**
The awslambda_function_invoke_api_operations_cloudtrail_logging_enabled check should pass as we have enabled the cloud trail for all lambdas rather than individual lambdas

**From where are you running Prowler?**
Please, complete the following information:
 - Resource: CloudTrail
 - OS: Mac
 - Prowler Version [`prowler --version`]: 3.1.4
 - Python version [`python --version`]: 3.9.6
 - Pip version [`pip --version`]: 23.0
 - Installation method (Are you running it from pip package or cloning the github repo?): pip package
 - Others:

**Comment by n4ch04** [comment]
Hi @akunap2 , we are going to review this and let you know asap, thanks for using Prowler !!

**Comment by n4ch04** [comment]
Hi @akunap2,  we have include a workaround here #1994, please check it out and let us know if everything works
