### ISSUE TITLE
Custom checks for Prowler 3

### ISSUE THREAD

**Issue by roisec** [toniblyx/prowler#1989]
Hi,
I am trying to use prowler 3 with custom checks, and I don't found any guide for this
( I saw a guide on the first version of prowler but it's not working on the new version)
Do prowler 3 support custom checks?

**Comment by toniblyx** [comment]
Hi @roisec we do support custom checks and we are still working on the developer guide. You can get an idea from this workshop in the meantime but it may be not 100% accurate since we have improved that since then https://docs.google.com/presentation/d/1HWthpt3-ROZijMoeAu5cMxwfOaTFGi22bGCRoN5n7N0/edit?usp=sharing

**Comment by roisec** [comment]
Hi @toniblyx ,
There is any option to use AWS cli? I think it's may easier to use.

**Comment by toniblyx** [comment]
for anything with AWS CLI in it, refer to Prowler v2.

**Comment by Musseri10** [comment]
Hey, I'm trying to write a custom check that looking for if some role in AWS exists. Can anybody help me with this. Also what are the steps to create custom check (after create directory with the metadata file and the python) . I would appreciate the help.

**Comment by toniblyx** [comment]
Hey @Musseri10 we have just updated the Developer Guide here https://docs.prowler.cloud/en/latest/tutorials/developer-guide/ if you want to give it a look and see if you can start writing your own checks. See the ones in `providers/aws/services/iam` as a reference.

**Comment by Ty-Cloudscaler** [comment]
Hello,

I seem to have a similar problem, I am trying to create a custom framework as well as custom checks. I followed the above guide but it does not appear when I type in prowler aws --list-compliance and prowler aws --list-checks. Is there something that is meant to populate the custom checks and frameworks after creating them? @toniblyx @sergargar

**Comment by MrCloudSec** [comment]
Hi @Ty-Cloudscaler, using the developer guide will let you know creating custom frameworks and checks: https://docs.prowler.cloud/en/latest/tutorials/developer-guide/
Can you execute the commands with `--log-level ERROR` so we can see if there are some unexpected errors when integrating your checks/compliances? Thank you.
