### ISSUE TITLE
Error when running from cloned repo

### ISSUE THREAD

**Issue by garym-krrv** [toniblyx/prowler#2021]
**What happened?**
I have cloned the repo and followed the instructions. I am using AWS as the provider. It starts to run and exists with an error on and early check

2023-03-02 09:25:13,951 [File: check.py:422]    [Module: check]  CRITICAL: Check 'autoscaling_find_secrets_ec2_launch_configuration' was not found for the AWS provider
-> Scan was aborted! |▉▉▊⚠︎                                    | (!) 18/248 [7%] in 12.3s

**How to reproduce it**
1. Clone from Master and execute python prowler.py aws -M csv json json-asff html
2. aws
3. this is running in the management account of an org. The credentials has full ReadyOnlyAccess

**Expected behavior**
Run without errors as it does in the docker image

**Screenshots or Logs**
Also, you can add logs (anonymize them first!). Here a command that may help to share a log
[debug.log](https://github.com/prowler-cloud/prowler/files/10869938/debug.log)

![prowler error](https://user-images.githubusercontent.com/117729745/222394349-5a0ff1e7-daad-44ab-a4cf-8a9249bc12c1.jpg)

**From where are you running Prowler?**

Please, complete the following information:
 - Resource: Windows 11 Workstation
 - OS: Windows
 - Prowler Version [`Prowler 3.2.4`]:
 - Python version [`Python 3.9.13`]:
 - Pip version [`pip 22.0.4 `]:
 - Installation method cloning git repo:
 - Others:

**Additional context**
I think the module/py file is incorrectly name or it has HARD Coded account number and region within

**Comment by toniblyx** [comment]
Hi @garym-krrv, we see that you are installing prowler cloning the repo, in that case you are probably missing some important dependencies. Considering that you have pip installed, would yo mind to install prowler as `pip install prowler` and run it like `prowler aws` (you don't need -M json-asff unless you use -S for security hub). Also it could be that, if you have an antivirus, it deletes some of the prowler temporary files regarding our find_secrets feature. Also, only with `ReadyOnlyAccess` Prowler won't shine ;) make sure you add all needed permissions.

**Comment by garym-krrv** [comment]
Hey @toniblyx I willl look at the pip verison and seem to have all dependacys installed. 

ReadOnlyAccess policy grants more access than you have documented i.e. plus readonlyaccess works fine in the image from DockerHub. Cloudtrail shows no permission errors.

For fun I added the extra permissions which made no difference..

**Comment by toniblyx** [comment]
We specify all required permissions here https://github.com/prowler-cloud/prowler/#aws

and here is a sample CFN template with all that is required so far for Prowler in case it helps you to scan multiple accounts https://github.com/prowler-cloud/prowler/blob/master/permissions/create_role_to_assume_cfn.yaml

**Comment by garym-krrv** [comment]
Yeah I have added those permissions it makes no difference.

ReadOnlyAccess I was using grants more access than your documentation.

I have no issues using the docker image from DockerHub

I do have several AWS certifications of so Im not a joeblogs of AWS

**Comment by garym-krrv** [comment]
Ok, I have now actully fixed it.. You pointed me in the right direction and have found in your source code it needs 
detect-secrets

I have installed detect-secrets and working fine now.. 

Please close the issue.. 

Thanks for your help and this is a great tool!!

**Comment by garym-krrv** [comment]
I was indeed missing a library from my Workstation. After installing missing library problem was resolved

**Comment by toniblyx** [comment]
thanks for let us know @garym-krrv and for using Prowler, your feedback is very welcomed! 
all dependencies are listed here https://github.com/prowler-cloud/prowler/blob/master/pyproject.toml
