### ISSUE TITLE
[Bug]: Quick inventory listing is not counting all aws s3 bucket.

### ISSUE THREAD

**Issue by RANJUBISWAS** [toniblyx/prowler#2036]
**What happened?**
Running `prowler -i` command is not listing all s3 bucket.If the bucket has no tag.prowler is not counting that bucket.

**How to reproduce it**
1. What command are you running?
`prowler -i`
2. Cloud provider you are launching
AWS
3. Environment you have like single account, multi-account, organizations, multi or single subsctiption, etc.
Single account.
No error occured.

**Expected behavior**
I was expecting that all my bucket would be counted even if some of them has no tag.

**Screenshots or Logs**
Also, you can add logs (anonymize them first!). Here a command that may help to share a log
`prowler <your arguments> --log-level DEBUG --log-file $(date +%F)_debug.log` then attach here the log file.

**From where are you running Prowler?**
Running prowler from bash.I have installed prowler from pypi.
Please, complete the following information:
 - Resource: (e.g. EC2 instance, Fargate task, Docker container manually, EKS, Cloud9, CodeBuild, workstation, etc.)
 S3
 - OS: [e.g. Amazon Linux 2, Mac, Alpine, Windows, etc. ]
 Mac 12.6.3, Linux Ubuntu 24
 - Prowler Version [`prowler --version`]:
 3.2.4
 - Python version [`python --version`]:
 3.10
 - Pip version [`pip --version`]:
 22.3.1
 - Installation method (Are you running it from pip package or cloning the github repo?):
 pip package
 - Others:

**Additional context**

**Comment by MrCloudSec** [comment]
Good catch @RANJUBISWAS ! The above PR solves this issue, thanks for letting us know.

**Comment by RANJUBISWAS** [comment]
Thank you, @sergargar for this quick fixing.
