### ISSUE TITLE
S3 public access not really public

### ISSUE THREAD

**Issue by roisec** [toniblyx/prowler#2052]
Hi,
When I have an S3 bucket policy that allows anyone to write objects, Prowler raises an alert about that, but there is no write access because the "ACL block public access" of the bucket is enabled.
Why do not change the rule to check if there is S3 if the configuration includes 3 at the same time?
ACL disabled for public access, resource policy allows the relevant action, account level bucket policy?

**Comment by MrCloudSec** [comment]
Hi @roisec, what Prowler check are you referring to?

**Comment by roisec** [comment]
@sergargar , thank you for the fast reply.
I meant for the following s3 checks:
s3_bucket_public_access
s3_bucket_policy_public_write_access
These checks are not validated if there is any block if "block public access" is disabled for the relevant s3 bucket,
If block public access is enabled, the bucket not really publicly accessable.
Can we modify the rule to support the combination of the checks?

**Comment by MrCloudSec** [comment]
I think that the check `s3_bucket_public_access` looks for all the cases:
1. Check if public buckets are restricted at account level
2. If public access is not blocked at account level, check it at each bucket level
3. If bucket has no public block, check bucket ACL
4. Check bucket policy

But the check `s3_bucket_policy_public_write_access` looks only in the bucket policy, so I will add the previous veririfcations, is that what you mean?

**Comment by roisec** [comment]
@sergargar 
Yes, adding these checks is more accurate regarding s3_bucket_policy_public_write_access.
Regarding the s3_bucket_public_access found it's as good but still has a resource policy with the condition, and I suggest separating the alerts with/without the condition(see the SNS check).

**Comment by MrCloudSec** [comment]
I agree on the `s3_bucket_public_access ` condition case, but the `s3_bucket_policy_public_write_access ` as its name indicates, it only checks the bucket policy.
Maybe it would add more value if we replace it to `s3_bucket_public_write_access`, what do you think?

**Comment by roisec** [comment]
Yes, I agree.
Do you create a pull request for that?

**Comment by roisec** [comment]
@sergargar ,
I found the same issue for the security group.
We found security groups are not in use when they allow any port.
Why do think about modifying or adding other rules that find security groups that are assigned to network interfaces?

**Comment by MrCloudSec** [comment]
Could you create an issue with the security group case, pls?

**Comment by roisec** [comment]
@sergargar #2069

**Comment by n4ch04** [comment]
Since it is referenced in #2069 we are going to close this.

Thanks for using Prowler !!
