### ISSUE TITLE
[Bug]: ec2_instance_managed_by_ssm triggers on terminated instances

### ISSUE THREAD

**Issue by pplu** [toniblyx/prowler#2059]
**What happened?**

We are getting FAILs for terminated instances on rule ec2_instance_managed_by_ssm, although the terminated instances were managed by SSM

**How to reproduce it**

Terminate an instance managed by SSM, and in short time, run prowler.

**Expected behavior**

FAIL is not reported on terminated instances

**Additional context**

https://github.com/prowler-cloud/prowler/blob/eb9d6fa25c0978136b1fb084bca2cf46f0a3332c/prowler/providers/aws/services/ec2/ec2_instance_managed_by_ssm/ec2_instance_managed_by_ssm.py#L9 seems to return terminated instances for a while after they are terminated (this is standard AWS DescribeInstances behaviour). The call to SSM fails when passed an instance id that is not managed anymore by SSM.

**Comment by MrCloudSec** [comment]
Hi @pplu, if I'm understand this issue right, you'd like that Prowler does not show terminated instances in this check?

**Comment by pplu** [comment]
@sergargar : you're right. Prowler should not show terminated instances in this check
