### ISSUE TITLE
[Bug]: Unable to run as Docker Container due to Ulimit issue

### ISSUE THREAD

**Issue by deybhayden** [toniblyx/prowler#2064]
**What happened?**

When scanning a single AWS account with Prowler via a Docker container, I'm getting a too many files error - even when specifying `--ulimit` in the command.

**How to reproduce it**
1. What command are you running?

    ```shell
    > docker run -it --rm -v output:/home/prowler/output --name prowler --env AWS_ACCESS_KEY_ID --env AWS_SECRET_ACCESS_KEY --env AWS_SESSION_TOKEN --env AWS_DEFAULT_REGION --ulimit nofile=4096 toniblyx/prowler:latest
    ```

2. Cloud provider you are launching
**AWS**
3. Environment you have like single account, multi-account, organizations, multi or single subscription, etc.
**Single Account**

**Expected behavior**
Prowler to run successfully and save its output to the host machine at `output`.

**Screenshots or Logs**

```
> docker run -it --rm -v output:/home/prowler/output --name prowler --env AWS_ACCESS_KEY_ID --env AWS_SECRET_ACCESS_KEY --env AWS_SESSION_TOKEN --env AWS_DEFAULT_REGION --ulimit nofile=4096 toniblyx/prowler:latest
                         _
 _ __  _ __ _____      _| | ___ _ __
| '_ \| '__/ _ \ \ /\ / / |/ _ \ '__|
| |_) | | | (_) \ V  V /| |  __/ |
| .__/|_|  \___/ \_/\_/ |_|\___|_|v3.2.4
|_| the handy cloud security tool

Date: 2023-03-08 15:30:35


This report is being generated using credentials below:

AWS-CLI Profile: [default] AWS Filter Region: [all]
AWS Account: [000000000000] UserId: [ABCDEFGHIJKLMNOPQRSTUVWXYZ:deybhayden]
Caller Identity ARN: [arn:aws:sts::000000000000:assumed-role/AWSReservedSSO_AdministratorAccess_cf123456789/deybhayden]

Executing 251 checks, please wait...

2023-03-08 15:30:43,022 [File: utils.py:20]     [Module: utils]  CRITICAL: Ooops! You reached your user session maximum open files. To solve this issue, increase the shell session limit by running this command `ulimit -n 4096`. For more info visit https://docs.prowler.cloud/en/latest/troubleshooting/
-> Scanning accessanalyzer service |⚠︎                                       | (!) 0/251 [0%] in 5.6s
```

**From where are you running Prowler?**

Running Prowler via `pip` on the host machine results in a successful command. The bug reported here is Docker container only.
Please, complete the following information:
 - Resource: Docker container manually
 - OS: Windows (and Ubuntu via WSL)
 - Prowler Version [`prowler --version`]: `3.2.4`
 - Python version [`python --version`]: Whatever version is in the Docker image
 - Pip version [`pip --version`]: ^
 - Installation method (Are you running it from pip package or cloning the github repo?): Docker image

**Comment by MrCloudSec** [comment]
Hi @deybhayden, thank you for reaching us out!
Can you try it with the command `--ulimit nofile=4096:4096`?

**Comment by deybhayden** [comment]
Hey @sergargar sure, I just tested, and I get the same error as before. According to Docker's docs only setting one will set both the soft & hard limit to the same number.

**Comment by MrCloudSec** [comment]
You're right @deybhayden, what amount of resources are you passing to that container (CPU, Memory, Swap and Disk)?

**Comment by deybhayden** [comment]
By default, WSL 2 with Docker uses Dynamic Resource consumption - that's what I have it set to currently.

> Docker Desktop uses the dynamic memory allocation feature in WSL 2 to improve the resource consumption. This means, Docker Desktop only uses the required amount of CPU and memory resources it needs, while enabling CPU and memory-intensive tasks such as building a container, to run much faster.

WSL is responsible for the resource management via a [wslconfig](https://learn.microsoft.com/en-us/windows/wsl/wsl-config#configure-global-options-with-wslconfig) file. I haven't configured anything special, so it's just the defaults which based on my PC is:

8 GB RAM, 14 CPU cores (20 logical processors), 16 GB swap, WSL auto grows disk space as well.

**Comment by mindfulmonk** [comment]
I think the error message is wrong, I got the same on MacOS and the problem was with the mount point(I used -v and somehow prowler couldn't write to it, trying all the ulimit fixes didn't do anything)

To debug it try running prowler with `--entrypoint sh` and `ls -lah` or try writing into the output directory. 

In my case mounting with ` --mount type=bind,src="$(pwd)"/output,dst=/home/prowler/output` worked fine.

**Comment by infantusgodfrey** [comment]
Hey, @deybhayden I too met the same issue and tried @mindfulmonk mount command as of the above comment and it still, didn't work. The docker runs in the prowler user and it seems the issue was mounting the src folder into the docker container that has root permission for the mounted folder rather than the prowler user. So for time being in the dockerfile, I commented `USER prowler` last before the line of `ENTRYPOINT ["prowler"]` , build it and it ran smoothly with the following docker command.
`docker run -it --rm -v $PWD:/home/prowler/output --name prowler --env-file=.env 1d30c282fe0a -M html csv -f ap-south-1 us-east-1`. Hope it helps.

**Comment by mattiashem** [comment]
Hade the same error and could not get it to work.
Switch to podman but same error.

As soon as a mount a folder into output, the error comes up.

On ubuntu

**Comment by stevemason** [comment]
I saw a similar error today with a Debian host. Although maybe not ideal, changing the permissions of the shared folder on the host to 777 worked as a quick fix.

**Comment by jfagoagas** [comment]
Are you still experiencing this issue with the latest version of Prowler?

**Comment by jfagoagas** [comment]
I'm testing it and running `docker run -v ~/.aws:/home/prowler/.aws -v ./output:/home/prowler/output --rm  toniblyx/prowler:latest` produces neither ulimit nor permissions errors.
```
(prowler-py3.11) ➜  prowler git:(master) docker run -v ~/.aws:/home/prowler/.aws -v ./output:/home/prowler/output --rm  toniblyx/prowler:latest
                         _
 _ __  _ __ _____      _| | ___ _ __
| '_ \| '__/ _ \ \ /\ / / |/ _ \ '__|
| |_) | | | (_) \ V  V /| |  __/ |
| .__/|_|  \___/ \_/\_/ |_|\___|_|v3.7.1
|_| the handy cloud security tool

Date: 2023-07-26 09:55:24


This report is being generated using credentials below:

AWS-CLI Profile: [XXXXXXXX] AWS Filter Region: [all]
AWS Account: [XXXXXXXX] UserId: [XXXXXXXX]
Caller Identity ARN: [arn:aws:sts::XXXXXXXX:XXXXXXXX]

Executing 283 checks, please wait...

-> Scan completed! |▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉| 283/283 [100%] in 8:48.0 

.....
```

Tested on `MacOs Ventura 13.2.1`.

**Comment by jfagoagas** [comment]
Hi @stevemason @mattiashem @gody48 @mindfulmonk @deybhayden could you please test it again with the latest version of Prowler?

Thanks!

**Comment by jfagoagas** [comment]
Hi, we are closing this issue since we did not receive any response in the last week and this issue is not present in the latest Prowler version `v3.7.2`. Please feel free to reopen it if you notice the same behaviour again.

Thanks for using Prowler 🚀

**Comment by stevemason** [comment]
Hi @jfagoagas. Just tried with v3.8.0 from https://hub.docker.com/r/toniblyx/prowler and I now get "OSError[13] Permission denied" which I guess makes sense if the output folder on the host is root:root 755 and the container's not running as root. Definitely a more meaningful error than "[Module: utils]	 CRITICAL: Ooops! You reached your user session maximum open files" :-)
