### ISSUE TITLE
Keep `s3_account_level_public_access_blocks` in AWS CIS Compliance Frameworks

### ISSUE THREAD

**Issue by addefisher** [toniblyx/prowler#2065]
**Is your feature request related to a problem? Please describe.**
I opened https://github.com/prowler-cloud/prowler/issues/1916 3 weeks ago to request a new check named `s3_bucket_level_public_access_block`. While we still want this check to be available in Prowler, I noticed that the associated PR also added this check to `prowler/compliance/aws/cis_1.5_aws.json`, replacing the `s3_account_level_public_access_blocks` check in that file (see my comment on https://github.com/prowler-cloud/prowler/pull/1953/files#r1130145399).

**Describe the solution you'd like**
I would like to have the `s3_bucket_level_public_access_block` check available to use, but I would still like the `s3_account_level_public_access_blocks` check to be used by default when Prowler is run with the `--compliance cis_1.5_aws` option.

**Describe alternatives you've considered**

**Additional context**
The `s3_bucket_level_public_access_block` is extremely useful for AWS accounts where 1 or more buckets have a legitimate reason to be publicly exposed, and are treated as compliance exceptions. However, for the majority of AWS accounts, this is typically not the case, and the `s3_account_level_public_access_blocks` check is preferable.

**Comment by addefisher** [comment]
@sergargar

**Comment by MrCloudSec** [comment]
Hi @addefisher, how about having both checks applying to 2.1.5 of the CIS?

> 2.1.5 Ensure that S3 Buckets are configured with 'Block public access (bucket settings)' (Automated)
Profile Applicability:
• Level 1 Description:
Amazon S3 provides Block public access (bucket settings) and Block public access (account settings) to help you manage public access to Amazon S3 resources. By default, S3 buckets and objects are created with public access disabled. However, an IAM principal with sufficient S3 permissions can enable public access at the bucket and/or object level. While enabled, Block public access (bucket settings) prevents an individual bucket, and its contained objects, from becoming publicly accessible. Similarly, Block public access (account settings) prevents all buckets, and contained objects, from becoming publicly accessible across the entire account.

**Comment by addefisher** [comment]
@sergargar I'm ok with including both checks.
