### ISSUE TITLE
Add result custom fields

### ISSUE THREAD

**Issue by roisec** [toniblyx/prowler#2068]
Hi,
There is an option to add custom fields for multiple checks results?
for example, the JSON output result will be with custom fields.
(for example- Maturity level)

**Comment by toniblyx** [comment]
Hi @roisec, can you give us more details about the use case? 

Remember you can add "Notes" on every check, adding your maturity level or whatever you need  in there and that will be part of the finding as well in the field Notes in both json and csv output files.

**Comment by n4ch04** [comment]
Hi @roisec since the outputs already have a field for Notes and we did not receive more feedback from you we assume that this is solved.
If you need something else related to this topic or another, please feel free to reopen the issue or open a new one.

Thanks for using Prowler !!
