### ISSUE TITLE
GCP Support

### ISSUE THREAD

**Issue by Musseri10** [toniblyx/prowler#2070]
Hi, When will GCP be supported? Is there a beta version?

**Comment by toniblyx** [comment]
Hello @Musseri10, thanks for your interest. Adding GCP support is in our roadmap for this year however we don't really know when we can start coding that part.

**Comment by toniblyx** [comment]
Hey @Musseri10, we have now a branch with the first integration with GCP including a bunch of checks, it is here https://github.com/prowler-cloud/prowler/pull/2125 please feel free to test it if you like.
