### ISSUE TITLE
Report output compatibility with DefectDojo

### ISSUE THREAD

**Issue by security101** [toniblyx/prowler#2076]
### New feature motivation

DefectDojo supported prowler v2.x csv and json output as import format. I looks like Prowler v3.y introduced a breaking change (see https://github.com/prowler-cloud/prowler/pull/1230) means  report output (-M csv json) in not compatible anymore. An issue has been created for the DefectDojo project (see https://github.com/DefectDojo/django-DefectDojo/issues/7348) 

### Solution Proposed

Preserving the prowler output format in the future would easy integration and usage without additional changes.  May thank's in advance!

### Describe alternatives you've considered

Announcing breaking changes upfront and provide details / the specification to ensure it can be considered by other development / maintenance team for their applications, e.g. DefectDojo, to ensure support and smooth upgrade experiences.

**Comment by jfagoagas** [comment]
Hi @security101, I agree with you that preserving the output format is great to maintain compatibility with other integrations but Prowler v3 was a complete refactor of the existing v2 and we warn all the users about the breaking changes of the new version here https://github.com/prowler-cloud/prowler/releases/tag/3.0.0.

Is there anything we could do to help you to adapt it to the new V3 output format?

The new format specification is detailed here:
- CSV https://docs.prowler.cloud/en/latest/tutorials/reporting/#csv
- JSON https://docs.prowler.cloud/en/latest/tutorials/reporting/#json
- JSON-ASFF https://docs.prowler.cloud/en/latest/tutorials/reporting/#json-asff

**Comment by security101** [comment]
Dear @jfagoagas, 

thank you for looking into it. 

The intention of my feature request is raising common awareness for future prowler changes. The issue has been taised  to the defectdojo team (see https://github.com/DefectDojo/django-DefectDojo/issues/7348 ) and they started to look into it. I am very confident that the DefectDojo import job will be updated resolving the issue.

I will post updates to this ticket if his if fine for you.

**Comment by jfagoagas** [comment]
Sure! Thank you for raising this.

Keep us posted and if we could do something to help you to adapt DefectDojo to the latest Prowler version, please let us know.

Thanks again!

**Comment by toniblyx** [comment]
I'm going to close this issue since no more to do in our side. Please @security101 let us know if we can help here in the future. Thanks!
