### ISSUE TITLE
Check lambda function invoke in cloudtrail logging

### ISSUE THREAD

**Issue by stenionljunior** [toniblyx/prowler#2090]
### Steps to Reproduce

Name of the check I tested: awslambda_function_invoke_api_operations_cloudtrail_logging_enabled

When the cloudtrail data event is enabled with the ALL FUNCTIONS option, the prowler considers the status as FAIL.

When enabling the cloudtrail data event and specifying the name of a lambda function, the prowler considers the status as PASS

### Expected behavior

Status as PASS when cloudtrail data events is enabled for all lambda functions

### Actual Result with Screenshots or Logs

1-prowler_screenshots_data_events_disabled.png - running the prowler with the cloudtrail data event disabled.

![1-prowler_screenshots_data_events_disabled](https://user-images.githubusercontent.com/56360594/225064709-bcf92188-aff3-45e5-b83f-c424d319e07d.png)

2-aws_cli_screenshots_data_events_disabled.png - checking cloudtrail properties using aws cli. Cloudtrail Data event disabled.

![2-aws_cli_screenshots_data_events_disabled](https://user-images.githubusercontent.com/56360594/225064763-3636c869-0718-49fa-ac5d-34cbc4d5243a.png)

3-prowler_screenshots_data_events_enabled_full.png - running the prowler after enabling the cloudtrail data event as FULL for all aws lambdas.

![3-prowler_screenshots_data_events_enabled_full](https://user-images.githubusercontent.com/56360594/225064846-1151615b-e052-4d10-9024-62f231223d46.png)

4-aws_cli_screenshots_data_events_enabled_full.png - checking cloudtrail properties using aws cli. Cloudtrail data events enabled as FULL for all aws lambdas.

![4-aws_cli_screenshots_data_events_enabled_full](https://user-images.githubusercontent.com/56360594/225064912-0648ea15-7933-4556-ba36-84f0aa4365dc.png)

5-prowler_screenshots_data_events_enabled_specifying_aws_lambda.png - running the prowler after enabling the cloudtrail data event and specifying the name of a lambda.

![5-prowler_screenshots_data_events_enabled_specifying_aws_lambda](https://user-images.githubusercontent.com/56360594/225064987-0fb61eee-fce4-4926-b6fd-4298fd76c9df.png)

6-aws_cli_screenshots_data_events_enabled_specifying_aws_lambda.png - checking cloudtrail properties using aws cli after enabling the cloudtrail data event and specifying the name of a lambda.

![6-aws_cli_screenshots_data_events_enabled_specifying_aws_lambda](https://user-images.githubusercontent.com/56360594/225065047-2cb4edcb-d20c-464f-a8e5-894b8b323e8f.png)

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

At my workstation

### OS used

Linux. Pop OS

### Prowler version

Prowler 3.1.1

### Pip version

pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)

**Comment by MrCloudSec** [comment]
Hi @stenionljunior, can you use the last version of prowler `pip install --upgrade prowler`? These errors should be solved in version 3.2.4. Let us know if that fixes the error.

**Comment by stenionljunior** [comment]
Hi @sergargar, I updated the prowler version but it showed the same behavior.
![7-prowler-check](https://user-images.githubusercontent.com/56360594/225082665-de222956-90c9-4e58-93a5-e138f12c40ba.png)

**Comment by n4ch04** [comment]
Hi @stenionljunior, 

We are going to review this and let you know asap !!

Thanks for using Prowler !!

**Comment by n4ch04** [comment]
Hi @stenionljunior,

We are trying to reproduce your issue but we can't.

We have created a trail that logs all Lambda events through an advanced event selector:

![Screenshot 2023-03-15 at 10 39 40](https://user-images.githubusercontent.com/59198746/225271450-c2f5e1c3-cfcb-45ab-992d-ad22c2c3af8b.png)

And then launched the check against 4 lambdas:

![Screenshot 2023-03-15 at 10 41 11](https://user-images.githubusercontent.com/59198746/225271859-d9bb0cb8-8a14-4162-a6dc-7c08213e3125.png)

**Comment by stenionljunior** [comment]
Hi @n4ch04,

I found something interesting. Running the same check using docker, the checks were PASS. Using via pip continues with the same behavior.

Using Docker: 

![docker](https://user-images.githubusercontent.com/56360594/225364802-c56d1eed-cf0e-410f-943b-311ccbb3597a.png)

Using pip: 

![pip](https://user-images.githubusercontent.com/56360594/225364946-65cbf339-ca55-40ef-9890-1f29608fdd6f.png)

Command used in docker: 

docker run -ti --rm \
    --name prowler \
    --volume "$(pwd)":/prowler/output \
    --env AWS_ACCESS_KEY_ID \
    --env AWS_SECRET_ACCESS_KEY \
    --env AWS_SESSION_TOKEN \
    toniblyx/prowler:latest \
    -c awslambda_function_invoke_api_operations_cloudtrail_logging_enabled --verbose

Command used in pip:

prowler aws -c awslambda_function_invoke_api_operations_cloudtrail_logging_enabled --verbose

**Comment by n4ch04** [comment]
Hummm interesting, we are going to check if everything is up to date with pip package, thank you for the catch !!
Can you try Github installation from docs ? It should work fine https://docs.prowler.cloud/en/latest/#installation

**Comment by n4ch04** [comment]
Yep, @stenionljunior you are right, the last release (`3.2.4` that comes from pip) does not include a fix for this case.
We are going to release a new one asap to solve it, until then we encourage you to use the latest version either from the repo or the docker container.

Thanks for using Prowler !!!
