### ISSUE TITLE
Check elbv2_request_smugling is superseded by elbv2_desync_mitigation_mode

### ISSUE THREAD

**Issue by visit1985** [toniblyx/prowler#2157]
### New feature motivation

In [ALB docs](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/application-load-balancers.html#load-balancer-attributes), there is the following note:

> The `routing.http.drop_invalid_header_fields.enabled` attribute was introduced to offer HTTP desync protection. The `routing.http.desync_mitigation_mode` attribute was added to provide more comprehensive protection from HTTP desync for your applications. You aren't required to use both attributes and may choose either, depending on your application's requirements.

And `routing.http.desync_mitigation_mode` is set to `defensive` by default ([more details](https://aws.amazon.com/about-aws/whats-new/2020/08/application-and-classic-load-balancers-adding-defense-in-depth-with-introduction-of-desync-mitigation-mode/)).

### Solution Proposed

I propose, to remove the elbv2_request_smugling check.

### Describe alternatives you've considered

-

**Comment by n4ch04** [comment]
Hi @visit1985, 

Interesting, we will inspect if that check adds value and delete it if not.
We'll let you know as soon as we have reviewed it.

Thanks for using Prowler !!

**Comment by n4ch04** [comment]
Hi @visit1985, we have merged both checks in one to ensure that at least the `routing.http.drop_invalid_header_fields.enabled` is enabled.

If `routing.http.desync_mitigation_mode` is enabled -> `PASS` 
If not but `routing.http.drop_invalid_header_fields.enabled` is enabled -> `PASS`
If neither of the two is enabled  -> `FAIL`

This way we ensure that at least one of the protection settings is enabled, with a higher priority for the most complete one.
Good catch and thanks for using Prowler !!
