### ISSUE TITLE
[Bug]: Prowler doesn't archive old SecurityHub findings from regions with zero new findings

### ISSUE THREAD

**Issue by dsech** [toniblyx/prowler#2190]
### Steps to Reproduce

Command used: `prowler -S -q -C /config/checklist.json -w /config/allowlist.yaml -R <role arn>`

How to reproduce:
1. Have some issues in two separate regions, for example a public bucket in each of us-east-1 and us-east-2
2. Run prowler, which will detect the issues and import both findings in SecurityHub
3. Fix the issue in us-east-2, for example we delete the bucket there
4. Run prowler, which correctly detects only the issue in us-east-1. It correctly updates the us-east-1 finding in SecurityHub, but the finding in us-east-2 is not archived.

### Expected behavior

The finding in us-east-2 is archived.

### Actual Result with Screenshots or Logs

The finding in us-east-2 is not archived.

### How did you install Prowler?

Docker (docker pull toniblyx/prowler)

### Environment Resource

Fargate task

### OS used

docker image

### Prowler version

Prowler 3.2.4

### Pip version

n/a

### Context

Apologies if I get this wrong, as I don't have much experience with python, but I think the issue is here: https://github.com/prowler-cloud/prowler/blob/f9f9ff0cb8acdd1c825d9f46590b0b2db18bc639/prowler/providers/aws/lib/security_hub/security_hub.py#L70-L81
The archive operation runs only in the regions found in the final report. If the final report doesn't have findings in a region, then old findings from this region will not get archived.

The archive operation should be executed for all scanned regions, regardless if they have findings or not.

**Comment by MrCloudSec** [comment]
Hi @dsech, thank you for reaching us out!
Good catch, I think that removing the following line will solve the issue and archive findings independent of the region where Security Hub is enabled:
https://github.com/prowler-cloud/prowler/blob/f9f9ff0cb8acdd1c825d9f46590b0b2db18bc639/prowler/providers/aws/lib/security_hub/security_hub.py#L102

**Comment by dsech** [comment]
I still think the actual scanned regions should be involved in the logic here.
For example, if I'm running `prowler -f us-east-1 -S -q` then I'd expect only the old findings from us-east-1 to be archived.

**Comment by MrCloudSec** [comment]
You're right, but we would also need to add the same logic to the services or checks (if you scan only one service or one check, we should only archive the findings related to them). This is a feature that we will add in the future.

**Comment by dsech** [comment]
In my current scenario, I'm passing a `checklist.json` to prowler (`prowler -C checklist.json`), which is still getting checks added and removed (because people are still deciding what checks are important or not). And right now I like that the corresponding findings are getting archived when checks are removed, as it keeps SecurityHub clean.

So, if this logic will include filtering of checks as well, then it would be great to somehow keep the above scenario possible.

**Comment by MrCloudSec** [comment]
Removing that line should work for that case. I made the changes in the brach [2190-bug-prowler-doesnt-archive-old-securityhub-findings-from-regions-with-zero-new-findings](https://github.com/prowler-cloud/prowler/tree/2190-bug-prowler-doesnt-archive-old-securityhub-findings-from-regions-with-zero-new-findings). Could you try your scenario in there?

**Comment by dsech** [comment]
Hi @sergargar!

I've played a bit with branch [2190-bug-prowler-doesnt-archive-old-securityhub-findings-from-regions-with-zero-new-findings](https://github.com/prowler-cloud/prowler/tree/2190-bug-prowler-doesnt-archive-old-securityhub-findings-from-regions-with-zero-new-findings), and found some problems with this change.

I've picked a couple scenarios that show these problems, and they were run on an AWS account with existing findings in us-east-1, eu-west-1, and eu-central-1. eu-central-1 is also configured as SecurityHub region aggregator.

**Scenario 1**:
- run prowler with `-f us-east-1 eu-west-1` and scan for some checks that have findings only in us-east-1
- the scanned finding from us-east-1 was correctly refreshed
- the old finding from us-east-1 was correctly archived
- the old findings from eu-west-1 were incorrectly ignored (these were supposed to be archived)
Reasoning: Removing the filter didn't change anything for this scenario, because SecurityHub in us-east-1 contains only us-east-1 findings

**Scenario 2**:
- run with `-f eu-central-1`
- the scanned findings from eu-central-1 were correctly refreshed
- the archiving step crashed with error `2023-04-13 10:50:02,419 [File: security_hub.py:131]     [Module: security_hub]   ERROR: InvalidInputException -- [122]:An error occurred (InvalidInputException) when calling the BatchImportFindings operation:
 productArn: "arn:aws:securityhub:us-east-1::product/prowler/prowler" in region eu-central-1`

Reasoning: eu-central-1 is the region aggregator, which means `security_hub.get_findings()` return all findings from all regions, but `security_hub.batch_import_findings()` can be called only in the finding's region. 
In this case the eu-central-1 SecurityHub reported an old finding from us-east-1, and prowler tried to archive it through the eu-central-1 SecurityHub, which is not allowed.

**Comment by MrCloudSec** [comment]
Thank you for this useful information @dsech ! 
It is a weird behavior since we initialize the security hub client in the resource's region, so it would archive the findings in the correct region:
https://github.com/prowler-cloud/prowler/blob/f9f9ff0cb8acdd1c825d9f46590b0b2db18bc639/prowler/providers/aws/lib/security_hub/security_hub.py#L78-L86
Can you repeat the scenarios with the new changes in the branch, please? (I change the Region filter to ResourceRegion filter, although it should be the same)

**Comment by dsech** [comment]
Hi @sergargar !
Apologies for my delayed response, I didn't get a chance to check out the changes until now.


> Can you repeat the scenarios with the new changes in the branch, please? (I change the Region filter to ResourceRegion filter, although it should be the same)

This looks to be the same as on master - it fails to archive old findings if the current scan didn't find any new findings.


> It is a weird behavior since we initialize the security hub client in the resource's region, so it would archive the findings in the correct region:

That is correct, but the problem I'm reporting is that prowler isn't initializing the security hub client with each of the scanned regions, and that's why it is failing to archive all the findings it's supposed to.

Maybe I didn't explained this properly, but this is a logic bug in prowler. If I'm running a scan in regions 1, 2, and 3 then prowler should initialize SecurityHub client and archive old findings in each of regions 1, 2, and 3.
Right now this doesn't happen - if the scan generates zero findings then NO old findings will get archived.

**Comment by MrCloudSec** [comment]
Hi @dsech, I think with the PR above solves the issue that you were addressing. Can you try it in the branch `archive-shub-regions`?

Feel free to reopen the issue if you still encounter the issue.
