### ISSUE TITLE
AWS iam_policy_allows_privilege_escalation check are not accurate

### ISSUE THREAD

**Issue by roisec** [toniblyx/prowler#2220]
### New feature motivation

Hi,
I got that the iam_policy_allows_privilege_escalation check is not accurate.
for example:
glue:GetDevEndpoints if this action is alone without IAM: PassRole privilege escalation can't be performed.
  
WDYT?

_Another issue from 2023/06/26_

Hi
Prowler alert for only glue:GetDevEndpoint action that allows performing PE.
I think need to check the combination of glue:UpdateDevEndpoint together glue:GetDevEndpoint.
today prowler alert wrong PE alert for only GetDevEndpoint action

### Solution Proposed

Identify a combination of policies that allows PE.

### Describe alternatives you've considered

NA

**Comment by jfagoagas** [comment]
Hi @roisec, you're right, some actions doesn't allow for privilege escalation by itself without some others. This check was built from https://bishopfox.com/blog/privilege-escalation-in-aws so maybe we can create some tuples within the policies list to map the right actions that needs to be together in order to allow for privilege escalation. 

We'll give this a thought.

Thanks for using Prowler!

**Comment by Fennerr** [comment]
A better solution, but it would require significantly more effort, would be to implment the graph-based approach pmapper uses

**Comment by jfagoagas** [comment]
This is our idea, to implement it with a matrix because you need the combination of several permissions to allow the privilege escalation.

**Comment by ernievd** [comment]
I assume that there is no ETA for a fix on this?

**Comment by jfagoagas** [comment]
Hi @ernievd, we are working on it but we don't have an ETA. We will update this issue as soon as we have the fix.

**Comment by jfagoagas** [comment]
Hi @ernievd @roisec I'm working on a fix right now. Could you please check it again with the branch `PRWLR-1969-aws-iam-policy-allows-privilege-escalation-check-are-not-accurate-2220`?

Thanks!
