### ISSUE TITLE
[Bug]: ECR Scan on push false positive

### ISSUE THREAD

**Issue by Baptiste-Leterrier** [toniblyx/prowler#2228]
### Steps to Reproduce

When running a scan on ECR on AWS, the scan on push setting is tested with the check "ecr_repositories_scan_images_on_push_enabled"

However, the configuration of Scan on push will be deprecated by AWS in favor of registry level scan.
![image](https://user-images.githubusercontent.com/5075233/232541965-d84e0c2a-261c-48ba-9965-a0ef1b0d6c52.png)

The check actually works correctly as the scan on push on the repository is disabled but it will return a FAIL even when registry level is enabled an scan results are seen on the console.

### Expected behavior

The check should rely on the filter set at the registry level to evaluate if scan on push is set.
![image](https://user-images.githubusercontent.com/5075233/232542522-215d4efb-d85c-411f-962d-8d7223d49011.png)

### Actual Result with Screenshots or Logs

![image](https://user-images.githubusercontent.com/5075233/232541965-d84e0c2a-261c-48ba-9965-a0ef1b0d6c52.png)

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

EC2 instance

### OS used

Amazon Linux 2

### Prowler version

Prowler 3.2.4

### Pip version

pip 20.2.2

**Comment by MrCloudSec** [comment]
Thank you for letting us know @Baptiste-Leterrier! We will change the check behavior in favor of registry level scan.

**Comment by MrCloudSec** [comment]
FYI @Baptiste-Leterrier, we created a new check with this new logic and leave the old one as deprecated.

**Comment by Baptiste-Leterrier** [comment]
Awesome ! Thanks for your quick answer ! And this awesome tool !
