### ISSUE TITLE
Add an AWS ISO 27001 security compliance framework

### ISSUE THREAD

**Issue by Sh4dow-BR** [toniblyx/prowler#2241]
### New feature motivation

Hey guys,

While talking to Toni, we noticed that the compliance check for 27001 was not in the available list of compliance frameworks since there was in the past.

### Solution Proposed

Is it should an “easy” add because there was already a compliance check but it's just not listed in the compliance folder for AWS.

### Describe alternatives you've considered

N/A

**Comment by toniblyx** [comment]
We are working on it now

**Comment by Sh4dow-BR** [comment]
Hey there Toni!
Alright, awesome!

**Comment by njmulsqb** [comment]
Why doesn't https://github.com/prowler-cloud/prowler/blob/master/docs/tutorials/compliance.md mention ISO 27001 in the list? Can we test Azure subscription for ISO 27001 compliance?
