### ISSUE TITLE
[Bug]: rds_instance_transport_encrypted not checked correctly

### ISSUE THREAD

**Issue by blaargh** [toniblyx/prowler#2244]
### Steps to Reproduce

With an RDS Aurora PostgreSQL Cluster, the mentioned check cannot get the correct result.
The check tries to find `rds.force_ssl` in the DB Parameter Group attached to the specific instance. But DB Parameter Groups don't even have that setting. The setting can only be found in DB Cluster Parameter Groups.

See here:https://github.com/prowler-cloud/prowler/blob/559c4c0c2c680642e43c8a0ac4b1a8e64cfaf041/prowler/providers/aws/services/rds/rds_service.py#L78

### Expected behavior

The check should get the information from DB Cluster Parameter Groups if there's a DB Cluster.

### Actual Result with Screenshots or Logs

![image](https://user-images.githubusercontent.com/49124793/233349182-07548f83-9186-4539-b09c-bd709a7ff40c.png)
![image](https://user-images.githubusercontent.com/49124793/233349473-300c1108-f83a-4906-b0d2-50a534eeb3bd.png)
![image](https://user-images.githubusercontent.com/49124793/233349401-88f106f9-3573-4cfd-95ae-0bca13ab0e73.png)

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

Workstation

### OS used

WSL2 under Windows 11

### Prowler version

Prowler 3.3.4

### Pip version

pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)

**Comment by MrCloudSec** [comment]
Hi @blaargh, thanks for reaching us out!
You are right, Aurora doesn't support `rds.force_ssl` in the DB Parameter Groups.
We will change the check behavior to only check Microsoft SQL Server and PostgreSQL instances, and we will create a check for Aurora instances in the future.
