### ISSUE TITLE
[Bug]: iam_role_cross_service_confused_deputy_prevention checks roles that are not capable of fulfill the intended check

### ISSUE THREAD

**Issue by blaargh** [toniblyx/prowler#2248]
### Steps to Reproduce

Prowler falsely checks IAM service-roles and IAM service-linked-roles. Recognizable by their ARN:
Service Role example: `arn:aws:iam::<account_id>:role/service-role/<role_name>`
Service Linked Role example: `arn:aws:iam::<account_id>:role/aws-service-role/servicename.amazonaws.com/<role_name>`

Service Roles are not capable of setting the condition keys that are checked here: https://github.com/prowler-cloud/prowler/blob/master/prowler/providers/aws/services/iam/iam_role_cross_service_confused_deputy_prevention/iam_role_cross_service_confused_deputy_prevention.py#L32

See documentation of available condition keys for Service Roles here: https://docs.aws.amazon.com/service-authorization/latest/reference/list_awssecuritytokenservice.html

Service Linked Roles on the other hand do not even have an editable trust relationship policy. Thus, you will never be able to set the condition keys to pass the check.

### Expected behavior

Only check actual roles for the confused deputy vulnerability, e.g. roles that have the following path: 
`arn:aws:iam::<account_id>:role/<role_name>`

### Actual Result with Screenshots or Logs

-

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

Workstation

### OS used

WSL2 under Windows 11

### Prowler version

Prowler 3.4.0 (it is the latest version, yay!)

### Pip version

pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)

**Comment by MrCloudSec** [comment]
Hi @blaargh, thanks for reaching us out!
You are right about service-linked roles. However, I could change the trust relationship of service-roles by adding the following condition:
```
	"Action": "sts:AssumeRole",
	"Condition": {
		"StringEquals": {
			"aws:SourceAccount": "<AWS_ACCOUNT>"
		}
	}
```
Can you try it and let me know if that works for you?

**Comment by blaargh** [comment]
Yes they are editable, but the condition key "aws:SourceAccount" does nothing for service-roles. See the section of the link I posted:
https://docs.aws.amazon.com/service-authorization/latest/reference/list_awssecuritytokenservice.html
![image](https://user-images.githubusercontent.com/49124793/233436190-d31ea834-22ad-4bf1-9135-af10e7aa98b1.png)

Only the listed conditionKeys have an effect on service-roles

**Comment by MrCloudSec** [comment]
@blaargh why does that screenshot only affect to service roles?
According to this documentation https://docs.aws.amazon.com/IAM/latest/UserGuide/confused-deputy.html#cross-service-confused-deputy-prevention, the cross service confused deputy prevention also affects to service roles:

> In the following role trust policy example, you can use the aws:SourceArn condition key to restrict access to the service role based on the incident record's ARN.

**Comment by blaargh** [comment]
Yeah so the AWS docs are very confusing on this topic and are not really offering a definitive explanation on one page. What I assume they are talking about are ONLY regular roles, e.g. `arn:aws:iam::<account_id>:role/<role_name>`. I tested using the `"aws:SourceArn"` condition in one of my service-policies in a very open way, just to prove it works. But it actually just blocked the whole service and didn't do anything.
Using the `"aws:SourceArn"` on regular roles on the other hand has the expected effect. So what I want to say is I can't prove my assumption at the moment because there are no docs confirming it, just my anecdotal evidence. But I will try to dig deeper and find prove.

**Comment by MrCloudSec** [comment]
Thank you @blaargh, I will try to do some testing also.
Feel free to reopen the issue if you find some prove, at the moment, we will avoid only the Service Linked Roles in this checks.
