### ISSUE TITLE
[Bug]: AM not able to run Prowler after all the installations it is showing prowler is a directory

### ISSUE THREAD

**Issue by KD17k** [toniblyx/prowler#2253]
### Steps to Reproduce

./prowler

bash: ./prowler: Is a directory - getting this response 
i used this link to clone https://github.com/prowler-cloud/prowler.git

### Expected behavior

The prowler tool is used to generate some reports

### Actual Result with Screenshots or Logs

it will show the checks and reports

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

EC2 Instance (linux)

### OS used

Amazon Linux 2

### Prowler version

cloned from repository

### Pip version

pip 20.2.2 from /usr/lib/python3.7/site-packages/pip (python 3.7)

**Comment by MrCloudSec** [comment]
Hi @KD17k, you will have to use Python to execute Prowler `python prowler.py`. 
These are the steps when executing Prowler from Github (https://github.com/prowler-cloud/prowler#from-github):
```
git clone https://github.com/prowler-cloud/prowler
cd prowler
poetry shell
poetry install
python prowler.py -v
```

**Comment by toniblyx** [comment]
Also @KD17k if yo install Prowler with `pip` you just can run `prowler`. 

`./prowler` was the way for Prowler v2 and before.

**Comment by KD17k** [comment]
> Also @KD17k if yo install Prowler with `pip` you just can run `prowler`.
> 
> `./prowler` was the way for Prowler v2 and before.

]$ pip3 install prowler
Defaulting to user installation because normal site-packages is not writeable
ERROR: Could not find a version that satisfies the requirement prowler (from versions: none)
ERROR: No matching distribution found for prowler

**Comment by KD17k** [comment]
> poetry shell
> poetry instal

---

[ec2-user@ip-33-33-33 prowtest]$ cd prowler
[ec2-user@ip-33-33-33 prowler]$ poetry shell
bash: poetry: command not found
[ec2-user@ip-33-33-33 prowler]$

**Comment by KD17k** [comment]
> Hi @KD17k, you will have to use Python to execute Prowler `python prowler.py`. These are the steps when executing Prowler from Github (https://github.com/prowler-cloud/prowler#from-github):
> 
> ```
> git clone https://github.com/prowler-cloud/prowler
> cd prowler
> poetry shell
> poetry install
> python prowler.py -v
> ```

---

[ec2-user@ip-33-33-33  prowler]$ python3 prowler.py -v
Traceback (most recent call last):
  File "prowler.py", line 5, in <module>
    from prowler.__main__ import prowler
  File "/prowtest/prowler/prowler/__main__.py", line 6, in <module>
    from prowler.lib.banner import print_banner
  File "/prowtest/prowler/prowler/lib/banner.py", line 1, in <module>
    from colorama import Fore, Style
ModuleNotFoundError: No module named 'colorama'
[ec2-user@ip-33-33-33  prowler]$

- After installing all the modules one by one it will tell no module named Azure (am running this in aws) i don't need that 

Previously i created a automation that will do the process now suddenly it is not working and also it is also showing Prowler is a directory

**Comment by MrCloudSec** [comment]
@KD17k, try to install `poetry` first with `pip install poetry`.

**Comment by MrCloudSec** [comment]
> > Also @KD17k if yo install Prowler with `pip` you just can run `prowler`.
> > `./prowler` was the way for Prowler v2 and before.
> 
> ]$ pip3 install prowler Defaulting to user installation because normal site-packages is not writeable ERROR: Could not find a version that satisfies the requirement prowler (from versions: none) ERROR: No matching distribution found for prowler

That seems a problem with Internet connection.

**Comment by KD17k** [comment]
[ec2-user@ip33-33-33 prowler]$ python3 prowler.py -v
Traceback (most recent call last):
  File "prowler.py", line 5, in <module>
    from prowler.__main__ import prowler
  File "/prowtest/prowler/prowler/__main__.py", line 6, in <module>
    from prowler.lib.banner import print_banner
  File "/prowtest/prowler/prowler/lib/banner.py", line 1, in <module>
    from colorama import Fore, Style
ModuleNotFoundError: No module named 'colorama'
[ec2-user@ip33-33-33 prowler]$ poetry shell
bash: poetry: command not found
[ec2-user@ip-33-33-33prowler]$

i installed poetry and running this command getting the same error am running this from linux 2 Ec2 instance . 

and about internet connection error are you mentioning about security rules here ?

**Comment by MrCloudSec** [comment]
Here you have how to install Prowler in Amazon Linux 2 instance: https://docs.prowler.cloud/en/latest/#installation
Please, make sure you have your instance in a public VPC with outbound connection to Internet.

**Comment by KD17k** [comment]
[ec2-user@ip-33-33-33 /]$ ping www.google.com
PING www.google.com (111.221.11.443) 56(84) bytes of data.
64 bytes from bl-in-f105.1e100.net (111.221.11.443): icmp_seq=1 ttl=52 time=3.45 ms
64 bytes from bl-in-f105.1e100.net (111.221.11.443): icmp_seq=2 ttl=52 time=2.50 ms
64 bytes from bl-in-f105.1e100.net (111.221.11.443): icmp_seq=3 ttl=52 time=2.41 ms
64 bytes from bl-in-f105.1e100.net (111.221.11.443): icmp_seq=4 ttl=52 time=2.37 ms



[ec2-user@ip-33-33-33 prowler]$ aws --version
aws-cli/2.11.14 Python/3.11.3 Linux/5.10.176-157.645.amzn2.x86_64 exe/x86_64.amzn.2 prompt/off
[ec2-user@ip-33-33-33 prowler]$ jq --version
jq-1.5
[ec2-user@ip-33-33-33 prowler]$ git --version
git version 2.39.2
[ec2-user@ip-33-33-33 prowler]$ pip3 --version
pip 20.2.2 from /usr/lib/python3.7/site-packages/pip (python 3.7)
[ec2-user@ip-33-33-33 prowler]$ python3 --version
Python 3.7.16
[ec2-user@ip-33-33-33 prowler]$pip3 install detect-secrets==1.0.3 - installed this as well
[ec2-user@ip-33-33-33 prowler]$ pip3 install poetry - installed this as well



[ec2-user@ip-33-33-33  prowler]$ python3 prowler.py -v
Traceback (most recent call last):
  File "prowler.py", line 5, in <module>
    from prowler.__main__ import prowler
  File "/prowtest/prowler/prowler/__main__.py", line 6, in <module>
    from prowler.lib.banner import print_banner
  File "/prowtest/prowler/prowler/lib/banner.py", line 1, in <module>
    from colorama import Fore, Style
ModuleNotFoundError: No module named 'colorama'
[ec2-user@ip-10-71-1-61 prowler]$

----
I installed all the things , am able to ping even i tried to install the the modules finally it is asking me to install Azure modules don't know why

**Comment by MrCloudSec** [comment]
Hi @KD17k, you still have to install the modules before executing Prowler:
```
poetry shell
poetry install
```

**Comment by KD17k** [comment]
am not able to run this commands inside prowler - altough i installed this [ec2-user@ip-33-33-33 prowler]$ pip3 install poetry - installed this as well

[ec2-user@ip-10-71-1-61 prowler]$ poetry shell
bash: poetry: command not found
[ec2-user@ip-33-33-33  prowler]$ pip3 poetry shell
ERROR: unknown command "poetry"

**Comment by KD17k** [comment]
Thankyou man for helping my issue is resloved
