### ISSUE TITLE
Allowlist: SecurityGroups shall be adressable by name

### ISSUE THREAD

**Issue by HarryBo112** [toniblyx/prowler#2254]
### New feature motivation

It looks like in the allowlist I cannot do:

`        "ec2_securitygroup_allow_wide_open_public_ipv4":

          Regions:
            - "eu-central-1"
          Resources:
            - "my-name"
`
but instead have to used its ID, i.e. "sg-097f3c59b0a1576e7".

Is this intended?

### Solution Proposed

Use "Resource" for both checking against the security-group's name and its ID.

### Describe alternatives you've considered

none

**Comment by MrCloudSec** [comment]
Hi @HarryBo112, Prowler only supports Resources' IDs in the allowlist and we will evaluate it. However, you can allowlist your resources by tags, maybe that can help you with your use case. See more info in: https://docs.prowler.cloud/en/latest/tutorials/allowlist/

**Comment by MrCloudSec** [comment]
@HarryBo112 feel free to reopen the issue if you have any problems with filtering the security groups by their ID.
