### ISSUE TITLE
How to allow-list iam_policy_allows_privilege_escalation?

### ISSUE THREAD

**Issue by HarryBo112** [toniblyx/prowler#2255]
### New feature motivation

How do I allow-list an accepted iam policy validation?

`Check ID: iam_policy_allows_privilege_escalation - iam [high]
        FAIL eu-central-1: Custom Policy arn:aws:iam::112:policy/service-role/Amazon_EventBridge_Invoke_Start_Automation_Execution_112 allows privilege escalation using the following actions: {'iam:PassRole'}
`

My allowlist snippet is:

`        "iam_policy_allows_privilege_escalation":

          Regions:
            - "eu-central-1"
          Resources:
            - "arn:aws:iam::112:policy/service-role/Amazon_EventBridge_Invoke_Start_Automation_Execution_112"`

The same question would also apply to i.e. the sns_topics_kms_encryption_at_rest_enabled provider. I would need to allow-list a similar "pattern" there:

`Check ID: sns_topics_kms_encryption_at_rest_enabled - sns [high]
        FAIL eu-central-1: SNS topic arn:aws:sns:eu-central-1:112:cloudwatch-pagerduty-alarms-ec2-state-changes is not encrypted
`

Thank you!

### Solution Proposed

none

### Describe alternatives you've considered

none

**Comment by MrCloudSec** [comment]
Hi @HarryBo112, the allowlist works with resource IDs. Can you try it to do it by including in the Resources section your resources' IDs? (in your case `Amazon_EventBridge_Invoke_Start_Automation_Execution_112` and `cloudwatch-pagerduty-alarms-ec2-state-changes`.

**Comment by HarryBo112** [comment]
Thank you!
