### ISSUE TITLE
[Bug]:  I have successfully installed prowler not able to do the checks due to ulimit issue

### ISSUE THREAD

**Issue by KD17k** [toniblyx/prowler#2256]
### Steps to Reproduce

Prowler aws service s3

### Expected behavior

It should generate some checks report

### Actual Result with Screenshots or Logs

it will show table of contents

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

ec2 instance

### OS used

amazon linux ec2

### Prowler version

2

### Pip version

1

### Context

(prowler-py3.9) [ec2-user@ip-33-33-33-33 prowler]$ prowler service s3
                         _
 _ __  _ __ _____      _| | ___ _ __| '_ \| '__/ _ \ \ /\ / / |/ _ \ '__|| |_) | | | (_) \ V  V /| |  __/ || .__/|_|  \___/ \_/\_/ |_|\___|_|v3.4.0|_| the handy cloud security tool
Date: 2023-04-21 13:38:20
This report is being generated using credentials below:AWS-CLI Profile: [default] AWS Filter Region: [all]
AWS Account: [3442342342] UserId: [aefsefaeefsefsefsef]
Caller Identity ARN: [arn:aws:iam::3442342342:user/Prowler]

Executing 270 checks, please wait...

2023-04-21 13:38:23,743 [File: utils.py:20]     [Module: utils]  CRITICAL: Ooops! You reached your user session maximum open files. To solve this issue, increase the shell session limit by running this command `ulimit -n 4096`. For more info visit https://docs.prowler.cloud/en/latest/troubleshooting/
-> Scanning accessanalyzer service |⚠︎                                       | (!) 0/27 [0%] in 1.8s
(prowler-py3.9) [ec2-user@ip-33-33-33-33 prowler]$ ulimit -n
65535

- AS you can see here i have increased the limit still the same is coming, how to resolve this error

**Comment by KD17k** [comment]
(prowler-py3.9) [ec2-user@ip-33-33-33-33 prowler]$ prowler aws --checks s3
                         _
 _ __  _ __ _____      _| | ___ _ __
| '_ \| '__/ _ \ \ /\ / / |/ _ \ '__|
| |_) | | | (_) \ V  V /| |  __/ |
| .__/|_|  \___/ \_/\_/ |_|\___|_|v3.4.0
|_| the handy cloud security tool




This report is being generated using credentials below:

AWS-CLI Profile: [default] AWS Filter Region: [all]
AWS Account: [3424234234234] UserId: [segsefsefasefsefse]
Caller Identity ARN: [arn:aws:iam::413747340919:user/Prowler]

Executing 1 check, please wait...

2023-04-21 13:57:04,161 [File: check.py:512]    [Module: check]  CRITICAL: Check 's3' was not found for the AWS provider
-> Scan was aborted! |⚠︎                                       | (!) 0/1 [0%] in 0.0s

**Comment by toniblyx** [comment]
Hi @KD17k,
for the file descriptors: it looks like it is not probably changed correctly, look at this resource and see if that helps https://www.soudegesu.com/en/linux/systemd_limits/

for the command you are running: it is wrong, you have to use `--checks` with check ids and to check services you have to use `--services s3` or whatever other service space separated. More info here https://docs.prowler.cloud/en/latest/tutorials/misc/#service

**Comment by KD17k** [comment]
Issue was i was running as ec2-user , just need to run as root user to get unlimited open files
