### ISSUE TITLE
[Bug]: Not able to run multiple aws accounts check

### ISSUE THREAD

**Issue by KD17k** [toniblyx/prowler#2265]
### Steps to Reproduce

```
# Set additional AWS account IDs to scan
ADDITIONAL_ACCOUNT_IDS=("23423429764" "23423423919")

# Loop through the additional account IDs
for ACCOUNT_ID in "${ADDITIONAL_ACCOUNT_IDS[@]}"; do
  # Run prowler aws command for each account ID and generate CSV report
  prowler aws ${ACCOUNT_ID} -M csv > prowler_report_${ACCOUNT_ID}.csv
```

### Expected behavior

Should check for all Aws accounts and send a csv report

### Actual Result with Screenshots or Logs
```
usage: prowler [-h] [-v] {aws,azure,gcp} ...
prowler: error: unrecognized arguments: -a 23423423919
```
### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

EC2 instance Linux 2

### OS used

Amazon Linux 2

### Prowler version

3

### Pip version

1

### Context

Am not able to check multiple AWS account checks like previous Prowler. There are the commands i tried .
----
1.
```

ADDITIONAL_ACCOUNT_IDS=("23423429764" "23423423919")


for ACCOUNT_ID in "${ADDITIONAL_ACCOUNT_IDS[@]}"; do

  prowler aws ${ACCOUNT_ID} -M csv > prowler_report_${ACCOUNT_ID}.csv
```

2.

```
ADDITIONAL_ACCOUNT_IDS=("23423429764" "23423423919")


for ACCOUNT_ID in "${ADDITIONAL_ACCOUNT_IDS[@]}"; do

  prowler aws ${ACCOUNT_ID} -M csv > prowler_report_${ACCOUNT_ID}.csv
```
3.
```
ADDITIONAL_ACCOUNT_IDS=("23423429764" "23423423919")


for ACCOUNT_ID in "${ADDITIONAL_ACCOUNT_IDS[@]}"; do

  prowler aws -a ${ACCOUNT_ID} -M csv > prowler_report_${ACCOUNT_ID}.csv

ERROR - usage: prowler [-h] [-v] {aws,azure,gcp} ...
prowler: error: unrecognized arguments: -a 23423429764
```

--------

Can someone help me the exact command how to run the checks for Multiple AWS accounts

**Comment by KD17k** [comment]
AM using Python3.9 and Installed Latest Prowler 
If i use single command Prowler AWS - it is working fine but if i want to check multiple accounts it is not working

**Comment by MrCloudSec** [comment]
Hi @KD17k, the command that you should use in Prowler 3 is the following:
`prowler aws -R <role_arn>`
In this version, you have to pass the ARN of the Role you want to assume in each account, see more in https://docs.prowler.cloud/en/latest/tutorials/aws/role-assumption/.

Remember to check our documentation when you are stuck using Prowler.
