### ISSUE TITLE
[Bug]: cloudwatch_log_group_retention_policy_specific_days_enabled not measuring "never expire"

### ISSUE THREAD

**Issue by blaargh** [toniblyx/prowler#2271]
### Steps to Reproduce

When having log groups in cloudwatch that are set to "never expire", the mentioned check sees it as "0 days"

### Expected behavior

Check should be able to detect the "never expire" log group retention setting

### Actual Result with Screenshots or Logs

![image](https://user-images.githubusercontent.com/49124793/234209263-caf09398-6eee-40f3-af76-2249899021b8.png)
![image](https://user-images.githubusercontent.com/49124793/234209482-7fe1abab-20dd-4982-a05c-f3b254d8e393.png)

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

Workstation

### OS used

WSL2 on Windows 11

### Prowler version

Prowler 3.4.0 (it is the latest version, yay!)

### Pip version

pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)

**Comment by jfagoagas** [comment]
Hi @blaargh, we are going to review this and we'll get back to you.

Thanks for using Prowler!

**Comment by jfagoagas** [comment]
Hi @blaargh, could you please execute it again using the `2271-bug-cloudwatch_log_group_retention_policy_specific_days_enabled-not-measuring-never-expire` branch?

Thanks.

**Comment by blaargh** [comment]
thank you, can you trigger a new build for pip?

**Comment by jfagoagas** [comment]
> thank you, can you trigger a new build for pip? 

This will be released soon in the next fixes release. Now it's available using the `latest` container tag and cloning from the `master` branch.

Thanks for using Prowler 🚀
