### ISSUE TITLE
[Bug]: RDS checks not checking Aurora RDS Clusters correctly

### ISSUE THREAD

**Issue by blaargh** [toniblyx/prowler#2275]
### Steps to Reproduce

Check `rds_instance_deletion_protection `does not check if the affected instance is part of a cluster. Instances that are part of an RDS cluster cannot individually set deletion-protection, it can only be enabled on the cluster itself

Check `rds_instance_multi_az ` does not check if the instance is part of a cluster that has multi AZ configured.

### Expected behavior

These checks should be able to detect RDS clusters 

### Actual Result with Screenshots or Logs

![image](https://user-images.githubusercontent.com/49124793/234266195-7a7a4606-2edb-4064-a9e4-3fa176ec1cea.png)
![image](https://user-images.githubusercontent.com/49124793/234266625-6eeb678b-c47b-46f5-bc02-58545b50f587.png)

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

Workstation

### OS used

WSL2 under Windows 11

### Prowler version

Prowler 3.4.0 (it is the latest version, yay!)

### Pip version

pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)

**Comment by MrCloudSec** [comment]
Good catch @blaargh ! We will fix it shortly
