### ISSUE TITLE
[Bug]: backup_plans_exist and backup_reportplans_exist trigger in regions where not backups exist

### ISSUE THREAD

**Issue by blaargh** [toniblyx/prowler#2276]
### Steps to Reproduce

The mentioned checks are triggered even if no backups are present or configured.

### Expected behavior

When the check can't find a resource ID (it actually says "No Backups"), the check shouldn't trigger

### Actual Result with Screenshots or Logs

![image](https://user-images.githubusercontent.com/49124793/234267687-dcbcbe11-2d15-43ba-84ee-575f28719ffd.png)

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

Workstation

### OS used

WSL2 under Windows 11

### Prowler version

Prowler 3.4.0 (it is the latest version, yay!)

### Pip version

pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)

**Comment by jfagoagas** [comment]
Hi @blaargh, we are checking that. We will get back to you when we finish our analysis.

Thanks for using Prowler 🚀

**Comment by jfagoagas** [comment]
Hi @blaargh, we've modified the behaviour of the Backups service and now the `backup_reportplans_exist` check, which only makes sense if a backup plans exist, returns empty if there are no report plans.

With that we are closing this issue. Please feel free to reopen it if you want to provide us more information about this or if you experience some unexpected behaviour.

Thanks for using Prowler 🚀
