### ISSUE TITLE
[Bug]: False positives on some checks?

### ISSUE THREAD

**Issue by HarryBo112** [toniblyx/prowler#2278]
### Steps to Reproduce

Hi,

it looks like some checks produce false positives (they are tagged as warning because I've allowlisted them):

```
Check ID: ec2_ebs_snapshots_encrypted - ec2 [medium]
        WARNING eu-central-1: EBS Snapshot snap-112 is unencrypted.
        WARNING eu-central-1: EBS Snapshot snap-113 is encrypted.  <<<<
```

```
Check ID: iam_policy_allows_privilege_escalation - iam [high]
        WARNING eu-central-1: Custom Policy arn:aws:iam::112:policy/aws_admin_access does not allow privilege  escalation
```

Are you maybe simply overring the status (also "PASS") by WARNING in case of an allowlist match?

Another type of issue but more like a question:

_sns_topics_not_publicly_accessible_ triggers with 
` WARNING eu-central-1: SNS topic cloudwatch-pagerduty-alarms-ec2-state-changes policy with public access but has a Condition`
which is (from the User's perspective) a false positive as well because we have a condition, which prowler cannot evaluate?

### Expected behavior

none

### Actual Result with Screenshots or Logs

none

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

locally

### OS used

Linux

### Prowler version

3.4.1

### Pip version

none

**Comment by jfagoagas** [comment]
Hi @HarryBo112, I'm going to answer each question down below:

> it looks like some checks produce false positives (they are tagged as warning because I've allowlisted them):
> 
> ```
> Check ID: ec2_ebs_snapshots_encrypted - ec2 [medium]
>         WARNING eu-central-1: EBS Snapshot snap-112 is unencrypted.
>         WARNING eu-central-1: EBS Snapshot snap-113 is encrypted.  <<<<
> ```
> 
> ```
> Check ID: iam_policy_allows_privilege_escalation - iam [high]
>         WARNING eu-central-1: Custom Policy arn:aws:iam::112:policy/aws_admin_access does not allow privilege  escalation
> ```
> 
> Are you maybe simply overring the status (also "PASS") by WARNING in case of an allowlist match?

That is right, the behaviour of the allowlist is just to add a `WARNING` instead of `INFO`, `PASS` or `FAIL` to any output format. Please, refer to the documentation here https://docs.prowler.cloud/en/latest/tutorials/allowlist/ to get more details and how the allowlist works.

> 
> Another type of issue but more like a question:
> 
> _sns_topics_not_publicly_accessible_ triggers with ` WARNING eu-central-1: SNS topic cloudwatch-pagerduty-alarms-ec2-state-changes policy with public access but has a Condition` which is (from the User's perspective) a false positive as well because we have a condition, which prowler cannot evaluate?
> 
We're going to review this and we'll get back to you soon.

Thanks for using Prowler!

**Comment by jfagoagas** [comment]
Hi @HarryBo112, could you please check the following PR https://github.com/prowler-cloud/prowler/pull/2282? 

We've changed the check's behaviour and also improved the messages.

Thanks!
