### ISSUE TITLE
[Bug]: ecr_repositories_scan_vulnerabilities_in_latest_image scans all images

### ISSUE THREAD

**Issue by HarryBo112** [toniblyx/prowler#2279]
### Steps to Reproduce

Hi,
it looks like ecr_repositories_scan_vulnerabilities_in_latest_image does scan all images. not just the latest:
 
```
       ...
        PASS eu-central-1: ECR repository service has imageTag 6601 scanned without findings
        PASS eu-central-1: ECR repository service has imageTag 6713 scanned without findings
        FAIL eu-central-1: ECR repository service has imageTag 1288 without a scan
        FAIL eu-central-1: ECR repository service has imageTag 1527 without a scan
        FAIL eu-central-1: ECR repository service has imageTag 1606 without a scan
        FAIL eu-central-1: ECR repository service has imageTag 1695 without a scan
        FAIL eu-central-1: ECR repository service has imageTag 1825 without a scan
```

### Expected behavior

Scanning latest image only

### Actual Result with Screenshots or Logs

none

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

locally

### OS used

Linux

### Prowler version

3.4.1

### Pip version

none

**Comment by jfagoagas** [comment]
Hi @HarryBo112, we are going to check this and we'll get back to you soon.

Thanks for using Prowler 🚀

**Comment by jfagoagas** [comment]
Hi @HarryBo112, could you please execute Prowler again using this branch `PRWLR-2033-bug-ecr-repositories-scan-vulnerabilities-in-latest-image-scans-all-images-2279`?

The above PR has the changes.

**Comment by HarryBo112** [comment]
Not quite sure if this is what you wanted it to do:


Check ID: ecr_repositories_scan_vulnerabilities_in_latest_image - ecr [medium]
        PASS eu-central-1: ECR repository forwarder has imageTag 402 scanned without findings
        PASS eu-central-1: ECR repository forwarder has imageTag 408 scanned without findings
        PASS eu-central-1: ECR repository forwarder has imageTag 403 scanned without findings
        PASS eu-central-1: ECR repository forwarder has imageTag 422 scanned without findings
        PASS eu-central-1: ECR repository forwarder has imageTag 429 scanned without findings
        PASS eu-central-1: ECR repository forwarder has imageTag 420 scanned without findings
        PASS eu-central-1: ECR repository forwarder has imageTag 421 scanned without findings
        PASS eu-central-1: ECR repository forwarder has imageTag 387 scanned without findings
        PASS eu-central-1: ECR repository forwarder has imageTag 432 scanned without findings
        PASS eu-central-1: ECR repository forwarder has imageTag 435 scanned without findings
        PASS eu-central-1: ECR repository forwarder has imageTag 365 scanned without findings
        PASS eu-central-1: ECR repository forwarder has imageTag 427 scanned without findings
        PASS eu-central-1: ECR repository forwarder has imageTag 410 scanned without findings
        PASS eu-central-1: ECR repository forwarder has imageTag 418 scanned without findings
        PASS eu-central-1: ECR repository forwarder has imageTag 433 scanned without findings
        PASS eu-central-1: ECR repository forwarder has imageTag 436 scanned without findings
        PASS eu-central-1: ECR repository forwarder has imageTag latest scanned without findings
        PASS eu-central-1: ECR repository forwarder has imageTag 413 scanned without findings
        PASS eu-central-1: ECR repository service-tls-sidecar has imageTag latest scanned without findings
        PASS eu-central-1: ECR repository service-tls-sidecar has imageTag 890 scanned without findings
        PASS eu-central-1: ECR repository service-tls-sidecar has imageTag 888 scanned without findings
        PASS eu-central-1: ECR repository service-tls-sidecar has imageTag 889 scanned without findings
        PASS eu-central-1: ECR repository service-tls-sidecar has imageTag 867 scanned without findings
        PASS eu-central-1: ECR repository service-tls-sidecar has imageTag 875 scanned without findings
        PASS eu-central-1: ECR repository gservice has imageTag 2904 scanned without findings
        PASS eu-central-1: ECR repository gservice has imageTag 2892 scanned without findings


It does not seem to scan all images, but for the single images it still scans "all" revisions?

**Comment by jfagoagas** [comment]
@HarryBo112 that's weird, what do you mean by "single images"? Did you fetch that branch?

Could you please run this for your repositories and paste the output?
```
aws ecr describe-images --repository-name forwarder --query 'sort_by(imageDetails, &to_string(imagePushedAt))[-1]'
aws ecr describe-images --repository-name service-tls-sidecar --query 'sort_by(imageDetails, &to_string(imagePushedAt))[-1]'
aws ecr describe-images --repository-name gservice --query 'sort_by(imageDetails, &to_string(imagePushedAt))[-1]'
```

Thanks!

**Comment by HarryBo112** [comment]
Hi, yes, I am running `PRWLR-2033-bug-ecr-repositories-scan-vulnerabilities-in-latest-image-scans-all-images-2279`.

Logs of master (I did not want to shorten it):  https://www.dropbox.com/s/bx1xmqx9gwana68/master.log?dl=0
Logs of branch: https://www.dropbox.com/s/9w6gxf3831z3jj3/PRWLR-2033-bug-ecr-repositories-scan-vulnerabilities-in-latest-image-scans-all-images-2279.txt?dl=0

Maybe that makes it clearer.

**Comment by jfagoagas** [comment]
Hi @HarryBo112, I cannot reproduce the behaviour you have in my environment. Would you mind to join our Slack (https://join.slack.com/t/prowler-workspace/shared_invite/zt-1tpbutlg7-PikVOs1b0kiA3wizdhOrnA) to follow up on this?

If so, please message me directly. Thanks!
