### ISSUE TITLE
[Bug]: apigatewayv2_authorizers_enabled false positive on HTTP API

### ISSUE THREAD

**Issue by blaargh** [toniblyx/prowler#2281]
### Steps to Reproduce

The code looks like it only check REST APIs in API Gateway, see here: https://github.com/prowler-cloud/prowler/blob/3c2096db68d171ca9f0313ffa48a6fa61d87f6f0/prowler/providers/aws/services/apigatewayv2/apigatewayv2_service.py#L39

Creating a HTTP API and activating Access Logging for a stage still triggers this check.

### Expected behavior

The check should also include HTTP APIs

### Actual Result with Screenshots or Logs

-

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

Workstation

### OS used

WSL2 under Windows 11

### Prowler version

Prowler 3.4.1 (it is the latest version, yay!)

### Pip version

pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)

**Comment by MrCloudSec** [comment]
Hi @blaargh , in our scenarios the HTTP APIs are correctly gathered. However, the name of this variable is wrong, it shoul be named `get_apis_paginator`.
