### ISSUE TITLE
[Bug]: Check ID: ecr_registry_scan_images_on_push_enabled failed without using this service 

### ISSUE THREAD

**Issue by SchmitzChristian** [toniblyx/prowler#2292]
### Steps to Reproduce

1. prowler aws \
    --verbose --quiet \
    --output-modes json \
    --allowlist-file prowler-allowlist.yaml \
    --region eu-central-1
2. aws
3. multi account, but scanning only one by command
4. Check ID: ecr_registry_scan_images_on_push_enabled is red, we don't use ecr at this account

### Expected behavior

no ecr findings should be occured, we don't use ecr on this account, bug occurs with 3.4.0, with 3.3.4 it is all fine

### Actual Result with Screenshots or Logs

Check ID: ecr_registry_scan_images_on_push_enabled - ecr [medium]
	FAIL eu-central-1: ECR registry XXX has BASIC scanning without scan on push

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

Docker container in CI

### OS used

Alpine Linux

### Prowler version

3.4.0

### Pip version

23.1.1

**Comment by jfagoagas** [comment]
Hi @SchmitzChristian, we are going to review this and we'll get back to you soon. 

Thanks for using Prowler 🚀

**Comment by jfagoagas** [comment]
Hi @SchmitzChristian could you please check the `PRWLR-2065-bug-check-id-ecr-registry-scan-images-on-push-enabled-failed-without-using-this-service-2292` branch and run Prowler again using the code from there?

We've fixed the behaviour of the `ecr_registry_scan_images_on_push_enabled` to run it only if the ECR Registry has repositories created.

**Comment by SchmitzChristian** [comment]
Hi @jfagoagas works for me.
