### ISSUE TITLE
Azure add more services

### ISSUE THREAD

**Issue by arunk-tx** [toniblyx/prowler#2316]
### New feature motivation

add more services to azure provider:

*Database services
*Logging and monitoring services

### Solution Proposed

for azure add
*Database services
*Logging and monitoring services

### Describe alternatives you've considered

for azure add
*Database services
*Logging and monitoring services

**Comment by n4ch04** [comment]
Hi @arunk-tx,

We have planned to include more Azure services as soon as we can.
Of course any help in regards to new features are welcomed, if you would like to help us I encourage you to join our slack 
(https://join.slack.com/t/prowler-workspace/shared_invite/zt-1tpbutlg7-PikVOs1b0kiA3wizdhOrnA) and we will guide you  !!

Thanks for using Prowler !!
