### ISSUE TITLE
[Bug]:  prowler: browser auth issue on azure provider

### ISSUE THREAD

**Issue by arunk-tx** [toniblyx/prowler#2332]
### Steps to Reproduce

run prowler with azure provider and browser-auth

### Expected behavior

should get results, as of now no results getting with browser auth, but with env based auth its working fine though

### Actual Result with Screenshots or Logs
attaching azure screenshots and logs

![20230509_172854](https://github.com/prowler-cloud/prowler/assets/104412259/6d49dc5a-27e5-445a-b228-04bf3fe75fb1)
![20230509_173252](https://github.com/prowler-cloud/prowler/assets/104412259/980919a4-0522-46c0-a4c9-9ec4296ead5a)
[logs.log](https://github.com/prowler-cloud/prowler/files/11431056/logs.log)

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

local

### OS used

linux

### Prowler version

latest

### Pip version

latest

### Context

no

**Comment by MrCloudSec** [comment]
Hi @arunk-tx, we will review this shortly. In the meanwhile, could you execute the command with `--log-level ERROR` and send us the logs?

**Comment by arunk-tx** [comment]
@sergargar already added log  logs.log above (after the images on description) with error log level

**Comment by MrCloudSec** [comment]
thank you, these are the ERROR logs:

> {"timestamp": "2023-05-09 08:05:48,127", "filename": "azure_provider.py:129", "level": "ERROR", "module": "azure_provider", "message": "Provided identity does not have permissions to access AAD to retrieve user's metadata"}
{"timestamp": "2023-05-09 08:05:48,127", "filename": "azure_provider.py:132", "level": "ERROR", "module": "azure_provider", "message": "KeyError[125] -- 'userPrincipalName'"}

**Comment by arunk-tx** [comment]
`{"timestamp": "2023-05-12 09:31:36,185", "filename": "audit_info.py:35", "level": "INFO", "module": "audit_info", "message": "Setting Audit Info ..."}
{"timestamp": "2023-05-12 09:31:36,186", "filename": "audit_info.py:329", "level": "INFO", "module": "audit_info", "message": "Setting Azure session ..."}
{"timestamp": "2023-05-12 09:31:36,186", "filename": "audit_info.py:332", "level": "INFO", "module": "audit_info", "message": "Checking if any credentials mode is set ..."}
{"timestamp": "2023-05-12 09:31:36,186", "filename": "azure_provider.py:21", "level": "INFO", "module": "azure_provider", "message": "Instantiating Azure Provider ..."}
{"timestamp": "2023-05-12 09:31:36,188", "filename": "azure_provider.py:95", "level": "INFO", "module": "azure_provider", "message": "Trying to retrieve tenant domain from AAD to populate identity structure ..."}
{"timestamp": "2023-05-12 09:31:36,198", "filename": "_universal.py:513", "level": "INFO", "module": "_universal", "message": "Request URL: 'https://login.microsoftonline.com/organizations/v2.0/.well-known/openid-configuration'
Request method: 'GET'
Request headers:
    'User-Agent': 'azsdk-python-identity/1.12.0 Python/3.9.10 (Linux-3.10.0-1160.88.1.el7.x86_64-x86_64-with-glibc2.17)'
No body was attached to the request"}
{"timestamp": "2023-05-12 09:31:36,427", "filename": "_universal.py:549", "level": "INFO", "module": "_universal", "message": "Response status: 200
Response headers:
    'Cache-Control': 'max-age=86400, private'
    'Content-Type': 'application/json; charset=utf-8'
    'Strict-Transport-Security': 'REDACTED'
    'X-Content-Type-Options': 'REDACTED'
    'Access-Control-Allow-Origin': 'REDACTED'
    'Access-Control-Allow-Methods': 'REDACTED'
    'P3P': 'REDACTED'
    'x-ms-request-id': '746a0c41-b451-4087-bb1f-e77318ac3100'
    'x-ms-ests-server': 'REDACTED'
    'X-XSS-Protection': 'REDACTED'
    'Set-Cookie': 'REDACTED'
    'Date': 'Fri, 12 May 2023 13:31:35 GMT'
    'Content-Length': '1589'"}
{"timestamp": "2023-05-12 09:31:53,927", "filename": "_universal.py:510", "level": "INFO", "module": "_universal", "message": "Request URL: 'https://login.microsoftonline.com/organizations/oauth2/v2.0/token'
Request method: 'POST'
Request headers:
    'Accept': 'application/json'
    'x-client-sku': 'REDACTED'
    'x-client-ver': 'REDACTED'
    'x-client-os': 'REDACTED'
    'x-client-cpu': 'REDACTED'
    'x-ms-lib-capability': 'REDACTED'
    'client-request-id': 'REDACTED'
    'x-client-current-telemetry': 'REDACTED'
    'x-client-last-telemetry': 'REDACTED'
    'X-AnchorMailbox': 'REDACTED'
    'User-Agent': 'azsdk-python-identity/1.12.0 Python/3.9.10 (Linux-3.10.0-1160.88.1.el7.x86_64-x86_64-with-glibc2.17)'
A body is sent with the request"}
{"timestamp": "2023-05-12 09:31:54,647", "filename": "_universal.py:549", "level": "INFO", "module": "_universal", "message": "Response status: 200
Response headers:
    'Cache-Control': 'no-store, no-cache'
    'Pragma': 'no-cache'
    'Content-Type': 'application/json; charset=utf-8'
    'Expires': '-1'
    'Strict-Transport-Security': 'REDACTED'
    'X-Content-Type-Options': 'REDACTED'
    'P3P': 'REDACTED'
    'client-request-id': 'REDACTED'
    'x-ms-request-id': '4676dad5-006d-4db4-b630-814176b34d00'
    'x-ms-ests-server': 'REDACTED'
    'x-ms-clitelem': 'REDACTED'
    'X-XSS-Protection': 'REDACTED'
    'Set-Cookie': 'REDACTED'
    'Date': 'Fri, 12 May 2023 13:31:53 GMT'
    'Content-Length': '5539'"}
{"timestamp": "2023-05-12 09:31:54,650", "filename": "interactive.py:157", "level": "INFO", "module": "interactive", "message": "InteractiveBrowserCredential.get_token succeeded"}
{"timestamp": "2023-05-12 09:31:55,072", "filename": "azure_provider.py:121", "level": "INFO", "module": "azure_provider", "message": "Trying to retrieve user information from AAD to populate identity structure ..."}
{"timestamp": "2023-05-12 09:31:55,080", "filename": "_universal.py:510", "level": "INFO", "module": "_universal", "message": "Request URL: 'https://login.microsoftonline.com/organizations/oauth2/v2.0/token'
Request method: 'POST'
Request headers:
    'Accept': 'application/json'
    'x-client-sku': 'REDACTED'
    'x-client-ver': 'REDACTED'
    'x-client-os': 'REDACTED'
    'x-client-cpu': 'REDACTED'
    'x-ms-lib-capability': 'REDACTED'
    'client-request-id': 'REDACTED'
    'x-client-current-telemetry': 'REDACTED'
    'x-client-last-telemetry': 'REDACTED'
    'X-AnchorMailbox': 'REDACTED'
    'User-Agent': 'azsdk-python-identity/1.12.0 Python/3.9.10 (Linux-3.10.0-1160.88.1.el7.x86_64-x86_64-with-glibc2.17)'
A body is sent with the request"}
{"timestamp": "2023-05-12 09:31:55,513", "filename": "_universal.py:549", "level": "INFO", "module": "_universal", "message": "Response status: 200
Response headers:
    'Cache-Control': 'no-store, no-cache'
    'Pragma': 'no-cache'
    'Content-Type': 'application/json; charset=utf-8'
    'Expires': '-1'
    'Strict-Transport-Security': 'REDACTED'
    'X-Content-Type-Options': 'REDACTED'
    'P3P': 'REDACTED'
    'client-request-id': 'REDACTED'
    'x-ms-request-id': '283d897f-4d65-4e57-abd4-eb9530ec4400'
    'x-ms-ests-server': 'REDACTED'
    'x-ms-clitelem': 'REDACTED'
    'X-XSS-Protection': 'REDACTED'
    'Set-Cookie': 'REDACTED'
    'Date': 'Fri, 12 May 2023 13:31:54 GMT'
    'Content-Length': '5513'"}
{"timestamp": "2023-05-12 09:31:55,515", "filename": "interactive.py:124", "level": "INFO", "module": "interactive", "message": "InteractiveBrowserCredential.get_token succeeded"}
{"timestamp": "2023-05-12 09:31:55,774", "filename": "azure_provider.py:130", "level": "ERROR", "module": "azure_provider", "message": "Provided identity does not have permissions to access AAD to retrieve user's metadata"}
{"timestamp": "2023-05-12 09:31:55,774", "filename": "azure_provider.py:149", "level": "INFO", "module": "azure_provider", "message": "Trying to retrieve subscriptions and tenant ids to populate identity structure ..."}
{"timestamp": "2023-05-12 09:31:55,777", "filename": "azure_provider.py:154", "level": "INFO", "module": "azure_provider", "message": "Scanning all the Azure subscriptions..."}
{"timestamp": "2023-05-12 09:31:55,826", "filename": "_universal.py:510", "level": "INFO", "module": "_universal", "message": "Request URL: 'https://login.microsoftonline.com/organizations/oauth2/v2.0/token'
Request method: 'POST'
Request headers:
    'Accept': 'application/json'
    'x-client-sku': 'REDACTED'
    'x-client-ver': 'REDACTED'
    'x-client-os': 'REDACTED'
    'x-client-cpu': 'REDACTED'
    'x-ms-lib-capability': 'REDACTED'
    'client-request-id': 'REDACTED'
    'x-client-current-telemetry': 'REDACTED'
    'x-client-last-telemetry': 'REDACTED'
    'X-AnchorMailbox': 'REDACTED'
    'User-Agent': 'azsdk-python-identity/1.12.0 Python/3.9.10 (Linux-3.10.0-1160.88.1.el7.x86_64-x86_64-with-glibc2.17)'
A body is sent with the request"}
{"timestamp": "2023-05-12 09:31:56,508", "filename": "_universal.py:549", "level": "INFO", "module": "_universal", "message": "Response status: 200
Response headers:
    'Cache-Control': 'no-store, no-cache'
    'Pragma': 'no-cache'
    'Content-Type': 'application/json; charset=utf-8'
    'Expires': '-1'
    'Strict-Transport-Security': 'REDACTED'
    'X-Content-Type-Options': 'REDACTED'
    'P3P': 'REDACTED'
    'client-request-id': 'REDACTED'
    'x-ms-request-id': '4676dad5-006d-4db4-b630-814197b34d00'
    'x-ms-ests-server': 'REDACTED'
    'x-ms-clitelem': 'REDACTED'
    'X-XSS-Protection': 'REDACTED'
    'Set-Cookie': 'REDACTED'
    'Date': 'Fri, 12 May 2023 13:31:56 GMT'
    'Content-Length': '4904'"}
{"timestamp": "2023-05-12 09:31:56,510", "filename": "interactive.py:124", "level": "INFO", "module": "interactive", "message": "InteractiveBrowserCredential.get_token succeeded"}
{"timestamp": "2023-05-12 09:31:56,512", "filename": "_universal.py:513", "level": "INFO", "module": "_universal", "message": "Request URL: 'https://management.azure.com/subscriptions?api-version=REDACTED'
Request method: 'GET'
Request headers:
    'Accept': 'application/json'
    'x-ms-client-request-id': '5d011797-f0c9-11ed-8bf8-000c29e55765'
    'User-Agent': 'azsdk-python-mgmt-subscription/3.1.1 Python/3.9.10 (Linux-3.10.0-1160.88.1.el7.x86_64-x86_64-with-glibc2.17)'
    'Authorization': 'REDACTED'
No body was attached to the request"}
{"timestamp": "2023-05-12 09:31:56,721", "filename": "_universal.py:549", "level": "INFO", "module": "_universal", "message": "Response status: 200
Response headers:
    'Cache-Control': 'no-cache'
    'Pragma': 'no-cache'
    'Content-Type': 'application/json; charset=utf-8'
    'Content-Encoding': 'REDACTED'
    'Expires': '-1'
    'Vary': 'REDACTED'
    'x-ms-ratelimit-remaining-tenant-reads': '11999'
    'x-ms-request-id': 'e452051e-80a5-497d-9fc5-c9f9bc7fa8cf'
    'x-ms-correlation-request-id': 'REDACTED'
    'x-ms-routing-request-id': 'REDACTED'
    'Strict-Transport-Security': 'REDACTED'
    'X-Content-Type-Options': 'REDACTED'
    'Date': 'Fri, 12 May 2023 13:31:55 GMT'
    'Content-Length': '133'"}
{"timestamp": "2023-05-12 09:31:56,722", "filename": "_universal.py:513", "level": "INFO", "module": "_universal", "message": "Request URL: 'https://management.azure.com/tenants?api-version=REDACTED'
Request method: 'GET'
Request headers:
    'Accept': 'application/json'
    'x-ms-client-request-id': '5d90eeb4-f0c9-11ed-b997-000c29e55765'
    'User-Agent': 'azsdk-python-mgmt-subscription/3.1.1 Python/3.9.10 (Linux-3.10.0-1160.88.1.el7.x86_64-x86_64-with-glibc2.17)'
    'Authorization': 'REDACTED'
No body was attached to the request"}
{"timestamp": "2023-05-12 09:31:56,917", "filename": "_universal.py:549", "level": "INFO", "module": "_universal", "message": "Response status: 200
Response headers:
    'Cache-Control': 'no-cache'
    'Pragma': 'no-cache'
    'Content-Type': 'application/json; charset=utf-8'
    'Content-Encoding': 'REDACTED'
    'Expires': '-1'
    'Vary': 'REDACTED'
    'x-ms-ratelimit-remaining-tenant-reads': '11998'
    'x-ms-request-id': '534e6171-0fca-4324-9fbe-643161154e32'
    'x-ms-correlation-request-id': 'REDACTED'
    'x-ms-routing-request-id': 'REDACTED'
    'Strict-Transport-Security': 'REDACTED'
    'X-Content-Type-Options': 'REDACTED'
    'Date': 'Fri, 12 May 2023 13:31:56 GMT'
    'Content-Length': '195'"}
{"timestamp": "2023-05-12 09:31:57,227", "filename": "defender_service.py:39", "level": "INFO", "module": "defender_service", "message": "Defender - Getting pricings..."}
{"timestamp": "2023-05-12 09:31:57,433", "filename": "iam_service.py:40", "level": "INFO", "module": "iam_service", "message": "IAM - Getting roles..."}
{"timestamp": "2023-05-12 09:31:57,593", "filename": "storage_service.py:40", "level": "INFO", "module": "storage_service", "message": "Storage - Getting storage accounts..."}
{"timestamp": "2023-05-12 09:31:57,721", "filename": "outputs.py:242", "level": "INFO", "module": "outputs", "message": "Extracting audit statistics..."}
`

**Comment by jfagoagas** [comment]
Hi @arunk-tx, we've solved the issue in the above PR. Please feel free to reopen this issue if you experience the same behaviour.

Thanks for using Prowler 🚀
