### ISSUE TITLE
[Bug]: Unable to scan AWS China region account

### ISSUE THREAD

**Issue by ah-jota** [toniblyx/prowler#2347]
### Steps to Reproduce

1. Running the following command: 
`prowler aws -o /home/prowler-output -p test-china-profile -f cn-north-1 cn-northwest-1 --log-level ERROR --verbose`
2. Running against cloud provider - `AWS`
3. Single account environment
4. Error I am experiencing: 
`2023-05-11 20:15:26,438 [File: audit_info.py:42] 	[Module: audit_info]	 CRITICAL: ClientError -- An error occurred (InvalidClientTokenId) when calling the GetCallerIdentity operation: The security token included in the request is invalid`

### Expected behavior

I am able to successfully configure the AWS credential, however I experience an error when trying to use it with Prowler. Any ideas what I am doing wrong? I noticed in the log file it is using the global sts endpoint but specifying the us-east-1 region. Shouldn't you be able to specify the region sts uses with whatever is passed to the -f flag? 

### Actual Result with Screenshots or Logs

[2023-05-11_debug.log](https://github.com/prowler-cloud/prowler/files/11456205/2023-05-11_debug.log)

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

Local workstation

### OS used

MacOS and Linux

### Prowler version

3.4.0

### Pip version

22.0.4

**Comment by jfagoagas** [comment]
Hi @ah-jota, we are going to review this and we will get back to you soon.

Thanks for using Prowler 🚀

**Comment by jfagoagas** [comment]
Hi @ah-jota, you were totally right, could you please execute it again using the branch `2347-bug-unable-to-scan-aws-china-region-account`.

Thanks!

**Comment by ah-jota** [comment]
Hey @jfagoagas ! Thank you for taking a look at this so quickly.  Just ran a test and it ran as expected. 


Just to confirm for gov cloud AWS as well, we would just need to pass the correct regions to the -f flag?

**Comment by jfagoagas** [comment]
Hi @ah-jota this sounds great!!

We are preparing a new entry for the Prowler documentation but I'm going to share it with you now. Please give it a look and tell us if this fits your need.

Thanks again.

----------------------------------------------------------------

# AWS Regions and Partitions

By default Prowler is able to scan the following AWS partitions:
- Commercial: `aws`
- China: `aws-cn`
- GovCloud (US): `aws-us-gov`

> To check the available regions for each partition and service please refer to the following document [aws_regions_by_service.json](https://github.com/prowler-cloud/prowler/blob/master/prowler/providers/aws/aws_regions_by_service.json)

It is important to take into consideration that to scan the China (`aws-cn`) or GovCloud (`aws-us-gov`) partitions it is either required to have a valid region for that partition in your AWS credentials (Refer to https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html#configuring-credentials for more information) or to specify the regions you want to audit for that partition using the `-f/--region` flag.

You can get more information about the available partitions and regions in the following [Botocore](https://github.com/boto/botocore) file https://github.com/boto/botocore/blob/22a19ea7c4c2c4dd7df4ab8c32733cba0c7597a4/botocore/data/partitions.json
## AWS China

To scan your AWS Account in the China partition (`aws-cn`):

- Using the `-f/--region` flag:
```
prowler aws --region cn-north-1 cn-northwest-1
```
- Using the region configured in your AWS profile at `~/.aws/credentials` or `~/.aws/config`:
```
[default]
aws_access_key_id = XXXXXXXXXXXXXXXXXXX
aws_secret_access_key = XXXXXXXXXXXXXXXXXXX
region = cn-north-1
```
> With this option all the partition regions will be scanned without the need of use the `-f/--region` flag


## AWS GovCloud (US)

To scan your AWS Account in the GovCloud (US) partition (`aws-us-gov`):

- Using the `-f/--region` flag:
```
prowler aws --region us-gov-east-1 us-gov-west-1
```
- Using the region configured in your AWS profile at `~/.aws/credentials` or `~/.aws/config`:
```
[default]
aws_access_key_id = XXXXXXXXXXXXXXXXXXX
aws_secret_access_key = XXXXXXXXXXXXXXXXXXX
region = us-gov-east-1
```
> With this option all the partition regions will be scanned without the need of use the `-f/--region` flag


## AWS ISO (US & Europe)

For the AWS ISO partitions, which are known as "secret partitions" and are air-gapped from the internet there is no builtin way to scanned it. In this scenario if you want to audit an AWS Account in one of the AWS ISO partitions you should manually update the [aws_regions_by_service.json](https://github.com/prowler-cloud/prowler/blob/master/prowler/providers/aws/aws_regions_by_service.json) and include the partition, region and services, e.g.:
```json
"iam": {
    "regions": {
    "aws": [
        "eu-west-1",
        "us-east-1",
    ],
    "aws-cn": [
        "cn-north-1",
        "cn-northwest-1"
    ],
    "aws-us-gov": [
        "us-gov-east-1",
        "us-gov-west-1"
    ],
    "aws-iso": [
        "aws-iso-global",
        "us-iso-east-1",
        "us-iso-west-1"
    ],
    "aws-iso-b": [
        "aws-iso-b-global",
        "us-isob-east-1"
    ],
    "aws-iso-e": [],
    }
},
```

**Comment by ah-jota** [comment]
Yes this documentation looks great. Thank you @jfagoagas.
