### ISSUE TITLE
Please upload to AWS Public ECR

### ISSUE THREAD

**Issue by HarryBo112** [toniblyx/prowler#2354]
### New feature motivation

Older versions like 3.4.1 and also the "latest" image are avaiable on public aws ecr, but the 3.5.0 seems to be missing.

### Solution Proposed

upload to aws ecr

### Describe alternatives you've considered

none

**Comment by toniblyx** [comment]
Hi @HarryBo112 there was an issue with Github last week that affected their actions and our release, we are waiting for Github support to respond and that release will be complete, give us a couple of days to sort it out. Thank you!

**Comment by jfagoagas** [comment]
Hi @HarryBo112, now both `stable` and `3.5.0` are uploaded in the Public ECR at https://gallery.ecr.aws/prowler-cloud/prowler.

Thanks for using Prowler 🚀 

<img width="1717" alt="Screenshot 2023-05-16 at 11 01 58" src="https://github.com/prowler-cloud/prowler/assets/16007882/58a9ba92-9f38-4ea7-a8ac-336dc696b232">

**Comment by jfagoagas** [comment]
We've released a new `3.5.1` version with a hot fix. Thanks!
