### ISSUE TITLE
Enhance Prowler Detection for Overly Permissive Policies in Critical Services

### ISSUE THREAD

**Issue by be-lka** [toniblyx/prowler#2365]
### New feature motivation

1. While experimenting with Prowler, I provisioned the following Policy Document, which was later attached to a Role:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Statement01",
            "Effect": "Allow",
            "Action": [
                "s3:*",
                "ec2:*",
                "ecr:*",
                "rds:*",
                "dynamodb:*",
                "route53:*",
                "sns:*",
                "sqs:*"
            ],
            "Resource": "*"
        }
    ]
}
```
2. After running `prowler aws --excluded-services <EVERY_SERVICE_BUT_IAM>`, Prowler only detected `ec2:*` and `dynamodb:*` as problematic.

![Captura de Tela 2023-05-16 às 18 35 48](https://github.com/prowler-cloud/prowler/assets/50663919/27b054e6-db5c-4343-8fe4-153b575d29e6)

This policy is arguably close to full Administrative Access, considering that an attacker with access to this Policy would have control over critical services, potentially compromising the entire AWS Account. For example, the s3:* action could be used to exfiltrate data, and route53:* could be employed to manipulate multiple DNS records that may be mission-critical. I'd like to emphasize that none of these actions adhere to the least privilege principle, which is something a blue team should be aware of and address promptly.

### Solution Proposed

I'd like to propose the addition of the following services to the Prowler IAM Checks:
```
["s3:*", "ec2:*", "ecr:*", "rds:*", "dynamodb:*", "route53:*", "sns:*", "sqs:*", "*"]
```

### Describe alternatives you've considered

As an alternative, it would be possible to fork Prowler's repo and provision a local instance of it, adding more actions and checks but this would make us fall behind on updates and new cool features that the team might release.

**Comment by be-lka** [comment]
By the way, I think the solution to this is a simple add to this [variable](https://github.com/prowler-cloud/prowler/blob/f63ff994ce7267b8b9437face68e1a75774dcac2/prowler/providers/aws/services/iam/iam_policy_allows_privilege_escalation/iam_policy_allows_privilege_escalation.py#L20). I tried to contribute with a PR but got caught with a deny. 😅
```
remote: Permission to prowler-cloud/prowler.git denied to exiett.
fatal: unable to access 'https://github.com/prowler-cloud/prowler.git/': The requested URL returned error: 403
```

**Comment by jfagoagas** [comment]
Hi @exiett, you're right and currently we are not checking it but I don't think it makes sense to include that permissions in the [iam_policy_allows_privilege_escalation](https://github.com/prowler-cloud/prowler/tree/master/prowler/providers/aws/services/iam/iam_policy_allows_privilege_escalation) check.

We have two similar checks to review full access to CloudTrail and KMS:
- [iam_policy_no_full_access_to_cloudtrail](https://github.com/prowler-cloud/prowler/tree/master/prowler/providers/aws/services/iam/iam_policy_no_full_access_to_cloudtrail)
- [iam_policy_no_full_access_to_kms](https://github.com/prowler-cloud/prowler/tree/master/prowler/providers/aws/services/iam/iam_policy_no_full_access_to_kms)

Maybe makes more sense to create new checks to cover the most important AWS services.


Regarding your permissions issue, did you create a new [fork](https://docs.github.com/en/get-started/quickstart/fork-a-repo) of the Prowler repository? To contribute you should fork the repository and then create a new Pull Request.

Thanks for using Prowler 🚀

**Comment by jfagoagas** [comment]
Hi @exiett, we have fixed some issues in the `iam_policy_allows_privilege_escalation` check at this branch `PRWLR-1969-aws-iam-policy-allows-privilege-escalation-check-are-not-accurate-2220`.

What were the permissions you want to include there?

Thanks!

**Comment by jfagoagas** [comment]
Hi @exiett we are closing this issue since the `iam_policy_allows_privilege_escalation` check now detects a policy like the following as a `FAIL` since allows to privilege escalation.

```json
{
  "Version": "2012-10-17",
  "Statement": [
      {
        "Sid": "Statement01",
        "Effect": "Allow",
        "Action": [
            "s3:*",
            "ec2:*",
            "ecr:*",
            "iam:*",
            "rds:*",
            "dynamodb:*",
            "route53:*",
            "sns:*",
            "sqs:*",
        ],
        "Resource": "*",
    }
  ],
}
```

Please feel free to reopen the issue if you notice some issue or unexpected behaviour.

Thanks for using Prowler 🚀
