### ISSUE TITLE
Check ecr-repositories-lifecycle-policies-enabled is raising a FAIL with policies configured

### ISSUE THREAD

**Issue by jfagoagas** [toniblyx/prowler#2369]
### Discussed in https://github.com/prowler-cloud/prowler/discussions/2362

<div type='discussions-op-text'>

<sup>Originally posted by **NMuee** May 16, 2023</sup>
Hello Prowler team, 

I have a question on ECR scan 

In prowler 3.0, [Check if ECR repositories have lifecycle policies enabled]
I have ECR lifecycle policies set, however it is being flagged as FAILED in prowler 3.0, but PASS in prowler 2.0 [extra7194].

May need the team help to understand why, thank you. 
</div>

Logs: https://github.com/prowler-cloud/prowler/discussions/2362#discussioncomment-5912712

Screenshot: https://github.com/prowler-cloud/prowler/discussions/2362#discussioncomment-5923114

**Comment by sergargar** [comment]
Hi @NMuee, I cannot reproduce this issue. Our ECR Repositories are correctly check, can we see your case further in our Slack channel? Thanks.
