### ISSUE TITLE
GCP - run checks on all projects in organization

### ISSUE THREAD

**Issue by alon-u3d** [toniblyx/prowler#2380]
### New feature motivation

Seems like the only way to run checks on all projects inside an organization is to either create or modify the credentials file for each project.
I first thought I would be able to list projects, then for each project to use the "gcloud config set project" command (the core project).

Would appreciate if you can elaborate on this and explain what are the best practices in this scenario.
 

### Solution Proposed

I would suggest a solution similar to the -c flag that takes an array of checks, to have --project flag with an array of project ids, if the user / service account doesn't have the right permissions error would pop up.
Another suggestion is to have another environment variable for project_id. 

### Describe alternatives you've considered

Currently, seems like multiple credentials file or modification each iteration is the only solution, correct me if I am wrong.

**Comment by MrCloudSec** [comment]
Hi @alonmuallem, thank you for reaching us out!
You're right, the only solution right now is to sequentially execute Prowler for each credential file.
We've just included in our roadmap to have this feature, I'll let you know when we finish it.
