### ISSUE TITLE
[Bug]: Inspector shows all closed findings

### ISSUE THREAD

**Issue by ichasco-heytrade** [toniblyx/prowler#2394]
### Steps to Reproduce

Run Prowler with inspector service enabled

### Expected behavior

Show only active findings

### Actual Result with Screenshots or Logs

![image](https://github.com/prowler-cloud/prowler/assets/77392885/ed1ab4a0-8faf-4296-941a-d10df627c465)

![image](https://github.com/prowler-cloud/prowler/assets/77392885/0e85c3ae-95a6-4e83-81b9-d370a4813fc6)

### How did you install Prowler?

Docker (docker pull toniblyx/prowler)

### Environment Resource

Docker container only

### OS used

Alpine Linux

### Prowler version

Prowler 3.5.2 (it is the latest version, yay!)

### Pip version

pip 23.1.2 from /home/prowler/.local/lib/python3.9/site-packages/pip (python 3.9)

**Comment by MrCloudSec** [comment]
Hi @ichasco-heytrade, thanks for letting us know. It will be fixed in the next release.
