### ISSUE TITLE
[Bug]: Prowler 2 - Check 2.3 "No CloudTrail trails were found in the account" should be Info, not Critical

### ISSUE THREAD

**Issue by trigger1919** [toniblyx/prowler#2397]
### Steps to Reproduce

The **"No CloudTrail trails were found in the account"** finding in check 2.3 **should be Info, not Critical**. Similarly to https://github.com/prowler-cloud/prowler/issues/971 "Check 2.3 Bucket - Access Denied assumes set bucket to public".

### Expected behavior

Change the code:
`textFail "$REGION: No CloudTrail trails were found in the account" "$REGION" "$trail"`
to
`textInfo "$REGION: No CloudTrail trails were found in the account" "$REGION" "$trail"`

### Actual Result with Screenshots or Logs

'No CloudTrail trails were found in the account' raised a Critical Issue.

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

--

### OS used

--

### Prowler version

2

### Pip version

--

**Comment by n4ch04** [comment]
Hi @trigger1919,

Can you please use Prowler v3? All the fixes and new features are included in that version.
Also the check ensures that at least exist one trail per region in the account, if there are no trails the checks returns FAIL.

Thanks for using Prowler !!

**Comment by trigger1919** [comment]
Hello,

is version 2 still supported? Does it make sense to file other bugs to version 2 or no changes to version 2 will be made?

**Comment by trigger1919** [comment]
If S3 CloudTrail does not exist, then it cannot be publicly available. In that sense "No CloudTrail trails were found in the account" should not be in this check as it may confuse security analysts, and all Prowler's scan results may be questioned and perceived with low confidence. There should be another check ensuring the existence of S3 CloudTrails.

**Comment by toniblyx** [comment]
Hi @trigger1919, thanks for let us know. That is the behavior of that check in that point in time. You can always change the severity by editing the check file in v2 or even in v3 (if you decide to use it as we recomend). Unless there is a critical bug in v2 we don´t plan to make any change or new fixes in that major version.

**Comment by n4ch04** [comment]
Hi @trigger1919, I understand your point, in the version 3 in that check those cases are well handled.
We encourage you to take a look at the new version, we can promise that you won't regret it
