### ISSUE TITLE
[Bug]: Cannot render big HTML file

### ISSUE THREAD

**Issue by blaargh** [toniblyx/prowler#2404]
### Steps to Reproduce

Running prowler against many resources (in my case it's ~350), the generated HTML cannot be displayed correclty due to the JavaScript error shown in the screenshot.

### Expected behavior

The HTML can render without any errors.

### Actual Result with Screenshots or Logs

![image](https://github.com/prowler-cloud/prowler/assets/49124793/23916da8-6044-4bb3-87ee-79a36284ef8b)

This might be due to the fact that there are actually THREE jquery calls that initialize the table

`$('#findingsTable').DataTable({ *..* })`

### How did you install Prowler?

Docker (docker pull toniblyx/prowler)

### Environment Resource

Kubernetes Cluster

### OS used

Ubuntu Linux

### Prowler version

Version: 3.5.2

### Pip version

pip 23.1 from /home/prowler/.local/lib/python3.9/site-packages/pip (python 3.9)

**Comment by christiandavilakoobin** [comment]
That's strange. I have an HTML with 1302 resources and it opens instantly.

**Comment by jfagoagas** [comment]
Hi @blaargh, are you still experiencing this issue?

I've created an HTML with 1733 and there is no issue when rendering it.
<img width="1727" alt="Screenshot 2023-07-24 at 16 26 25" src="https://github.com/prowler-cloud/prowler/assets/16007882/e84539ce-ff8d-4aeb-a7eb-c68f43d8c55e">

**Comment by jfagoagas** [comment]
I'm closing this issue since we cannot reproduce it with the latest version of Prowler.

Please feel free to reopen it if you notice the same behaviour again.

Thanks for using Prowler 🚀
