### ISSUE TITLE
Improve Allowlist exceptions

### ISSUE THREAD

**Issue by zfLQ2qx2** [toniblyx/prowler#2412]
### New feature motivation

One of the long time issues I've had with Prowler is that we use AWS Organizations in our environment so some services, particularly Cloudtrail, are actually enabled at the organization level so I want to ignore a lot of the per-account AWS-CIS checks because all of the cloudtrails, metric filters, etc. are configured and received in our organization master account. However I do want the Prowler checks to run on the organization master account in case they are ever disabled or misconfigured.

The Allowlist functionality allows me to ignore the checks in all of the accounts, however there is no ability to omit the master account from that allowlist entry short of creating an entry for every account that isn't the master - which doesn't scale well when you have > 100 AWS accounts.

### Solution Proposed

I wrote my own report generator that filters the Json output from Prowler. I duplicated the Allowlist functionality in Prowler and then I added exceptions - the internal structure (in Golang) looks like this:

```
type Check struct {
        Regions          []string           `yaml:"Regions"`
        Resources        []*regexp.Regexp   `yaml:"-"`
        Tags             [][]*regexp.Regexp `yaml:"-"`
        ResourcePatterns []string           `yaml:"Resources"`
        TagPatterns      []string           `yaml:"Tags,omitempty"`
        Exceptions       struct {
                AccountIDs       []string           `yaml:"AccountIDs,omitempty"`
                Regions          []string           `yaml:"Regions,omitempty"`
                Resources        []*regexp.Regexp   `yaml:"-"`
                Tags             [][]*regexp.Regexp `yaml:"-"`
                ResourcePatterns []string           `yaml:"Resources"`
                TagPatterns      []string           `yaml:"Tags,omitempty"`
        } `yaml:"Exceptions,omitempty"`
}
```
The corresponding yaml looks like this:

```
        'cloudtrail_s3_dataevents_write_enabled':
          Regions:
            - '*'
          Resources:
            - '*'
          Exceptions:
            AccountIDs:
              - 'ORG_MASTER_ACCOUT_ID'
            Regions:
              - '*'
            Resources:
              - '*'
```

If I find a result with a matching allowlist entry, then I look to see if any of the exceptions negate the match. The logic of the exceptions works exactly like the logic of the Allowlist except I allow a list of account IDs (including the wildcard). For future proofing I might go back and allow an Array of Exceptions.

### Describe alternatives you've considered

I wanted to keep to the spirit and feel of what Prowler has today so I based my solution on that concept. If I hire someone who is already familiar with Prowler the allowlist should seem familiar except for the additional exception logic.

### Additional context

Feel free to use the idea! Always been a big Prowler fan, I used to contribute code to v2 and agreed to all the terms, but I don't know Python well enough to contribute code to v3.

**Comment by toniblyx** [comment]
hey @zfLQ2qx2 nice to see your ideas and recommendations! We will work on it, makes a lot of sense.

**Comment by zfLQ2qx2** [comment]
@toniblyx One other change I ended up making is that if Resource or Regions is omitted in the yaml then its an implicit "*". This reduced the size of my allowlist by about two thirds because almost every check I was disabling for every region and resource to which it applied.

**Comment by MrCloudSec** [comment]
Great ideas @zfLQ2qx2 , thanks!
We will include them in the allowlist logic.

**Comment by MrCloudSec** [comment]
@zfLQ2qx2 we've just included the exceptions in the allowlist as you mentioned. Thanks again for the feedback!
