### ISSUE TITLE
[Bug]: False positive on efs_not_publicly_accessible

### ISSUE THREAD

**Issue by kenske** [toniblyx/prowler#2431]
### Steps to Reproduce

Running on single AWS account:
```
prowler --checks efs_not_publicly_accessible --verbose
```

### Expected behavior

No findings

### Actual Result with Screenshots or Logs

```
Executing 1 check, please wait...


Check ID: efs_not_publicly_accessible - efs [critical]
	FAIL us-east-1: EFS fs-abc123 doesn't have any policy which means it grants full access to any client
```

### How did you install Prowler?

Docker (docker pull toniblyx/prowler)

### Environment Resource

Pod running in EKS 

### OS used

Amazon Linux 2

### Prowler version

3.5.3

### Pip version

23.1.2

### Context

If I run the aws cli for the failed EFS  resource I get the policy as expected:

```
$ aws efs describe-file-system-policy --file-system-id fs-abc123
{
    "FileSystemId": "fs-abc123",
    "Policy": "{\n  \"Version\" : \"2012-10-17\",\n  \"Statement\" : [ {\n  <redacted>  ]\n}"
}
```

**Comment by jfagoagas** [comment]
Hi @kenske, how are you?

I'm trying to reproduce your issue but I'm not being able to, could you please share the policy present in your EFS?

This is the scenario where I'm testing the issue, please modify it to mimic your environment and I could test it again.

EFS Policy:
```
{
    "Version": "2012-10-17",
    "Id": "efs-policy-wizard-44f078aa-4fc7-42ac-989d-6bc6a35dc635",
    "Statement": [
        {
            "Sid": "efs-statement-40e8d185-6847-4a57-a2e0-35ceb3a928e2",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::111111111111:root"
            },
            "Action": "",
            "Resource": "arn:aws:elasticfilesystem:eu-west-1:111111111111:file-system/fs-060254d4ca4928555"
        }
    ]
}
```

And the following is the Prowler output with a PASS:
<details open>
<summary>Prowler Output</summary>

<code>
./prowler.py --checks efs_not_publicly_accessible --region eu-west-1 --verbose --profile dev --resource-arn arn:aws:elasticfilesystem:eu-west-1:111111111111:file-system/fs-060254d4ca4928555
                         _
 _ __  _ __ _____      _| | ___ _ __
| '_ \| '__/ _ \ \ /\ / / |/ _ \ '__|
| |_) | | | (_) \ V  V /| |  __/ |
| .__/|_|  \___/ \_/\_/ |_|\___|_|v3.5.3
|_| the handy cloud security tool

Date: 2023-06-06 13:36:50


Color code for results:
- INFO (Information)
- PASS (Recommended value)
- WARNING (Ignored by allowlist)
- FAIL (Fix required)
            

This report is being generated using credentials below:

AWS-CLI Profile: [dev] AWS Filter Region: [eu-west-1]
AWS Account: [111111111111] UserId: [XXXXXXXXXXXXX]
Caller Identity ARN: [arn:aws:sts::111111111111:XXXXXXXXXXXXX]

Executing 1 check, please wait...

Check ID: efs_not_publicly_accessible - efs [critical]
        PASS eu-west-1: EFS fs-060254d4ca4928555 has a policy which does not allow access to everyone

-> Scan completed! |▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉| 1/1 [100%] in 0.7s 

Overview Results:
╭─────────────────┬───────────────────╮
│ 0.0% (0) Failed │ 100.0% (1) Passed │
╰─────────────────┴───────────────────╯

Account 106908755756 Scan Results (severity columns are for fails only):
╭────────────┬───────────┬──────────┬────────────┬────────┬──────────┬───────╮
│ Provider   │ Service   │ Status   │   Critical │   High │   Medium │   Low │
├────────────┼───────────┼──────────┼────────────┼────────┼──────────┼───────┤
│ aws        │ efs       │ PASS (1) │          0 │      0 │        0 │     0 │
╰────────────┴───────────┴──────────┴────────────┴────────┴──────────┴───────╯
* You only see here those services that contains resources.

Detailed results are in:
 - HTML: /output/prowler-output-111111111111-20230606133650.html
 - CSV: /output/prowler-output-111111111111-20230606133650.csv
 - JSON: /output/prowler-output-111111111111-20230606133650.json
</code>
</details>

Thanks for using Prowler 🚀

**Comment by kenske** [comment]
@jfagoagas thanks, here is the policy I'm using:

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::<redacted>:role/<redacted>"
            },
            "Action": [
                "elasticfilesystem:ClientWrite",
                "elasticfilesystem:ClientRootAccess",
                "elasticfilesystem:ClientMount"
            ],
            "Resource": "arn:aws:elasticfilesystem:us-east-1:<redacted>:file-system/fs-<redacted>",
            "Condition": {
                "Bool": {
                    "elasticfilesystem:AccessedViaMountTarget": "true"
                }
            }
        },
        {
            "Sid": "",
            "Effect": "Allow",
            "Principal": {
                "AWS": "arn:aws:iam::<redacted>:role/<redacted>"
            },
            "Action": "elasticfilesystem:TagResource",
            "Resource": "arn:aws:elasticfilesystem:us-east-1:<redacted>:file-system/fs-<redacted>"
        }
    ]
}
```

**Comment by jfagoagas** [comment]
HI @kenske, I've pasted your policy into my testing EFS and Prowler raises a PASS.

As you can see in the following images I can't reproduce it.
![Screenshot 2023-06-06 at 17 12 00](https://github.com/prowler-cloud/prowler/assets/16007882/979fe779-dabd-411b-a669-7c8f6c070ad7)
![Screenshot 2023-06-06 at 17 17 12](https://github.com/prowler-cloud/prowler/assets/16007882/3bb4a4d1-8262-4015-9a2f-8e8b389f4784)


Are you using the latest version of Prowler?

If you can, please join our Slack https://join.slack.com/t/prowler-workspace/shared_invite/zt-1whii3rzb-QqMuv0XMums9QO5K~m7h1w to talk about this issue. Open a conversation with @sergargar and @n4ch04 too.

Thanks!

**Comment by kenske** [comment]
Thanks @jfagoagas , I figured it out

I was missing the `elasticfilesystem:DescribeFileSystemPolicy` permission for the prowler role. I was able to see the error when I set the log level to `DEBUG`. It would be helpful if prowler surfaced those kinds of errors by default.
