### ISSUE TITLE
[Bug]: Prowler gets stuck at 82th check

### ISSUE THREAD

**Issue by dmdhrumilmistry** [toniblyx/prowler#2433]
### Steps to Reproduce

1. Start AWS ec2 instance (free tier) with ubuntu distro and ReadOnlyAccess Policy
2. SSH into the machine
3. Installed prowler using pip
4. Start prowler

```bash
prowler aws
```

### Expected behavior

Should run checks and generate output

### Actual Result with Screenshots or Logs

![image](https://github.com/prowler-cloud/prowler/assets/56185972/f61eb170-9544-433c-9135-57f318ee760f)

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

EC2

### OS used

Ubuntu

### Prowler version

Prowler 3.5.3 (it is the latest version, yay!)

### Pip version

pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)

**Comment by jfagoagas** [comment]
Hi @dmdhrumilmistry, could you please execute Prowler again but using the `--log-level ERROR` flag and paste the output here?

Also I see that there are two  `^C` (`ctrl + C`) to the right of the progress bar? Do you know if something on your side could be triggering that?

Thanks for using Prowler 🚀

**Comment by dmdhrumilmistry** [comment]
@jfagoagas yes, I tried stopping the program. Could it be issues with resources? I'm running it on t2.micro instance.

Will update this comment soon with logs.

**Comment by jfagoagas** [comment]
> @jfagoagas yes, I tried stopping the program. Could it be issues with resources? I'm running it on t2.micro instance.
> 
> Will update this comment soon with logs.

Yes, it could be related with your workstation specifications. Please, execute Prowler with `--log-level ERROR` flag and paste the output here.

**Comment by dmdhrumilmistry** [comment]
> > @jfagoagas yes, I tried stopping the program. Could it be issues with resources? I'm running it on t2.micro instance.
> > Will update this comment soon with logs.
> 
> Yes, it could be related with your workstation specifications. Please, execute Prowler with `--log-level ERROR` flag and paste the output here.

Yes, issue was with my ec2 instance. I was using t2.micro with IAM role attached to run prowler. I increased it to t3.medium and it was working fine. 

Is there any way to limit resources cpu/ram/threads so I can work with t2.micro as well?

**Comment by jfagoagas** [comment]
Hi @dmdhrumilmistry, we don't have any minimum specification to run Prowler since it depends on the number of resources you have in your cloud provider.

The most common case is to have 1 vCPU and 2 GiB RAM.

Thanks for using Prowler 🚀
