### ISSUE TITLE
[Bug]: Prowler3 spends hours in "awslambda_function_no_secrets_in_code" check

### ISSUE THREAD

**Issue by zfLQ2qx2** [toniblyx/prowler#2435]
### Steps to Reproduce

```
prowler aws \
  --role ${ROLEARN} \
  --verbose \
  --output-modes json \
  --checks awslambda_function_no_secrets_in_code \
  --log-level DEBUG \
  --session-duration 3600
```

This one is really tough to debug because I can't tell what it is doing when it hangs, it does a GetFunctionUrlConfig for each function in the account, then the last line in the debug output is:

```
2023-06-02 19:48:54,974 [File: check.py:396] 	[Module: check]	 DEBUG: Executing check: awslambda_function_no_secrets_in_code
```

And there is no output after that line. 

### Expected behavior

The check should complete at some point

### Actual Result with Screenshots or Logs

I can provide logs in private if needed but I think there needs to be additional debug logging added so we can see what is happening where the hang occurs.

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

Fargate Task

### OS used

Alpine Linux

### Prowler version

Prowler 3.5.3 (it is the latest version, yay!)

### Pip version

pip 22.3.1 from /opt/prowler/lib/python3.11/site-packages/pip (python 3.11)

**Comment by n4ch04** [comment]
Hi @zfLQ2qx2 we will check this and let you know.
Since that check downloads the lambda code in order to launch `detect-secrets` tool over it, it is likely due to the scanning over a large number of lambda functions.
To verify the check is working properly, can you launch it against a single lambda (you can specify it  with `--resource-arn`)?

**Comment by zfLQ2qx2** [comment]
@n4ch04 I tried adding the resource parameter, I tried to copy the ARN from the AWS Console lambda GUI, but I'm getting this error for every one I tried:

prowler aws: error: argument --resource-arn: invalid arn_type value: 'arn:aws:lambda:us-east-1:nnnnnnnnnn:function:function-name'

I'm not sure what it is looking for, I couldn't find any other format for lambda ARNs.

**Comment by n4ch04** [comment]
@zfLQ2qx2 It happens the same to me, I'll fix this parsing error and we can continue working on the lambda check issue

**Comment by n4ch04** [comment]
It is solved here https://github.com/prowler-cloud/prowler/pull/2471 can you try again @zfLQ2qx2 ?

**Comment by zfLQ2qx2** [comment]
@n4ch04 Good news! I rebuilt with your fix discovered that of the ~100 lambda functions in the account, there are just a dozen of them that stall out the detect secrets check. All of the lambdas are basically nodejs wrappers for ffmpeg which pull a file from S3, do some sort of analysis or transformation, then write the result back to S3. The heavy lifting is done by an ffmpeg binary executable which is included in the lambda payload. So the root issue might be that detect secrets is expecting text and getting a binary blob instead. Are there any known issues around that?

**Comment by n4ch04** [comment]
@zfLQ2qx2 It is the first time we face this.
Right now we do not have a flag to exclude resources, in this kind of cases we recommend to exclude the check from the general executions with the flag `--exclude-checks`

**Comment by zfLQ2qx2** [comment]
@n4ch04 Thats what I'm doing for now. Maybe a fix could be to do something like file command to exclude binary files, or doing a quick check of the first N bytes for valid utf or something.

**Comment by n4ch04** [comment]
Hi @zfLQ2qx2 I've spending a little bit of time inspecting how can we identify binary files prior launching the `detect-secrets` tool, and it does not seem to be an easy and reliable way to do it.
Until we find a valid workaround we'll leave as it is.

Thanks for using Prowler !!
