### ISSUE TITLE
[Bug]: Can't run prowler cronjob in kubernetes cluster

### ISSUE THREAD

**Issue by dudeja2-iresh2** [toniblyx/prowler#2463]
### Steps to Reproduce

1. Create a namespace.
2. Create a secret with required values as mentioned [here](https://github.com/prowler-cloud/prowler/blob/master/contrib/k8s/secret.yml).
3. Create a cronjob as mentioned [here](https://github.com/prowler-cloud/prowler/blob/master/contrib/k8s/cronjob.yml).
4. Run the job manually.

### Expected behavior

Job should run successfully.

### Actual Result with Screenshots or Logs

`Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "./prowler.py": stat ./prowler.py: no such file or directory: unknown`

### How did you install Prowler?

Docker (docker pull toniblyx/prowler)

### Environment Resource

Kubernetes Cluster (kops)

### OS used

Flatcar Container Linux

### Prowler version

3.5.3

### Pip version

Using pip version defined in docker image

**Comment by christiandavilakoobin** [comment]
Hi there,

Try to create the cronjob task with absolute path. Crontab runs on user home directoy by default, so "./prowler.py" may be not there.

**Comment by jfagoagas** [comment]
Hi @dudeja2-iresh2, as @christiandavilakoobin it seems to be an issue related with your execution `PATH`. Please check where is Prowler installed in your system and the use that path in your cronjob.

I'm going to close the issue. Please fell free to reopen it if encounter any more problems.

**Comment by dudeja2-iresh2** [comment]
Thanks for your replies.  @christiandavilakoobin @jfagoagas 

I was able to make it work after making changes in the _spec.containers.command_, also added _securityContext.runAsUser: 1000_ and _volumes_. 

I would like to know if the example mentioned [here](https://github.com/prowler-cloud/prowler/tree/master/contrib/k8s) is the working example?

**Comment by christiandavilakoobin** [comment]
I wasn't using k8s, but docker, using this:

```
docker run --user 0 --rm -ti -v $(pwd)/prowler/config.yaml:/home/prowler/.local/lib/python3.9/site-packages/prowler/config/config.yaml -v $(pwd)/prowler/results/:/home/prowler/output $(printf -- "--env AWS_ACCESS_KEY_ID=%s --env AWS_SECRET_ACCESS_KEY=%s --env AWS_SESSION_TOKEN=%s" $(aws sts assume-role --role-arn arn:aws:iam::xxxxxxx:role/global-prowler-ProwlerRole--role-session-name prowler --query 'Credentials.[ AccessKeyId, SecretAccessKey, SessionToken ]' --output text)) public.ecr.aws/o4g1s5r6/prowler:3.7.1 aws -M csv json json-asff html -w arn:aws:lambda:eu-west-1:xxxxxx:function:global-prowler-AllowList -f eu-west-1 us-east-1 --compliance ens_rd2022_aws
```
