### ISSUE TITLE
Bug: Prowler .csv header question re: ";COMPLIANCE;CATEGORIES;"

### ISSUE THREAD

**Issue by jfagoagas** [toniblyx/prowler#2475]
### Discussed in https://github.com/prowler-cloud/prowler/discussions/2473

<div type='discussions-op-text'>

<sup>Originally posted by **edschreibman** June  9, 2023</sup>
Running v3.5.3;
" prowler -M csv   --verbose"
Noticed the .csv header results in 38 fields, was expecting 37.
Looking at the header, should ";COMPLIANCE;CATEGORIES;"  be ";COMPLIANCE_CATEGORIES;"  ?   
It looks like it is creating a new column in error. 
</div>

**Comment by MrCloudSec** [comment]
Hi @edschreibman, the Compliance and Categories columns are two different attributes:

The Compliance column contains all the compliance's requirements applicable to each finding
The Category column contains the categories applicable to the finding that can be seen in each check's metadata.
