### ISSUE TITLE
[Bug]: shield_advanced_protection_in_route53_hosted_zones arn comparison fails

### ISSUE THREAD

**Issue by dlouzan** [toniblyx/prowler#2490]
### Steps to Reproduce

Recently prowler seems to have enabled by default the AWS well-architected framework with more tests. Our prowler pipelines started failing when testing AWS Shield Advanced resources on Route53 Hosted Zones.

AWS Shield resources are created on our end via Terraform using the AWS provider with something like:

```terraform
resource "aws_shield_protection" "some-dns-protection" {
  name         = "Some Name"
  resource_arn = "arn:aws:route53:::hostedzone/<hosted_zone_id>"
}
```

Terraform will NOT allow us to provide a resource without the `hostedzone/` prefix. I'm not sure if this is correct or not, but in the created resource, the AWS UI shows the resource correctly and linked to the appropriate Route53 zone resource.

We have tracked the prowler check failure to comparisons done on `shield_advanced_protection_in_route53_hosted_zones.py`, and adding some debug statements to the code show that this line:

```python
if hosted_zone.arn == protection.resource_arn:
```

is comparing resources returned by the `route53_client` as `arn:aws:route53:::<hosted_zone_id>`, while `protection.resource_arn` is using a format such as `arn:aws:route53:::hostedzone/<hosted_zone_id>` including the `hostedzone/` prefix, which never fulfills the comparison.

### Expected behavior

Passed check

### Actual Result with Screenshots or Logs

Failed check:

```
╭────────────┬───────────┬───────────┬────────────┬────────┬──────────┬───────╮
│ Provider   │ Service   │ Status    │   Critical │   High │   Medium │   Low │
├────────────┼───────────┼───────────┼────────────┼────────┼──────────┼───────┤
│ aws        │ shield    │ FAIL (10) │          0 │      0 │       10 │     0 │
╰────────────┴───────────┴───────────┴────────────┴────────┴──────────┴───────╯
```

### How did you install Prowler?

Docker (docker pull toniblyx/prowler)

### Environment Resource

gitlab-ci

### OS used

official docker image

### Prowler version

3.5.3 (also tested 3.6.0)

### Pip version

not applicable

**Comment by dlouzan** [comment]
Additionally: the checks seem to run unconditionally also on private hosted zones, which I'm not sure is correct either, but here I'd be happy to stand corrected. In theory they should be ignored?

**Comment by MrCloudSec** [comment]
Hi @dlouzan, thank you for reaching us out! You're totally right, the problem is that we are creating a wrong Hosted Zone ARN. Can you try the PR above to see if that solves it?

**Comment by MrCloudSec** [comment]
As far as I know you can create Shield Advanced protections to all R53 hosted zones either if they are public or private, correct me if I'm wrong.

**Comment by jfagoagas** [comment]
@sergargar is this issue related with the latest comment in this discussion https://github.com/prowler-cloud/prowler/discussions/2408? If so, please link them together. Thanks!

**Comment by dlouzan** [comment]
@sergargar Thanks for the quick reaction! I have just given a try with latest master, and this works now :thumbsup:
