### ISSUE TITLE
[Bug]: Unable to push findings to Security Hub when Recommendation Url is blank.

### ISSUE THREAD

**Issue by ckdake** [toniblyx/prowler#2492]
### Steps to Reproduce

We're running prowler against aws, reporting into Security Hub using asff.  Any similar setup should produce this same outcome, as long as all default checks are used. 

The first check in my output I see with this failure is `prowler-backup_reportplans_exist`.  Security Hub rejects this finding due to the Remediation Recommendation Url being blank.

### Expected behavior

All Prowler findings are successfully reported to Security Hub.

ALSO, it's expected that Security Hub will accept a finding with a blank Url, per their documentation: https://docs.aws.amazon.com/securityhub/1.0/APIReference/API_Recommendation.html

Manually adding a URL to the finding gets Security Hub to accept the finding, so their documentation is likely incorrect.

### Actual Result with Screenshots or Logs

Sample finding:

```json
{
    "SchemaVersion": "2018-10-08",
    "Id": "prowler-backup_reportplans_exist-[FILTERED}",
    "ProductArn": "arn:aws:securityhub:us-east-1::product/prowler/prowler",
    "RecordState": "ACTIVE",
    "ProductFields": {
        "ProviderName": "Prowler",
        "ProviderVersion": "3.6.0",
        "ProwlerResourceName": "arn:aws:iam::[FILTERED]:root"
    },
    "GeneratorId": "prowler-backup_reportplans_exist",
    "AwsAccountId": "[FILTERED]",
    "Types": [
        "Recover",
        "Resilience",
        "Backup"
    ],
    "FirstObservedAt": "2023-06-14T16:54:10Z",
    "UpdatedAt": "2023-06-14T16:54:10Z",
    "CreatedAt": "2023-06-14T16:54:10Z",
    "Severity": {
        "Label": "LOW"
    },
    "Title": "Ensure that there is at least one AWS Backup report plan",
    "Description": "No Backup Report Plan Exist",
    "Resources": [
        {
            "Type": "Other",
            "Id": "arn:aws:iam::[FILTERED]:root",
            "Partition": "aws",
            "Region": "us-east-1"
        }
    ],
    "Compliance": {
        "Status": "FAILED",
        "RelatedRequirements": [],
        "AssociatedStandards": []
    },
    "Remediation": {
        "Recommendation": {
            "Text": "Use AWS Backup to create backup report plans that provide visibility into the success or failure of backup operations.",
            "Url": ""
        }
    }
}
```

Sample log output:
```2023-06-14 16:58:02,313 [File: security_hub.py:50] 	[Module: security_hub]	 ERROR: Failed to send archived findings to AWS Security Hub -- InvalidInput -- Finding does not adhere to Amazon Finding Format. data.Remediation.Recommendation.Url should NOT be shorter than 1 characters, data.Remediation.Recommendation.Url should match format "uri".```

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

Fargate Task (on ECS)

### OS used

Wolfi via Chainguard docker images

### Prowler version

Prowler 3.6.0

### Pip version

pip 23.1.2

### Context

Populating the Url anywhere it is not populated may do the trick, there may be good URLs for checks that are missing URLs, or `https://` may be enough?

**Comment by MrCloudSec** [comment]
Hi @ckdake, thank you for letting us know!
I think the best idea is to set a default URL when it is empty, such us https://docs.aws.amazon.com/securityhub/latest/userguide/what-is-securityhub.html

We will fill all checks' Recommendation URLs in the future.

**Comment by ckdake** [comment]
Sounds good to me! Thanks for the quick fix.
