### ISSUE TITLE
Ability to match security groups by name

### ISSUE THREAD

**Issue by zfLQ2qx2** [toniblyx/prowler#2493]
### New feature motivation

Security groups are identified in prowler primarily by their sg-xxxxxxxxxx identifier - the only place I see the name being used is in the extended status. The sg identifiers by themselves don't mean anything and requires someone to look them up by name when maintaining allowlists or other mechanisms.

### Solution Proposed

My proposed solution would be to make the security group name available as an additional resource identifier or maybe a virtual Name tag so that we can match against it with regex.

### Describe alternatives you've considered

In the mean time I have a script I can run which generates a list of sg identifiers for groups matching a list of regex patterns.

**Comment by MrCloudSec** [comment]
Hi @zfLQ2qx2, good idea! 
What we can do is leaving the SG ID as resource_details and setting the SG Name as resource_id.

**Comment by pr3l14t0r** [comment]
Heyho! @sergargar ! I was looking for exactly this. How exactly does it work now? I still get the `sg-12345678` written into `RESOURCE_ID` and the name of the group into `RESOURCE_DETAILS` . Thus, i still can't use a `RESOURCE` filter in my mutelist.yaml file based on the security group's name... or am i having a mistake somewhere?

**Comment by jfagoagas** [comment]
> Heyho! @sergargar ! I was looking for exactly this. How exactly does it work now? I still get the `sg-12345678` written into `RESOURCE_ID` and the name of the group into `RESOURCE_DETAILS` . Thus, i still can't use a `RESOURCE` filter in my mutelist.yaml file based on the security group's name... or am i having a mistake somewhere?

Hello @pr3l14t0r, as of today the Mutelist only supports the values of the `resource_id`, the Security Group name is only included into the `resource_details` field to help users do the lookup faster. Maybe we can include a new feature in the allowlist to match either by `resource_id` or `resource_details`, but we'll need to discuss it internally.
