### ISSUE TITLE
[Bug]: Prowler ignores region filter & tries to send findings to AWS Security Hub in us-east-1 

### ISSUE THREAD

**Issue by jbro-tp** [toniblyx/prowler#2499]
### Steps to Reproduce

1. Running the following command ./prowler/prowler -R "$ROLE" -A "$accountId" -M json-asff -q -S -f "$REGION" > /dev/null which is part of this shell script https://github.com/prowler-cloud/prowler/blob/master/contrib/multi-account-securityhub/run-prowler-securityhub.sh
2.  I have tried hardcoding the region to eu-west-1 and it still tries to send its output to us-east-1

### Expected behavior

Prowler should send its findings to the region which has been specified (in this case eu-west-1).

### Actual Result with Screenshots or Logs

Log output from th ECS Task.

An error occurred (AccessDeniedException) when calling the BatchImportFindings operation: User: arn:aws:sts::*:assumed-role/*/ProwlerAssessmentSession is not authorized to perform: securityhub:BatchImportFindings on resource: arn:aws:securityhub:us-east-1::product/prowler/prowler

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

1. Fargate Task

### OS used

1. MacOS

### Prowler version

2.9.0

### Pip version

3

**Comment by jfagoagas** [comment]
Hi @jonathanbro, the latest version of Prowler is the 3.6.1. 

Could you please execute that version and let us know if this issue still persists?

Prowler was fully rewritten in Python several months ago and I recommend you to start using it. It's way faster and efficient than the v2 and we've included a lot of improvements as well as bug fixes.

You can know more about v3 at https://docs.prowler.cloud

Thanks for using Prowler 🚀

**Comment by jbro-tp** [comment]
Hi @jfagoagas I have changed the version to 3.6.1 and the error just changes "line 8: ./prowler/prowler: Is a directory"
which is here https://github.com/prowler-cloud/prowler/blob/d82d1abab609d0ddb2a7869ca02a2210d2b84965/contrib/multi-account-securityhub/run-prowler-securityhub.sh#L8

**Comment by jfagoagas** [comment]
This script needs to be updated to run with Prowler v3. We will update it and let you know to check it again.

Thanks!

**Comment by MrCloudSec** [comment]
Hi @jonathanbro, can you try the script from the above PR? Thanks.

**Comment by jbro-tp** [comment]
Hi @sergargar if I updated this Dockerfile https://github.com/prowler-cloud/prowler/blob/master/contrib/multi-account-securityhub/Dockerfile `ARG PROWLERVER=3.6.1 ` and the script.  I am getting the following errors in my ECS Task.



6/20/2023, 8:12:50 AM GMT+1 | Traceback (most recent call last): | security-prowler
-- | -- | --
6/20/2023, 8:12:50 AM GMT+1 | File "//./prowler/prowler.py", line 5, in <module> | security-prowler
6/20/2023, 8:12:50 AM GMT+1 | from prowler.__main__ import prowler | security-prowler
6/20/2023, 8:12:50 AM GMT+1 | File "/prowler/prowler/__main__.py", line 7, in <module> | security-prowler
6/20/2023, 8:12:50 AM GMT+1 | from prowler.lib.banner import print_banner | security-prowler
6/20/2023, 8:12:50 AM GMT+1 | File "/prowler/prowler/lib/banner.py", line 1, in <module> | security-prowler
6/20/2023, 8:12:50 AM GMT+1 | from colorama import Fore, Style | security-prowler
6/20/2023, 8:12:50 AM GMT+1 | ModuleNotFoundError: No module named 'colorama'

**Comment by jfagoagas** [comment]
Hi @jonathanbro, this Dockerfile is not updated for Prowler v3. We will update it soon.

**Comment by jbro-tp** [comment]
Thanks @jfagoagas

**Comment by jfagoagas** [comment]
Hi @jonathanbro, could you please test it again using the branch `2499-bug-prowler-ignores-region-filter-tries-to-send-findings-to-aws-security-hub-in-us-east-1`. We've updated the Dockerfile and the script too to run with Prowler v3.
