### ISSUE TITLE
[Bug]: prowler attempting to post some findings to Security Hub in us-east-1 when not configured to use us-east-1

### ISSUE THREAD

**Issue by ckdake** [toniblyx/prowler#2518]
### Steps to Reproduce

Run prowler against AWS with resources in us-east-2 and us-west-2. Ensure AWS has Security Hub enabled in these regions for recording errors. Ensure that us-east-1 has Security Hub disabled, since we don't have resources there and aren't explicitly scanning it.

```bash
prowler aws --region us-east-2 us-west-2 \
    --allowlist-file allowlist.yaml \
    --output-modes json json-asff \
    --log-level WARNING \
    --security-hub \
    --excluded-checks ec2_elastic_ip_shodan
```

### Expected behavior

Prowler should run and do it's thing with the configured regions. 

### Actual Result with Screenshots or Logs

It runs and does it's things in configured regions, but is also attempting to do some things with us-east-1 even though us-east-1 is not configured.

![Screenshot 2023-06-20 at 10 54 14 AM](https://github.com/prowler-cloud/prowler/assets/87742/e9463fd2-056c-4494-b758-6625a98e5c03)

Outputs this as part of it's run:

```
2023-06-20 14:49:58,602 [File: security_hub.py:55]      [Module: security_hub]   ERROR: InvalidAccessException -- [34]:An error occurred (InvalidAccessException) when calling the DescribeHub operation: Account 047154925365 is not subscribed to AWS Security Hub in region us-east-1
```

These appear to be the checks failing to record due to Security Hub not being enabled on us-east-1:

```
    "Id": "prowler-account_maintain_current_contact_details-${ACCOUNT_ID}-us-east-1-${ID}",
    "Id": "prowler-account_security_contact_information_is_registered-${ACCOUNT_ID}-us-east-1-${ID}",
    "Id": "prowler-account_security_questions_are_registered_in_the_aws_account-${ACCOUNT_ID}-us-east-1-${ID}",
    "Id": "prowler-backup_reportplans_exist-${ACCOUNT_ID}-us-east-1-${ID}",
    "Id": "prowler-cloudtrail_s3_dataevents_read_enabled-${ACCOUNT_ID}-us-east-1-${ID}",
    "Id": "prowler-cloudtrail_s3_dataevents_write_enabled-${ACCOUNT_ID}-us-east-1-${ID}",
    "Id": "prowler-ssmincidents_enabled_with_plans-${ACCOUNT_ID}-us-east-1-${ID}",
    "Id": "prowler-trustedadvisor_errors_and_warnings-${ACCOUNT_ID}-us-east-1-${ID}",
    "Id": "prowler-vpc_different_regions-${ACCOUNT_ID}-us-east-1-${ID}",
```

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

Docker container locally

### OS used

Wolfi

### Prowler version

3.6.1

### Pip version

23.1.2

### Context

It's likely Prowler is doing something more interesting with us-east-1, even though it's not configured  via the CLI to do so, because many AWS resources that appear "Global" are actually housed in us-east-1.  

This error is coming from https://github.com/prowler-cloud/prowler/blob/master/prowler/providers/aws/lib/security_hub/security_hub.py#L17 , so prowler is attempting to send some finding to Security Hub in us-east-1. 

The specific checks are listed above. Can/should they run against the target regions instead so that they get reported there?

**Comment by MrCloudSec** [comment]
Hi @ckdake, Prowler may be getting your profile region which is us-east-1. We use this method for global services as you've mentioned. Can you confirm your region that is set in your AWS profile? Thanks.

https://github.com/prowler-cloud/prowler/blob/f875cd05be11563b0e1bc9de7f626e88af12111a/prowler/providers/aws/services/account/account_service.py#L13-L19

**Comment by ckdake** [comment]
Hmm, `aws sts get-caller-identity` doesn't pin these credentials to a region, nor does my `~/.aws/credentials` and there is no `~/.aws/config`, so it's getting a default a few levels down maybe?  Should Prowler pick a default based on the first available configured region, instead of relying on aws? If not should the prowler/aws docs recommend specifying a region in aws config to match one of the regions that it is scanning?

**Comment by ckdake** [comment]
I'm attempting to work around this by explicitly settings `AWS_DEFAULT_REGION` in the script that runs prowler. We're running on ECS as a fargate task so `AWS_REGION` is currently expected to be populated, but this isn't enough to set the default region for the current AWS creds that we're passing into the container as environment variables.

**Comment by MrCloudSec** [comment]
Hi @ckdake, can you try it in the branch `2518-bug-prowler-attempting-to-post-some-findings-to-security-hub-in-us-east-1-when-not-configured-to-use-us-east-1`? I've added a function to pick the first audited_region if your profile_region is not going to be audited.

**Comment by ckdake** [comment]
Thanks @sergargar !  Confirmed here, no more attempts at us-east-1 when scanning with `AWS-CLI Profile: [default] AWS Filter Region: [us-west-2, us-east-2]`

First 'clear' run of prowler here since the rewrite. 🎉   Now to fix up the allowlist and maybe fix an IAM policy or two...


```
 _ __  _ __ _____      _| | ___ _ __
| '_ \| '__/ _ \ \ /\ / / |/ _ \ '__|
| |_) | | | (_) \ V  V /| |  __/ |
| .__/|_|  \___/ \_/\_/ |_|\___|_|v3.6.1
|_| the handy cloud security tool

Date: 2023-06-22 14:06:01


This report is being generated using credentials below:

AWS-CLI Profile: [default] AWS Filter Region: [us-west-2, us-east-2]
AWS Account: [---filtered---] UserId: [---filtered---]
Caller Identity ARN: [---filtered---]

Executing 282 checks, please wait...

-> Scan completed! |▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉| 282/282 [100%] in 18:48.7 

Overview Results:
╭───────────────────┬────────────────────╮
│ 7.03% (74) Failed │ 84.6% (890) Passed │
╰───────────────────┴────────────────────╯
```

**Comment by MrCloudSec** [comment]
Glad to hear that! We will merge the PR then. Thanks for using Prowler 🚀
