### ISSUE TITLE
[Bug]: Additional output formats causing errors reporting to Security Hub, preventing findings from being recorded.

### ISSUE THREAD

**Issue by ckdake** [toniblyx/prowler#2519]
### Steps to Reproduce

```bash
prowler aws --region us-east-2 us-west-2 \
    --allowlist-file allowlist.yaml \
    --output-modes json json-asff \
    --log-level WARNING \
    --security-hub \
    --excluded-checks ec2_elastic_ip_shodan
```

### Expected behavior

Prowler should run and do it's thing, and report all findings to Security Hub.

### Actual Result with Screenshots or Logs

Several errors due to formatting in the finding details:

1. `data.Types` is invalid for a handful of checks. I think this is `[""]` being set where it should be `[]` instead. One example is the finding from cloudfront_distributions_using_deprecated_ssl_protocols. This may be something else, but I think this is it, which should be a quick fix.
```
2023-06-20 14:50:05,265 [File: security_hub.py:50]      [Module: security_hub]   ERROR: Failed to send archived findings to AWS Security Hub -- InvalidInput -- Finding does not adhere to Amazon Finding Format. data.Types[0] should match pattern "^([^/]+)(/[^/]+){0,2}$".
```

2. `data.Description` is too long for some check output from `cloudwatch_log_group_no_secrets_in_logs`.  This should get trimmed to 1024 characters, even through it loses some information.
```
2023-06-20 14:52:51,312 [File: security_hub.py:50]      [Module: security_hub]   ERROR: Failed to send archived findings to AWS Security Hub -- InvalidInput -- Finding does not adhere to Amazon Finding Format. data.Description should NOT be longer than 1024 characters.
```

3. `data.Remediation.Recommendation.Text` is blank, and should be provided. This is the `prowler-rds_instance_deprecated_engine_version` check. This should be a quick fix. 
```
2023-06-20 15:12:55,123 [File: security_hub.py:50]      [Module: security_hub]   ERROR: Failed to send archived findings to AWS Security Hub -- InvalidInput -- Finding does not adhere to Amazon Finding Format. data.Remediation.Recommendation.Text should NOT be shorter than 1 characters.
```

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

Docker container locally

### OS used

Wolfi

### Prowler version

3.6.1

### Pip version

23.1.2

**Comment by MrCloudSec** [comment]
Hi @ckdake, thank you for this information!
Can you try it again from the branch `2519-bug-additional-output-formats-causing-errors-reporting-to-security-hub-preventing-findings-from-being-recorded`, please?

**Comment by ckdake** [comment]
Sure thing! I have to run things a bit differently in order to run from git instead of inside the container builds we run in production. I'm now running "locally" in a Debian/bullseye container with a `git clone` (instead of in a Wolfi container with prowler from pip). Running from this branch (which still appears at 3.6.1 in the initial output of `python prowler.py [...]`), I am no longer seeing the 3 errors described above. 🎉 

I am now seeing a new error appear 2 times, probably because we cleared a few earlier on in the chain:

```
023-06-20 16:31:13,729 [File: security_hub.py:50]      [Module: security_hub]   ERROR: Failed to send archived findings to AWS Security Hub -- InvalidInput -- Finding does not adhere to Amazon Finding Format. data.Compliance.AssociatedStandards should NOT have more than 20 items.
```

This is coming from `cloudtrail_multi_region_enabled` running once for each configured region we are scanning.

**Comment by MrCloudSec** [comment]
Now it should work! @ckdake

**Comment by ckdake** [comment]
It does! The only errors I'm seeing here now are the unrelated ones in https://github.com/prowler-cloud/prowler/issues/2518 . This looks good to merge from my end.
