### ISSUE TITLE
[Bug]: wrong AWS privilleage escalation through glue service

### ISSUE THREAD

**Issue by roisec** [toniblyx/prowler#2526]
### Steps to Reproduce

Hi
Prowler alert for only glue:GetDevEndpoint action that allows performing PE.
I think need to check the combination of glue:UpdateDevEndpoint together glue:GetDevEndpoint.
today prowler alert wrong PE alert for only GetDevEndpoint action

Can you fix that, please?

### Expected behavior

 Alert of glue:UpdateDevEndpoint 

### Actual Result with Screenshots or Logs

.

### How did you install Prowler?

From brew (brew install prowler)

### Environment Resource

EC2

### OS used

MacOS

### Prowler version

3.5.1

### Pip version

19

**Comment by jfagoagas** [comment]
Hi @roisec, this issue is related with this one https://github.com/prowler-cloud/prowler/issues/2220

I'm going to close this issue and include it in that one.

Thanks for using Prowler 🚀
