### ISSUE TITLE
ecr_repositories_scan_vulnerabilities_in_latest_image: Configure level

### ISSUE THREAD

**Issue by HarryBo112** [toniblyx/prowler#2535]
### New feature motivation

Hi, is it possible to configure the level from which the test shall fail?
AWS tags some findings as medium which I might want to ignore, but of course I don't want to mute critical findings for the image.

### Solution Proposed

none

### Describe alternatives you've considered

none

**Comment by n4ch04** [comment]
Hi @HarryBo112,

There are various solutions to filter the results, if you want to filter results from concrete resources/regions/checks/accounts/tags I suggest you to use the allowlist feature (https://docs.prowler.cloud/en/latest/tutorials/allowlist/).
If you only want to receive results from those checks with `Critical` severity  you can launch Prowler with the `--severity` flag to only launch the critical ones

**Comment by MrCloudSec** [comment]
Hi @HarryBo112, we will add a config variable to set your desire severity of the findings of an ECR image that you do not want to ignore.

**Comment by jfagoagas** [comment]
Hi @HarryBo112, we've included a new feature to be able to set the base vulnerability level for this check to raise a `FAIL`, could you please check the above PR?
