### ISSUE TITLE
Prowler rate limiting

### ISSUE THREAD

**Issue by roisec** [toniblyx/prowler#2556]
### New feature motivation

Hi,
We would like to set a limit for Prowler API calls, today we ran Prowler every day, and we received EC2 API Limit exceeding.

### Solution Proposed

limit the API Calls from prowler

### Describe alternatives you've considered

Set limit for Api calls

**Comment by n4ch04** [comment]
Hi @roisec,

You can configure how Prowler retries API calls with the `--aws-retries-max-attempts` flag https://docs.prowler.cloud/en/latest/tutorials/aws/boto3-configuration/.

Thanks for using Prowler !!

**Comment by jfagoagas** [comment]
I'm closing this issue. Please @roisec feel free to reopen it if you notice the same behaviour again. 

Thanks for using Prowler 🚀
