### ISSUE TITLE
[Bug]: AWS sqs_queues_not_publicly_accessible false positive

### ISSUE THREAD

**Issue by rubtoa** [toniblyx/prowler#2565]
### Steps to Reproduce

1. running the sqs_queues_not_publicly_accessible rule
2. AWS
3. create a sqs queue with the following policy 

> {
>     "Version": "2012-10-17",
>     "Id": "__default_policy_ID",
>     "Statement": [
>       {
>         "Sid": "__owner_statement",
>         "Effect": "Allow",
>         "Principal": "*",
>         "Action": "SQS:*",
>         "Resource": "arn:aws:sqs:eu-west-1:11111111111:check-false-positive",
>         "Condition": {
>           "ArnEquals": {
>             "aws:SourceArn": "arn:aws:sns:us-east-1:11111111111:xxxxxxxxxxxxxxxxxxxxx"
>           }
>         }
>       }
>     ]
>   }

The check will return a fail (the status extended will mention that there is a condition)
![image](https://github.com/prowler-cloud/prowler/assets/3840518/9fbbd932-acd7-4b74-950c-315bdaf55e5d)

### Expected behavior

Ideally - the rule should check the contents of the condition and not just for it's existence.
Less ideal but still better - to have a separate rule that checks for the existence of a condition but lower the severity to medium.

### Actual Result with Screenshots or Logs

![image](https://github.com/prowler-cloud/prowler/assets/3840518/0bd20720-a630-47eb-989e-2fa1250f58fa)

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

4. EKS

### OS used

3. Alpine Linux

### Prowler version

3.4.0

### Pip version

pip 23.1

**Comment by n4ch04** [comment]
Hi @rubtoa,

We've included a workaround here #2575

Could you test it?

**Comment by rubtoa** [comment]
> Hi @rubtoa,
> 
> We've included a workaround here #2575
> 
> Could you test it?

Looks good! thanks
