### ISSUE TITLE
[Bug]: GCP Scan

### ISSUE THREAD

**Issue by BachateroJ** [toniblyx/prowler#2573]
### Steps to Reproduce

Im trying to run Prowler on GCP, using the following command
```
prowler gcp --project-ids dmz-env -F dmz-env --credentials-file /home/assaf/.config/gcloud/application_default_credentials.json
```

Using the latest version of prowler:
prowler -v
Prowler 3.7.0 (it is the latest version, yay!)

on Ubuntu LTS:
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04

### Expected behavior

the credentials are for user account, the credentials are correct and have been verified to be working with another process.
the scan didnt begin due to a credentials issue, even if i specified the path

### Actual Result with Screenshots or Logs

the environment has 21 projects, the command didnt work even if i dropped --project-ids, getting this error:
```
2023-07-10 15:19:23,762 [File: gcp_provider.py:29] 	[Module: gcp_provider]	 CRITICAL: No Project IDs can be accessed via Google Credentials.
```

### How did you install Prowler?

Via pip

### Environment Resource

running on a single gcp project 

### OS used

Ubuntu linux 20.04.3

### Prowler version

3.7

### Pip version

pip 22.3.1 from /usr/local/lib/python3.9/dist-packages/pip (python 3.9)

**Comment by n4ch04** [comment]
Hi @BachateroJ,

¿Can you launch the tool with `--log-level ERROR` flag and share the logs here please?

**Comment by BachateroJ** [comment]
Date: 2023-07-13 07:22:06
```
2023-07-13 07:22:22,003 [File: gcp_provider.py:89] 	[Module: gcp_provider]	 ERROR: RefreshError[78]: ('invalid_grant: Account has been deleted', {'error': 'invalid_grant', 'error_description': 'Account has been deleted'})
2023-07-13 07:22:22,004 [File: gcp_provider.py:29] 	[Module: gcp_provider]	 CRITICAL: No Project IDs can be accessed via Google Credentials.
```


i have verified that the account is working and have access to the environment, as well as rechecked the credentials in the credentials file

**Comment by MrCloudSec** [comment]
Hi @BachateroJ, it seems that something is going wrong with your credentials file. 
Can you try to autenticate your GCP Account using `gcloud auth application-default login` see more in https://docs.prowler.cloud/en/latest/#google-cloud. Thanks.

**Comment by MrCloudSec** [comment]
@BachateroJ feel free to reopen the issue if you are still encountering this problem. Thanks!
