### ISSUE TITLE
[Bug]: Unbound local variable `checks_multi_account`

### ISSUE THREAD

**Issue by thomscode** [toniblyx/prowler#2584]
### Steps to Reproduce

1. What command are you running:
  `prowler aws -M html json -f us-west-2 -w allowlist.yaml --ignore-exit-code-3`
2. Cloud provider you are launching: AWS
3. Environment you have: single account

### Expected behavior

Prowler analyzes the account and successfully returns a report.

### Actual Result with Screenshots or Logs

```
 _ __  _ __ _____      _| | ___ _ __
| '_ \| '__/ _ \ \ /\ / / |/ _ \ '__|
| |_) | | | (_) \ V  V /| |  __/ |
| .__/|_|  \___/ \_/\_/ |_|\___|_|v3.7.1
|_| the handy cloud security tool

Date: 2023-07-13 10:33:15


This report is being generated using credentials below:

AWS-CLI Profile: [default] AWS Filter Region: [us-west-2]
AWS Account: [************] UserId: [**************]
Caller Identity ARN: [arn:aws:sts::************:assumed-role/AWSReservedSSO_AdministratorAccess_*******/****@****.***]

Executing 284 checks, please wait...

2023-07-13 10:33:17,306 [File: allowlist.py:144] 	[Module: allowlist]	 CRITICAL: UnboundLocalError -- cannot access local variable 'checks_multi_account' where it is not associated with a value[130]
-> Scanning accessanalyzer service |⚠︎                                       | (!) 0/284 [0%] in 0.2s 
```

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

We are seeing the error on multiple environments:
- CI/CD build node
- Local macOS workstation

### OS used

1. RHEL
2. macOS 13.4

### Prowler version

3.7.1

### Pip version

23.0.1

### Context

Prowler performs as expected in version `3.7.0`, and fails on `3.7.1`

We are using an `allowlist.yaml` file, with our account number specified instead of using a `*` for the account.

**Comment by n4ch04** [comment]
Hi @thomscode,

Yep, there was an error there, it has been solved here #2585 
Can you check it and let us know if now works ?

Thanks for using Prowler !!!

**Comment by thomscode** [comment]
@jfagoagas,

Thanks for checking. I'm the one that submitted that PR. Yes, I checked the fix locally before submitting it and it fixes the problem I'm having.

**Comment by thomscode** [comment]
Yes, that does solve the problem. I'll close the PR #2586 I submitted to fix the issue since you have this fix.

**Comment by n4ch04** [comment]
Actually, your solution seems cleaner than mine, so we are going to merge your branch into mine that include the tests and then merge it to main to solve it.
Thanks for all @thomscode !!
