### ISSUE TITLE
Please support another Provider Open Telekom Cloud like AWS Azure or GCP

### ISSUE THREAD

**Issue by magicmener** [toniblyx/prowler#2601]
### New feature motivation

Please support another Provider Open Telekom Cloud like AWS Azure or GCP

### Solution Proposed

Please support another Provider Open Telekom Cloud like AWS Azure or GCP

### Describe alternatives you've considered

Please support another Provider Open Telekom Cloud like AWS Azure or GCP

**Comment by toniblyx** [comment]
Thanks @magicmener for your suggestion, do you mean OpenStack?

**Comment by magicmener** [comment]
Yes OpenStack with otcextension

**Comment by toniblyx** [comment]
We don't have much experience on that but would be open to help if you are interested on writing checks for that provider

**Comment by toniblyx** [comment]
I found this on Github https://github.com/opentelekomcloud/python-otcextensions I´ll close the issue since this is not in our plans at least short-mid term. However we are open to hear what is needed and teach how to add this provider and checks.
