### ISSUE TITLE
CLI option to set the path to config file

### ISSUE THREAD

**Issue by ghost** [toniblyx/prowler#2602]
### New feature motivation

Configuration file `config.yaml` can be read by the tool only if it's placed in the `prowler/config/config.yaml`. But if the prowler is installed by pip which is installed by the pyenv (e.g) it's difficult to find the place to put a custom config file because it will be like this `.pyenv/versions/3.9.13/lib/python3.9/site-packages/prowler/config/`

### Solution Proposed

I proposed 3 options:
- to add a cli argument which will tell the prowler from where to take the config file like `--config ./config.yaml` 
- try to find config file in the current working directory with fallback to default location
- both of 2 above

### Describe alternatives you've considered

just hardcode the path to destination folder in the pipeline

**Comment by jfagoagas** [comment]
Hi @ivan-morhun, you are totally right. We are going to work on a fix to be able to pass the path for the config file.

Thanks!

**Comment by jfagoagas** [comment]
Hi @ivan-morhun, could you please take a look at this branch `fix-external-config-file`. We have included a new flag `--config-file` to pass custom configuration files to Prowler.

Thanks!
