### ISSUE TITLE
[Bug]: Prowler not reporting all GCE VMs with external ip addresses in GCP

### ISSUE THREAD

**Issue by nealharris** [toniblyx/prowler#2604]
### Steps to Reproduce

command: `prowler gcp -c compute_instance_public_ip --project-ids <single-project-id> -o /tmp -F compute`
cloud provider: gcp
environment description: gcp organization with many projects
results:
``` _ __  _ __ _____      _| | ___ _ __
| '_ \| '__/ _ \ \ /\ / / |/ _ \ '__|
| |_) | | | (_) \ V  V /| |  __/ |
| .__/|_|  \___/ \_/\_/ |_|\___|_|v3.7.0
|_| the handy cloud security tool

Date: 2023-07-20 08:58:14


This report is being generated using credentials below:

GCP Account: [default]  GCP Project IDs: [<project-name>]

Executing 1 check, please wait...

-> Scan completed! |▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉| 1/1 [100%] in 32.5s 

 There are no findings in Project ID/s
```

### Expected behavior

There are several VMs in the target project that have external ip addresses. I would expect prowler to report them.

### Actual Result with Screenshots or Logs

(See above.)

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

Running from my laptop, and also from a k8s job in a GKE cluster (same results).

### OS used

laptop: MacOS
GKE: Linux

### Prowler version

3.70 (laptop) and 3.7.1 (GKE)

### Pip version

22.2.1

### Context

Prowler does report other findings for this project, so I know it has at least some level of access to it. In both cases (laptop and GKE), the service account being used has at least the permissions documented as required.

**Comment by MrCloudSec** [comment]
Hi @nealharris, thank you for reaching us out!
Could you execute it the command again with `--log-level ERROR` to find potential problems?

**Comment by nealharris** [comment]
Aha, there are some interesting logs there. Here they are:
```
2023-07-23 08:44:58,925 [File: compute_service.py:250] 	[Module: compute_service]	 ERROR: KeyError[241]: 'defaultService'
2023-07-23 08:44:59,555 [File: compute_service.py:267] 	[Module: compute_service]	 ERROR: AttributeError[265]: 'bool' object has no attribute 'get'
2023-07-23 08:45:03,302 [File: compute_service.py:139] 	[Module: compute_service]	 ERROR: us-central1-a -- KeyError[115]: 'confidentialInstanceConfig'
2023-07-23 08:45:23,050 [File: compute_service.py:226] 	[Module: compute_service]	 ERROR: KeyError[215]: 'sourceRanges'
```

**Comment by MrCloudSec** [comment]
Hi @nealharris, can you try it again in the branch `fix-compute-service`? Thanks.

**Comment by nealharris** [comment]
@sergargar yes, this seems to have resolved the issue! It's now reporting the VMs I would expect to see reported.
