### ISSUE TITLE
[Bug]: AWS vpc_endpoint_connections_trust_boundaries errors on valid endpoint policy

### ISSUE THREAD

**Issue by ckdake** [toniblyx/prowler#2605]
### Steps to Reproduce

1. In an AWS account 123456789, configure an AWS VPC Private Endpoint (interface) with a valid policy that uses the account ID as the Principal. e.g:

```json
{
	"Statement": [
		{
			"Action": "*",
			"Effect": "Allow",
			"Principal": {
				"AWS": [
					"123456789"
				]
			},
			"Resource": "*"
		}
	]
}
```

2. Run prowler

### Expected behavior

Expect a clean bill of health from vpc_endpoint_connections_trust_boundaries because it has a principal that matches the account id of the current account (Per https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_principal.html#principal-accounts -> just setting the account ID is a valid AWS account prinicipal), which is included in trusted_account_ids without configuring it explicitly (see the comment at https://github.com/prowler-cloud/prowler/blob/master/prowler/config/config.yaml#L10)

### Actual Result with Screenshots or Logs

Instead, prowler errors out:

```
7/20/2023, 2:54:06 PM EDT | 2023-07-20 18:54:06,299 [File: check.py:399] [Module: check] ERROR: vpc_endpoint_connections_trust_boundaries -- IndexError[41]: list index out of range | prowler
-- | -- | --
7/20/2023, 2:54:06 PM EDT | Something went wrong in vpc_endpoint_connections_trust_boundaries, please use --log-level ERROR | prowler
```

This is due to https://github.com/prowler-cloud/prowler/blob/d2e34c42fd2a2f470e6e7fcc8c84da653ebd2d19/prowler/providers/aws/services/vpc/vpc_endpoint_connections_trust_boundaries/vpc_endpoint_connections_trust_boundaries.py#L41

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

Any

### OS used

Any

### Prowler version

3.7.1

### Pip version

Any

### Context

https://github.com/prowler-cloud/prowler/blob/d2e34c42fd2a2f470e6e7fcc8c84da653ebd2d19/prowler/providers/aws/services/vpc/vpc_endpoint_connections_trust_boundaries/vpc_endpoint_connections_trust_boundaries.py#L41 Should not assume that the contents of `statement["Principal"]["AWS"]` is a list of ARNs _or_ `*`.  It also needs to account for a string consisting of an aws account ID. (per https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_principal.html)

This can be worked around by updating policies within AWS to have the full ARN of the root user, and VPC Endpoint Gateway policies seem to transform this automatically (in my limited testing) but  VPC Endpoint Interface policies seem to save it as just the account id.  Prowler should not error on a "legal" AWS policy.  Thanks!

[edit]:  Having ARNs in the `principal` key actually seems to break policies on endpoints, and the `condition` key should be used instead. See discussion below.

**Comment by ckdake** [comment]
Additionally, I'm working with AWS support troubleshooting some policies. Prowler is looking for a "Principal" to be set to restrict access in VPC Endpoint policies.  AWS seems to recommend (both in documentation, and via a person in support) to limit things using "Condition" in policies instead.

See:

*  "Example: Restrict access to buckets in a specific AWS account" on https://docs.aws.amazon.com/vpc/latest/privatelink/vpc-endpoints-s3.html#bucket-policies-s3.  -> They use a condition

* "Principals for gateway endpoints" on https://docs.aws.amazon.com/vpc/latest/privatelink/vpc-endpoints-access.html#vpc-endpoint-policies-gateway. -> this says "With gateway endpoints, you must use the aws:PrincipalArn condition key to grant access to a principal."
 
It looks like Prowler _must_ use the `condition` key for Gateway endpoints (Amazon S3 and DynamoDB), where it is currently just looking in the `principal` key.  From the documentation, I can't tell if this is a hard requirement for Interface endpoints (things other than S3 or DynamoDB) but I should have this worked out next week.

**Comment by jfagoagas** [comment]
Hi @ckdake, we've fixed the issue with the AWS Account number set in the `Principal` key. Please check it again in the above PR.

Regarding the condition keys, based on the AWS documentation you provided the ones to check will be:
- `aws:PrincipalArn`
- `s3:ResourceAccount`
- `aws:PrincipalArn`
- `aws:PrincipalAccount`

Since this check is only using the AWS Account ID, right?

**Comment by ckdake** [comment]
Thanks @jfagoagas !   This fix for the account ID in the Principal key looks great to me.

For the Condition key (which I think is the "right" one to use per AWS support, but I still haven an open ticket with them),  I'm expecting to be using `aws:PrincipalArn`.  There is a chance it will be something else, so you're welcome to pause here until I can confirm with AWS what this all should be. In addition to the ones you list, there is a chance it may be a condition on `aws:SourceAccount` our SourceArn as well. (see https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_condition-keys.html#condition-keys-sourceaccount)

**Comment by jfagoagas** [comment]
Awesome, keep me posted!

**Comment by ckdake** [comment]
For unrelated reasons, I've gotta make some changes on our end which will prevent me from getting this one working. I think you'll have a better check here looking for a condition matching aws:PrincipalArn to and ID in the allowed accounts list, but can't confirm it, but merging the PR you linked as-is will at least get this check correctly passing for some people.

**Comment by jfagoagas** [comment]
Hi @ckdake, can you test it again with the `PRWLR-2434-bug-aws-vpc-endpoint-connections-trust-boundaries-errors-on-valid-endpoint-policy-2605` branch? I've included the condition keys we talked about, it'd be great if you can test it again.

It's a little bit complicated when you include the condition keys but I think we sorted it out. Otherwise we can only left the fix for the `Principal` with the AWS Account ID.

**Comment by ckdake** [comment]
Unfortunately the startup I was using this at hit end-of-life and we've spun down AWS already so I don't have an environment at the moment.

This should be reproducible if you have access to an AWS organization with two accounts, I'd be happy to walk you through specifics async or live if it's helpful.

**Comment by jfagoagas** [comment]
Hi @ckdake, it'd be great if we can test it because I've made some changes to the `PRWLR-2434-bug-aws-vpc-endpoint-connections-trust-boundaries-errors-on-valid-endpoint-policy-2605` and now it should work as expected.

**Comment by ckdake** [comment]
I set up an AWS org to test this out. With the "valid" (but maybe not working/right) policy:

```
{
	"Statement": [
		{
			"Action": "*",
			"Effect": "Allow",
			"Principal": {
				"AWS": [
					"123redacted456"
				]
			},
			"Resource": "*"
		}
	]
}
```

Running with the current main branch of prowler I get the `2023-08-02 13:33:25,424 [File: check.py:399] 	[Module: check]	 ERROR: vpc_endpoint_connections_trust_boundaries -- IndexError[41]: list index out of range` error.

Running with the `RWLR-2434-bug-aws-vpc-endpoint-connections-trust-boundaries-errors-on-valid-endpoint-policy-2605` branch I get

  ```
╭─────────────────┬───────────────────╮
│ 0.0% (0) Failed │ 100.0% (1) Passed │
╰─────────────────┴───────────────────╯
```

So that part is good!   

Trying out the other formatted policy (which may also not be "right", but should at least be valid and pass the prowler check:

```
{
	"Statement": [
		{
			"Action": "*",
			"Effect": "Allow",
			"Principal": "*",
			"Resource": "*",
			"Condition": {
				"StringEquals": {
					"aws:PrincipalAccount": "123redacted456"
				}
			}
		}
	]
}
```

This one also fails in the main branch, and still fails in the new branch. I tried changing the condition key to "aws:SourceAccount" which should also pass in the branch, but it is failing too.

**Comment by jfagoagas** [comment]
Hi @ckdake, are you using the `trusted_account_ids` config value to test it? I've made a tiny change to always include the `audited_account` as trusted even if the `trusted_account_ids` variable is empty, what do you think?

Please, give it a try again if you get a chance.

Thanks!

**Comment by ckdake** [comment]
I am not using trusted_account_ids, I'm relying on the default behavior described in the docs for the id of the current account to be included in trusted_account_ids.  

This now works correctly with the policy above, so from here it looks like it's good to merge.

**Comment by jfagoagas** [comment]
Awesome @ckdake, thank you very much for your help.

BTW, could you share the docs you are referring to?

We'll merge this tomorrow 🥳 

Thanks!
