### ISSUE TITLE
Requesting a project review

### ISSUE THREAD

**Issue by ssmayamp** [toniblyx/prowler#2607]
### New feature motivation

I'd like to havve @ChatGPT review this project to facilitate easier install for different environments and have more examples of application use and benefits

### Solution Proposed

I'd like to havve @ChatGPT review this project to facilitate easier install for different environments and have more examples of application use and benefits

### Describe alternatives you've considered

Share links, videos on prowler usage

### Additional context

I'd like to havve @ChatGPT review this project to facilitate easier install for different environments and have more examples of application use and benefits

**Comment by toniblyx** [comment]
I wonder if @ssmayamp is also an AI managed bot. Have you seen our docs and all ways to install and use Prowler here? [https://docs.prowler.cloud](https://docs.prowler.cloud)

**Comment by jfagoagas** [comment]
Hi @ssmayamp, I'm closing this issue. Please feel free to reopen it if you encounter some issues installing or using Prowler. And please refer first to the documentation site at https://docs.prowler.cloud/

Thanks for using Prowler 🚀
