### ISSUE TITLE
[Bug]: GuardDuty List Detectors Only Gets Enabled Detectors

### ISSUE THREAD

**Issue by WillSilverstone25** [toniblyx/prowler#2612]
### Steps to Reproduce

1. Running prowler aws -c guardduty_is_enabled
2. This check is only outputting enabled detectors and is not listing when regions fail with GuardDuty disabled
3. This is because line 45 in guardduty_service.py is looking for DetectorID. However, this field is blank when the detector is not enabled. Therefore the detectors array is being populated with enabled detectors only.

### Expected behavior

This check should output both enabled and disabled GuardDuty detectors

### Actual Result with Screenshots or Logs

The check is only outputting enabled GuardDuty detectors

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

Workstation

### OS used

MacOS

### Prowler version

3.7

### Pip version

23.1.2

**Comment by MrCloudSec** [comment]
Hi @WillSilverstone25, you're right, thanks for letting us know! We've just fixed the issue and it'll be available in the next version.
