### ISSUE TITLE
[Bug]: 'EC2 AMI is currently public' check's 'Title' is inconsistent with 'Risk' and 'Remediation' details

### ISSUE THREAD

**Issue by trigger1919** [toniblyx/prowler#2617]
### Steps to Reproduce

**The 'CheckTitle' is inconsistent with 'Description', 'Risk', 'Recommendation', 'Status Extended', 'Remediation' fields:**

"CheckID": "ec2_ami_public"
"CheckTitle": "Ensure there are no EC2 AMIs set as Public.",
"StatusExtended": "EC2 AMI ami-XXX is currently public.",
"Description": "Ensure there are no EC2 AMIs set as Public.",
    "Risk": "A shared AMI is an AMI that a developer created and made available for other developers to use. If AMIs have embebed information about the environment could pose a security risk. You use a shared AMI at your own risk. Amazon can not vouch for the integrity or security of AMIs shared by Amazon EC2 users.",
    "RelatedUrl": "",
    "Remediation": {
        "Code": {
            "NativeIaC": "",
            "Terraform": "",
            "CLI": "https://docs.bridgecrew.io/docs/public_8#cli-command",
            "Other": "https://docs.bridgecrew.io/docs/public_8#aws-console"
        },
        "Recommendation": {
            "Text": "List all shared AMIs and make sure there is a business reason for them.",
            "Url": "https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/usingsharedamis-finding.html"
        }

The title is about EC2 AMI being 'Public', but the description is about shared AMI, which is far not the same.

Could you please clarify the 'Title' by adding the string 'Ensure there are no EC2 AMIs set as Public **or Shared**'.

If my logic is not correct, please explain what the check actually does.

### Expected behavior

Check's fields are consistent with each other.

### Actual Result with Screenshots or Logs

-

### How did you install Prowler?

Docker (docker pull toniblyx/prowler)

### Environment Resource

Fargate task

### OS used

-

### Prowler version

3

### Pip version

-

**Comment by MrCloudSec** [comment]
Hi @trigger1919, this check verifies if an AMI is publicly shared. I will change the Risk text for not causing confusion. Thanks for reaching us out.

**Comment by trigger1919** [comment]
Thanks for the reply. But what does it mean "Publicly shared"? Is it only having the "Public" key set to "True"?

**Comment by MrCloudSec** [comment]
Yes, you can privately share an AMI between other AWS accounts. But if you have the Public key set to True, any AWS account can launch your AMI so it is publicly shared.

**Comment by trigger1919** [comment]
Please also review the other fields: Recommendation's Text and URL describe the case of Private Shared AMIs, not the Public.

**Comment by trigger1919** [comment]
Ok, but in this case a have several false positives. The 'Public' key is 'false', but the check fires. I guess the check is straightforward, but I cannot understand how it fails.

How should I fix that?

**Comment by MrCloudSec** [comment]
@trigger1919, we've just fixed that issue in the branch `2617-bug-ec2-ami-is-currently-public-checks-title-is-inconsistent-with-risk-and-remediation-details`. Can you try it again in that branch, please?

**Comment by trigger1919** [comment]
I can only try to parse the log produced by public.ecr.aws/prowler-cloud/prowler:latest, but I cannot run the tool on my data. Once the fix is in the 'latest' I can see the difference.

**Comment by MrCloudSec** [comment]
Okay, we will merge this fix. Reopen this issue if you still encounter this issue in latest.
