### ISSUE TITLE
[Bug]: Line numbers are incorrect in 'Potential secret found in variables of ECS task definition' check

### ISSUE THREAD

**Issue by trigger1919** [toniblyx/prowler#2620]
### Steps to Reproduce

The line numbers in 'Potential secret found in variables of ECS task definition' check do not point the actual secrets.
Example:
"Potential secret found in variables of ECS task definition XXXXX with revision XX -> Private Key on line 6, Secret Keyword on line 8, Basic Auth Credentials on line 9"

When checking the task_definition.json file in AWS, the lines do not point to the secrets found.

Judging by the code, prowler searches in the 'environment' section and compile its own file.
https://github.com/prowler-cloud/prowler/blob/6328ef44444bb51afc3715ea16e224cad82a3919/prowler/providers/aws/services/ecs/ecs_task_definitions_no_environment_secrets/ecs_task_definitions_no_environment_secrets.py#L36

Probably line numbers reference to this temporary file.

Is there a way to fix the prowler's output to return the line numbers from the original task_definition.json file?

Is there a workaround to fix the manually in the output? 

### Expected behavior

Line numbers points to correct lines in task_definition.json.

### Actual Result with Screenshots or Logs

-

### How did you install Prowler?

Docker (docker pull toniblyx/prowler)

### Environment Resource

Fargate

### OS used

-

### Prowler version

3

### Pip version

-

**Comment by jfagoagas** [comment]
Hi @trigger1919 I answered your question here --> https://github.com/prowler-cloud/prowler/discussions/2619

"These line numbers starts at the environment key of your ECS Task Definition."

**Comment by jfagoagas** [comment]
Comment from the discussion:

Each entry in the task definition is transformed right, so:
- Task Definition:
```
"environment": [
  {
      "name": "Super_Secret_Password",
      "value": "password"
  },
]
```
- Prowler temporary file:
```
{
  "Super_Secret_Password": "password"
}
```

You are right, we have to check it because I'm not sure if the library we use to detect secrets can work with the Task Definition `environment` format.

Thanks!

**Comment by trigger1919** [comment]
But can you make a back mapping to the original line numbers in finding's title? I guess the transformation is quite straightforward.

**Comment by jfagoagas** [comment]
Yes, but the numbers comes from the process auditing that file transformed. I'm wondering that maybe the numbers could match because the transformation reduces one line per secret so the matching number is pointing to the `environment.name`, could you check it?

**Comment by trigger1919** [comment]
Yes, it matches now. But I need to convey the finding to third hands so
they can understand it with common sense only, without knowledge about this
transformations. That is why I created a bug for this issue.

вт, 25 июл. 2023 г., 18:38 Pepe Fagoaga ***@***.***>:

**Comment by jfagoagas** [comment]
Thanks for the answer, we are going to update the check's description to note that the finding line number matches with the environment variable name.

Thanks for using Prowler 🚀
