### ISSUE TITLE
[Bug]: False positives in check "EC2 AMI is currently public"

### ISSUE THREAD

**Issue by trigger1919** [toniblyx/prowler#2626]
### Steps to Reproduce

AMI images with flag "Public: false" do not pass prowler's check "EC2 AMI is currently public".

I validate results using the command specifying the exact image:
`aws ec2 describe-images --owners XXXXX --image-ids ami-XXXX`

the output is like:
```
"Images": [
        {
            "Architecture": "x86_64",
            "CreationDate": "2023-07-25T22:08:49.000Z",
            "ImageId": "ami-XXXX",
            "ImageLocation": "XX",
            "ImageType": "machine",
            "Public": false,
            "OwnerId": "XXXXX",
            "Platform": "windows",
            "PlatformDetails": "Windows",
            "UsageOperation": "XXXX:XXXX",
            "State": "available",
```

### Expected behavior

Not public AMIs pass the check

### Actual Result with Screenshots or Logs

--

### How did you install Prowler?

Docker (docker pull toniblyx/prowler)

### Environment Resource

Fargate

### OS used

--

### Prowler version

3

### Pip version

--

**Comment by MrCloudSec** [comment]
Hi, can you try it again with the latest version of Prowler?

**Comment by trigger1919** [comment]
How often public.ecr.aws/prowler-cloud/prowler:latest is updated?

**Comment by trigger1919** [comment]
5 hours ago the issue was still there pulling docker from public.ecr.aws/prowler-cloud/prowler:latest

**Comment by jfagoagas** [comment]
Hi @trigger1919, `public.ecr.aws/prowler-cloud/prowler:latest` is updated every time we merge a PR from a branch to the`master` branch. We also made a fixes release today two hours ago --> https://github.com/prowler-cloud/prowler/releases/tag/3.7.2

So you can re-test either with either `public.ecr.aws/prowler-cloud/prowler:latest` or `public.ecr.aws/prowler-cloud/prowler:3.7.2`.

Thanks!

**Comment by trigger1919** [comment]
Checked again with v.3.7.2. False positives are still there, but now the count is less.

**Comment by trigger1919** [comment]
Should I treat those AMIs with the key 'Public' set to 'false' (returned by `aws ec2 describe-images --owners XXXXX --image-ids ami-XXXX` as shown in the bug description above) as false positives?

**Comment by MrCloudSec** [comment]
It's weird, could you execute it again with `--log-level ERROR` ?

**Comment by trigger1919** [comment]
I do not have access to the launching setup of prowler in own environment. I can only work with the report.
What is the way to simulate how prowler actually captures the 'Public' key?

This check works just fine in version 2.

**Comment by trigger1919** [comment]
Rechecked again today. Looks like false positives are gone.

**Comment by jfagoagas** [comment]
That's great @trigger1919!!

Is the issue fixed then?

**Comment by trigger1919** [comment]
I guess so, although still not clear what caused the issue.

**Comment by MrCloudSec** [comment]
The variable storing the Public value was not changing for each image.
