### ISSUE TITLE
[Bug]: The check 'Potential secret found in EC2 instance * User Data.' does not include the line numbers where the secrets were found

### ISSUE THREAD

**Issue by trigger1919** [toniblyx/prowler#2632]
### Steps to Reproduce

The check 'Potential secret found in EC2 instance * User Data.' does not show the line numbers, whereas 'Potential secret found in variables of ECS task definition' does. Why is it so?

The results of check without precise pointing at the line are frustrating: you do not know where exactly the scanner found the secret and how many secrets were found.

Same issue will rise if you need to troubleshoot the scanner.

### Expected behavior

Numbers of lines with secrets are included in issue description.

### Actual Result with Screenshots or Logs

-

### How did you install Prowler?

Docker (docker pull toniblyx/prowler)

### Environment Resource

Fargate

### OS used

--

### Prowler version

3

### Pip version

--

**Comment by Fennerr** [comment]
I update the code for some of the checks to give the line number and secret type, but i must've missed this one. Thanks for pointing it out.

**Comment by jfagoagas** [comment]
Hi @trigger1919 @Fennerr could you please test it again with the above PR. We've fixed it and now the `status_extended` shows the line numbers and the secret type. Thanks!
