### ISSUE TITLE
[Bug]: "[extra7113] Check if RDS instances have deletion protection enabled" report FAIL for RDS Aurora Clusters with deletion protection enabled

### ISSUE THREAD

**Issue by murand78** [toniblyx/prowler#2635]
### Steps to Reproduce

Scan of AWS account with an AURORA RDS Cluster with Deletion Protection enabled on Cluster

### Expected behavior

CHECK_RESULT: PASS for:
[extra7113] Check if RDS instances have deletion protection enabled 

### Actual Result with Screenshots or Logs

CHECK_RESULT: FAIL
for every RDS Instance in the Cluster

### How did you install Prowler?

Docker (docker pull toniblyx/prowler)

### Environment Resource

EC2 Instance

### OS used

Amazon Linux 2

### Prowler version

3.7.2

### Pip version

.

**Comment by jfagoagas** [comment]
Hi @murand78, are you using Prowler v3 or v2? I see that you input `3.7.2` but the `[extra7113] Check if RDS instances have deletion protection enabled` was a naming from the old v2.

Also, I cannot reproduce it in our side so, please execute it again with the `--log-level ERROR` flag and paste here the output.

Thanks!

**Comment by murand78** [comment]
My apologize, I was executing using docker image toniblyx/prowler:latest , but the image on the server I was using was an older version cached.
All works fine with correct version 3.7.2

**Comment by jfagoagas** [comment]
Awesome!! 

Thanks for using Prowler 🚀🚀
