### ISSUE TITLE
[Bug]: resolve_security_hub_previous_findings() doesn't honor -F

### ISSUE THREAD

**Issue by jchrisfarris** [toniblyx/prowler#2686]
### Steps to Reproduce

When running Prowler with: 
```bash
	prowler aws -M csv json json-asff html -b -z $SLACK -S \
		--checks-file checks.json -f $REGIONS \
		--log-file prowler-logs-${ACCOUNT_ID}-${TODAY}.log \
		-F prowler-${ACCOUNT_ID}-${TODAY} --log-level ERROR \
		-R arn:aws:iam::$ACCOUNT_ID:role/$ROLENAME \
		-O arn:aws:iam::$PAYER_ID:role/$ROLENAME \
		-D ${OUTPUT_BUCKET} -o prowler-output 2> prowler-errors-${ACCOUNT_ID}-${TODAY}.log
```
If Security Hub isn't setup to accept findings, the function `resolve_security_hub_previous_findings()` is called at the end of the run. But the log file that this function processes is fixed on line 71 of prowler/providers/aws/lib/security_hub/security_hub.py

### Expected behavior

The file format specified in -F should be passed to `resolve_security_hub_previous_findings()` and used on line 71. 

### Actual Result with Screenshots or Logs

These errors will appear due to SecHub not being enabled in some regions
```
2023-08-07 12:38:07,057 [File: security_hub.py:40] 	[Module: security_hub]	 ERROR: Security Hub is enabled in ap-northeast-1 but Prowler integration does not accept findings. More info: https://docs.prowler.cloud/en/latest/tutorials/aws/securityhub/
```

This this error is thrown and prowler exits with error code 1:
```
Traceback (most recent call last):
  File "/home/prowler/.local/bin/prowler", line 8, in <module>
    sys.exit(prowler())
  File "/home/prowler/.local/lib/python3.9/site-packages/prowler/__main__.py", line 222, in prowler
    resolve_security_hub_previous_findings(args.output_directory, audit_info)
  File "/home/prowler/.local/lib/python3.9/site-packages/prowler/providers/aws/lib/security_hub/security_hub.py", line 70, in resolve_security_hub_previous_findings
    with open(
FileNotFoundError: [Errno 2] No such file or directory: 'prowler-output/prowler-output-REDACTED_ACCOUNT_ID-20230807123032.asff.json'
```

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

Fargate Container, using command described above

### OS used

Docker file is 
FROM python:3.9

### Prowler version

Prowler 3.8.0 (it is the latest version, yay!)

### Pip version

pip 23.2.1 from /Users/chris/AWS/prowler-elastistats/.env/lib/python3.9/site-packages/pip (python 3.9)

**Comment by MrCloudSec** [comment]
Great catch @jchrisfarris ! I could reproduce this error and will fix it shortly. Thank you for letting us know
