### ISSUE TITLE
[Bug]: Context name on conditions are case-insensitive

### ISSUE THREAD

**Issue by christiandavilakoobin** [toniblyx/prowler#2723]
### Steps to Reproduce

As yo can see here https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition.html, context name on conditions are case-insensitive. Some default aws policies are "AWS:xxxx" instead of "aws:xxxx", so prowler fails to detect it. Also can happen with manual policies, if someone put "aws:sourceaccount" inseat of "aws:SourceAccount". So is_account_only_allowed_in_condition must be case-insensitive to work.

I found it on SNS default policy, which look like this:

```
{
  "Version": "2008-10-17",
  "Id": "__default_policy_ID",
  "Statement": [
    {
      "Sid": "__default_statement_ID",
      "Effect": "Allow",
      "Principal": {
        "AWS": "*"
      },
      "Action": [
        "SNS:GetTopicAttributes",
        "SNS:SetTopicAttributes",
        "SNS:AddPermission",
        "SNS:RemovePermission",
        "SNS:DeleteTopic",
        "SNS:Subscribe",
        "SNS:ListSubscriptionsByTopic",
        "SNS:Publish",
        "SNS:Receive"
      ],
      "Resource": "arn:aws:sns:eu-west-1:XXXXXXXX:config-topic",
      "Condition": {
        "StringEquals": {
          "AWS:SourceOwner": "XXXXXXXX"
        }
      }
    }
  ]
}
```

### Expected behavior

It should pass when found a condition like "AWS:SourceOwner" with a valid value. 

### Actual Result with Screenshots or Logs

It can't detect correctly the condition, so the test fails.
╭────────────┬───────────┬───────────┬────────────┬────────┬──────────┬───────╮
│ Provider   │ Service   │ Status    │   Critical │   High │   Medium │   Low │
├────────────┼───────────┼───────────┼────────────┼────────┼──────────┼───────┤
│ aws        │ sns       │ FAIL (13) │          0 │     13 │        0 │     0 │
╰────────────┴───────────┴───────────┴────────────┴────────┴──────────┴───────╯

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

8. SNS

### OS used

5. Ubuntu

### Prowler version

Prowler 3.8.2

### Pip version

pip 23.2.1

**Comment by jfagoagas** [comment]
Hi @christiandavilakoobin, good catch here, so changing the `is_account_only_allowed_in_condition` function to transform the condition input in a lowercase string should fix that?

**Comment by christiandavilakoobin** [comment]
I think so. I'm trying to do that, but i'm not enough python skilled and my modifications crashes everytime. I'm still trying.

**Comment by jfagoagas** [comment]
That's good, I can help you if you need it.

**Comment by christiandavilakoobin** [comment]
I think I have it:

https://github.com/prowler-cloud/prowler/pull/2726

**Comment by jfagoagas** [comment]
@christiandavilakoobin I've included some changes, please check them out in the PR.

I'll merge it once you test it again.
