### ISSUE TITLE
[Bug]:  Unable to filter by severity when using compliance, service, etc.

### ISSUE THREAD

**Issue by jicunningham** [toniblyx/prowler#2751]
### Steps to Reproduce

I am running the following command, hoping to only get findings that are considered critical and high, however, I get an error when trying to do so:

`prowler aws --compliance cis_2.0_aws --profile cloudops-dev --verbose --only-logs --severity high`

This trows the following error:  `prowler aws: error: argument --severity: not allowed with argument --compliance`

I get the same error when I use services, checks, etc. The only time the filtering does work is when I do not add a specific compliance/check/category.

### Expected behavior

The results of only the high and critical findings for my selected compliance/service

### Actual Result with Screenshots or Logs

The command above to get the logs will not work, it exits immediately saying I cannot filter the severity

### How did you install Prowler?

From pip

### Environment Resource

Workstation

### OS used

Mac

### Prowler version

> prowler --version Prowler 3.8.2 (it is the latest version, yay!)

### Pip version

> pip --version pip 23.2.1 from /opt/homebrew/lib/python3.10/site-packages/pip (python 3.10)

**Comment by n4ch04** [comment]
Hi @jicunningham we are going to review this and let you know
Thanks for using Prowler !!!

**Comment by jicunningham** [comment]
Thanks, appreciate all your hard work on this project!

**Comment by n4ch04** [comment]
Hi @jicunningham,
Right now the compliance execution loads all the checks included in the framework executed and does not allow filtering.
We are planning to include it sooner than later but in this moment is not available.

Can we help you with something else?

**Comment by jicunningham** [comment]
Yes, but I will open a separate issue for that. Still want to try and troubleshoot myself before I `bug` you again (Sorry for the dad joke)

**Comment by n4ch04** [comment]
Thanks !! I'll close this, don't hesitate and open a new one even if you think it is only you fighting against Prowler
We are always happy to help !!
