### ISSUE TITLE
[Bug]: ec2_securitygroup_default_restrict_traffic Title does not match check logic 

### ISSUE THREAD

**Issue by jmanduca-psfy** [toniblyx/prowler#2761]
### Steps to Reproduce

Run a prowler aws scan that includes the `ec2_securitygroup_default_restrict_traffic` check against an account with a `default` security group that has ingress and/or egress rule attached:

`prowler aws --checks ec2_securitygroup_default_restrict_traffic`

### Expected behavior

The AWS check `ec2_securitygroup_default_restrict_traffic` should report any `default` Security Group that does not have 0 ingress and 0 egress rules attached.

### Actual Result with Screenshots or Logs

This default SG exists in the account:
![image](https://github.com/prowler-cloud/prowler/assets/136485579/fa9589ce-074f-4eed-bcec-37963bfb7f3e)

Not in report:
Executing 1 check, please wait...

-> Scan completed! |▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉| 1/1 [100%] in 29.2s

Overview Results:
╭─────────────────┬────────────────────╮
│ 0.0% (0) Failed │ 100.0% (XX) Passed │
╰─────────────────┴────────────────────╯

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

Fargate

### OS used

AWS Linux 2

### Prowler version

3.8.2

### Pip version

pip 23.2 from /usr/lib/python3/dist-packages/pip (python 3.11)

### Context

Default security groups should not be used, and ensuring they have no SG Rules attached is one way to validate that. This also ensures that if they are mistakenly used (for example in an AWS resource creation that automatically selects the Default group), no additional attack surface is created.

Currently the rule checks for "Internet exposed" rules instead of just the existence of them: https://github.com/prowler-cloud/prowler/blob/22f8855ad7dad2e976dabff78611b643e234beaf/prowler/providers/aws/services/ec2/ec2_securitygroup_default_restrict_traffic/ec2_securitygroup_default_restrict_traffic.py#L17C13-L17C13

**Comment by n4ch04** [comment]
Hi @jmanduca-psfy  we will inspect this and reach you when we have an answer, thanks for using Prowler !!!

**Comment by n4ch04** [comment]
Hi @jmanduca-psfy you are right, that check should look for any changes in the default sg that means allowing inbound or outbound traffic, we are working on it.
I'll let you know when I've finished
