### ISSUE TITLE
[Bug]: iam_policy_allows_privilege_escalation is raising false positives

### ISSUE THREAD

**Issue by ernievd** [toniblyx/prowler#2770]
### Steps to Reproduce

When looking at the scan results for "Ensure no Customer Managed IAM policies allow actions that may lead into Privilege Escalation" it look like we are getting bad results for it now using Prowler version 3.8.2.

If I run a scan on an AWS IAM policy defined with the below json I get the failure -

_Custom Policy arn:aws:iam::xxxxxxxxxxx:policy/app-user-policy-hertzcp-pprd allows privilege escalation using the following actions: {'iam:CreateAccessKey'}_

The below is the AWS IAM policy json that it scanned and as you can see the policy does not have 'iam:CreateAccessKey' within it :
 
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": [
                "es:List*",
                "es:Get*",
                "es:Describe*"
            ],
            "Resource": "*"
        },
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": "es:*",
            "Resource": "arn:aws:es:us-west-2:xxxxxxxxxxxx:domain/g-clients-infra-pprd/*"
        }
    ]
}
```

When I used prowler version 3.4.1 it did not find/report on the above issue.

Also - 
Prowler version 3.8.2 now reports the below policy as passing for "Ensure no Customer Managed IAM policies allow actions that may lead into Privilege Escalation"  :

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": "sts:AssumeRole",
            "Resource": "arn:aws:iam::*:role/xena-role"
        }
    ]
}
```

When a scan using prowler version 3.4.1 was run the above policy was reported as a failure for "Ensure no Customer Managed IAM policies allow actions that may lead into Privilege Escalation". 
I would believe that this policy should still be reported as a failure and that Prowler version 3.8.2 has issues.

### Expected behavior

The first policy should pass and the second policy should fail.

### Actual Result with Screenshots or Logs

[prowler-output-741743798098-20230823103540.csv](https://github.com/prowler-cloud/prowler/files/12421414/prowler-output-741743798098-20230823103540.csv)

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

EKS and ran the scan locally

### OS used

MacOS

### Prowler version

3.8.2

### Pip version

21.1.3

**Comment by jfagoagas** [comment]
Thanks for reporting it @ernievd, I'll take a look at it and let you know once I've a fix.

Regarding the `sts:AssumeRole` permission we've changed not to raise a FAIL by itself since it needs another permissions to allow the policy to escalate privileges.

**Comment by jfagoagas** [comment]
The above PR is the fix ⬆️

**Comment by ernievd** [comment]
When do you think a new major release will be created with this fix?

**Comment by jfagoagas** [comment]
I think tomorrow maybe.

**Comment by ernievd** [comment]
I see that it did not make it into the latest release from today - 3.9.0
