### ISSUE TITLE
[Bug]: False Positives for - Check if SNS topics have policy set as Public Checks

### ISSUE THREAD

**Issue by json-yo** [toniblyx/prowler#2782]
### Steps to Reproduce

1. Run Prowler Pro scanner against tgt account.

***** I think it might be throwing false positives because it checks Principal Statement value only and does not take into consideration a Condition block value.

### Expected behavior

Expected behavior would be to more robustly check the Topic policy to avoid any false positives.

### Actual Result with Screenshots or Logs

![image](https://github.com/prowler-cloud/prowler/assets/103769090/7bee005c-6b2b-4578-9a06-40667fba4643)

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

Prowler Pro account.

### OS used

N/A

### Prowler version

Whatever the Prowler Pro version as of 8.28.23 is. I don't see it.

### Pip version

N/A

**Comment by n4ch04** [comment]
Hi @json-yo, we'll follow up this in the slack channel if you don't mind

**Comment by n4ch04** [comment]
Is already solved in release `3.9.0` closing this
