### ISSUE TITLE
Ability to write pure unix timestamp to output files

### ISSUE THREAD

**Issue by ramses999** [toniblyx/prowler#2805]
### New feature motivation

Currently, the file output (for example, a json file) contains the "AssessmentStartTime" field, which has already been converted taking into account the clock time of the running environment.
In a large organization with different time zones and different SIEMs, we want to have a universal metric.

### Solution Proposed

Add the key `--unixtimestamp`, which will write unix timestamp instead of the converted time

### Describe alternatives you've considered

This is a simple addition, no alternatives

### Additional context

In real life, we encountered the fact that SIEM from one region does not correctly parse the “AssessmentStartTime” field and thus events fall into a future period, which for SIEM has not yet arrived

**Comment by n4ch04** [comment]
Hi @ramses999,

Very good idea, we'll add it as a general flag.
We'll let you know when we have something

**Comment by n4ch04** [comment]
Hi @ramses999, 
Can you try the solution of the linked PR?

**Comment by ramses999** [comment]
@n4ch04 I tested it on a real account and uploaded it to SIEM, everything works correctly, thanks for doing it quickly!

I will be looking forward to the merge into the main branch and the new version of https://hub.docker.com/r/toniblyx/prowler to use in the Kubernetes environment )

**Comment by ramses999** [comment]
@n4ch04 After testing for several days, it seemed to me that using sub-second in unixtimestamp is an excessive measure. Perhaps it should be removed.
So, for example, my SIEM, when trying to display many events from prowler, issues a warning "Events might not be returned in sub-second order due to search memory limits. See search.log for more information. Increase the value of the following limits.conf setting:[ search]:max_rawsize_perchunk."

This doesn’t break anything, but again, it seems that no one needs sub-seconds in unixtimestamp.

Explanation: sub-second is when after the numbers there is still a dot and additional numbers (example: 1694671804.0)
<img width="321" alt="image" src="https://github.com/prowler-cloud/prowler/assets/108680000/5d43b02a-7428-43e7-a78d-1b822fd85735">
<img width="1415" alt="image" src="https://github.com/prowler-cloud/prowler/assets/108680000/7cb5c49c-e49d-4e0a-ba44-30408f6b9f4f">

**Comment by jfagoagas** [comment]
Hi @ramses999, could you please test it with the above PR? We've removed the sub-second part from the unix timestamp.
