### ISSUE TITLE
Add "curl" to Docker image

### ISSUE THREAD

**Issue by ramses999** [toniblyx/prowler#2806]
### New feature motivation

In the docker file (https://hub.docker.com/r/toniblyx/prowler) install the “curl” command in order to be able to sequentially send output to the SIEM HTTP Event Collector.

### Solution Proposed

Add curl to the Dockerfile

### Describe alternatives you've considered

Nope

### Additional context

When using image inside a cronjob (for example like here:
https://github.com/prowler-cloud/prowler/blob/master/contrib/k8s/cronjob.yml) it is impossible to add a command that sends results to SIEM HEC.
You need to either (1) rebuild the image and lose flexibility in updating, or (2) keep a sidecar container for sending files, which increases the amount of resources.

It seems that adding the curl command to the shared image does not pose any big risks and does not increase disk space.

**Comment by n4ch04** [comment]
Hi @ramses999,

Since it is not a big change, or a non-official package, we could add it yes.
We'll reach you when it is done.
