### ISSUE TITLE
Add batching for sending AWS Security Hub findings 

### ISSUE THREAD

**Issue by scottbward** [toniblyx/prowler#2840]
### New feature motivation

When customers with a large volume of resources run prowler to report on their resources and import the results into Security Hub they are running into API throttling rate limits which is impacting the ability for customers to get all their Prowler findings into Security Hub in a timely manner.  The main cause of this is that findings are sent to Security Hub one by one instead of batches.   The BatchImportFindings API for Security Hub allows up to 100 findings to be batched together in a single request.  

The feature ask is that the integration with AWS Security Hub be updated so that findings are collected and sent to Security Hub in batches.  Batch sizes of 100 are the max that can be sent but even an non-optimal batching strategy could help in significantly reducing the number of calls that are made to BatchImportFindings.  

Here is the API limits that are published for Security Hub: https://docs.aws.amazon.com/securityhub/1.0/APIReference/Welcome.html

### Solution Proposed

From what I can tell the sending of findings to Security Hub is initiated here: https://github.com/prowler-cloud/prowler/blob/bc11537350e1e919eff4a02d4d3fcd3e109c6d11/prowler/lib/outputs/outputs.py#L116.   

What I believe would need to happen is that some logic would need to be added before the send_to_security_hub call is made where findings are collected into a batch and then when a batch limit is reached, or there are no more findings to report on, the current batch of findings is sent to Security Hub.  

### Describe alternatives you've considered

No other alternatives considered.

**Comment by jfagoagas** [comment]
Thanks for reporting it @scottbward, I'll take a look this week. Thanks!

**Comment by jfagoagas** [comment]
Hi @scottbward, the above PR improves the behaviour of the Security Hub integration sending the findings in batches up to 100.

Thanks for using Prowler 🚀
