### ISSUE TITLE
Change where Prowler integration check for AWS Security Hub is called

### ISSUE THREAD

**Issue by scottbward** [toniblyx/prowler#2841]
### New feature motivation

When a customer is importing findings into AWS Security Hub a call is made to confirm that the prowler integration is enabled in Security Hub.    The current implementation of the security hub integration is making this confirmation call every time a finding is sent to Security Hub.   This means that if during one prowler report run a customer has 1000 findings, this call to confirm the integration is enabled is also called 1000 times when only needs to be called once before sending the first finding as part of a report run.  

### Solution Proposed

The current check to see if the integration is enabled is called in this library: https://github.com/prowler-cloud/prowler/blob/bc11537350e1e919eff4a02d4d3fcd3e109c6d11/prowler/providers/aws/lib/security_hub/security_hub.py#L32C1-L33C1.    I think that the right place to put this check is right before the call to send a finding to security hub: https://github.com/prowler-cloud/prowler/blob/bc11537350e1e919eff4a02d4d3fcd3e109c6d11/prowler/lib/outputs/outputs.py#L111.  Logic here should have a variable to track that the integration is confirmed as enabled and then use the state of that variable to only check that the integration is enabled for the first finding and then skip the check for all additional findings.  

### Describe alternatives you've considered

No alternatives considered.

**Comment by jfagoagas** [comment]
Thanks for reporting it @scottbward, I'll take a look this week. Thanks!

**Comment by jfagoagas** [comment]
Hi @scottbward, the above PR improves the behaviour of the Security Hub integration, checking just one time per region audited if the service is enabled and the integration configured.

Thanks for using Prowler 🚀
