### ISSUE TITLE
[Bug]:  ssm_managed_compliant_patching: value of FindingUniqueId changes but the resource is the same

### ISSUE THREAD

**Issue by aviramshm** [toniblyx/prowler#2854]
### Steps to Reproduce

Just run Prowler scan that includes this check

### Expected behavior

I expect that for the same resource I will get the same id (item["ResourceId"]).

### Actual Result with Screenshots or Logs

resource_id seems to be changing for any new query for resource summary, even if the resource remains the same. That breaks the fingerprint.

Relevant code:
```python
def __list_resource_compliance_summaries__(self, regional_client):
        logger.info("SSM - List Resources Compliance Summaries...")
        try:
            list_resource_compliance_summaries_paginator = (
                regional_client.get_paginator("list_resource_compliance_summaries")
            )
            for page in list_resource_compliance_summaries_paginator.paginate():
                for item in page["ResourceComplianceSummaryItems"]:
                    resource_id = item["ResourceId"]
                    resource_status = item["Status"]

                    self.compliance_resources[resource_id] = ComplianceResource(
                        id=resource_id,
                        status=resource_status,
                        region=regional_client.region,
```
For each new summary query, item["ResourceId"] refers to to the new summary id and not to the resource id. When it’s saved to resource_id, it breaks the fingerprint, since it practically points to other resource, while it’s the same one.

### How did you install Prowler?

`RUN pip3 install prowler==$CONTROL_VERSION`

### Environment Resource

Fargate batch

### OS used

linux debian slim bookworm image (https://github.com/docker-library/python/blob/81b6e5f0643965618d633cd6b811bf0879dee360/3.9/slim-bookworm/Dockerfile#L7)

### Prowler version

3.8.2

### Pip version

23.0.1

**Comment by jfagoagas** [comment]
Hi @aviramshm, I can't reproduce the issue on our side. What is the `ResourceType` for the items whose `ResourceId` changes?

For the `ManagedInstance` type the `ResourceId` is always the same with the EC2 Instance Id.

**Comment by jfagoagas** [comment]
Hi @aviramshm, do you have any updates on this? Thanks!

**Comment by avichayJit** [comment]
Hi @jfagoagas thanks for responding and sorry for the delay on our side,

the ResourceType is AwsEc2Instance as declared in the check's json [link](https://github.com/prowler-cloud/prowler/blob/1230a3323dc558e53c83f7d4dab7d0299ba9a93e/prowler/providers/aws/services/ssm/ssm_managed_compliant_patching/ssm_managed_compliant_patching.metadata.json#L10C20-L10C34).

The scenario was that we ran the tool once a day, and for each run we got different ResourceId  about the same instance.

Thanks

**Comment by jfagoagas** [comment]
Hi @aviramshm @avichayJit I'm not being able to reproduce the issue on our side. I'm running Prowler several times and for the same EC2 instance the check `ssm_managed_compliant_patching` generates the same `FindingUniqueId`.

Could you please try again using the latest Prowler release `3.10.0`?

Thanks!

**Comment by jfagoagas** [comment]
Hi @aviramshm @avichayJit we cannot reproduce this on our side. Please try again with Prowler `3.11.2` which is the latest release and feel free to reopen it if you notice the same behaviour.

Thanks for using Prowler 🚀
