### ISSUE TITLE
[Bug]: Cloudwatch Logs Metric Failures Alert Not Passing

### ISSUE THREAD

**Issue by zfLQ2qx2** [toniblyx/prowler#2904]
### Steps to Reproduce

1. prowler aws --role ${ROLE_ARN} --verbose --output-modes json --checks cloudwatch_log_metric_filter_and_alarm_for_aws_config_configuration_changes_enabled --log-level DEBUG --session-duration 3600
2. AWS
4. AWS w/ Organizatons
5. 4. Fail

### Expected behavior

Under Power v3 we are failing all of the cloudwatch log metric filter alert checks even though they pass unde rProwler v2 and a commerical equivelant. I have been working with @jfagoagas on this issue which stemmed from a previous issue. Currrent thoughts are that the failure is due to the presence of newline characters in the filter definition, however the \s modifiers in the regex pattern should match the \n's just fine - it looks like the Python regex module needs an additional api level flag in order to process multiline patterns. If that is not the issue we might need to do a detailed comparison of the pattern and the filter definition to see why it does not match.  

### Actual Result with Screenshots or Logs

The check fails

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

Fargate task run in the master account for our AWS Organization where both the organization cloudtrail and the metric filters both live.

### OS used

Alpine Linux

### Prowler version

Prowler 3.9.0

### Pip version

Latest

**Comment by jfagoagas** [comment]
Thanks @zfLQ2qx2, to add more context I'm going to include the configuration you have in this thread (removing any sensitive data):

### CloudWatch FilterPattern
```
{
            "filterName": "AWSConfigConfigurationChangeFilter",
            "filterPattern": "{\n  ($.eventSource = config.amazonaws.com) &&\n  (($.eventName=StopConfigurationRecorder)||\n   ($.eventName=DeleteDeliveryChannel)||\n   ($.eventName=PutDeliveryChannel)||\n   ($.eventName=PutConfigurationRecorder))\n}",
            "metricTransformations": [
                {
                    "metricName": "AWSConfigConfigurationChanges",
                    "metricNamespace": "CloudTrailMetrics",
                    "metricValue": "1"
                }
            ],
            "creationTime": 1642559444033,
            "logGroupName": "/cloudtrail"
        },
```

### Regex Used by the check
`cloudwatch_log_metric_filter_and_alarm_for_aws_config_configuration_changes_enabled`

```
r"\$\.eventSource\s*=\s*.?[config.amazonaws.com](http://config.amazonaws.com/).+\$\.eventName\s*=\s*.?StopConfigurationRecorder.+\$\.eventName\s*=\s*.?DeleteDeliveryChannel.+\$\.eventName\s*=\s*.?PutDeliveryChannel.+\$\.eventName\s*=\s*.?PutConfigurationRecorder.?"
```

### Test with Python 3.11
```
Python 3.11.4 (main, Jun 20 2023, 17:23:00) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> pattern = r"\$\.eventSource\s*=\s*.?config.amazonaws.com.+\$\.eventName\s*=\s*.?StopConfigurationRecorder.+\$\.eventName\s*=\s*.?DeleteDeliveryChannel.+\$\.eventName\s*=\s*.?PutDeliveryChannel.+\$\.eventName\s*=\s*.?PutConfigurationRecorder.?"
>>> from re import search
>>> search(pattern, "{\n  ($.eventSource = config.amazonaws.com) &&\n  (($.eventName=StopConfigurationRecorder)||\n   ($.eventName=DeleteDeliveryChannel)||\n   ($.eventName=PutDeliveryChannel)||\n   ($.eventName=PutConfigurationRecorder))\n}")
None
```

### Comments
- Regarding the possibility of including `re.MULTILINE` within the `search` does not changes the output, it is still not matching it.
- Without the newline character `\n` the regex matches fine.

**Comment by MrCloudSec** [comment]
Hi @zfLQ2qx2 , I've just made a PR with adding a flag that may solve this issue. Can you try it and reopen the issue if you still face it? Thanks!
