### ISSUE TITLE
[Bug]: ec2_securitygroup_not_used does not take security groups protecting lambdas into account

### ISSUE THREAD

**Issue by niclan** [toniblyx/prowler#2943]
### Steps to Reproduce

1. `prowler aws --checks ec2_securitygroup_not_used`
2. In aws
3. Multi-account environment but scanning a single AWS account only

### Expected behavior

Create a report of all unused ec2 security groups

### Actual Result with Screenshots or Logs

The report lists security groups that are attached to lambas as shown by

```shell
aws lambda list-functions --region $region --query 'Functions[*].VpcConfig.SecurityGroupIds[*]'
```

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

7. Linux laptop

### OS used

5. Ubuntu 23.04

### Prowler version

Prowler 3.10.0 (it is the latest version, yay!)

### Pip version

pip 23.0.1 from /usr/lib/python3/dist-packages/pip (python 3.11)

### Context

I have tested prowler and another tool to find _the_ list of unused SGs so they can be deleted by script. Tested both and found that the list of unused SGs had different lengths.

The difference, as far as I can understand, is that prowlers `ec2_securitygroup_not_used` lists security groups that are attached to lambdas as shown by

```
aws lambda list-functions --query 'Functions[*].VpcConfig.SecurityGroupIds[*]' --output text
```

... which means that they are used and does not belong in the report.

**Comment by MrCloudSec** [comment]
Hi @niclan , awesome catch!! 
We will add this logic soon, thank you 😄
