### ISSUE TITLE
[Bug]: Region Case Discrepancy

### ISSUE THREAD

**Issue by TheTechromancer** [toniblyx/prowler#2967]
### Steps to Reproduce

Thanks for making this tool, it's very useful. We've run into a small bug where the same region shows up twice due to case a discrepancy.

1. Command: `gcp --project-ids project1 project2 --credentials-file cred.json -o prowler --verbose`
2. Environment: GCP

### Expected behavior

It would be nice if regions were lowercased so they don't show up as duplicates.

### Actual Result with Screenshots or Logs

![image](https://github.com/prowler-cloud/prowler/assets/20261699/c293ff83-c76f-4abf-a01e-6bea0f23e3b3)

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

Workstation

### OS used

Arch Linux

### Prowler version

3.10.0

### Pip version

22.0.2 (python 3.10)

**Comment by MrCloudSec** [comment]
Good catch @TheTechromancer ! Thank you for letting us know, we will fix it shortly.
