### ISSUE TITLE
[Bug]: the "ec2_securitygroup_not_used" rule doesn't contain "security group associated" situation

### ISSUE THREAD

**Issue by ripperi8u** [toniblyx/prowler#3009]
### Steps to Reproduce

as the title describes,the "ec2_securitygroup_not_used" rule doesn't contain "security group associated" situation

### Expected behavior

the rule should be updated

### Actual Result with Screenshots or Logs

N/A

### How did you install Prowler?

From brew (brew install prowler)

### Environment Resource

Workstation

### OS used

MacOS

### Prowler version

3.10.0

### Pip version

23.2.1

**Comment by MrCloudSec** [comment]
Hi @ripperi8u , thanks for reaching us out. What do you mean about the "security group associated" situation?

**Comment by ripperi8u** [comment]
> Hi @ripperi8u , thanks for reaching us out. What do you mean about the "security group associated" situation?
The situation that a security group is used by another security group.Then you delete a security group in aws console,it will prompt you like the picture below
![image](https://github.com/prowler-cloud/prowler/assets/14286761/bf4694ce-81a0-4ca4-a88f-f57ab3857d14)

**Comment by MrCloudSec** [comment]
Good point @ripperi8u , can we know to which asset is this security group associated?

**Comment by ripperi8u** [comment]
> Good point @ripperi8u , can we know to which asset is this security group associated?

This security group is associated by another security group.The usage is like securitygroup A is used in the source area of one of securitygroup B's rule,such as the picture below:
![image](https://github.com/prowler-cloud/prowler/assets/14286761/a566e06d-ae77-4def-ab3f-0019e66755f1)

**Comment by MrCloudSec** [comment]
The PR above solves this issue, thanks for letting us know !
