### ISSUE TITLE
[Bug]:  empty json-ocsf output

### ISSUE THREAD

**Issue by joaoneri-io** [toniblyx/prowler#3018]
### Steps to Reproduce

When I run:
aws-vault exec env -- prowler aws -R arn:aws:iam::{account_id}:role/{role_name} -I {external_id} -M json-ocsf -s cloudwatch -F test1-json-ocsf
it generates an empty json-ocsf file, the content is just [ ]
But when I run:
aws-vault exec env -- prowler aws -R arn:aws:iam::{account_id}:role/{role_name} -I {external_id} -M json -s cloudwatch -F test2-json 
it works.
And when I run:
aws-vault exec env -- prowler aws -R arn:aws:iam::{account_id}:role/{role_name} -I {external_id} -s cloudwatch -F test3-all-files
it generates all extensions, including the json-ocsf, but not empty
![prowler-outputs](https://github.com/prowler-cloud/prowler/assets/122455095/a6ab1c0f-819f-4a5a-9f20-492b1ac81704)

### Expected behavior

The -M json-ocsf should not generate an empty json-ocsf file

### Actual Result with Screenshots or Logs

![prowler-result-output](https://github.com/prowler-cloud/prowler/assets/122455095/41fa11a8-dc2f-4243-9b13-243f212c18d2)

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

Fargate task.
Local machine.

### OS used

Ubuntu

### Prowler version

3.11

### Pip version

22.0.2

**Comment by MrCloudSec** [comment]
Hi @joaoneri-io , good catch! Thanks for reaching us out, we will fix it shortly.

**Comment by MrCloudSec** [comment]
Hi @joaoneri-io , I could not reproduce your error with the same commands. It may be a problem with your machine. Are you still facing the issue?

**Comment by rvisc** [comment]
I encountered a similar problem in version 3.11.2.
If I run the command 
**prowler aws --log-level CRITICAL --log-file prowler.log -M json-ocsf -z**
I get an ocsf.json file that contains only "[]".
If I run the same command asking to generate a json, csv, or json-osff, everything works.

**Comment by MrCloudSec** [comment]
@rvisc can you execute it with `--log-level ERROR`? and send us the logs, please?

**Comment by rvisc** [comment]
[prowler.log](https://github.com/prowler-cloud/prowler/files/13377457/prowler.log)
Here is the log you requested.

**Comment by MrCloudSec** [comment]
The above PR solves the issue, thanks for letting us know!

**Comment by rvisc** [comment]
Perfect!
Thanks

**Comment by joaoneri-io** [comment]
Thank you @sergargar

**Comment by djinnert** [comment]
@sergargar This might have got reintroduced in 4.x. Having the same issue in 4.1.0 where it's not present in 3.16.3.
