### ISSUE TITLE
support for aws msk

### ISSUE THREAD

**Issue by akothawala** [toniblyx/prowler#3049]
### New feature motivation

enable support for aws msk (Managed service for kafka)

### Solution Proposed

Enable msk service support in prowler

### Describe alternatives you've considered

Not Yet

**Comment by MrCloudSec** [comment]
Hi @akothawala, thanks for opening the issue. We have added Amazon Managed Streaming for Apache Kafka service's checks in our roadmap. Stay tuned for the next releases!
