### ISSUE TITLE
[Bug]: Getting too many files open error

### ISSUE THREAD

**Issue by matttheplanet** [toniblyx/prowler#3061]
### Steps to Reproduce

I hadn't noticed this before, but running on the AWS Ubuntu image I was getting a too many open files error. Increasing the ulimit to 4096 `ulimit -n 4096` fixed the issue. I was running in Screen in one case and had the same issue within Tmux. Didn't try not in Tmux or Screen. 

### Expected behavior

To work with default Ubuntu builds. 

### Actual Result with Screenshots or Logs

2023-11-22 23:36:00,875 [File: utils.py:24]     [Module: utils]  CRITICAL: Ooops! You reached your user session maximum open files. To solve this issue, increase the shell session limit by running this command `ulimit -n 4096`. For more info visit https://docs.prowler.cloud/en/latest/troubleshooting/

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

EC2 instance, with 8GB and one with 16GB of RAM.

### OS used

Ubuntu 22.04.3 LTS

### Prowler version

3.11.3

### Pip version

22.0.2

**Comment by jfagoagas** [comment]
Hi @matttheplanet, we decided to do it that way and inform users about the error not to modify session's user settings while running Prowler. Do you have any ideas or workarounds to handle this better? It'll be appreciated to hear from you.

Thanks for using Prowler 🚀

**Comment by jfagoagas** [comment]
Hi @matttheplanet, we are closing this issue since there is no possible action from our side.

Please if you have any ideas or workarounds to handle this better, it'd be appreciated to hear from you.

Thanks for using Prowler 🚀
