### ISSUE TITLE
--status PASS|INFO|FAILED

### ISSUE THREAD

**Issue by MrAtheist** [toniblyx/prowler#3062]
### New feature motivation

Provides a quick glimpse at the failed resources, instead of doing the filtering after the fact; besides the output filesize would be much smaller as well (semi related to #1928 )

### Solution Proposed

`prowler <provider> --status PASS|INFO|FAILED`

### Describe alternatives you've considered

Filtering after the fact on a giant csv/html/json is probably less than ideal...

**Comment by jfagoagas** [comment]
Hi @MrAtheist actually Prowler supports the `-q/--quiet` flag just to raise `FAIL` findings, have you tried that? 

Please refer to the following link to check the documentation for this flag https://docs.prowler.cloud/en/latest/tutorials/misc/#show-only-fails

**Comment by MrAtheist** [comment]
d'oh, thanks!

**Comment by jfagoagas** [comment]
Hi @MrAtheist just to let you know that Prowler v4 supports the `--status` flag, you can read more https://docs.prowler.com/projects/prowler-open-source/en/latest/tutorials/misc/#filter-findings-by-status

Thanks for using Prowler 🚀
