### ISSUE TITLE
[Bug]: VPC Scan for empty account fails to find resilient VPCs

### ISSUE THREAD

**Issue by williambrady** [toniblyx/prowler#3080]
### Steps to Reproduce

Target an empty account, or one with No VPCs.

`prowler aws --services vpc `

### Expected behavior

If there are no VPCs there should be an assumption none are needed. A failure to detect a fault tolerant VPC in another region should not throw an error that there is no second VPC; because there is no first VPC.

### Actual Result with Screenshots or Logs

![2023-11-29_12-11-45-prowler-no-vpc](https://github.com/prowler-cloud/prowler/assets/32752121/8616acf0-56ff-4ec6-b620-84108d5c6b5c)

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

Local Windows host using WSL: Kali

### OS used

Kali Linux

### Prowler version

Prowler 3.11.3

### Pip version

pip 23.3.1

### Context

I fixed this locally by adding a simple ` or len(vpc_regions) == 0` to the check in `vpc_different_regions.py`

**Comment by jfagoagas** [comment]
Hi @williambrady, I totally agree with you, the check `vpc_different_regions` should not raise any findings if there are no VPCs. We will push a fix for this and a test tomorrow.

Thanks for noticing this and using Prowler 🚀

**Comment by williambrady** [comment]
Thanks for the feedback. I submitted a PR of the change I made locally in case you want to just use that.

https://github.com/prowler-cloud/prowler/pull/3081

This is a fun tool.
