### ISSUE TITLE
[Suggestion] Improve Lambda code pulling and secret checking performance

### ISSUE THREAD

**Issue by Fennerr** [toniblyx/prowler#3084]
### New feature motivation

Performance can be improved by not checking the same lambda function deployed across different regions (reduces time taken to pull the code for the functions, and the time taken repeatedly scanning the same function)

### Solution Proposed

Make a map of the lambda hashes, and the regions the lambda is deployed in.
Only scan each unique lambda function.

### Describe alternatives you've considered

None

**Comment by jfagoagas** [comment]
Discussion in the Prowler Slack -> https://prowler-workspace.slack.com/archives/C045JNJLUDA/p1701418142297439

**Comment by jfagoagas** [comment]
Closed since Lambdas have different hashes and ARNs -> https://prowler-workspace.slack.com/archives/C045JNJLUDA/p1701431960990969?thread_ts=1701418142.297439&cid=C045JNJLUDA
