### ISSUE TITLE
[Bug]: prowler azure is not scanning virtual machines in azure

### ISSUE THREAD

**Issue by anushaks579** [toniblyx/prowler#3171]
### Steps to Reproduce

![Azure services for prowler](https://github.com/prowler-cloud/prowler/assets/52813866/33f2ebc1-1181-4ad8-8b1a-a5ea977596ea)

### Expected behavior

prowler services by default it provide 4 services but its not included virtual machines , Is there any way we can scan azure virtual machines to get the open port details.

### Actual Result with Screenshots or Logs

![Azure services for prowler](https://github.com/prowler-cloud/prowler/assets/52813866/e589ed82-9d5b-409e-9504-6e22024dfa6e)

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

azure Virtual machine

### OS used

Linux ubuntu 22.04

### Prowler version

v3.11.0

### Pip version

3.5.6

### Context

Please help in steps for prowler for azure in Linux machine to scan azure virtual machines.

**Comment by n4ch04** [comment]
Hi @anushaks579,

Yes, the azure provider is missing some checks and services, we would like to have it completed as soon as possible.
If you can list which checks are you missing, apart from the vm open ports one, it would help us a lot (we can start from that point)

**Comment by anushaks579** [comment]
In the report prowler scans azure subscription for VMs it has to display in which VM port are open if its open it should display some warning message some thing like that because when all ports open its easy to hack the data.
Also we need to add one check about the user who opened which port OR who created the network security group and access , log time like that in that report.
Lack of Azure documentation compare to AWS prowler.

**Comment by jfagoagas** [comment]
Hi @anushaks579 recently we've finished the CIS 2.0 and 2.1 for Azure including the following checks related to open ports:
- `network_rdp_internet_access_restricted`
- `network_ssh_internet_access_restricted`
- `network_watcher_enabled`

What are your requirements about scanning virtual machines? Does those checks cover what you need? Please give it a try and let us know.

Thanks for using Prowler 🚀

**Comment by MrCloudSec** [comment]
Closing the PR since the checks were already added.
