### ISSUE TITLE
[Bug]: Prowler killed by OOM killer when run in AWS CloudShell

### ISSUE THREAD

**Issue by AlexGidarakos** [toniblyx/prowler#3187]
### Steps to Reproduce

1. What command are you running?
prowler aws -M csv

2. Cloud provider you are launching
AWS

3. Environment you have, like single account, multi-account, organizations, multi or single subscription, etc.
AWS account managed by an Organization

The process stops before reaching 100% and the CLI output shows the word "Killed" in the progress meter line

### Expected behavior

Prowler finishes the scan to 100% 

### Actual Result with Screenshots or Logs

```
[cloudshell-user@ip-10-2-39-206 ~]$ prowler aws -M csv
                         _
 _ __  _ __ _____      _| | ___ _ __
| '_ \| '__/ _ \ \ /\ / / |/ _ \ '__|
| |_) | | | (_) \ V  V /| |  __/ |
| .__/|_|  \___/ \_/\_/ |_|\___|_|v3.11.3
|_| the handy cloud security tool

Date: 2023-12-12 12:45:15
This report is being generated using credentials below:
AWS-CLI Profile: [default] AWS Filter Region: [all]
AWS Account: [REDACTED] UserId: [REDACTED]
Caller Identity ARN: [REDACTED]
Executing 301 checks, please wait...
Killednning trustedadvisor service |▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▏ | - 287/301 [95%] in 6:17 

[cloudshell-user@ip-10-2-39-206 ~]$ dmesg | grep prowler
[ 5397.074654] [10724]  1000 10724   740192   425393    1093       7   114848             0 prowler
[ 5397.077604] Memory cgroup out of memory: Kill process 10724 (prowler) score 927 or sacrifice child
[ 5397.078569] Killed process 10724 (prowler) total-vm:2960768kB, anon-rss:1701572kB, file-rss:0kB, shmem-rss:0kB
[ 5397.496623] oom_reaper: reaped process 10724 (prowler), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB

[cloudshell-user@ip-10-2-39-206 ~]$ uname -a
Linux ip-10-2-39-206.eu-west-2.compute.internal 4.14.255-326-265.539.amzn2.x86_64 #1 SMP Fri Oct 6 23:55:28 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

AWS CloudShell

### OS used

```
[cloudshell-user@ip-10-2-39-206 ~]$ cat /etc/os-release 
NAME="Amazon Linux"
VERSION="2023"
ID="amzn"
ID_LIKE="fedora"
VERSION_ID="2023"
PLATFORM_ID="platform:al2023"
PRETTY_NAME="Amazon Linux 2023"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2023"
HOME_URL="https://aws.amazon.com/linux/"
BUG_REPORT_URL="https://github.com/amazonlinux/amazon-linux-2023"
SUPPORT_END="2028-03-01"
```

### Prowler version

3.11.3

### Pip version

21.3.1

### Context

I understand that the AWS CloudShell environment has limited RAM:

```
cloudshell-user@ip-10-2-39-206 ~]$ free -m
               total        used        free      shared  buff/cache   available
Mem:            2571         266        1211           0        1093        2151
Swap:            488          37         450
```

However the Prowler documentation implies that CloudShell is a supported installation method:
https://docs.prowler.cloud/en/latest/#installation

**Comment by jfagoagas** [comment]
Hi @AlexGidarakos currently we are working to improve the Prowler's memory management. The AWS CloudShell is a supported environment to execute Prowler but due to the restricted memory on that environment you can experience some issues if you are auditing a big AWS account. 

Can you estimate the number of resources in the account?

Do you know if some services have a large number of resources, I mean way more than the rest of the services?

Thanks for using Prowler 🚀

**Comment by AlexGidarakos** [comment]
Hi @jfagoagas. Checking in AWS Tag Editor there are around 400 resources in this account, with the most important ones being:

15 CloudFormation stacks
235 Config rules
2 DynamoDB tables
1 IGW
1 NACL
20 ENIs
9 RTBs
8 SGs
8 Subnets
1 VPC
1 ECS Cluster with 3 Fargate Services running 2 tasks each
1 ElastiCache cluster with 2 nodes
1 ALB with 3 Target Groups
5 KMSs
16 Lambdas
1 Aurora Cluster with PSQL-compatible engine with 2 instances
13 DB Cluster Snapshots
17 S3 buckets
5 SSM Parameters
32 Secrets Manager secrets

Thanks for looking into this bug report.

**Comment by jfagoagas** [comment]
@AlexGidarakos thanks for the quick response. Could you please execute Prowler using the branch `Fennerr:issue-2516` from this PR? https://github.com/prowler-cloud/prowler/pull/3167?

Thanks!

**Comment by AlexGidarakos** [comment]
Hi again @jfagoagas. I can confirm that using the code from said branch allows the scan to complete without issues. Please let me know if any further information would be useful.

Thanks.

P.S.: Just FYI the limited storage that AWS CloudShell provides for the user's home directory causes issues when installing the poetry dependencies to run Prowler from GitHub. For posterity, here's a workaround:

```
git clone https://github.com/Fennerr/prowler.git
cd prowler
git checkout issue-2516
pip install poetry
mkdir /tmp/pypoetry
poetry config cache-dir /tmp/pypoetry
poetry shell
...
```

**Comment by jfagoagas** [comment]
> Hi again @jfagoagas. I can confirm that using the code from said branch allows the scan to complete without issues. Please let me know if any further information would be useful.
> 
> Thanks.
> 
> P.S.: Just FYI the limited storage that AWS CloudShell provides for the user's home directory causes issues when installing the poetry dependencies to run Prowler from GitHub. For posterity, here's a workaround:
> 
> ```
> git clone https://github.com/Fennerr/prowler.git
> cd prowler
> git checkout issue-2516
> pip install poetry
> mkdir /tmp/pypoetry
> poetry config cache-dir /tmp/pypoetry
> poetry shell
> ...
> ```

That's a great catch @AlexGidarakos, I'm going to include in our docs. Btw, we've merged the fix PR!

**Comment by jfagoagas** [comment]
Included in the docs @AlexGidarakos --> https://github.com/prowler-cloud/prowler/pull/3190 Thanks!
