### ISSUE TITLE
[Bug]: Cross account sqs flagged as public/critical 

### ISSUE THREAD

**Issue by SwanimaChinnappa** [toniblyx/prowler#3199]
### Steps to Reproduce

prowler -c "sqs_queues_not_publicly_accessible" --verbose

SQS queue with a policy out of the AWS [docs](https://repost.aws/knowledge-center/sns-and-sqs-cross-account-subscription) to allow SendMessage from SNS in another AWS Account:
```
{
  "Sid": "Stmt1234",
  "Effect": "Allow",
  "Principal": "*",
  "Action": "sqs:SendMessage",
  "Resource": "arn:aws:sqs:us-west-2:111111111111:QueueName",
  "Condition": {
    "ArnEquals": {
      "aws:SourceArn": "arn:aws:sns:us-west-2:555555555555:TopicName"
    }
  }
}
```
Will cause the critical finding here: https://github.com/prowler-cloud/prowler/blob/master/tests/providers/aws/services/sqs/sqs_queues_not_publicly_accessible/sqs_queues_not_publicly_accessible_test.py#L270

### Expected behavior

It should act the same as when the condition is for an [SNS topic in the same account](https://github.com/prowler-cloud/prowler/blob/master/tests/providers/aws/services/sqs/sqs_queues_not_publicly_accessible/sqs_queues_not_publicly_accessible_test.py#L236), which doesn't lead to a finding. 

### Actual Result with Screenshots or Logs

Critical finding here: https://github.com/prowler-cloud/prowler/blob/master/tests/providers/aws/services/sqs/sqs_queues_not_publicly_accessible/sqs_queues_not_publicly_accessible_test.py#L270

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

CodeBuild

### OS used

Amazon Linux2

### Prowler version

3.11.3

### Pip version

23.3.1

**Comment by n4ch04** [comment]
HI @SwanimaChinnappa, interesting ...
We'll inspect this a little bit and reach you when we have something.
Thanks for using Prowler !!!

**Comment by n4ch04** [comment]
After reviewing this, @SwanimaChinnappa you are right, that condition testing in the check should not be that restrictive.
We are gonna change it and let you know !!
Good catch !!!

**Comment by n4ch04** [comment]
@SwanimaChinnappa please check the proposed solution
