### ISSUE TITLE
[Bug]: Website Down?

### ISSUE THREAD

**Issue by wingcomm** [toniblyx/prowler#3247]
### Steps to Reproduce

Go to www.prowler.com as listed on Github.

### Expected behavior

The website should work.

### Actual Result with Screenshots or Logs

![Screenshot 2024-01-08 at 5 57 43 PM](https://github.com/prowler-cloud/prowler/assets/9159510/97f2c053-d461-46a7-b4f4-0c7291a9caa8)

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

N/A

### OS used

N/A

### Prowler version

N/A

### Pip version

N/A

**Comment by n4ch04** [comment]
Hi @wingcom, it seems we input a bad url in the repo description, it is now updated.
Thank you for let us now .
Regards !!
