### ISSUE TITLE
Possibility to custom output file using quick inventory

### ISSUE THREAD

**Issue by Mohsen51** [toniblyx/prowler#3305]
### New feature motivation

Today it is impossible to specify a custom file when using the quick inventory option in AWS.

### Solution Proposed

Support for the already existing options -F (output file) when using the quick inventory feature (-i) on AWS.

### Describe alternatives you've considered

N/A

**Comment by MrCloudSec** [comment]
Thank you for solving this, the PR is merged and it will be available in the next release!
