### ISSUE TITLE
[Bug]: False positive on s3_bucket_policy_public_write_access

### ISSUE THREAD

**Issue by dabo-devconsole** [toniblyx/prowler#3346]
### Steps to Reproduce

When scanning a public s3 bucket with an bucket policy like the following, prowler alerts for possible write access.
`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "Statement",
            "Effect": "Allow",
            "Principal": "*",
            "Action": "s3:Get*",
            "Resource": "arn:aws:s3:::redacted-bucket-name/*"
        }
    ]
}`

### Expected behavior

Action statement in bucket policy is properly evaluated.

### Actual Result with Screenshots or Logs

Account with two buckets:

Overview Results:
╭──────────────────┬──────────────────╮
│ 50.0% (1) Failed │ 50.0% (1) Passed │
╰──────────────────┴──────────────────╯

Account *REDACTED* Scan Results (severity columns are for fails only):
╭────────────┬───────────┬──────────┬────────────┬────────┬──────────┬───────╮
│ Provider   │ Service   │ Status   │   Critical │   High │   Medium │   Low │
├────────────┼───────────┼──────────┼────────────┼────────┼──────────┼───────┤
│ aws        │ s3        │ FAIL (1) │          1 │      0 │        0 │     0 │
╰────────────┴───────────┴──────────┴────────────┴────────┴──────────┴───────╯

### How did you install Prowler?

Docker (docker pull toniblyx/prowler)

### Environment Resource

ECS task scanning the account

### OS used

Alpine Linux v3.19

### Prowler version

3.12.1

### Pip version

pip 23.3.2 from /home/prowler/.local/lib/python3.11/site-packages/pip (python 3.11)

**Comment by MrCloudSec** [comment]
Hi @dabo-devconsole , thanks for reaching us out!
We will solve this false positive shortly 👍🏼
