### ISSUE TITLE
[Bug]: The assumed role ARN contains a value for resource type different than role, please input a valid ARN

### ISSUE THREAD

**Issue by pennywise-01** [toniblyx/prowler#3418]
### Steps to Reproduce

1. I was running python prowler.py --security-hub
2. Then i got this output `2024-02-20 11:37:26,698 [File: audit_info.py:379]       [Module: audit_info]     CRITICAL: RoleArnParsingInvalidResourceType[372]: The assumed role ARN contains a value for resource type different than role, please input a valid ARN
`
3. I already do the aws configure stuff

### Expected behavior

The command should run checks for my aws account

### Actual Result with Screenshots or Logs

![image](https://github.com/prowler-cloud/prowler/assets/54774679/b6aad8b6-92b0-47ac-b01a-8a5b29e154fc)

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

Kali Linux

### OS used

Kali Linux

### Prowler version

Prowler 3.13.0

### Pip version

pip

**Comment by jfagoagas** [comment]
Hi @Hafzan-250601, I can't reproduce the issue on our test environments.

- Can you execute it using the `--log-level ERROR` flag? Attach the output here please.
- What type credentials are you using to execute it? 

Thanks for using Prowler 🚀

**Comment by pennywise-01** [comment]
Hi @jfagoagas I already tried to run prowler with the flag you mentioned but the output still the same
![image](https://github.com/prowler-cloud/prowler/assets/54774679/a8c8c9f9-af85-4cd6-a9b9-c1760195f76d)

I used aws configure then put in my access key and secret access key

**Comment by jfagoagas** [comment]
@Hafzan-250601 How did you install Prowler? You said using `pip` in the issue form but then I realised that you are executing `python prowler.py`. 

I'm trying to reproduce the issue again but I can't do either with the `pip` version or cloning from the Github `master` branch.

**Comment by pennywise-01** [comment]
I tried using pip to install prowler but it diddn't work. My bad

**Comment by jfagoagas** [comment]
@Hafzan-250601 is it now fixed? What was the error installing it through `pip`?

**Comment by pennywise-01** [comment]
The installation is fine but when i trying to run it said command not found

**Comment by jfagoagas** [comment]
Probably you don't have the Python in your `${PATH}`, could you please check it?

**Comment by jfagoagas** [comment]
Hi @Hafzan-250601, have you been able to check your ${PATH}? 

Could you please share you AWS credentials configuration since it seems that the IAM Role ARN that you are using is not valid.

Thanks!

**Comment by ghost** [comment]
Hi I am actually getting the same error. Here is my setup and what I did...
MaxOS with zsh
Python version 3.1
Added alias that python3 = python into .zshrc file
running prowler aws under root account having keys stored in the aws credential file.

**Comment by jfagoagas** [comment]
Hi @LongauerJuraj, 

- Could you please execute it using the --log-level ERROR flag? Attach the output here please.
- What type credentials are you using to execute it? Please share the keys, not the values, you have configured in your AWS credentials file.

Thanks!

**Comment by ghost** [comment]
Hi Pepe 👋, so I actually fixed the issue, here is what I did - it was not prowler related.
1. I am using saml2aws tool to establish SSO connection using our SSO Platform Jumpcloud
2. For some reason and this was the root cause for my issue I had this line in my ~/.aws/config file that I commented out
role_arn = arn:aws:iam::<aws ID>:role/view-only
3. Issue fixed 🎉 
Thanks for reaching out Pepe!

**Comment by jfagoagas** [comment]
> Hi Pepe 👋, so I actually fixed the issue, here is what I did - it was not prowler related.
> 
> 1. I am using saml2aws tool to establish SSO connection using our SSO Platform Jumpcloud
> 
> 2. For some reason and this was the root cause for my issue I had this line in my ~/.aws/config file that I commented out
> 
> role_arn = arn:aws:iam::<aws ID>:role/view-only
> 
> 3. Issue fixed 🎉 
> 
> Thanks for reaching out Pepe!

It's nothing @LongauerJuraj, always here to help!!

Thanks for using Prowler 🚀

**Comment by jfagoagas** [comment]
> Hi @Hafzan-250601, have you been able to check your ${PATH}?
> 
> Could you please share you AWS credentials configuration since it seems that the IAM Role ARN that you are using is not valid.
> 
> Thanks!

@Hafzan-250601 Have you been able to review this? Please check that out and let us know.

Thanks!

**Comment by ta1bbty** [comment]
Hey @jfagoagas and @Hafzan-250601 👋 
I've just installed prowler and facing the exact same issue. I am using root creds from my account and `aws sts get-caller-identity` is working fine.

Any suggestions ?
Thank you.

**Comment by jfagoagas** [comment]
Hi @ta1bbty can you share the execution logs with `--log-level ERROR`? Also please share with us the arguments passed to Prowler and the contents of your AWS configuration, either in the `~/.aws/config`, `~/.aws/credentials` or environment variables.

Thanks!

**Comment by jfagoagas** [comment]
Hi @Hafzan-250601 @ta1bbty do you have any update on this?

Thanks!

**Comment by jfagoagas** [comment]
Hi @ta1bbty @Hafzan-250601 @LongauerJuraj , we are closing this issue since we didn't receive any response. Please feel free to reopen it if you notice the same behaviour again.

Thanks for using Prowler 🚀

**Comment by satoridev01** [comment]
@jfagoagas Hi! I'm also currently facing the previously mentioned bug. 

When running on a python docker image with nothing else installed, I get the `CRITICAL: RoleArnParsingInvalidResourceType[363]: The assumed role ARN contains a value for resource type different than role, please input a valid ARN`

<img width="1345" alt="Image" src="https://github.com/user-attachments/assets/d8a0df46-2c12-4a30-b307-e6741be5fbfd" />

**Comment by satoridev01** [comment]
@MrCloudSec Thoughts?

**Comment by jfagoagas** [comment]
Hello @satoridev01 I recommend you using Prowler v5.3 because you are using an old version, if you want to continue using v3 please use the latest release which is 3.16.17.

Let us know if this fixes the issue you are facing.

**Comment by satoridev01** [comment]
@jfagoagas I followed the installation instructions from the README. How should I install a working CLI version?

<img width="650" alt="Image" src="https://github.com/user-attachments/assets/47058284-f695-4e0e-8cf1-6d223bc1a33d" />

**Comment by satoridev01** [comment]
@jfagoagas When trying to install from sources as instructed, it is throwing a colorama error even though it is being installed?

![Image](https://github.com/user-attachments/assets/45ffc454-a5bf-420e-b124-224498167c3c)

**Comment by satoridev01** [comment]
Installing from source (with some slight modifications to the original instructions) did the trick, seems to be running as expected

<img width="1440" alt="Image" src="https://github.com/user-attachments/assets/3ed50caf-2191-438b-8926-c7c1c85705f8" />
