### ISSUE TITLE
[Bug]: Not getting results for GCP compute instances with public IPs

### ISSUE THREAD

**Issue by alon-u3d** [toniblyx/prowler#3426]
### Steps to Reproduce

Running the following check "compute_instance_public_ip" returns 0 results despite there are VMs with public IP in the project.
I also believe there are multiple checks in compute_instance that are not showing true results - compared to what I am seeing in the console.

### Expected behavior

Expected to see the instances with their status.

### Actual Result with Screenshots or Logs

The screenshot shared shows I am not getting any results.

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

Compute Instances / VMs

### OS used

MacOS / Linux

### Prowler version

Prowler 3.13.0

### Pip version

pip 23.3.1

**Comment by alon-u3d** [comment]
Figured it was a permissions issue, thanks for keeping everything updated!

**Comment by alon-u3d** [comment]
False positive, permissions issue on my end :)

**Comment by alon-u3d** [comment]
Actually, double checked, I am an owner on the account, mange to see everything on the console.
When running the checks without specifying the compute_instance_public_ip check it does give me the result, when running it specifically it doesn't return anything.

**Comment by MrCloudSec** [comment]
hey @alonmuallem, can you give us the two commands that are you using, please?

**Comment by alon-u3d** [comment]
prowler gcp --project-ids {project_id} -c compute_instance_public_ip 
Tried that with -F and a filename as well, didn't work either.

**Comment by MrCloudSec** [comment]
tahnks @alonmuallem, and which is the one that works?

**Comment by alon-u3d** [comment]
None of them is giving me actual results.

**Comment by MrCloudSec** [comment]
can you execute it with `--log-level ERROR` and send us the logs, if any, please?

**Comment by alon-u3d** [comment]
Here's the error:
"ERROR: us-central1-f -- KeyError[103]: 'shieldedInstanceConfig'"

**Comment by alon-u3d** [comment]
Just to clarify, with the same account configured, running the gcloud command to list instances does work, so I can get the external IP
![image](https://github.com/prowler-cloud/prowler/assets/88378906/e4ffd4d4-2d3f-4bfc-bee9-e2c72c188119)

**Comment by alon-u3d** [comment]
I intercepted the requests from my terminal, found the following request which does return the relevant instance info, not sure why it doesn't return that in the output or in a file tho
![image](https://github.com/prowler-cloud/prowler/assets/88378906/49575ead-d9a6-4f37-9d5e-6b6ded329edc)

**Comment by MrCloudSec** [comment]
Hi @alonmuallem , thanks for letting us know the error.
I have solved it in the above PR and it will fix this issue.

**Comment by alon-u3d** [comment]
Hi, should I see it when upgrading with brew?
Not sure why but I am always getting version 3.13 instead of 3.14...

Thanks!
