### ISSUE TITLE
[Bug]: AWS ECR service crashing if a repo with no policies exists.

### ISSUE THREAD

**Issue by lucasaboud0** [toniblyx/prowler#3447]
### Steps to Reproduce

Just crate a ecr repository and delete all existent policies.

### Expected behavior

When the script crashes, it stops to check ECR repos policies.

### Actual Result with Screenshots or Logs

An error occurred (RepositoryPolicyNotFoundException) when calling the GetRepositoryPolicy operation: Repository policy does not exist for the repository with name 'REPO_NAME' in the registry with id 'ACCOUNT_ID'

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

Locally

### OS used

2 - Mac OS

### Prowler version

3.14.0

### Pip version

23.3.1

### Context

The problem happens in this file https://github.com/prowler-cloud/prowler/blob/master/prowler/providers/aws/services/ecr/ecr_service.py#L73

I suggest that you implement something like:
```
try:
    policy = client.get_repository_policy(
        repositoryName=repository.name
    )
except:
    policy = []
```

**Comment by lucasaboud0** [comment]
UPDATE: I just tested the solution above, and it works well.
I didn't say, but this is the check: `ecr_repositories_not_publicly_accessible`
<img width="813" alt="Captura de Tela 2024-02-26 às 20 56 48" src="https://github.com/prowler-cloud/prowler/assets/161393583/3b86b964-f1fb-4f3f-aee0-45d037d1d671">

**Comment by lucasaboud0** [comment]
Result without workaround:
![Captura de Tela 2024-02-26 às 21 11 19](https://github.com/prowler-cloud/prowler/assets/161393583/3f3dc64c-b480-4d30-9438-9f9575befb4f)

**Comment by MrCloudSec** [comment]
Hi @lucasaboud0 , thanks for letting us know!
I have fix this issue in the branch `3447-bug-aws-ecr-service-crashing-if-a-repo-with-no-policies-exists`, can you test it there and let me know if it works too?

**Comment by lucasaboud0** [comment]
Hello @sergargar. I just tested and it worked fine. Thank you for your attention.
