### ISSUE TITLE
Allow AWS Control Tower Account Factory for Terraform(AFT) IAM Roles

### ISSUE THREAD

**Issue by dmkim22-lguplus** [toniblyx/prowler#3458]
### New feature motivation

When using AWS Control Tower Account Factory for Terraform (AFT), AFT creates `AWSAFTExecution` and `AWSAFTService` IAM Roles on every AFT managed accounts.

These two roles have `AdministratorAccess` under permission and is checked by `iam_role_administratoraccess_policy.py`, but they also have trust policy set for `AWSAFTAdmin`.

This would be similar to `AWSControlTowerExecution` IAM Role created by AWS Control Tower on every managed accounts, which was added to allow list per [https://github.com/prowler-cloud/prowler/pull/2953](https://github.com/prowler-cloud/prowler/pull/2953).

### Solution Proposed

Add `AWSAFTExecution` and `AWSAFTService` to default aws_allowlist.yaml configuration file.

### Describe alternatives you've considered

None

**Comment by MrCloudSec** [comment]
Hi @dmkim22-lguplus , thanks for letting us know!
I have added them in the above PR.

**Comment by dmkim22-lguplus** [comment]
@sergargar Thank you!
