### ISSUE TITLE
[Bug]: Brew install Prowler requires python 3.12 - Google CLI SDK doesn't support 3.12.2

### ISSUE THREAD

**Issue by alon-u3d** [toniblyx/prowler#3477]
### Steps to Reproduce

Hi, 
When using Brew install prowler I am getting dependency for python 3.12.2 which is not supported by Google CLI SDK.
![image](https://github.com/prowler-cloud/prowler/assets/88378906/86de22ed-721b-4079-a106-e8db26d3348b)

### Expected behavior

Use Prowler with a lower version of Python.

### Actual Result with Screenshots or Logs

Added

### How did you install Prowler?

From brew (brew install prowler)

### Environment Resource

MacOS

### OS used

MacOS

### Prowler version

Prowler 3.14.0 (You are running the latest version, yay!)

### Pip version

pip 24.0 from /opt/homebrew/lib/python3.12/site-packages/pip (python 3.12)

**Comment by jfagoagas** [comment]
Hi @alonmuallem, we need more information to get what's happening. Currently Prowler supports Python 3.12 as well as the Google Cloud SDKs we use internally for the GCP provider. Remember that in Python it is a good practice to use [virtualenvs](https://docs.python.org/3/library/venv.html) to isolate dependencies between projects.

Thanks for using Prowler 🚀

**Comment by jfagoagas** [comment]
Hi @alonmuallem do you have any update on this?

Thanks!

**Comment by jfagoagas** [comment]
Hi @alonmuallem, we are closing this issue since we didn't receive any response. Please feel free to reopen it if you notice the same behaviour again.

Thanks for using Prowler 🚀
