### ISSUE TITLE
[Bug]: 'NoneType' on checks_to_execute

### ISSUE THREAD

**Issue by Xarlos89** [toniblyx/prowler#3478]
### Steps to Reproduce

Command:
`docker run -v NAME:PATH --name NAME --user 0 -e AZURE_CLIENT_ID=XXXX-XXX-XXXX-XXXX -e AZURE_CLIENT_SECRET=******** -e AZURE_TENANT_ID=XXXX-XXX-XXXX-XXXX public.ecr.aws/prowler-cloud/prowler:latest azure --sp-env-auth`

Has worked for ~6 months, and this morning it's failing. 

### Expected behavior

Expected Prowler to connect to the Azure client, and run as normal

### Actual Result with Screenshots or Logs

failure with the following error

```
Traceback (most recent call last):
  File "/home/prowler/.local/bin/prowler", line 8, in <module>
    sys.exit(prowler())
             ^^^^^^^^^
  File "/home/prowler/.local/lib/python3.11/site-packages/prowler/__main__.py", line 173, in prowler
    checks_to_execute = sorted(checks_to_execute)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not iterable
```

### How did you install Prowler?

Docker (docker pull toniblyx/prowler)

### Environment Resource

Locally hosted Debian server

### OS used

Debian 11

### Prowler version

latest docker image

### Pip version

23.3.2

### Context

From our side, nothing changed recently with this service.

**Comment by jfagoagas** [comment]
Hi @Xarlos89, thanks for issue, we've identified the bug and we are working on a fix. We'll get back to you soon.

Thanks for using Prowler 🚀

**Comment by jfagoagas** [comment]
Hi @Xarlos89, the above PR fixes the bug. We'll merge that ASAP, please check that out and let us know if everything is fine. Thanks!

We'll release Prowler 3.15.0 this week also.
