### ISSUE TITLE
[Bug]: iam_user_mfa_enabled_console_access - includes root user

### ISSUE THREAD

**Issue by jchrisfarris** [toniblyx/prowler#3519]
### Steps to Reproduce

In the AWS Check iam_user_mfa_enabled_console_access, the results include a finding for the root user (since it is included in the credential report), the `Status Extended` field states: "User <root_account> does not have Console Password enabled." which is factually incorrect, as the root user can always login to the console.

### Expected behavior

Exclude the root user from this check. There is a specific check for root MFA. 

### Actual Result with Screenshots or Logs

I don't have the logs. 

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

ECS

### OS used

Amazon Linux I think

### Prowler version

3.13.0

### Pip version

pip 23.2.1

**Comment by jfagoagas** [comment]
Hi @jchrisfarris, this is a great catch! We will fix that soon. Thanks for using Prowler 🚀
