### ISSUE TITLE
[Bug]: compliance csv file seems to be broken

### ISSUE THREAD

**Issue by qbrusa** [toniblyx/prowler#3530]
### Steps to Reproduce

prowler aws --compliance cis_3.0_aws -o <path/to/folder>

### Expected behavior

The CSV file `prowler-output-<accountid>-20240312161608_cis_3.0_aws.csv` provided by the command `prowler aws --compliance cis_3.0_aws -o <path/to/folder`>seems to be broken. When I import the file in an Excel file or LibreOffice, with semicolon separator, column are not aligned. Maybe missing column name in header of CSV file ?

### Actual Result with Screenshots or Logs

![image](https://github.com/prowler-cloud/prowler/assets/122641985/99c3232b-70a6-4bd9-8e6b-2f1b87a27c89)

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

From a virtual machine with VirtualBox

### OS used

Ubuntu 22.04.4 LTS

### Prowler version

Prowler 3.14.0

### Pip version

ip 24.0 from /usr/local/lib/python3.10/dist-packages/pip (python 3.10)

### Context

I have follow this procedure to install prowler : https://docs.prowler.com/projects/prowler-open-source/en/latest/#__tabbed_1_3

**Comment by MrCloudSec** [comment]
Hi @qbrusa , thanks for reaching us out!
This issue is already fixed in the master branch on GitHub and will be soon available in the next Prowler release 🚀
