### ISSUE TITLE
[Bug]: Recommendation is incorrect for check "cloudwatch_changes_to_network_route_tables_alarm_configured"

### ISSUE THREAD

**Issue by adistasio** [toniblyx/prowler#3536]
### Steps to Reproduce

prowler aws cloudwatch

### Expected behavior

The recommendation section should have the correct filter pattern that prowler is actually looking for:

 '{ ($.eventSource = ec2.amazonaws.com) \\&\\& (($.eventName = CreateRoute) || ($.eventName = CreateRouteTable) || ($.eventName = ReplaceRoute) || ($.eventName = ReplaceRouteTableAssociation) || ($.eventName = DeleteRouteTable) || ($.eventName = DeleteRoute) || ($.eventName = DisassociateRouteTable)) }'

### Actual Result with Screenshots or Logs

The recommendation section of this check indicates the filter pattern should be as follows which is wrong since it is misisng the eventSource. 

 '{ ($.eventName = CreateRoute) || ($.eventName = CreateRouteTable) || ($.eventName = ReplaceRoute) || ($.eventName = ReplaceRouteTableAssociation) || ($.eventName = DeleteRouteTable) || ($.eventName = DeleteRoute) || ($.eventName = DisassociateRouteTable) }'

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

Workstation

### OS used

MacOS

### Prowler version

3.14.0

### Pip version

23.3.2

### Context

The recommendation section is misleading since it provides the wrong filter pattern. I would've just updated this myself but I can't seem to create a branch to commit a fix to the documentation.

**Comment by MrCloudSec** [comment]
Hi @adistasio, good catch! We will fix that soon. 
Thanks for using Prowler 🚀
