### ISSUE TITLE
Security Group Allows Public IP address(es)

### ISSUE THREAD

**Issue by HugeUA** [toniblyx/prowler#3553]
### New feature motivation

Currently offered check [ec2_securitygroup_allow_wide_open_public_ipv4] nor other checks specific to the services (MySQL, MSSQL, RDP, SSH, etc.) do not flag security groups with a single public IP or Public subnet in source; 

### Solution Proposed

Create detection that flags any security groups with public IPs in source of the rules

### Describe alternatives you've considered

Developing labda that uses regex to check IP/range of every rule of every security group and output list of security groups of non RFC1918 addresses

**Comment by abant07** [comment]
Hey @puchy22 is this something that I can work on?

Thanks

**Comment by abant07** [comment]
@jfagoagas Is this something I can work on, or has it already been resolved?

Thanks

**Comment by jfagoagas** [comment]
Hello @abant07, for sure that you can work on this. I think first we'd need to:
- Analyze what is happening.
- Get a list of affected checks if any
- Get a list of possible new checks if any
- See how can make a general solution, i.e.: having a common function to check that.

What do you think? If we do this analysis first we can get to a better and quicker solution.

**Comment by abant07** [comment]
Sure @jfagoagas , sounds good. I can message you on Slack when I am done with the analysis. Should be able to get it done by end of this week, have a couple things in the backlog that I need to get around to.

Thanks

**Comment by jfagoagas** [comment]
> Sure @jfagoagas , sounds good. I can message you on Slack when I am done with the analysis. Should be able to get it done by end of this week, have a couple things in the backlog that I need to get around to.
> 
> Thanks

As you prefer, but I'd like to continue the conversation here since it is where we have the issue opened and it could help other users and also provide more visibility about the current status.

Thank you!

**Comment by abant07** [comment]
@jfagoagas @HugeUA From what I am understanding from this issue and looking at the code for ec2_securitygroup_allow_wide_open_public_ipv4, we want to flag security groups that have a rule exposing the internet by checking for RFC1918 addresses and showing which security groups are non RFC1918 addresses.


However, it seems like the code already does this:
`

# Loop through every security group's ingress rule and check it
                for ingress_rule in security_group.ingress_rules:
                    for ipv4 in ingress_rule["IpRanges"]:
                        ip = ipaddress.ip_network(ipv4["CidrIp"])
                        # Check if IP is public according to RFC1918 and if 0 < prefixlen < 24
                        if (
                            ip.is_global
                            and ip.prefixlen < cidr_treshold
                            and ip.prefixlen > 0
                        ):
                            report.status = "FAIL"
                            report.status_extended = f"Security group {security_group.name} ({security_group.id}) has potential wide-open non-RFC1918 address {ipv4['CidrIp']} in ingress rule."
                            break

                # Loop through every security group's egress rule and check it
                for egress_rule in security_group.egress_rules:
                    for ipv4 in egress_rule["IpRanges"]:
                        ip = ipaddress.ip_network(ipv4["CidrIp"])
                        # Check if IP is public according to RFC1918 and if 0 < prefixlen < 24
                        if (
                            ip.is_global
                            and ip.prefixlen < cidr_treshold
                            and ip.prefixlen > 0
                        ):
                            report.status = "FAIL"
                            report.status_extended = f"Security group {security_group.name} ({security_group.id}) has potential wide-open non-RFC1918 address {ipv4['CidrIp']} in egress rule."
                            break

                findings.append(report)

`
                
However, do you want me to include this for other services that use such as RDS databases (MySQL, MSSQL), Remote Desktop Protocol, SSH?

**Comment by jfagoagas** [comment]
Hello @abant07 @HugeUA this is a little bit confusing. I'm to try to clarify some things:

The check `ec2_securitygroup_allow_wide_open_public_ipv4` verifies that either the ingress or egress rules of the Security Group contains just private CIDRs. So in my opinion I think there is nothing to do with this check.

Regarding the point of this issue  `No check specific to the services (MySQL, MSSQL, RDP, SSH, etc.) do not flag security groups with a single public IP or Public subnet in source`, I think that the issue owner wants to cover the scenario where a Security Group is not open to the internet (0.0.0.0/0) but opened to an specific CIDR.

I think there is little value in creating N checks to cover the above per Security Group and I'm not sure if a generic check could address this, maybe ...

What do you think? @abant07 @HugeUA

I don't see a security issue if you have a Security Group configured with a /32 CIDR since you are explicitly allowing some host in your network. Also this check must raise a `FAIL` finding if the Security Group has a public subnet in source.

I think this issue does not need further work but maybe I'm missing something.

CC: @sergargar @pedrooot

**Comment by pedrooot** [comment]
My opinion it's the same as @jfagoagas. We are open to talk to see if we are missing any point and if it's needed, we'll work more in this issue. At this point it's the only thing we can do

**Comment by abant07** [comment]
Yeah @jfagoagas @pedrooot I had the same thought, which is why I wanted to run it by you all first before I started.

**Comment by MrCloudSec** [comment]
I agree with @jfagoagas, I think there is a little added value compared with all the effort that these new checks would need.

**Comment by jfagoagas** [comment]
Taking all the above into account, I'm going to close the issue. Thank you very much for all the work put here.

Please @HugeUA, feel free to reopen it if you have anything that we didn't consider.

Thanks for using Prowler 🚀
