### ISSUE TITLE
[Bug]: STS endpoint is wrong for the Chinese AWS regions

### ISSUE THREAD

**Issue by daftkid** [toniblyx/prowler#3612]
### Steps to Reproduce

1. Install local env and run the prowler tool.
```
> poetry shell
> poetry install
> python3 prowler aws --region cn-northwest-1
```

2. See the error:
```
2024-03-26 14:21:47,146 [File: credentials.py:37]       [Module: credentials]     CRITICAL: EndpointConnectionError[33]: Could not connect to the endpoint URL: "https://sts.cn-north-1.amazonaws.com/"
```

3. It seems that STS endpoint is constructed in a wrong way.

### Expected behavior

STS endpoint for the Chinese AWS regions is correct (ending with `.cn` as stated here: https://docs.amazonaws.cn/en_us/aws/latest/userguide/endpoints-Ningxia.html)
and the Prowler is able to run the scans.

### Actual Result with Screenshots or Logs

-

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

Workstation

### OS used

MacOS

### Prowler version

Prowler 3.15.2 (latest is 3.15.3, upgrade for the latest features)

### Pip version

pip 23.1.2 from /Users/omykyte/Library/Caches/pypoetry/virtualenvs/prowler-WsEEJ6ww-py3.11/lib/python3.11/site-packages/pip (python 3.11)

**Comment by MrCloudSec** [comment]
Hi @daftkid, good catch!!
Can you test it again in the branch `3612-bug-sts-endpoint-is-wrong-for-the-chinese-aws-regions`? I have added there a fix. Thanks!

**Comment by daftkid** [comment]
Hi @sergargar . Yeah it works. Just was in the middle of preparing a fix for that in my forked repo :D nice job!

**Comment by daftkid** [comment]
@sergargar  when is this going to be released? It seems this is broken for the Chinese regions starting from 3.11.0 ver

**Comment by MrCloudSec** [comment]
Hi @daftkid , glad that my fix solved the issue. We will try to release it this week.
