### ISSUE TITLE
[Bug]:  Prowler AWS' JSON-OCSF output format is corrupted, not valid JSON

### ISSUE THREAD

**Issue by yungcero** [toniblyx/prowler#3675]
### Steps to Reproduce

1. Command being run: `prowler aws -b --verbose -M json-ocsf -F my-test -o tmp-dir` and then within python, opening the file my_test.json into a string and then running `json.loads(my_test_string)`. When loading into cyberchef the file syntax is also wrong.
2. AWS 
3. Single Env 
4. `json.decoder.JSONDecodeError: Extra data: line (NA) column (NA) (char (NA))`

### Expected behavior

This file should be load without fail if in correct json format. The reason that this is happening is because there is an error (which is rare) is that when appending findings, sometimes findings will be separated with a `]` instead of a `,`

### Actual Result with Screenshots or Logs

<img width="817" alt="image" src="https://github.com/prowler-cloud/prowler/assets/133906218/f625bc2f-eeaf-4d94-9ee2-40d0c3f85395">

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

Being run in a docker container

### OS used

Ubuntu

### Prowler version

prowler 4.0.0

### Pip version

23.0.1

### Context

As mentioned in the expected behavior, there is a bug that is causing the findings within the json to be appended to each other with` ]` instead of `,`. When i run a replace on the areas where it is offending ex. `prowler_output.replace('}]{', '},{'))`, it works. I'll take a look at where this is happening within the source and see if i can push a potentially quick fix, but seems like something easily resolvable.

**Comment by toniblyx** [comment]
Hi @yungcero, I just tried your command on Prowler v4.0 and doesn´t work, are you sure you are using that command and that is the version you have? `prowler aws -b --verbose -F my_test` should work instead. Remember on v4 JSON OCSF is generated always by default.

**Comment by toniblyx** [comment]
actually I have just seen what's going on, you have a typo on OCSF on your command. here is the right one `prowler aws -b --verbose -M json-ocsf -F my_test`

**Comment by yungcero** [comment]
hey! @toniblyx . Yeah that is my bad. I accidentally mistyped the command when opening the issue. The same error persists however with the correct command

**Comment by yungcero** [comment]
I also updated the command to have the file name be `my-test` instead of `my_test` to be more accurate to what i am running. The naming probably does not matter but just in case...

**Comment by jfagoagas** [comment]
Hi @yungcero, I can't reproduce your issue in our tests environment. The JSON-OCSF outputs is well generated following JSON syntax.

I just inserted the output in CyberShef using the `JSON Minify` recipe and it works fine using Prowler v4.
![Screenshot 2024-04-11 at 10 54 22](https://github.com/prowler-cloud/prowler/assets/16007882/9e4911ff-ae09-4ac0-b21f-4b38178b182c)

**Comment by yungcero** [comment]
Looks like it was an edge case in my environment. I restarted my container and updated to 4.0.1 and looks like its good now. This was the output before in cyberchef, but looks like im not running into that issue anymore. And from the output looks like my ocsf json was stuck on a previous version.

<img width="1378" alt="image" src="https://github.com/prowler-cloud/prowler/assets/133906218/fc4d1c99-7db3-49fc-bd6e-a4b4191ff1dc">

Thanks for looking at this @jfagoagas @toniblyx

**Comment by jfagoagas** [comment]
Awesome, thanks for the heads up @yungcero!
