### ISSUE TITLE
[Bug]: obsolete_lambda_runtimes in config.yaml is out of date

### ISSUE THREAD

**Issue by hakanson** [toniblyx/prowler#3717]
### Steps to Reproduce

running `prowler aws -c awslambda_function_using_supported_runtimes` with Lambda functions not in AWS Lambda [Supported Runtimes](https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtime-support-policy) list

### Expected behavior

Expect `dotnetcore3.1`, `nodejs14.x`, `nodejs12.x`, ... to not **PASS** and report as supported.

These are missing from https://github.com/prowler-cloud/prowler/blob/v3/prowler/config/config.yaml#L51-L67

### Actual Result with Screenshots or Logs

Lambda function XXX is using dotnetcore3.1 which is supported.
Lambda function YYY is using nodejs14.x which is supported.
Lambda function ZZZ is using nodejs12.x which is supported.

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

7. Workstation

### OS used

2. MacOS

### Prowler version

Prowler 3.16.0 (latest is 4.0.0, upgrade for the latest features)

### Pip version

pip 24.0 (python 3.9)

**Comment by pedrooot** [comment]
Hi! @hakanson thanks for the report, we will review it and we'll get back to you soon.
Thanks for using Prowler! 😁

**Comment by pedrooot** [comment]
Hi! @hakanson it is already fixed. For future issues keep in mind that you can change "obsolete_lambda_runtimes" variable present in the config.yaml file. 
Thanks for using Prowler 🚀
