### ISSUE TITLE
[Bug]: renamed mute list not aligned between released version and docs

### ISSUE THREAD

**Issue by jansepke** [toniblyx/prowler#3720]
### Context

The pull request #3690 renamed the `Mute List` key of the `--mutelist-file` to `Mutelist`. The new key is also documented in the docs but not released in the latest release 4.0. If this PR gets released it would likely be a breaking change.

Please think about reverting the key and documentation until the next major release.

### Actual Result with Screenshots or Logs

error in logs:
`[File: mutelist.py:109] 	[Module: mutelist]	 CRITICAL: KeyError -- 'Mute List'[99]`

### How did you install Prowler?

From pip package (pip install prowler)

### Prowler version

4.0

**Comment by MrCloudSec** [comment]
Hi @jansepke , we have just released version 4.0.1 with that change. Thanks for using Prowler 🚀

**Comment by jfagoagas** [comment]
@jansepke regarding the breaking change you mention, the space within `Mute List` was a bug detected during the v4 release.
