### ISSUE TITLE
[Bug]: Output formats for JSON, HTML not accepted

### ISSUE THREAD

**Issue by jmanduca-psfy** [toniblyx/prowler#3742]
### Steps to Reproduce

Install prowler via pip
Attempt to run a prowler scan with json and/or html output specified:
`prowler aws -b -z -M json html`

### Expected behavior

Prowler scan should run and complete, outputting documents in the formats specified

### Actual Result with Screenshots or Logs

Prowler refuses to run, stating a reduced list of allowed values for output formats.
```
prowler aws -b -z -M html
usage: prowler aws [-h] [--status {PASS,FAIL,MANUAL} [{PASS,FAIL,MANUAL} ...]] [--output-formats {csv,json-asff,json-ocsf} ...
prowler aws: error: argument --output-formats/--output-modes/-M: invalid choice: 'html' (choose from 'csv', 'json-asff', 'json-ocsf')
prowler aws -b -z -M json
usage: prowler aws [-h] [--status {PASS,FAIL,MANUAL} [{PASS,FAIL,MANUAL} ...]] [--output-formats {csv,json-asff,json-ocsf} ...
prowler aws: error: argument --output-formats/--output-modes/-M: invalid choice: 'json' (choose from 'csv', 'json-asff', 'json-ocsf')
```

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

AWS CloudShell, AWS ECS

### OS used

Amazon Linux/Alpine

### Prowler version

4.0.1

### Pip version

pip 21.3.1 from /usr/lib/python3.9/site-packages/pip (python 3.9)

### Context

Per the documentation, output formats include JSON and HTML: https://docs.prowler.com/projects/prowler-open-source/en/latest/tutorials/reporting/#output-formats
Both formats also worked with previous prowler versions.

**Comment by adv4000** [comment]
Same issue here, Version 4.0.1 removed support for HTML:
```
prowler aws -M html
prowler aws: error: argument --output-formats/--output-modes/-M: invalid choice: 'html' (choose from 'csv', 'json-asff', 'json-ocsf')
```

**Comment by jfagoagas** [comment]
Hi @jmanduca-psfy @adv4000, since v4 we have been deprecated the following outputs:
- The HTML is replaced for the new Prowler Dashboard, you can try it with `prowler dashboard`.
- The native JSON is replaced for the JSON [OCSF](https://schema.ocsf.io/) v1.1.0, common for all the providers.

Thanks for using Prowler 🚀

**Comment by christiandavilakoobin** [comment]
I tried the dashboard, and is very handy, but it requieres some extra steps to view the results. The html version was very useful for a quick view.

**Comment by pr3l14t0r** [comment]
@jfagoagas Thanks for that information,  i have absolutely overseen the `prowler dashboard` functionality. 

Quick question if allowed: Is there a reason why you/the team have chosen the `Detection Finding [2004] Class` over `Compliance Finding [2003] Class`  in OCSF-JSON? I can't find a discussion for that anywhere.

**Comment by jmanduca-psfy** [comment]
This new OCSF-JSON does not include the Compliance Info, which was previously included in the previous JSON option. It is a requirement for the `Compliance Finding [2003] Class` but not in the `Detection Finding [2004] Class` which appears to be in use per @pr3l14t0r .
We were using this field to help sort through findings for our compliance requirements, now that it is gone it will create additional work or duplication of scans to sort them out in this version.

**Comment by jfagoagas** [comment]
@pr3l14t0r we decided to use `Detection Finding` since it is the most accurate event for a Prowler finding. Regarding compliance we are evaluating the option to generate a `Compliance Finding` since as it happens with Prowler outputs, compliance and findings cannot be mapped into the same output.

CC: @jmanduca-psfy

**Comment by jfagoagas** [comment]
@pr3l14t0r @jmanduca-psfy We are going to include the JSON v3 `Compliance` key in the Detection Finding at `unmapped.compliance` probably tomorrow. Sorry for the incovenience.

**Comment by jfagoagas** [comment]
https://github.com/prowler-cloud/prowler/pull/3753

CC: @pr3l14t0r @jmanduca-psfy

**Comment by pr3l14t0r** [comment]
@jfagoagas Thanks for the explanation, highly appreciated! :)

**Comment by jfagoagas** [comment]
> @jfagoagas Thanks for the explanation, highly appreciated! :)

It's nothing! Always here to help 🙌

**Comment by jfagoagas** [comment]
We are going to close this issue once the above PR gets merged. Please let us know if everything works fine and feel free to reopen it if notice something not expected.

Thanks for using Prowler 🚀

**Comment by jmanduca-psfy** [comment]
Working great, thank you @jfagoagas !
