### ISSUE TITLE
Prowler v4 Output Format Change

### ISSUE THREAD

**Issue by zfLQ2qx2** [toniblyx/prowler#3788]
### New feature motivation

@toniblyx Going back to the original Prowler (you know I've been here since nearly the beginning) my approach has always been to run every check Prowler offers, then I had a post processor that would take the Prowler output, organize it around various compliance standards, whitelist or skip things that didn't make sense in our environment or we decided were acceptable risks, then I can show my boss (and he can show his boss) how compliant we were according to various standards. I have kept a ten day running record so we could tie decrease in overall scores back to changes and make people go back and do things the right way.

With the new format there isn't enough information to tie a check to any of the standards. There isn't a good way to differentiate checks except by their verbose description. I think we have lost a lot of utility. The ability to organize the data into something that was actionable to technical people and meaningful to business people was what really set Prowler apart from everyone else that was simply spamming a console someplace.

### Solution Proposed

I'd like to see the old format restored

### Describe alternatives you've considered

Still working on a Plan B

**Comment by jfagoagas** [comment]
Hi @zfLQ2qx2 I really appreciate your feedback but I'm not getting it. Which output format are you referring to? Both CSV and JSON format contains the same information as in v3, we've just standardize the structure using the same for all the providers, including the check's metadata and all the information retrieved from the Cloud provider.

Please, give us more details about what you are missing. Here https://docs.prowler.com/projects/prowler-open-source/en/latest/tutorials/reporting/#v4-deprecations you can see the changes from v3.

Which version of Prowler are you running?


Thanks for using Prowler 🚀

**Comment by zfLQ2qx2** [comment]
@jfagoagas It looks like the two main issues are that 1) there is no equivalent for the "Compliance" member of the Prowler v3 json formation in the v4 oscf json format and 2) there is no equivalent for the "CheckID" member of the Prowler v3 json formation in the v4 oscf json format. The documentation mentions metadata.event_code being the v4 equivalent for CheckID but that is not actually present in the ocsf results.

**Comment by jfagoagas** [comment]
@zfLQ2qx2 both of your requests will be pushed in the next Prowler release, right now are merged on `master` branch. You can give this a try there.

Thanks for using Prowler 🚀

**Comment by zfLQ2qx2** [comment]
@jfagoagas Thank you, I'll be able to try it this evening and let you know

**Comment by zfLQ2qx2** [comment]
@jfagoagas I've had a look:

```
    "unmapped": {
        "check_type": "IAM",
        "related_url": "https://docs.aws.amazon.com/IAM/latest/UserGuide/what-is-access-analyzer.html",
        "categories": "",
        "depends_on": "",
        "related_to": "",
        "notes": "",
        "compliance": {
            "CIS-1.5": [
                "1.20"
            ],
            "CIS-1.4": [
                "1.20"
            ],
            "CIS-3.0": [
                "1.20"
            ],
            "AWS-Account-Security-Onboarding": [
                "Enabled security services",
                "Create analyzers in each active regions",
                "Verify that events are present in SecurityHub aggregated view"
            ],
            "CIS-2.0": [
                "1.20"
            ]
        }
    },
```

I'm assuming that "unmapped" is the "ocsf" way of passing information outside of the "ocsf" standard. The compliannce."AWS-Account-Security-Onboarding" does not look right - maybe namespace collision in the unmapped members and multiple 'compliance' objects are being merged?

**Comment by jfagoagas** [comment]
Hi @zfLQ2qx2 as you said the unmapped section in the OCSF schema allows you to include information generated from Prowler that are not currently mapped in the Detection Finding event, which is the event we use to generate findings.

Regarding the compliance format, it's fine since we gather the requirements and each compliance framework has their specific format and naming.

**Comment by zfLQ2qx2** [comment]
@jfagoagas Ok, I just wanted to make sure. Looks good then!

**Comment by zfLQ2qx2** [comment]
@jfagoagas If I can re-open this - I found one other omission, in Prowler v3 the ResourceDetails member of the json format was being used to return the name of AWS security groups as this is an attribute of the resource and not a tag, and the sg-xxxxxxxxx identifier isn't really useful for whitelisting. In the Prowler v4 format ResourceDetails is unmapped though currently does not appear in the unmapped section. I'm not aware of any other resource like this, I think it is a hold-over from AWS's earliest days, tagging was an afterthought, each AWS service has its own tagging API, and they don't all work the same way! Though they all seem to follow one of seven different patterns. Crazy stuff.

**Comment by jfagoagas** [comment]
HI @zfLQ2qx2 you were right, we've just included that in the above PR. We'll include that in the next Prowler release. Thanks!
