### ISSUE TITLE
[Bug]: False negative in Azure NSG checks

### ISSUE THREAD

**Issue by varunupps** [toniblyx/prowler#3802]
### Steps to Reproduce

1) Command run: prowler azure --az-cli-auth
2) Running on ubuntu workstation
3) Run against a single Azure account and subscription
4) az cli credentials have Admin Permissions
5) A VM created in Azure subscription with NSG that allows traffic to TCP port 22 from anywhere
6) Verified that SSH works and is accessible from anywhere

### Expected behavior

The status of the "network_ssh_internet_access_restricted " check for the NSG should be "FAIL". But it's "PASS" as shown in the screenshot. Also attaching screenshot from Azure console to confirm misconfiguration.

### Actual Result with Screenshots or Logs

![image](https://github.com/prowler-cloud/prowler/assets/55276653/80f92a4b-b836-48bf-a20d-e923b5146a73)

![image](https://github.com/prowler-cloud/prowler/assets/55276653/c449c0de-050f-4da6-a5c7-d5bc2f433540)

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

Workstation

### OS used

Ubuntu 22.0

### Prowler version

v4.0.1

### Pip version

22.0.2

**Comment by varunupps** [comment]
![image](https://github.com/prowler-cloud/prowler/assets/55276653/145d93c9-a5cb-4732-a6e7-024b3c2ab487)

**Comment by pedrooot** [comment]
Hi! @varunupps thanks for the report, I´ll work on this issue and reach you with a solution!
Thanks for using Prowler!!!

**Comment by varunupps** [comment]
awesome. if you need more details, just gimme a shout. ta

**Comment by pedrooot** [comment]
@varunupps I´m trying to replicate your issue but I´m getting this: 
![Screenshot 2024-04-17 at 14 07 31](https://github.com/prowler-cloud/prowler/assets/56402503/4b3b7731-8d9e-4690-90d7-dee07d38857c)

**Comment by pedrooot** [comment]
Could you send me a screenshot like this one?:
![Screenshot 2024-04-17 at 14 09 46](https://github.com/prowler-cloud/prowler/assets/56402503/3239a261-cab1-4c7d-b378-14fe7f5a2685)
It appears when creating an inbound security rule

**Comment by varunupps** [comment]
hello @pedrooot . pls see attached.

![image](https://github.com/prowler-cloud/prowler/assets/55276653/a2f231d8-f21e-4974-8d5a-51d13d47559b)
![image](https://github.com/prowler-cloud/prowler/assets/55276653/b3667567-e02c-4324-a99e-3b20b7e5df34)

**Comment by pedrooot** [comment]
@varunupps To ensure that we have the same configuration, can you check that this configuration?:
```json
"securityRules": [
            {
                "name": "SSH",
                "id": "/subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.Network/networkSecurityGroups/<nsg>/securityRules/SSH",
                "etag": "W/\"<etag>\"",
                "type": "Microsoft.Network/networkSecurityGroups/securityRules",
                "properties": {
                    "provisioningState": "Succeeded",
                    "protocol": "TCP",
                    "sourcePortRange": "*",
                    "destinationPortRange": "22",
                    "sourceAddressPrefix": "*",
                    "destinationAddressPrefix": "*",
                    "access": "Allow",
                    "priority": 1000,
                    "direction": "Inbound",
                    "sourcePortRanges": [],
                    "destinationPortRanges": [],
                    "sourceAddressPrefixes": [],
                    "destinationAddressPrefixes": []
                }
            }
        ],
```
From 
![Screenshot 2024-04-17 at 16 05 30](https://github.com/prowler-cloud/prowler/assets/56402503/4a12180a-594b-4116-9fa5-34a0582a0eb8)

**Comment by varunupps** [comment]
hello @pedrooot . Please see below. Only variation I can see is the case of 'Tcp'

```
 "securityRules": [
            {
                "name": "SSH",
                "id": "/subscriptions/<subscription_id>/resourceGroups/<resource_group>/providers/Microsoft.Network/networkSecurityGroups/<NSG>/securityRules/SSH",
                "etag": "W/\"<ETAG>\"",
                "type": "Microsoft.Network/networkSecurityGroups/securityRules",
                "properties": {
                    "provisioningState": "Succeeded",
                    "protocol": "Tcp",
                    "sourcePortRange": "*",
                    "destinationPortRange": "22",
                    "sourceAddressPrefix": "*",
                    "destinationAddressPrefix": "*",
                    "access": "Allow",
                    "priority": 1000,
                    "direction": "Inbound",
                    "sourcePortRanges": [],
                    "destinationPortRanges": [],
                    "sourceAddressPrefixes": [],
                    "destinationAddressPrefixes": []
                }
            }
        ],
```

**Comment by varunupps** [comment]
@pedrooot - could this be it? https://github.com/prowler-cloud/prowler/blob/master/prowler/providers/azure/services/network/network_ssh_internet_access_restricted/network_ssh_internet_access_restricted.py#L26

**Comment by pedrooot** [comment]
Yes, I´m pretty sure that changing this line wuould resolve the issue, I´ll do it asap

**Comment by pedrooot** [comment]
Hey! @varunupps you can try [here](https://github.com/prowler-cloud/prowler/pull/3808) the new fix. If the error persists just tell me!
Thanks for using Prowler 😄

**Comment by varunupps** [comment]
hi @pedrooot - it's fixed. thanks for your help

![image](https://github.com/prowler-cloud/prowler/assets/55276653/b1963f51-1e2c-4949-94bc-127b26a1f88a)
