### ISSUE TITLE
Unable to run kubernetes Scan

### ISSUE THREAD

**Issue by weisinc** [toniblyx/prowler#3845]
### Steps to Reproduce

1. command: prowler kubernetes --context <current context in kubeconfig> --namespace <an existing namespace>
2. Cloud provider: GCP/GKE
3. Environment: Single project in GCP
4. Error: [File: kubernetes_provider.py:151]   [Module: kubernetes_provider]  CRITICAL: ConfigException[141]: Service host/port is not set.

### Expected behavior

Prowler should start scanning the k8 namespace I've specified.

### Actual Result with Screenshots or Logs

[File: kubernetes_provider.py:151]   [Module: kubernetes_provider]  CRITICAL: ConfigException[141]: Service host/port is not set.

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

GKE

### OS used

macOS: Sonoma 14.4.1

### Prowler version

Prowler 4.1.0

### Pip version

pip 23.3.1

**Comment by MrCloudSec** [comment]
Hi @weisinc, thanks for reaching us out!
Can you check if you have connection to your Kubernetes cluster, please?

**Comment by weisinc** [comment]
@sergargar , yes I do have connection to my kubernetes cluster. ie I'm getting back k8 info from kubectl

**Comment by weisinc** [comment]
It is working for me now. I just need to explicitly specify the config file. I thought the command would default to it.
