### ISSUE TITLE
Look for externally shared DynamoDB Tables

### ISSUE THREAD

**Issue by jchrisfarris** [toniblyx/prowler#3867]
### New feature motivation

On march 20th, AWS announced [Amazon DynamoDB now supports resource-based policies](https://aws.amazon.com/about-aws/whats-new/2024/03/amazon-dynamodb-resource-based-policies/). It would be good to have a Prowler check to look for DDB tables that have been shared to other accounts (note: it's not possible to share a table publicly, so this is good). 

### Solution Proposed

Boto3 call for the solution
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/dynamodb/client/get_resource_policy.html

### Describe alternatives you've considered

None, this is a new feature release.

**Comment by MrCloudSec** [comment]
Thanks for letting us know this new change @jchrisfarris !
I'm working on this new check 💪🏼
