### ISSUE TITLE
Add support for AWS Lightsail resource

### ISSUE THREAD

**Issue by weibeu** [toniblyx/prowler#3869]
### New feature motivation

It would be great if Prowler starts supporting AWS Lightsail as this as well is a common service used by several teams.

### Solution Proposed

Support AWS Lightsail instance scanning for things like:
- Open ports
- Static IPs
- Snapshots
- Disk usage

### Describe alternatives you've considered

NA

**Comment by MrCloudSec** [comment]
Hi @weibeu , thanks for the feedback!
We have included in our roadmap to do the following LightSail checks, let us know what you think:

- lightsail_instance_public

Ensures no LightSail instances are unnecessarily exposed to the internet by having a public IP address and open ports.

- lightsail_instance_automated_snapshots

Check if instances have automated snapshots enabled

- lightsail_static_ip_unused

Audits for static IPs that are allocated but unused.

- lightsail_database_public

Check if the database has the public mode.

**Comment by weibeu** [comment]
Really thanks for this. Forgot to mention thanks. We have been actively using this and its really helpful.
