### ISSUE TITLE
[Bug]: csv output is empty (only column names)

### ISSUE THREAD

**Issue by marcosnr** [toniblyx/prowler#3897]
### Steps to Reproduce

prowler aws -s iam -M csv 

### Expected behavior

After execution, it says:
```
Detailed results are in:
 - CSV: /shared/prepo/prowler/output/prowler-output-XXXXXX-20240430165309.csv
 ```
 But that csv only have the name of the columns, but no info of findings (there many fails)

### Actual Result with Screenshots or Logs

[2024-04-30_debug.log](https://github.com/prowler-cloud/prowler/files/15159665/2024-04-30_debug.log)
@lok-sec-prod-admin$ cat /Users/marcosnr/shared/prepo/prowler/output/prowler-output-1234567890123-20240430170020.csv
AUTH_METHOD;TIMESTAMP;ACCOUNT_UID;ACCOUNT_NAME;ACCOUNT_EMAIL;ACCOUNT_ORGANIZATION_UID;ACCOUNT_ORGANIZATION_NAME;ACCOUNT_TAGS;FINDING_UID;PROVIDER;CHECK_ID;CHECK_TITLE;CHECK_TYPE;STATUS;STATUS_EXTENDED;MUTED;SERVICE_NAME;SUBSERVICE_NAME;SEVERITY;RESOURCE_TYPE;RESOURCE_UID;RESOURCE_NAME;RESOURCE_DETAILS;RESOURCE_TAGS;PARTITION;REGION;DESCRIPTION;RISK;RELATED_URL;REMEDIATION_RECOMMENDATION_TEXT;REMEDIATION_RECOMMENDATION_URL;REMEDIATION_CODE_NATIVEIAC;REMEDIATION_CODE_TERRAFORM;REMEDIATION_CODE_CLI;REMEDIATION_CODE_OTHER;COMPLIANCE;CATEGORIES;DEPENDS_ON;RELATED_TO;NOTES;PROWLER_VERSION

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

7. Workstation MacBook Pro  under `poetry shell`

### OS used

MacOS Sonoma 14.4.1

### Prowler version

Prowler 4.1.0 (You are running the latest version, yay!) (prowler-py3.10) 

### Pip version

pip 23.3.1 from /Users/marcosnr/Library/Caches/pypoetry/virtualenvs/prowler-5X3pVy1M-py3.10/lib/python3.10/site-packages/pip (python 3.10) (prowler-py3.10)

### Context

Recently like 2 weeks ago I was using v3 with no problem, today I saw the prompt to upgrade, so I did, 'git pull' 'poetry install' all good, but now this csv output is not working :(

**Comment by pedrooot** [comment]
Hi! @marcosnr thanks for the report, I´ll work on this issue and reach you with a solution!
Thanks for using Prowler!!!

**Comment by pedrooot** [comment]
@marcosnr I'm not able to reproduce your error, could you execute the same command using the `log-level ERROR` flag and share with me the output? Thanks!

**Comment by marcosnr** [comment]
My absolute pleasure to work with prowler! Let me know what I can do to help out!

**Comment by marcosnr** [comment]
FYI, just git co tag 3.15 version and all worked as expected

**Comment by pedrooot** [comment]
Hey! @marcosnr  could you please execute: `aws organizations list-tags-for-resource --resource-id AWS_ACCOUNT_NUMBER` and send me the output? Thanks

**Comment by pedrooot** [comment]
hey @marcosnr ! In [this pr](https://github.com/prowler-cloud/prowler/pull/3914) the issue should be solved, test it and reopen the issue if you have any problem! Thanks for using Prowler 🚀
