### ISSUE TITLE
[Bug]: empty json-ocsf output in 4.1.0

### ISSUE THREAD

**Issue by djinnert** [toniblyx/prowler#3909]
### Steps to Reproduce

Command ran:
python prowler.py aws -R arn:aws:iam::[accountid]:role/[role] -M json-ocsf json-asff csv

NOTE: Issue isn't present in 3.16.3 but is in 4.1.0 
It generates an empty JSON-OCSF with only []. 

This doesn't occur in 3.16.3 only in 4.x
Prior bug seen in 3.x that was fixed: https://github.com/prowler-cloud/prowler/issues/3018?new_signup=true and possibly was reintroduced in the 4.x code.
 
![image](https://github.com/prowler-cloud/prowler/assets/168663180/a2f49c6b-9433-4b2e-9a25-77cdac81e494)

### Expected behavior

The -M json-ocsf should not generate an empty json-ocsf file

### Actual Result with Screenshots or Logs

Command: python prowler.py aws -R arn:aws:iam::[accountid]:role/[priv-role] --compliance aws_foundational_security_best_practices_aws -M json-ocsf json-asff csv -F test2-4.1.0
![2024-05-01_12h34_57](https://github.com/prowler-cloud/prowler/assets/168663180/d0006ddd-9779-417e-a534-0efedb33507b)

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

Ubuntu VM

### OS used

Ubuntu 

### Prowler version

Prowler 4.1.0 (You are running the latest version, yay!)

### Pip version

pip 23.2.1

**Comment by pedrooot** [comment]
Hi! @djinnert We are investigating this issue, I'll reach you when the solution is found. Thanks for the report and using Prowler!! 😄

**Comment by pedrooot** [comment]
Hi! @djinnert I'm not able to reproduce your issue. Could you please share with me the log using the `log-file <filename>` flag? Thanks!

**Comment by djinnert** [comment]
@pedrooot I did a log-level ERROR and attached it
[prowler-error.log](https://github.com/prowler-cloud/prowler/files/15189104/prowler-error.log)
.

**Comment by djinnert** [comment]
Hi @pedrooot I did some additional testing to ensure it wasn't something specific on my install but the same issue with [] in the contents and same error log.
I tried a fresh system with gitlab clone - json-ocsf contains only []
Also tried with the latest docker container - json-ocsf contains only [] 
If there is anything I can do to help or provide, let me know.

**Comment by pedrooot** [comment]
Thanks @djinnert we finally found the bug and it's expected to be fixed today!

**Comment by pedrooot** [comment]
Hey @djinnert can you execute: `aws organizations list-tags-for-resource --resource-id AWS_ACCOUNT_NUMBER` and send me the output? Thank you

**Comment by pedrooot** [comment]
Good news! @djinnert [this pr](https://github.com/prowler-cloud/prowler/pull/3914) the bug is solved! Give it a try and reopen the issue if have any problem! Thanks for using Prowler! 🤟🏼

**Comment by djinnert** [comment]
Thanks so much for getting it solved @pedrooot! I cloned that branch you made with the fix and looks like it did create the json-ocsf. Greatly appreciate it!
