### ISSUE TITLE
[Bug]: V4 sends muted fails to Security Hub

### ISSUE THREAD

**Issue by roneystein** [toniblyx/prowler#3921]
### Steps to Reproduce

1. Running command:
prowler aws -c s3_bucket_no_mfa_delete --log-level WARNING -z -f us-east-1 -O arn:aws:iam::X:role/X-D security-prowler-X -S --send-sh-only-fails -w allowlist.yaml -R arn:aws:iam::X:role/X

2. Cloud provider: aws

3. Using Organizations

### Expected behavior

When using Prowler v3 with options -q and -S the muted fails were not sent to Security Hub. When using v4 with options -S and --send-sh-only-fails the muted fails are sent to Security Hub.
It was expected to keep same behavior.

### Actual Result with Screenshots or Logs

Scans 18 resources of which 17 are muted and sends all 18 findings to SH:

```
18 findings sent to AWS Security Hub![0m
[1m
Archiving previous findings in AWS Security Hub, please wait...[0m
[1m[32m
26 findings archived in AWS Security Hub![0m
Overview Results:
╭────────────────────┬─────────────────┬───────────────────╮
│ [31m100.0% (18) Failed[0m │ [32m0.0% (0) Passed[0m │ [38;5;208m94.44% (17) Muted[0m │
╰────────────────────┴─────────────────┴───────────────────╯
Account [33mXXX[0m Scan Results (severity columns are for fails only):
```

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

Fargate task

### OS used

Amazon Linux 2023

### Prowler version

4.1.0

### Pip version

21.3.1

**Comment by jfagoagas** [comment]
Hi @roneystein, thanks for notifying this, it is a bug in Prowler v4. In the above branch a fix is available, please check that out cloning the branch with `git checkout PRWLR-3647-bug-v-4-sends-muted-fails-to-security-hub-3921` and let us know if this works as expected.

Thanks for using Prowler 🚀

**Comment by roneystein** [comment]
> Hi @roneystein, thanks for notifying this, it is a bug in Prowler v4. In the above branch a fix is available, please check that out cloning the branch with `git checkout PRWLR-3647-bug-v-4-sends-muted-fails-to-security-hub-3921` and let us know if this works as expected.
> 
> Thanks for using Prowler 🚀

It works!
