### ISSUE TITLE
Support for custom metadata fields

### ISSUE THREAD

**Issue by jchrisfarris** [toniblyx/prowler#3923]
### New feature motivation

I'd love to be able to override the various elements of a check's metadata. Right now we can override Severity, but I'd also like to override:
1. CheckTitle so I can align specific CheckIDs to my policy statements
2. Description & Risk so I can also reference internal documentation
3. RelatedUrl so I can point to internal wikis and KBs
4. Remedation.Code.Terraform / NativeIAC to point to my internal golden modules
5. Same for Recommendation

I'm not sure what the "Notes" element is for, so perhaps that can be left off the list

### Solution Proposed

Extend support in the metadata.yaml file for the above elements

### Describe alternatives you've considered

I could create my own lookup table and decorate/replace going into reports, but that wouldn't allow me to adjust what is sent to SecurityHub. 

### Additional context

IIRC we discussed this awhile back when the custom severities were implemented. Not sure if the Issue made it over into the v4 list of issues.

**Comment by pedrooot** [comment]
Hi! @jchrisfarris this task is really interesing, we are working on it. I'll reach you when it's done. Thanks for using Prowler! 🚀

**Comment by pedrooot** [comment]
Hi! @jchrisfarris in the pr above you can check the new fields!
