### ISSUE TITLE
[Bug]: Security group name missing from new json-oscf format

### ISSUE THREAD

**Issue by zfLQ2qx2** [toniblyx/prowler#3958]
### Steps to Reproduce

Run prowler checks r/ aws security groups

### Expected behavior

@jfagoagas One of the regressions I mentioned in https://github.com/prowler-cloud/prowler/issues/3788 is that in the Prowler v3 json format the name of security groups was included in ResourceDetails and this was much simplier to build whitelist functionality around then sg-xxxxxxxxxxxxxxx which doesn't really convey any meaning to humans. I was expecting that the human readable security group name, which is an attribute of the security group itself and not a tag like "Name", to be added to the unmapped section of the Prowler v4 format. I revisited this today, using Prowler v4.1.0, and spot checked a number of items from different security group related checks but I was unable to find the security group name in any of them. I think the intended fix got missed.

### Actual Result with Screenshots or Logs

Connect me directly if you need logs

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

security groups

### OS used

Alpine Linux

### Prowler version

Prowler 4.1.0

### Pip version

pip 24.0

**Comment by jfagoagas** [comment]
Hi @zfLQ2qx2, we already did that in the following PR https://github.com/prowler-cloud/prowler/pull/3819 coming from your issue and it is present in Prowler v4.1.

As you can see in the following screenshot, this is the format of the `resources` field in the JSON OCSF output:
<img width="1080" alt="Screenshot 2024-05-08 at 17 47 13" src="https://github.com/prowler-cloud/prowler/assets/16007882/aade558a-81ec-47ee-897a-446435fcb8a7">

Thanks for using Prowler 🚀

**Comment by zfLQ2qx2** [comment]
@jfagoagas Let me look at some sample results and get back to you - I am concerned that parsing the name out of the UID might not be stable. It looks like the general format of the UID is ```prowler-<cloud>-<checkname>-<security-group-name>```. AWS does allow dashes, underscores, and dots in its security group names so the immediate algorithm I see is to split the uid by dash into four fields and and and assume everything in the fourth field would be the security group name. I would only do this if there was a resource of type AwsEc2SecurityGroup present. If there were ever a check name with a dash in it then it would break this algorithm, and likewise if there were ever additional information added before or after the security group name then it would break the algorithm. If I don't see any exceptions to what is in the screenshot or if you can assure me there is stability in the uid format and check names barring a major release, then this would work.

**Comment by jfagoagas** [comment]
Hi @zfLQ2qx2 the Prowler's finding unique id won't be changed in v4. The format uses the `finding.respurce_id` not the `finding.resource_details`. In the case of the AWS EC2 Security Groups, just the name is included in the `resource_details` field. Does this shed some light into your issue?

Let me know if I can help you with anything else.

Thanks for using Prowler 🚀

**Comment by zfLQ2qx2** [comment]
@jfagoagas Yes! I was just about to write and say that I didn't see the names in the UIDs, just the identifiers, but I do see the names in resources->data->details. I'm not sure how I missed that yesterday - maybe I got confused and though what I was looking at was part of the next record. But anyway we are good! Thank you so much for your help! :)

**Comment by jfagoagas** [comment]
Thank you too! Happy to help 🙌
