### ISSUE TITLE
Bring back HTML reports

### ISSUE THREAD

**Issue by Outrun207** [toniblyx/prowler#4062]
### New feature motivation

Pulling down the findings and running a dashboard for them isn't viable for many of my customers. Please keep the HTML report format. 

### Solution Proposed

Keep the HTML report format. 

### Describe alternatives you've considered

I have tried the dashboard but it isn't viable for my customers.

**Comment by pedrooot** [comment]
Hi! @Outrun207 HTML outputs are already in master! We'll release the changes on monday!
