### ISSUE TITLE
Getting FileNotFoundError while trying to set up prowler for aws

### ISSUE THREAD

**Issue by Prabhanjali** [toniblyx/prowler#4064]
### Steps to Reproduce

downloaded prowler and trying to execute command ```prowler aws``` and getting this FileNotFoundError

### Expected behavior

prowler to work for aws

### Actual Result with Screenshots or Logs

<img width="688" alt="image" src="https://github.com/prowler-cloud/prowler/assets/79193434/4e152658-c111-4da4-b2f7-7c28ffc13c6e">

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

-

### OS used

Linux

### Prowler version

4.1.0

### Pip version

24.0

**Comment by jfagoagas** [comment]
Hi @Prabhanjali if you are cloning Prowler from Github using Windows you have to use the `git config core.longpaths true`, please refer to our documentation [here](https://docs.prowler.com/projects/prowler-open-source/en/latest/#__tabbed_1_4) for more information.

Thanks for using Prowler 🚀

**Comment by Prabhanjali** [comment]
Hi @jfagoagas, I have cloned the repo and then used ```git config core.longpaths true``` in my terminal.
Do I need to set up anything else?

**Comment by jfagoagas** [comment]
> Hi @jfagoagas, I have cloned the repo and then used `git config core.longpaths true` in my terminal. Do I need to set up anything else?

Nothing more than that, this will allow you to clone file paths exceeding the default Windows size.

**Comment by Prabhanjali** [comment]
But I'm still running into this issue

**Comment by jfagoagas** [comment]
@Prabhanjali Did you configure that and then cloned the repo? So:
1. Run `git config core.longpaths true`
2. Then, `git clone https://github.com/prowler-cloud/prowler.git`

**Comment by Prabhanjali** [comment]
Yeah... this worked fine.... but now I'm running into different issues when I run ```prowler dashboard```

**_ERROR_**:
File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 5171: invalid start byte

Can you please help me how to resolve this error?

**Comment by Prabhanjali** [comment]
Also, I observed that ```prowler aws```  this command is taking so much time to check all the resources in the account we provided. Is there any other way that makes the sync faster?

**Comment by jfagoagas** [comment]
> Yeah... this worked fine.... but now I'm running into different issues when I run `prowler dashboard`
> 
> **_ERROR_**: File "", line 322, in decode UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 5171: invalid start byte
> 
> Can you please help me how to resolve this error?

I saw that you opened a new issue related to the above so let's continue there. Thanks.

**Comment by jfagoagas** [comment]
> Also, I observed that `prowler aws` this command is taking so much time to check all the resources in the account we provided. Is there any other way that makes the sync faster?

The amount of time spent by Prowler while scanning a provider depends on your cloud environment. You can speed up the execution just scanning a subset of checks `--checks` or services `--services`. You can also scan just the regions where you have resources with the `--regions` argument.

**Comment by Prabhanjali** [comment]
How can we restrict the compliance standards we are using? Like I need to run prowler with some **cis_3.0_aws, soc2_aws, nist_csf_1.1_aws** compliance standards and with **some** **regions** enabled and also for **some set of services**.

Can you provide command for this requirement?

**Comment by jfagoagas** [comment]
> How can we restrict the compliance standards we are using? Like I need to run prowler with some **cis_3.0_aws, soc2_aws, nist_csf_1.1_aws** compliance standards and with **some** **regions** enabled and also for **some set of services**.
> 
> Can you provide command for this requirement?

Please refer to the Prowler documentation [here](https://docs.prowler.com/projects/prowler-open-source/en/latest/tutorials/compliance/) to know more about how to run compliance frameworks. You can found more information for [regions](https://docs.prowler.com/projects/prowler-open-source/en/latest/tutorials/aws/regions-and-partitions/) and [services](https://docs.prowler.com/projects/prowler-open-source/en/latest/tutorials/misc/#service).

**Comment by Prabhanjali** [comment]
How can I give --compliance for 3 different categories(cis_3.0_aws, soc2_aws, nist_csf_1.1_aws)?

**Comment by jfagoagas** [comment]
Hi @Prabhanjali you can use `--compliance cis_3.0_aws soc2_aws nist_csf_1.1_aws`.

I recommend you to join Prowler's Slack community using this [invite](https://join.slack.com/t/prowler-workspace/shared_invite/zt-2j7ot11wn-0DlRMtyNaEZ~f9mv4oU9Jg) since it is the place where this kind of questions are answered!
