### ISSUE TITLE
Getting Error when using prowler dashboard command - UnicodeDecodeError 'utf-8' codec can't decode byte 0x92 in position 5171

### ISSUE THREAD

**Issue by Prabhanjali** [toniblyx/prowler#4066]
### Steps to Reproduce

Run prowler dashboard

### Expected behavior

Prowler dashboard should work correctly

### Actual Result with Screenshots or Logs

ERROR:
File "", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 5171: invalid start byte

Can you please help me how to resolve this error?

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

.

### OS used

Linux

### Prowler version

4.1.0

### Pip version

24.0

### Context

Also, I observed that ```prowler aws``` this command is taking so much time to check all the resources in the account we provided. Is there any other way that makes the sync faster?

**Comment by Prabhanjali** [comment]
Hi @pedrooot any update regarding this?

**Comment by pedrooot** [comment]
Hey! @Prabhanjali the issue you are getting is related with encodings of csv outputs from Prowler. I have two checks for you to fix this issue:
- Take the latest changes from master branch using git pull, after that delete the output folder and re-run Prowler.
- If you already have the latest Prowler version, delete the output folder an re-run Prowler.

Tell me if it works for you and if not we will investigate furthermore!


Regarding to the times question, Prowler takes this time to scan your account because of the interaction with aws. We are trying to improve and we are open to new changes. Thanks for using Prowler!😁😁

**Comment by Prabhanjali** [comment]
Where can I find the output folder?

**Comment by pedrooot** [comment]
It should be inside the Prowler directory

**Comment by Prabhanjali** [comment]
prowler/lib/outputs?
only this outputs directory?

**Comment by pedrooot** [comment]
it should be in prowler/output, if you don't have this folder you can run Prowler

**Comment by Prabhanjali** [comment]
Hi, I am using the latest version
<img width="260" alt="image" src="https://github.com/prowler-cloud/prowler/assets/79193434/08ab81ca-4bd8-499f-89e3-fe3ad0b433de">

<img width="239" alt="image" src="https://github.com/prowler-cloud/prowler/assets/79193434/e25502bf-748e-4eec-835e-a8da7ae78f18">

I can't see any folder named outputs inside this

**Comment by pedrooot** [comment]
I can see it! It´s above permissions

**Comment by pedrooot** [comment]
btw running `python prowler.py -v` checks that you have the changes from the latest release, not the latest changes from the github repository. Use git pull to take the latest changes!

**Comment by Prabhanjali** [comment]
Hey!.. Thanks that worked now.. will reach out to you if we face any issues

**Comment by Prabhanjali** [comment]
Also, I have other doubts..
1. If we run prowler for multiple accounts from various cloud providers and store the output in same folder, will prowler be able to view it in dashboard?
2. What are the recommended file output format if we have lot of account? We wanted to store it as parquet. Will it support this? 
3. How to integrate prowler with S3 and QuickSight?

**Comment by pedrooot** [comment]
Hey! I answer your questions:
1. Yes, no problem with this
2. Currently we support the output formats shown in the [docs](https://docs.prowler.com/projects/prowler-open-source/en/latest/tutorials/reporting/). We don't support parquet but you can go from CSV to parquet with pandas
3. S3 integration it's documented [here](https://docs.prowler.com/projects/prowler-open-source/en/latest/tutorials/aws/s3/), about quicksight you can check this [link](https://docs.aws.amazon.com/quicksight/latest/user/create-a-data-set-s3.html) and see if it's valid for you.

BTW you can join our slack comunity to ask anything and share your thoughts! https://join.slack.com/t/prowler-workspace/shared_invite/zt-1hix76xsl-2uq222JIXrC7Q8It~9ZNog

**Comment by Prabhanjali** [comment]
Joined!!.. Thanks!!

**Comment by Prabhanjali** [comment]
Hi, I had all my output files that are generated for all accounts in s3, It contains a lots of GB of data. How can I visualize this using ```prowler dashboard``` on top of this by using the data I had in S3?
As your dashboard looks very clean and impressive, we don't want to disturb that dashboard visualization and use this as it is.
can you please help us with this?

**Comment by jfagoagas** [comment]
> Hi, I had all my output files that are generated for all accounts in s3, It contains a lots of GB of data. How can I visualize this using `prowler dashboard` on top of this by using the data I had in S3? As your dashboard looks very clean and impressive, we don't want to disturb that dashboard visualization and use this as it is. can you please help us with this?

Thank you very much for your feedback! We really appreciate it ❤️ 

You can use the dashboards with your data in S3 syncing it, please refer [here](https://docs.prowler.com/projects/prowler-open-source/en/latest/tutorials/dashboard/#s3-integration) to know more about it.

**Comment by Prabhanjali** [comment]
Is this Applicable for free version too? because first we want to try to it once and check how this is working

**Comment by jfagoagas** [comment]
> Is this Applicable for free version too? because first we want to try to it once and check how this is working

Right! This is available in Prowler Open Source.

**Comment by Prabhanjali** [comment]
Can you guide me how to do that? I have pushed all my outputs from local output folder to S3. How to get the dashboard now? I don't want to run the dashboard locally. Are there any other ways?

**Comment by jfagoagas** [comment]
> Can you guide me how to do that? I have pushed all my outputs from local output folder to S3. How to get the dashboard now? I don't want to run the dashboard locally. Are there any other ways?

That works in a different way, basically you can download your files fron S3 and analyse them with `prowler dashboard`.

**Comment by Prabhanjali** [comment]
Hi @jfagoagas, I have a doubt, again I'm running into this utf-8 Unicode issue, If I remove the output folder, will this dashbaord be cleared now?? Like all my account security findings be erased?

**Comment by pedrooot** [comment]
yes, it seems that you have a corrupt output in your outputs folder. To make dashboards work please follow the steps from https://github.com/prowler-cloud/prowler/issues/4066#issuecomment-2126362803

**Comment by pedrooot** [comment]
Hey! @Prabhanjali I'll close this issue, If you still have problems just re-open it. Thanks for using Prowler! 🚀
