### ISSUE TITLE
[Bug]: Pre-commit Execution Failure Due to Missing TruffleHog Dependency

### ISSUE THREAD

**Issue by Davidm4r** [toniblyx/prowler#4091]
### Steps to Reproduce

Commit a new change to start the pre-commit 
`git commit -am "Any commit message"`
Or launch pre-commit to launch trufflehog
`pre-commit run trufflehog `

### Expected behavior

When you install the Prowler dependencies using this guide: [Prowler Developer Guide](https://docs.prowler.com/projects/prowler-open-source/en/latest/developer-guide/introduction/#contributing-with-your-code-or-fixes-to-prowler), the library TruffleHog is not mentioned as a required installation. However, TruffleHog is necessary for certain functionalities. You can find more information about TruffleHog here: [TruffleHog GitHub Repository](https://github.com/trufflesecurity/trufflehog).

Because trufflehog is not installed, it returns an error.

### Actual Result with Screenshots or Logs

TruffleHog...............................................................Failed
- hook id: trufflehog
- exit code: 127

<img width="607" alt="image" src="https://github.com/prowler-cloud/prowler/assets/5548549/6a627bb2-b26d-41ae-83a2-dd6ae641887c">

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

Workstation

### OS used

MacOs

### Prowler version

Prowler 4.1.0

### Pip version

pip 24.0

**Comment by MrCloudSec** [comment]
Good catch @Davidm4r, we will change the documentation to include the installation of this requirement.
