### ISSUE TITLE
[Bug]: Inconsistent severity assigned to iam_no_custom_policy_permissive_role_assumption

### ISSUE THREAD

**Issue by rieck-srlabs** [toniblyx/prowler#4142]
### Steps to Reproduce

This issue concerns the severity classification for check ID `iam_no_custom_policy_permissive_role_assumption`.

The check has `critical` severity. It flags policies that allow unconstrained `sts:AssumeRole`.

**Why is this check classified as critical, especially when compared to other related checks, which are classified only as high? How can an attacker abuse unconstrained `sts:AssumeRole` to escalate privileges in a generic way?**
I understand that `sts:AssumeRole` allows assuming any role _in theory_. However, the role's trust policy is also consulted. Roles can only be assumed if their trust policy explicitly allowlists the caller. In addition, the role's name might not be public and is not always known.

Other AWS IAM checks that are similar are
- `iam_policy_allows_privilege_escalation`: classified as `high`, generically covering multiple options to escalate privileges
- `iam_inline_policy_no_administrative_privileges`: classified as `high`, checks for administrative permissions assigned inline.

### Expected behavior

I expect severity scores to be comparable across similarly-severe issue. However, I don't understand why the severities for the checks mentioned above differ. Part of this might be that **the check's metadata does not sufficiently explain the risk, which is stated as: `If not restricted unintended access could happen.`.**

### Actual Result with Screenshots or Logs

See above.

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

Not relevant / Workstation

### OS used

Not relevant / macOS

### Prowler version

4.1.0

### Pip version

24.0

### Context

**Note:** I've been writing up relatively minor points as issues on GitHub. I do this because I think it's useful for others to be able to revisit and find issues, and I believe GitHub's issue search to be more accessible than Slack. **Let me know if you'd prefer I raise these points via chat.**

**Comment by jfagoagas** [comment]
Hi @rieck-srlabs you're doing great! Having Github as the knowledge base is perfect 👏 

Regarding that check I agree with you that we should downgrade the severity to just `high` to also be consistent with the other related/similar checks. Do you want to modify the code and open up a PR?

Thanks for using Prowler 🚀

**Comment by rieck-srlabs** [comment]
Sounds good, I'll create a PR.

> How can an attacker abuse unconstrained sts:AssumeRole to escalate privileges in a generic way?

Do you have further insights to this question? Would love to know if there is something I'm missing.

**Comment by jfagoagas** [comment]
> Sounds good, I'll create a PR.

Great, thanks!

> > How can an attacker abuse unconstrained sts:AssumeRole to escalate privileges in a generic way?
> 
> Do you have further insights to this question? Would love to know if there is something I'm missing.

The check `iam_no_custom_policy_permissive_role_assumption` aims to comply with the Least Privilege Principle enforcing not to allow policies to assume whatever role, but as you well mentioned the role assumption in AWS requires also to check the role's trust relationship. Even with that if `Resource` is set to `*`, the user can assume any role in any account that trusts the user's account. (In other words, the role's trust policy specifies the user's account as `Principal`). As a best practice, the official recommendation from AWS is to specify the complete ARN for only the roles that the user needs.

Also I'll add this https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_permissions-to-switch.html#roles-usingrole-createpolicy to the `RelatedURL` field in the check's metadata.
