### ISSUE TITLE
Stuck in Poetry install

### ISSUE THREAD

**Issue by imvignesh27** [toniblyx/prowler#4179]
### Steps to Reproduce

poetry install

### Expected behavior

Poetry install taking too much time to install the dependencies. Expected to install the dependencies.

### Actual Result with Screenshots or Logs

![image](https://github.com/prowler-cloud/prowler/assets/79822800/c4fa6e92-1dae-4810-8f45-622d1a78ee5c)

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

VMWare

### OS used

Kali Linux

### Prowler version

4

### Pip version

23.3

### Context

After execuring poetry install, the installation take more time to install don't show any progress

![image](https://github.com/prowler-cloud/prowler/assets/79822800/6a652305-78c3-41cc-8807-1979b37494fe)

**Comment by jfagoagas** [comment]
Hi @imvignesh27, coul you please run the same command with the `--verbose -vvv` flag? Like `poetry install --verbose -vvv` and share the output here.

Thanks for using Prowler 🚀

**Comment by imvignesh27** [comment]
[Kali linux 2024 2024-06-06 16-18-37.zip](https://github.com/user-attachments/files/15613912/Kali.linux.2024.2024-06-06.16-18-37.zip)
Pls check the video I have attached.


Using virtualenv: /home/vivriti/.cache/pypoetry/virtualenvs/prowler-SHCiN9uI-py3.11

  Stack trace:

  9  /usr/lib/python3/dist-packages/cleo/application.py:327 in run
      325│
      326│             try:
    → 327│                 exit_code = self._run(io)
      328│             except BrokenPipeError:
      329│                 # If we are piped to another process, it may close early and send a

  8  /usr/lib/python3/dist-packages/poetry/console/application.py:190 in _run
      188│         self._load_plugins(io)
      189│
    → 190│         exit_code: int = super()._run(io)
      191│         return exit_code
      192│

  7  /usr/lib/python3/dist-packages/cleo/application.py:431 in _run
      429│             io.input.interactive(interactive)
      430│
    → 431│         exit_code = self._run_command(command, io)
      432│         self._running_command = None
      433│

  6  /usr/lib/python3/dist-packages/cleo/application.py:473 in _run_command
      471│
      472│         if error is not None:
    → 473│             raise error
      474│
      475│         return terminate_event.exit_code

  5  /usr/lib/python3/dist-packages/cleo/application.py:457 in _run_command
      455│
      456│             if command_event.command_should_run():
    → 457│                 exit_code = command.run(io)
      458│             else:
      459│                 exit_code = ConsoleCommandEvent.RETURN_CODE_DISABLED

  4  /usr/lib/python3/dist-packages/cleo/commands/base_command.py:102 in run
      100│
      101│         try:
    → 102│             io.input.bind(self.definition)
      103│         except CleoError:
      104│             if not self._ignore_validation_errors:

  3  /usr/lib/python3/dist-packages/cleo/io/inputs/input.py:100 in bind
       98│         self._definition = definition
       99│
    → 100│         self._parse()
      101│
      102│     def validate(self) -> None:

  2  /usr/lib/python3/dist-packages/cleo/io/inputs/argv_input.py:157 in _parse
      155│                 self._parse_long_option(token)
      156│             elif parse_options and token.startswith("-") and token != "-":
    → 157│                 self._parse_short_option(token)
      158│             else:
      159│                 self._parse_argument(token)

  1  /usr/lib/python3/dist-packages/cleo/io/inputs/argv_input.py:178 in _parse_short_option
      176│                 self._add_short_option(shortcut, name[1:])
      177│             else:
    → 178│                 self._parse_short_option_set(name)
      179│         else:
      180│             self._add_short_option(name, None)

  CleoRuntimeError

  The option "e" does not exist

  at /usr/lib/python3/dist-packages/cleo/io/inputs/argv_input.py:187 in _parse_short_option_set
      183│         length = len(name)
      184│         for i in range(length):
      185│             shortcut = name[i]
      186│             if not self._definition.has_shortcut(shortcut):
    → 187│                 raise CleoRuntimeError(f'The option "{name[i]}" does not exist')
      188│
      189│             option = self._definition.option_for_shortcut(shortcut)
      190│             if option.accepts_value():
      191│                 self._add_long_option(

**Comment by jfagoagas** [comment]
Hi @imvignesh27 I cannot say much with that stack trace and video, I think something in your Python environment is not right, could you try with a fresh new installation or Python environment?

Thanks!

**Comment by jfagoagas** [comment]
Hi @imvignesh27 I'm closing this issue. Please feel free to reopen it if you notice the same behaviour again.

You can also join our Slack workspace using this invite https://join.slack.com/t/prowler-workspace/shared_invite/zt-2j7ot11wn-0DlRMtyNaEZ~f9mv4oU9Jg where we provide support and guidance and we have a great community!


Thanks for using Prowler 🚀
