### ISSUE TITLE
Dashboard overview no longer has pages

### ISSUE THREAD

**Issue by kmatheson1** [toniblyx/prowler#4180]
### Steps to Reproduce

Launch dashboard with data from scan - view the new top findings table.  It used to be paginated.
Is this by design?

### Expected behavior

Be able to set number of rows available and also toggle through pages.

### Actual Result with Screenshots or Logs

![Screenshot 2024-06-04 at 11 48 17](https://github.com/prowler-cloud/prowler/assets/116664311/1ac34c12-1bff-4a64-afe4-5b8a57f43669)

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

Docker Container Locally

### OS used

MacOS

### Prowler version

4.2.1

### Pip version

24.0

**Comment by pedrooot** [comment]
Hey! @kmatheson1 since the number of shown findings can be set using the table rows dropdown, the paginator has been removed. We are thinking about taking it back for this new component and investigating how to do it, at the moment this is not an Bug but i'll leave the issue open to reach you when the paginator it's added. Thanks for using Prowler! 🚀

**Comment by kmatheson1** [comment]
Hey @pedrooot great that makes sense - It would be great to have it back in the future!
Thanks for the quick response!

**Comment by abant07** [comment]
Hey @pedrooot , is this something I can work on. If so, are there any specific details I should keep in mind while I figure out how to add the pagination back?

Thanks

**Comment by pedrooot** [comment]
Hey! @abant07 How are you?
We are working on a new Prowler app that it's expected to be released by september. This "new" Prowler will have its own improved UI, API, findings database... This is the reason why we are not working more on the current dashboard. 
I'll close this issue and ping you once the new version it's released.
Thanks for using Prowler! 🚀

**Comment by abant07** [comment]
No worries @pedrooot do you know if there any other issues that you guys need some urgent help with?

Thanks
