### ISSUE TITLE
[Bug]: Unable to filter muted findings in HTML output

### ISSUE THREAD

**Issue by alanrickman-keysight** [toniblyx/prowler#4181]
### Steps to Reproduce

1. Run a scan with a mutelist against an account with failures and muted failures e.g. `prowler aws --profile xxx --compliance cis_1.5_aws --mutelist-file mutelist.yaml --output-modes html csv`
2. Open the HTML report

### Expected behavior

The status filter in the HTML output should provide options for both `FAIL` and `MUTED (FAIL)` in the same way that the dashboard does.

### Actual Result with Screenshots or Logs

The dashboard shows all findings as `FAIL` so there's no easy way in the HTML output to filter out findings you've chosen to mute.

### How did you install Prowler?

From brew (brew install prowler)

### Environment Resource

Workstation

### OS used

MacOS

### Prowler version

4.2.1

### Pip version

23.3.2

**Comment by pedrooot** [comment]
Hi! @alanrickman-keysight thanks for the report! We will investigate this issue and reach you with a fix 😄

**Comment by pedrooot** [comment]
Hey! @alanrickman-keysight in [this pr](https://github.com/prowler-cloud/prowler/pull/4195) you can find the solution for this issue. Give it a try and tell me if it works for you!
Thanks for using Prowler 🚀

**Comment by alanrickman-keysight** [comment]
Hey @pedrooot thanks for this! I've given it a try and it's looking great to me. I see both `FAIL` and `Muted(FAIL)` and the filtering works perfectly.

![image](https://github.com/prowler-cloud/prowler/assets/160761476/d004155d-231e-4bdc-b969-54441bc22235)
