### ISSUE TITLE
HTML outputs no filters

### ISSUE THREAD

**Issue by pedrooot** [toniblyx/prowler#4196]
### Steps to Reproduce

prowler aws -M html

*from pip installation*

### Expected behavior

Filters in html outputs

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

windows

### OS used

windows

### Prowler version

4.2.1

### Pip version

*

**Comment by abant07** [comment]
Hey @pedrooot , I'm currently just looking for open issues I can contribute to. I sent you a message in the other issue, but in case there is no help required on that issue, I was wondering if I can help out on this issue?

Thanks

**Comment by pedrooot** [comment]
Thanks for your help! @abant07 currently we don't need help for this issue. In this one I asked a customer for more details to try to solve this issue but he didn't answered. 

I'll ping you when we need help in something.

Thanks for all!!

**Comment by pedrooot** [comment]
@abant07 remember that in our slack community people ask for new features, bugs and questions. Keep an eye there, when someone ask for something you can help 😄
