### ISSUE TITLE
[Bug]:  with the -B option  o not create the report in S3 in HTML format,

### ISSUE THREAD

**Issue by mvianardgz** [toniblyx/prowler#4239]
### Steps to Reproduce

 Task definition in ECS startup with fargate, ECR public image

"entryPoint": [
                "prowler",
                "aws",
                "-s",
                "ec2",
                "-B",
                "bucket-name"
            ],

### Expected behavior

with the -B option

Do not create the report in S3 in HTML format, only in JSON and CSV.

### Actual Result with Screenshots or Logs

![Captura de pantalla 2024-06-11 a las 10 34 27](https://github.com/prowler-cloud/prowler/assets/146238612/8ee844ae-812b-472b-8499-21fce1481a62)

### How did you install Prowler?

Docker (docker pull toniblyx/prowler)

### Environment Resource

Fargate Task

### OS used

ecr public image

### Prowler version

4.2.3

### Pip version

ecr image ppip version

**Comment by jfagoagas** [comment]
Hi @mvianardgz, we are going to check this in our test environments and we'll get back to you soon.

Thanks for using Prowler 🚀

**Comment by jfagoagas** [comment]
Hi @mvianardgz we've just fixed the issue in the above PR, could you please test it using the branch `PRWLR-3905-bug-with-the-b-option-o-not-create-the-report-in-s-3-in-html-format-4239` and let us know if this works as expected?

Thanks!
