### ISSUE TITLE
[Bug]: Assume Role Region is not valid for GovCloud Regions

### ISSUE THREAD

**Issue by collin-miller** [toniblyx/prowler#4244]
### Steps to Reproduce

1.  prowler aws --region us-gov-east-1 --role arn:aws-us-gov:iam::<account-id>:role/<role> --log-level DEBUG
2. aws
3. kubernetes
4. An error occurred (InvalidClientTokenId) when calling the AssumeRole operation: The security token included in the request is invalid

### Expected behavior

Assume role works properly with an applicable govcloud region. This is occurring because the AWS region being set does not use the region being set as a CLI argument.

### Actual Result with Screenshots or Logs

{"timestamp": "2024-06-11 20:04:10,218", "filename": "aws_provider.py:872", "level": "CRITICAL", "module": "aws_provider", "message": "ClientError[855] -- An error occurred (InvalidClientTokenId) when calling the AssumeRole operation: The security token included in the request is invalid"}

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

EKS

### OS used

Linux

### Prowler version

Prowler 4.2.4

### Pip version

pip 23.0.1

**Comment by jfagoagas** [comment]
Hi @collin-miller I'm actively checking this issue. I'll get back to you soon.

Thanks for using Prowler 🚀

**Comment by jfagoagas** [comment]
Hi @collin-miller could you please test it again with the above PR? You can clone the branch `PRWLR-3913-bug-assume-role-region-is-not-valid-for-gov-cloud-regions-4244` and let us know if this works for you.

Thanks!
