### ISSUE TITLE
[Bug]: parameter --checks is not honored anymore since v4.2.4

### ISSUE THREAD

**Issue by kagahd** [toniblyx/prowler#4253]
### Steps to Reproduce

I use prowlers option `--checks-folder` to add some customized checks to prowler. However, I also want to execute only some specific checks by using prowlers option `--checks` or `-c`. So the prowler command may look like `prowler aws -z -b --status FAIL -M json-ocsf --region eu-central-1 -c inspector2_active_findings_exist --checks-folder /home/prowler/checks/ 
`
However, instead to execute only the check `inspector2_active_findings_exist`, **all** checks within the `checks-folder` are executed since prowler v4.2.4. It still correctly worked in v4.2.3.
I think the culprit is this [code line](https://github.com/prowler-cloud/prowler/pull/4202/files#diff-dd87697c33331e0278a201e22811e95778ba4c66c9b5c7277057a7abf371067aR184) from this PR https://github.com/prowler-cloud/prowler/pull/4202, see also my comment there.

### Expected behavior

Execute the checks given by parameter `--checks` or `-c`.

### Actual Result with Screenshots or Logs

Prowler v4.2.4 executes all checks within the given `--checks-folder`.

### How did you install Prowler?

Docker (docker pull toniblyx/prowler)

### Environment Resource

workstation

### OS used

macOS

### Prowler version

4.2.4

### Pip version

24.0

### Context

I reported the bug also in [Prowlers Slack Channel](https://prowler-workspace.slack.com/archives/C045DAM2NE9/p1718612441463249).

**Comment by jfagoagas** [comment]
Hi @kagahd, as far as I can see in Prowler v4.2.3 the custom checks logic was broken so that PR fixed that. Your execution went well since you were not executing a custom check even while passing the flag to load it. I'm working to find a fix to support the following:
- Load custom checks and execute them.
- Load custom checks, specify checks or services to execute and execute them regardless if they are custom checks or not.

**Comment by kagahd** [comment]
> Your execution went well since you were not executing a custom check even while passing the flag to load it.

Well, even when I specified `-c my_custom_check` in prowler v4.2.3 , `my_custom_check` was correctly executed but not the rest of my custom checks, which is the expected behavior. Or did I misunderstand the issue you mentioned @jfagoagas?

**Comment by jfagoagas** [comment]
@kagahd that's right. The `-c/--check(s)` works in a way that allows you to filter the checks that you want to execute. The `--checks-folder` just loads those checks into Prowler and then they are executed if you want to execute all or one within that subset.

**Comment by kagahd** [comment]
> @kagahd that's right. The `-c/--check(s)` works in a way that allows you to filter the checks that you want to execute. The `--checks-folder` just loads those checks into Prowler and then they are executed if you want to execute all or one within that subset.

Yes, that's how I understood it as well. But why did you state, that:

> in Prowler v4.2.3 the custom checks logic was broken

I experienced in Prowler v4.2.3 that the custom checks logic still worked as expected, didn't it?

**Comment by jfagoagas** [comment]
> > @kagahd that's right. The `-c/--check(s)` works in a way that allows you to filter the checks that you want to execute. The `--checks-folder` just loads those checks into Prowler and then they are executed if you want to execute all or one within that subset.
> 
> Yes, that's how I understood it as well. But why did you state, that:
> 
> > in Prowler v4.2.3 the custom checks logic was broken
> 
> I experienced in Prowler v4.2.3 that the custom checks logic still worked as expected, didn't it?

As far as I can tell it was broken since Prowler wasn't executing all the custom checks alongside the current ones.
