### ISSUE TITLE
[Bug]: Prowler Dashboard in Kubernetes CronJob

### ISSUE THREAD

**Issue by Imiler** [toniblyx/prowler#4325]
### Steps to Reproduce

I have no trouble with my prowler command but as I am running this as Kubernetes CronJob inside Rancher i do not know how to generate prowler dashboard to same location as reports.

Command: `prowler aws -M html csv -R arn:aws:iam::$accountID:role/iam-prowler-access-3333333333-D prowler-3333333333`

My current prowler reports get generated and exported to s3 bucket which works fine but i do not see any options in documentation how to customize dashboard output if you are not SaaS user.

Prowler version is latest from docker image: toniblyx/prowler:latest

### Expected behavior

I run kubernetes cronjob which has prowler command to scan across 14 AWS accounts and outputs results as html and csv in single s3 bucket. 
After this i would need to add in same cronjob to generate prowler dashboard as well but i am unable to figure this out. Only command i was able to find was for SaaS users. Is it even possible to have dashboard generated in this setup?

### Actual Result with Screenshots or Logs

i dont have logs.

### How did you install Prowler?

Docker (docker pull toniblyx/prowler)

### Environment Resource

1. Rancher Kubernetes CronJob

### OS used

1. Linux
2. Kubernetes Cronjob configuration

### Prowler version

prowler 4.2.4

### Pip version

-

**Comment by pedrooot** [comment]
Hey! @Imiler I'm investigating your issue, I'll reach you with a solution soon. 
Thanks for using Prowler! 🚀

**Comment by pedrooot** [comment]
Good news! @Imiler docs related with s3 integration on Prowler dashboard were badly explained.
You can use the command show in docs to get all the Prowler outputs from your s3 bucket.
Tell me if it works for you! 😄

**Comment by pedrooot** [comment]
Reopen this issue if it's needed 🙏🏼
