### ISSUE TITLE
[Bug]: Subnets with No Resource misses evaluation by Prowler for VPC

### ISSUE THREAD

**Issue by jatin-infosys** [toniblyx/prowler#4333]
### Steps to Reproduce

1. Create a VPC
2. Add subnets and associate with them route tables
3. Create additional subnet which doesn't has any resource attached (make sure all ip's are unused for that CIDR block)
4. Run Prowler Command to test VPC

### Expected behavior

Additional Subnet should get evaluated and show either Pass/Fail

### Actual Result with Screenshots or Logs

Additional Subnet entirely missing in the output

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

EC2 Instance

### OS used

Windows

### Prowler version

4.2.4

### Pip version

24.0

**Comment by pedrooot** [comment]
Hi! @jatin-infosys How are you?
Could you share the Prowler output using `--log-level ERROR`?? It would be really useful to help you with this issue and find a solution. 
Thanks for using Prowler! 🚀

**Comment by jatin-infosys** [comment]
Thanks for the Quick Reply from logs I found that adding "--scan-unused-services" was the Key

**Comment by pedrooot** [comment]
Nice! 😄
