### ISSUE TITLE
[Bug]: Update Security Hub documentation to remove --quiet

### ISSUE THREAD

**Issue by js37** [toniblyx/prowler#4398]
### Steps to Reproduce

1. In the documentation, the instructions still mention --quiet which has been deprecated with the update to v4.
https://github.com/prowler-cloud/prowler/issues/3743

### Expected behavior

Update the documentation to use --status
https://docs.prowler.com/projects/prowler-open-source/en/latest/tutorials/aws/securityhub/#send-only-failed-findings-to-security-hub

### Actual Result with Screenshots or Logs

prowler: error: unrecognized arguments: --quiet

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

N/A

### OS used

N/A

### Prowler version

4.2.4

### Pip version

23.2.1

**Comment by MrCloudSec** [comment]
Hi @js37, thanks your reaching us out!
You're right, we will solve this shortly 🚀
