### ISSUE TITLE
Installing Prowler on AWS CloudShell fails due to no space left on device

### ISSUE THREAD

**Issue by paulschwarzenberger** [toniblyx/prowler#4453]
### Steps to Reproduce

1. Open AWS CloudShell
2. Delete CloudShell environment and start new one
3. `pip install prowler`

### Expected behavior

Prowler installs successfully

### Actual Result with Screenshots or Logs

`ERROR: Could not install packages due to an OSError: [Errno 28] No space left on device: '/home/cloudshell-user/.local/lib/python3.9/site-packages/msgraph_sdk-1.4.0.dist-info/INSTALLERlsp4cvn3.tmp'`

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

AWS CloudShell

### OS used

Amazon Linux 2023 (AWS CloudShell)

### Prowler version

4.2.4

### Pip version

21.3.1

**Comment by jfagoagas** [comment]
Hello @paulschwarzenberger, how are you?

Did you follow the installation steps detailed here https://docs.prowler.com/projects/prowler-open-source/en/latest/#__tabbed_1_7 for AWS CloudShell?

Thanks for using Prowler 🚀

**Comment by paulschwarzenberger** [comment]
Thanks @jfagoagas for picking this up, yes that seems to work - apologies for not reading the documentation!
I just read `Prowler can thus be easily installed following the Generic method of installation via pip` without reading the clarification for v4.

**Comment by jfagoagas** [comment]
@paulschwarzenberger that's totally fine, we are here to help!
