### ISSUE TITLE
HTML Assessment Overview Not Reporting Numbers

### ISSUE THREAD

**Issue by sarahlizpurkey** [toniblyx/prowler#4460]
### Steps to Reproduce

The command I ran was 
```
prowler aws
```
It generated an HTML report, and when I opened the HTML report in the browser it had the string 'TOTAL_FINDINGS' where it should have the actual number of findings.

### Expected behavior

It should say the actual number of Total Findings, Passed, etc.

### Actual Result with Screenshots or Logs

![image](https://github.com/user-attachments/assets/fb06d0df-3d18-4b7f-aaef-532e01bff6c3)

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

1. EC2 instance

### OS used

5. Other - Ubuntu Linux

### Prowler version

4.2.4

### Pip version

24.0

### Context

I can open up a pull request and fix it myself!

**Comment by pedrooot** [comment]
Hey! @sarahlizpurkey How are you doing? This seems to be a weird bug, we will investigate furthermore about this issue and I´ll reach you with a solution.
We'll keep in touch, thanks for using Prowler! 🚀

**Comment by pedrooot** [comment]
Could you add the flag `--log-level ERROR` and share with me the log?

**Comment by pedrooot** [comment]
Hey @sarahlizpurkey  did you have time to take a look at this? Please send us the ERROR log and please go ahead if you want to open up a PR to fix that as you mentioned!

**Comment by pedrooot** [comment]
Hey! @sarahlizpurkey this it's just a reminder of this issue, If you could check my previous messages it would be nice 😄

**Comment by pedrooot** [comment]
Hey! @sarahlizpurkey this PR will be closed, if you need any help just re-open it. Thanks for using Prowler!!! 🚀
