### ISSUE TITLE
Filter findings by status does not have any effect on output files

### ISSUE THREAD

**Issue by nrvnrvn** [toniblyx/prowler#4571]
### Steps to Reproduce

```sh
prowler aws --profile <profile_name> --status FAIL --output-formats csv json-ocsf html
```

### Expected behavior

Passing `--status FAIL` in v4 [should behave](https://github.com/prowler-cloud/prowler/pull/3238) in a similar way it worked in v3 but in current state it generates the same output as if the flag is not passed at all.

### Actual Result with Screenshots or Logs

n/a

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

workstation

### OS used

macos

### Prowler version

Prowler 4.3.0

### Pip version

pip 24.2

**Comment by jfagoagas** [comment]
Hello @nrvnrvn, thank you for reporting this. I'm going to take a look a it now and I'll get back to you once I have more information about it.

Thanks for using Prowler 🚀

**Comment by jfagoagas** [comment]
@nrvnrvn I brought back that behaviour. We got rid of it doing some refactors and the lack of proper testing in that part allowed this to happen. I apologise for this.

Please take a look at the above PR and it'd be great if you could test it. Let us know if everything works as expected. We are going to work to improve testing for that part of the code to prevent this from happening again.

Thanks!

**Comment by nrvnrvn** [comment]
a quick and dirty fix that I have tested and it works is to filter `finding_outputs`:

https://github.com/prowler-cloud/prowler/blob/4.3.0/prowler/__main__.py#L305-L307

and change it to 
```python
Finding.generate_output(global_provider, finding) for finding in findings if (not global_provider.output_options.status or finding.status in global_provider.output_options.status)
```

But it is not what is actually needed because in case of no failures at all no output is generated whatsoever. At a glance it looks like it needs to be filtered at the [`Output`](https://github.com/prowler-cloud/prowler/blob/4.3.0/prowler/lib/outputs/output.py#L46) level similar to how [`SecurityHub.filter`](https://github.com/prowler-cloud/prowler/blob/4.3.0/prowler/providers/aws/lib/security_hub/security_hub.py#L97-L102) method does.

**Comment by nrvnrvn** [comment]
@jfagoagas the fix works as described above and at this moment I need to understand whether it is the expected behavior.

with `--status FAIL`:
- all checks pass: no output is created and prowler says `There are no findings in Account XXXXX`.
- some checks fail: the report contains all the failures but in case of html report the number of Total findings shown is equal to the number of failures. Whereas v3 showed the total number.
v4 dashboard also does not show the overall number of findings. 

The question is: is it ok that `--status` will not only filter out the output as expected but also will hide the number of filtered out findings? 

For example, running all checks against a crystal clear AWS account will show no findings but at the same time the end user will not be able to distinguish a PASS with zero checks and zero findings from a PASS with all checks and 1500 passed findings.

**Comment by MrCloudSec** [comment]
Hi @nrvnrvn, thans for reaching us out. We are working on the fix.

About your questions, the `--status` flag filter the findings while Prowler is executing so no findings other that the input status are going to be shown in the outputs.

If you want to other findings to appear in the outputs, you can do a normal execution of Prowler and then use the filters of the HTML, CSV...

We will document this better in the docs for making it clear, let me know if that makes sense to you 😄

**Comment by nrvnrvn** [comment]
@sergargar that makes perfect sense, thanks a lot!
