### ISSUE TITLE
Errors in scanning AWS Managed Registries

### ISSUE THREAD

**Issue by agasthik** [toniblyx/prowler#4573]
### Steps to Reproduce

Deploy the [aws-security-assessment-solution](https://github.com/awslabs/aws-security-assessment-solution) using the CFT templates provided.
Set the Prowler log level in the ProwlerOptions Parameter `aws --ignore-exit-code-3 --log-level ERROR`
Run the CodeBuild job and review the execution logs

### Expected behavior

Prowler should not scan for AWS Managed registries. This error in the logs should not be encountered. 

### Actual Result with Screenshots or Logs

Seeing this error in the logs

`024-07-27 03:12:18,169 [File: eventbridge_service.py:142] 	[Module: eventbridge_service]	 ERROR: us-east-1 -- ForbiddenException[132]: An error occurred (ForbiddenException) when calling the GetResourcePolicy operation: You do not have the permission to view/modify policies for AWS managed registries with name prefixed with 'aws.'`

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

6. CodeBuild 

### OS used

Codebuild Image `aws/codebuild/amazonlinux2-x86_64-standard:5.0`

### Prowler version

4.2.4

### Pip version

24.0

**Comment by MrCloudSec** [comment]
Hi @agasthik, thanks for openning the issue!
This issue was solved [here](https://github.com/prowler-cloud/prowler/pull/4289) by avoiding to get policies from AWS managed schema registries.
Feel free to reopen the issue if you are still facing the issue with Prowler 4.3.0.
