### ISSUE TITLE
Missing Permissions

### ISSUE THREAD

**Issue by agasthik** [toniblyx/prowler#4576]
### Steps to Reproduce

- Deploy the [aws-security-assessment-solution](https://github.com/awslabs/aws-security-assessment-solution) using the CFT templates provided.
- Set the Prowler log level in the ProwlerOptions Parameter aws --ignore-exit-code-3 --log-level ERROR
- Run the CodeBuild job and review the execution logs

### Expected behavior

This error in the logs should not be encountered.

### Actual Result with Screenshots or Logs

#1
`2024-07-30 14:09:29,030 [File: backup_service.py:137] 	[Module: backup_service]	 ERROR: ap-northeast-3 -- ClientError[112]: An error occurred (AccessDeniedException) when calling the ListReportPlans operation: Insufficient privileges to perform this action.`

#2
`2024-07-30 14:17:38,644 [File: ec2_service.py:410] 	[Module: ec2_service]	 ERROR: us-west-1 -- ClientError[402]: An error occurred (UnauthorizedOperation) when calling the GetSnapshotBlockPublicAccessState operation: You are not authorized to perform this operation. User: arn:aws:sts::XXXXXXXXXXXX:assumed-role/ProwlerMemberRole/ProwlerAssessmentSession is not authorized to perform: ec2:GetSnapshotBlockPublicAccessState because no identity-based policy allows the ec2:GetSnapshotBlockPublicAccessState action`

#3
`2024-07-30 15:18:35,328 [File: ec2_elastic_ip_shodan.py:39] [Module: ec2_elastic_ip_shodan] ERROR: No Shodan API Key -- Please input a Shodan API Key with -N/--shodan or in config.yaml`

For #2 , We need to add another permission for `ec2:GetSnapshotBlockPublicAccessState`  in the [prowler-additions-policy.json](https://github.com/prowler-cloud/prowler/blob/master/permissions/prowler-additions-policy.json)

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

Codebuild

### OS used

Codebuild Image aws/codebuild/amazonlinux2-x86_64-standard:5.0

### Prowler version

4.3.0

### Pip version

24.0

**Comment by MrCloudSec** [comment]
Hi @agasthik, thanks for opening the issue!
We will work on it and release a fix soon 🚀

**Comment by MrCloudSec** [comment]
@agasthik I saw the necessary permissions for case #1 [here](https://github.com/awslabs/aws-security-assessment-solution/blob/9ccc99153cd2fc8fe6dc6629153b4cac1b614a40/2-sat2-codebuild-prowler.yaml#L121).
How do you have configured your Backup Report plans so we can get more information? Thanks!

**Comment by js37** [comment]
#1 is because Backup Audit Manager isn't launched in that region https://docs.aws.amazon.com/aws-backup/latest/devguide/backup-feature-availability.html

**Comment by agasthik** [comment]
@sergargar - the error is seen only in that region. @js37 's comment explains it. Thanks @js37 . We can ignore it
