### ISSUE TITLE
documentdb_cluster_backup_enabled fails when retention time is equal to minimum

### ISSUE THREAD

**Issue by cetteup** [toniblyx/prowler#4588]
### Steps to Reproduce

Run prowler (`docker run toniblyx/prowler`) against an AWS account with a DocumentDB cluster configured to retain backups for 7 days.

### Expected behavior

`documentdb_cluster_backup_enabled` should pass when the retention period is configured to satisfy the minimum.

### Actual Result with Screenshots or Logs

`documentdb_cluster_backup_enabled` check still fails when backup retention is set to the minimum value given in the extended status (7 days).

> DocumentDB Cluster [redacted] has backup enabled with retention period 7 days. Recommended to increase the backup retention period to a minimum of 7 days.

### How did you install Prowler?

`pip install prowler`

### Environment Resource

Workstation/GitHub Actions

### OS used

`ubuntu-latest` (GitHub Actions)/Fedora 40 Workstation

### Prowler version

4.3.0

### Pip version

24.2

### Context

The status message is not aligned with the condition in the check, which requires the configured retention period to be *greater* than 7 days.
https://github.com/prowler-cloud/prowler/blob/f639dc8bf4e3b2180ec60ff79557bb702625fad1/prowler/providers/aws/services/documentdb/documentdb_cluster_backup_enabled/documentdb_cluster_backup_enabled.py#L20-L29

Note that the same config value is used by `neptune_cluster_backup_enabled`, which has the same issue.
https://github.com/prowler-cloud/prowler/blob/f639dc8bf4e3b2180ec60ff79557bb702625fad1/prowler/providers/aws/services/neptune/neptune_cluster_backup_enabled/neptune_cluster_backup_enabled.py#L18-L27

I'm happy to send a PR for this, I'm just not sure whether the status message or the condition is to be considered correct.

**Comment by jfagoagas** [comment]
Hello @cetteup that's a great catch! We need to change the comparison to `>=`. Please open up a PR to fix that, could you be able to adjust also the tests for both checks?

Regarding the `status_extended` I think it is correct.

Thanks for contributing with Prowler 🚀

**Comment by cetteup** [comment]
Fixed for both services in #4593. Also added a new test for both to cover the "equal" case.
