### ISSUE TITLE
Add new EKS check to ensure they run on a supported Kubernetes version

### ISSUE THREAD

**Issue by puchy22** [toniblyx/prowler#4589]
### New feature motivation

Implement a new EKS check to verify that clusters are running on a supported Kubernetes version.

### Solution Proposed

This control checks whether an Amazon Elastic Kubernetes Service (Amazon EKS) cluster runs on a supported Kubernetes version. The control fails if the EKS cluster runs on an unsupported version. The latest supported version is the 1.28 so this checks must be configurable adding for now this version as default parameter.

### Describe alternatives you've considered

There is no alternative.

### Additional context

https://docs.aws.amazon.com/securityhub/latest/userguide/eks-controls.html#eks-2

**Comment by abant07** [comment]
Hey @puchy22 can I work on this one?

Thanks
