### ISSUE TITLE
--status FAIL flag does not seem to work on 4.3.0

### ISSUE THREAD

**Issue by be-lka** [toniblyx/prowler#4599]
### Steps to Reproduce

Whenever we've updated Prowler to 4.1.0, --status FAIL flag would return us no results allowing us to parse JSON responses to see only real problems found by Prowler. 

Now on 4.3.0 running `prowler aws -c efs_not_publicly_accessible --no-banner -M json-ocsf --status FAIL` does not returns empty JSON file for PASSED checks like before. Seems to not work.

### Expected behavior

Output JSON file was expected to return empty since there is no FAILED checks on the account.

### Actual Result with Screenshots or Logs

![image](https://github.com/user-attachments/assets/655b8212-a381-43f5-baa5-5f770057b53d)

### How did you install Prowler?

From brew (brew install prowler)

### Environment Resource

Local workstation

### OS used

MacOS

### Prowler version

4.3.0

### Pip version

24.1.2

**Comment by jfagoagas** [comment]
Hello @exiett, this issue was identified earlier at https://github.com/prowler-cloud/prowler/issues/4571 and now is currently fixed. You can try it out using the `master` branch.

We are targeting later today or tomorrow to release a patch version.

Thanks for using Prowler 🚀
