### ISSUE TITLE
Wrong KMS crypto key id in output

### ISSUE THREAD

**Issue by benlahav** [toniblyx/prowler#4600]
### Steps to Reproduce

1. Run prowler for gcp, e.g. `prowler gcp --credentials-file ./credentials.json`
2. Watch the output CSV and see for kms checks `kms_key_not_publicly_accessible`, `kms_key_rotation_enabled` that `RESOURCE_UID` & `RESOURCE_NAME` are both the same kms key name.

### Expected behavior

Have the `RESOURCE_UID` include the key-ring which this key is included in for distinction.

### Actual Result with Screenshots or Logs

<img width="902" alt="image" src="https://github.com/user-attachments/assets/4bbc79d2-49b1-40d5-8651-d192c216f5b7">

### How did you install Prowler?

From brew (brew install prowler)

### Environment Resource

Workstation

### OS used

MacOS

### Prowler version

4.3.0

### Pip version

24.1.2

### Context

Running prowler for gcp account and see that this can't have distinction.  
Different key can have same name if they are under the different key ring, this means that in the current report we can't distinct between 2 similar keys.

**Comment by pedrooot** [comment]
Hey! @benlahav in [this PR](https://github.com/prowler-cloud/prowler/pull/4610) you can find the solution for your issue. Tell me if it works for you 🙏🏼 
Thanks for using Prowler and the report! 🚀
