### ISSUE TITLE
Bug on cloudsql_instance_ssl_connections

### ISSUE THREAD

**Issue by JOSHUAJEBARAJ** [toniblyx/prowler#4618]
### Steps to Reproduce

Hey folks, I am currently running Prowler on the GCP provider. Under Cloud SQL, one of the checks is `cloudsql_instance_ssl_connections`. This check evaluates whether Cloud SQL is allowing insecure SSL connections.

### Expected behavior

According to the CIS benchmark 
Ensure that section settings: `ipConfiguration` has the parameter `sslMode` set to
`ENCRYPTED_ONLY` .

### Actual Result with Screenshots or Logs

But we are currently looking for [require_ssl](https://github.com/prowler-cloud/prowler/blob/master/prowler/providers/gcp/services/cloudsql/cloudsql_service.py#L35) field  instead of the `sslMode` field

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

1. Local

### OS used

Mac

### Prowler version

Prowler 4.2.1

### Pip version

pip 20.3.4

### Context

Even though the current check doesn't produce any false positives, I thought it would be better to stick to the CSI Benchmark. Feel free to close this issue if you believe it’s not a significant concern.

**Comment by thejaywhy** [comment]
Heya @JOSHUAJEBARAJ thanks for letting us know about this and the great write up. We'll review it with the team, and we'll get back to you soon.

Thanks for using Prowler 🚀 !

**Comment by pedrooot** [comment]
Hey! @JOSHUAJEBARAJ do you think that we should also check that `requireSsl` is True? 
I think that it's needed because if no ssl is required, no matter how is the ssl mode.

**Comment by JOSHUAJEBARAJ** [comment]
Technically checking `requireSsl` would be suffice in my point of view, but the CSI benchmark specifies to check the `sslMode` rather than the `requireSsl` field thats why I suggested that

**Comment by pedrooot** [comment]
Nice! I'll refactor this check to check both parameters: `requireSsl` and `sslMode`. The reason to do this is because ssl should be applied to take into account the sslMode. I'll ping you once this issue is resolved

**Comment by pedrooot** [comment]
Hi! @JOSHUAJEBARAJ [in this pr](https://github.com/prowler-cloud/prowler/pull/4635) you can find the solution for this issue. Thanks for using Prowler! 🚀
