### ISSUE TITLE
No data available Check the data folder to see if the files are in the correct format (prowler publish with public ip)

### ISSUE THREAD

**Issue by mauricio024** [toniblyx/prowler#4619]
### Steps to Reproduce

docker run -e HOST=0.0.0.0 -p 11666:11666 toniblyx/prowler:latest dashboard
I am using elastic ip in ec2 instance 
I want publish the site prowler

### Expected behavior

the site doesnt load the graphs and data account was 

### Actual Result with Screenshots or Logs

i dont have logs, I donk know the logs error in linux
![prowlererror](https://github.com/user-attachments/assets/11ab83ef-e21e-4521-a1f9-bbef5753483c)

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

EC2 instance

### OS used

amazon linux

### Prowler version

lastest

### Pip version

lastest

### Context

I am trying to publish the porwler through ec2 with a public IP and I am using docker within the instance, but when the page loads it does not bring the data of the scans that I have performed.

**Comment by thejaywhy** [comment]
Hi @mauricio024, thanks for notifying us about this! It looks like we need to update our docs. 

When running the dashboard with docker, you may need to specify a volume, `--volume` flag to the `docker run` command:

```copy
docker run --env HOST=0.0.0.0 --publish 127.0.0.1:11666:11666 --volume ${PWD}/output:/home/prowler/output toniblyx/prowler:latest dashboard
```

In this command, the `--volume` argument will load the current working directory, plus the `/output` director into the container at `/home/prowler/output`.

When using `${PWD}` like this, it assumes you are starting the container from the directory that has your prowler results. 

You can pass the complete path instead: `--volume /full/path/to/prowler/output:/home/prowler/output`. 

Let me know if this helps you load the dashboard, and we'll work on updating the docs.
