### ISSUE TITLE
Mutelist pattern

### ISSUE THREAD

**Issue by christiandavilakoobin** [toniblyx/prowler#4634]
### Steps to Reproduce

It seems that mutelist object have changed somehow. We have this mutelist block:

```
"cloudwatch_log_group_retention_policy_specific_days_enabled": {
    "Regions": [
      "*"
    ],
    "Resources": [
      "processmail-Archiver"
    ]
  }
```

Until 4.2.4, it muted correctly all log groups containing the string "processmail-Archiver", such "live-processmail-Archiver" or "pre-processmail-Archiver", but on 4.3.1, both log groups raised an alert:

![image](https://github.com/user-attachments/assets/09d594b6-32c1-4565-99eb-3525f3387aad)

### Expected behavior

It should be muted like 4.2.4:

![image](https://github.com/user-attachments/assets/96486bf3-fa25-482f-85b4-8687478d1300)

### Actual Result with Screenshots or Logs

![image](https://github.com/user-attachments/assets/09d594b6-32c1-4565-99eb-3525f3387aad)

### How did you install Prowler?

Docker (docker pull toniblyx/prowler)

### Environment Resource

3. Docker cointainer

### OS used

5. Docker cointainer

### Prowler version

4.3.1

### Pip version

the one on docker

**Comment by pedrooot** [comment]
Hey! @christiandavilakoobin thanks for the report! We'll review it with the team, and we'll get back to you soon. 
Thanks for using Prowler 🚀 !!

**Comment by jfagoagas** [comment]
Hello @christiandavilakoobin we changed the behaviour in a previous PR by mistake. I apologize for that. 

We have fixed and improved our documentation in the above PR.

Thank you!
