### ISSUE TITLE
check id "iam_root_hardware_mfa_enabled" PASS for virtual MFA device!

### ISSUE THREAD

**Issue by pjhavariotis** [toniblyx/prowler#4652]
### Steps to Reproduce

I have just realized that the check id `iam_root_hardware_mfa_enabled` is not working as expected!
To be specific, I have enabled a "**virtual MFA device**" for my AWS account root user.
As far as I know, If the ARN of the associated IAM user returned by the `aws iam list-virtual-mfa-devices` command output is `arn:aws:iam::[aws-account-id]:root`, then my AWS root account is not using a hardware-based MFA device for MFA protection.

### Expected behavior

I would expect this check to **FAIL**. On the contrary, prowler reports back that this check has status **PASS**!

### Actual Result with Screenshots or Logs

![image](https://github.com/user-attachments/assets/1d863236-85bb-4c0f-b019-d27a86b4abad)

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

Workstation

### OS used

Windows

### Prowler version

Prowler 4.3.2

### Pip version

pip 24.2

**Comment by pedrooot** [comment]
Hey! @pjhavariotis thanks for the report! We will review this issue with the team and reach you with a solution! 
Thanks for using Prowler 🚀

**Comment by MrCloudSec** [comment]
Hi @pjhavariotis, I could not reproduce your error, Prowler will mark this check as FAIL if the call `aws iam list-virtual-mfa-devices` returns `arn:aws:iam::[aws-account-id]:root` as you mentioned. 

Is the AWS API returning that? If yes, are you using the same credentials for the AWS CLI and Prowler?

Thanks!

**Comment by pjhavariotis** [comment]
Please check below the screenshots from the AWS CLI call as well as from Prowler:
![image](https://github.com/user-attachments/assets/90c85069-4e11-43b6-9959-4517d7c7ad3f)
![image](https://github.com/user-attachments/assets/d4cf0c30-d150-48b6-b7be-94d2fde731f1)

**Comment by MrCloudSec** [comment]
Thanks for the information @pjhavariotis, could you do the `aws iam list-virtual-mfa-devices` API Call without the filters please? Make sure that you hide any sensitive information.

**Comment by pjhavariotis** [comment]
![image](https://github.com/user-attachments/assets/2d63ada3-bb15-4a1f-96bd-9ba3670c30d8)

**Comment by MrCloudSec** [comment]
That is exactly what I needed to work in a fix, I'll let you know when we have it ready so you can test it. Thank you @pjhavariotis !

**Comment by MrCloudSec** [comment]
@pjhavariotis, the above PR solves this issue, let us know if the solution works on your side!
