### ISSUE TITLE
Report Security Groups that are not attached to any instances

### ISSUE THREAD

**Issue by be-lka** [toniblyx/prowler#4667]
### New feature motivation

Current state of Prowler only reports Security Groups that are attached to any instance.

### Solution Proposed

Have a flag or specific check (securitygroup_**all**_allow_ingress_to_tcp_22) which reports every security group that offends a given check.

### Describe alternatives you've considered

Listing out using AWS CLI and filtering out offending open ports would work too.

### Additional context

It would be nice though if Prowler had an option to not take into account if the Security Group is attached. It would help in some clean-up operations. [Refer to Slack thread if you want more details](https://prowler-workspace.slack.com/archives/C045DAM2NE9/p1722958094617639).

**Comment by jfagoagas** [comment]
Hello @exiett thanks for suggesting this new feature but the behaviour you need is already covered by the `--scan-unused-services` flag, you can get more information about it here https://docs.prowler.com/projects/prowler-open-source/en/latest/tutorials/scan-unused-services/.

As an example, I have just created the following AWS Security Group, not attached to anything with an ingress rule allowing traffic to the 22/tcp port from the Internet:
![Screenshot 2024-08-07 at 08 50 07](https://github.com/user-attachments/assets/935fb8d9-e449-455e-876a-2ffe361b6f1a)

Running a scan without the flag `--scan-unused-services` generates 0 findings for this AWS Security Group but if I set the flag, the Prowler output is the following:
```
prowler git:(master) ✗ prowler \
  --region eu-west-1 \
  --check ec2_securitygroup_allow_ingress_from_internet_to_tcp_port_22 \
  --verbose \
  --scan-unused-services
                         _
 _ __  _ __ _____      _| | ___ _ __
| '_ \| '__/ _ \ \ /\ / / |/ _ \ '__|
| |_) | | | (_) \ V  V /| |  __/ |
| .__/|_|  \___/ \_/\_/ |_|\___|_|v4.3.1
|_| the handy multi-cloud security tool

Date: 2024-08-07 08:48:13


Color code for results:
- MANUAL (Manual check)
- PASS (Recommended value)
- MUTED (Muted by muted list)
- FAIL (Fix required)
            
-> Using the AWS credentials below:
  · AWS-CLI Profile: test
  · AWS Regions: eu-west-1
  · AWS Account: 111122223333
  · User Id: XXXXXXXXXXXXX
  · Caller Identity ARN: arn:aws:sts::111122223333:XXXXXXXXXXXXX

-> Using the following configuration:
  · Config File: prowler/prowler/config/config.yaml
  · Mutelist File: prowler/prowler/config/aws_mutelist.yaml
  · Scanning unused services and resources: True

Executing 1 check, please wait...

Check ID: ec2_securitygroup_allow_ingress_from_internet_to_tcp_port_22 - ec2 [high]
        FAIL eu-west-1: Security group not-attached (sg-05d92c9de73c29c2d) has SSH port 22 open to the Internet.
```

Could you please test it and let us know if this works for you?

Thank you for using Prowler 🚀

**Comment by be-lka** [comment]
Hey @jfagoagas , you're correct! Just tried the flag and it works like a charm. Thank you so much.
