### ISSUE TITLE
cis_2.1_azure incorrect checks resulting in incorrect outputs 

### ISSUE THREAD

**Issue by centralBellHop** [toniblyx/prowler#4754]
### Steps to Reproduce

Running cis_2.1_azure compliancy checks results in incorrect results for controls 9.5, 9.6, 9.7, 9.8 and 9.9

### Expected behavior

PHP should use PHP check, Java should use Java check, etc.

### Actual Result with Screenshots or Logs

<img width="755" alt="image" src="https://github.com/user-attachments/assets/13fa98d0-3163-4b21-96e9-aaef463df74c">

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

VM

### OS used

Kali Linux

### Prowler version

cis 2.1

### Pip version

-

**Comment by puchy22** [comment]
Hi @centralBellHop,

Thank you for bringing this to our attention and for using Prowler! We've addressed the mapping issues you pointed out, along with a few others we discovered during our review. The fixes have been included in a new pull request #4760.

We appreciate your contribution and your help in making Prowler better 🚀
