### ISSUE TITLE
Check to see if IAM Users or Roles have Administrator access

### ISSUE THREAD

**Issue by jmanduca-psfy** [toniblyx/prowler#4777]
### New feature motivation

While a check to see if a policy exists with Admin access and if it is attached to users or roles (`iam_aws_attached_policy_no_administrative_privileges`), it checks the Policy resource. It does not tell us what actual users or roles have it attached, and does not work well with allowlisting for users/roles where administrator is expected to actually be used.

### Solution Proposed

A new check that will target the IAM User/Role resources to see if they have policies with Administrator access attached.

### Describe alternatives you've considered

Building a script myself to use AWS cli to perform the check, similar to https://www.trendmicro.com/cloudoneconformity/knowledge-base/aws/IAM/admin-permissions.html.
Or adding in the description or other field in the results of the `iam_aws_attached_policy_no_administrative_privileges` check to display which user/roles are impacted.

### Additional context

The default AdministratorAccess role is commonly used for an actual Admin user, and while it should be avoided, it is not often feasible to do so. The current check can show that it is used, but will not actually show that it is used by a user/role that should not have it.

**Comment by pedrooot** [comment]
Hello @jmanduca-psfy , that is a great improvement, we will think about it and get back to you once the team has an update.

Thanks for using Prowler! 😄

**Comment by puchy22** [comment]
Hi @jmanduca-psfy,

I've implemented the feature you requested and created a [PR](https://github.com/prowler-cloud/prowler/pull/4802) for it. Please review it and let me know if it meets your expectations. I focused on adding the admin user check, as the role-related check is already covered in `iam_role_administratoraccess_policy`.

Looking forward to your feedback!

**Comment by jmanduca-psfy** [comment]
Hey @puchy22 , just tested it out and it works as described! And thanks for pointing out `iam_role_administratoraccess_policy`, I missed that one.
I did notice that this will find users with the policy directly attached, but does not detect users that have admin due to group membership - and there doesn't seem to be checks for Groups with administrator access currently. Would that be a separate request, or does it make sense to also check if the group(s) the user has provides administrator access within this check?

**Comment by puchy22** [comment]
Hey @jmanduca-psfy, I'm glad to hear that the solution worked for you! I think that is a great point about checking for groups with administrator access, following the same logic as other it makes sense to me. I will close this issue, but I’ve opened this new one #4807 to you can track the development of this new check.

Thanks again for your valuable input and for using Prowler! 🚀
