### ISSUE TITLE
Execution Failure 'str' object has no attribute 'items'

### ISSUE THREAD

**Issue by vishakh-falcon** [toniblyx/prowler#4799]
### Steps to Reproduce

1. Ran the command "prowler aws" with IAM credentials configured in the environment variables
2. The application/code runs for nearly 40mins and then fails at the error 'str' object has no attribute 'items' 
3. No data/compliance event reports (json, csv) are written into the ./output/compliance folder
<img width="1155" alt="Screenshot_2024-08-19_at_8_39_33 PM" src="https://github.com/user-attachments/assets/70da80a5-0e54-4dcf-88fa-9c77f4d6701c">

### Expected behavior

As expected behavior, the application should complete the execution successfully and then generate the compliance reports (csv, json) 

### Actual Result with Screenshots or Logs

<img width="1155" alt="Screenshot_2024-08-19_at_8_39_33 PM" src="https://github.com/user-attachments/assets/94fd0ff2-0eb5-4466-a137-5eabd6c934de">
Attached is the screenshot of the execution

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

1. Launched/tried from Amazon EC2 Amzn Linux 2 and Linux 3 servers
2. Launched/tried from MacOS M1 Pro with Sonoma OS

### OS used

1. Launched/tried from Amazon EC2 Amzn Linux 2 and Linux 3 servers
2. Launched/tried from MacOS M1 Pro with Sonoma OS

### Prowler version

Prowler 4.3.3

### Pip version

pip 24.2 with python 3.12

**Comment by pedrooot** [comment]
Hey! @vishakh-falcon this issue is related with #4740 
To get more info from this, could you share with me the syntax of the resource tags? This way we can track the error easier, if you have serveral tags and is difficult to get the one failing, you can add a `print(tags)` just before this line: 
`return {key: value for d in tags for key, value in d.items()}`
Thanks for reporting this!

**Comment by pedrooot** [comment]
Hey! @vishakh-falcon in [this pr](https://github.com/prowler-cloud/prowler/pull/4817) you can find the solution for your issue, tell me if that works for you!

**Comment by vishakh-falcon** [comment]
Hi @pedrooot Thanks for your response and sharing the information.
I see the fix is not merged or released with new app version for validation

```
Merging is blocked
Merging can be performed automatically with 1 approving review.
```

**Comment by pedrooot** [comment]
Hey! @vishakh-falcon  It's already merged on master and we will add this to the next release.
