### ISSUE TITLE
New check to ensure that a group has not administrative privileges

### ISSUE THREAD

**Issue by puchy22** [toniblyx/prowler#4807]
### New feature motivation

As described in this issue #4777 there were no checks for checking Admin privileges. Following the same logic Groups must have his own check.

### Solution Proposed

Implement new check following the same logic as `iam_role_administratoraccess_policy` and  `iam_user_administrator_access_policy`.

### Describe alternatives you've considered

Use `iam_aws_attached_policy_no_administrative_privileges` with inline policies attached to groups.

**Comment by puchy22** [comment]
Hi @jmanduca-psfy, I hope everything is going well. The [PR](https://github.com/prowler-cloud/prowler/pull/4831) with the new check for groups is ready if you want to take a look at it and send me some feedback.

Thanks for everything.

**Comment by jmanduca-psfy** [comment]
Hey @puchy22 , just tried it out and it works great. Thanks for implementing this! And so quickly.
