### ISSUE TITLE
Improve `detect-secrets` engine: configuration + plugins

### ISSUE THREAD

**Issue by jfagoagas** [toniblyx/prowler#4893]
### Steps to Reproduce

Prowler relies on https://github.com/Yelp/detect-secrets to detect secrets for some AWS resources in some checks:

- autoscaling_find_secrets_ec2_launch_configuration
- awslambda_function_no_secrets_in_code
- awslambda_function_no_secrets_in_variables
- cloudformation_stack_outputs_find_secrets
- cloudwatch_log_group_no_secrets_in_logs
- ec2_instance_secrets_user_data
- ec2_launch_template_no_secrets
- ecs_task_definitions_no_environment_secrets
- ssm_document_secrets

Currently the detection engine is raising some false positives we need to work on to improve detection.

Some examples:
- `MYSQL_ALLOW_EMPTY_PASSWORD` is flagged as a secret when the value is just `yes` or `no`.
- `detect-secrets` TelegramBotToken plugin is flagging some strings to be a secret when it is not.

### Expected behavior

Prowler should not raise false positives regarding secrets detection.

- We need to investigate more about adding/removing plugins.
- Adjust the `base64-limit` and the `hex-limit`

### Actual Result with Screenshots or Logs

N/A

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

N/A

### OS used

N/A

### Prowler version

4.3.5

### Pip version

24.0

**Comment by jchrisfarris** [comment]
Here is another example of a false positive 
`Potential secret found in Lambda function guardduty-to-splunk-lambda variables -> Secret Keyword in variable SECRET_REGION.`
I use envvar to tell my lambda what secrets manager to use and which region. This gets flagged because of the word "SECRET"

I'm glad you're thinking about this, I was about to turn off all the secrets checks due to the shear number of false positives.

**Comment by jchrisfarris** [comment]
Another example `cloudformation_stack_outputs_find_secrets` is flagging resources created by cloudformation with the random suffixes that Cloudformation likes to use.

**Comment by pedrooot** [comment]
Thanks for the info @jchrisfarris we are working to improve this, if you find anything else related with secrets report it here please! This way we will track it better.

**Comment by jfagoagas** [comment]
We also had https://github.com/prowler-cloud/prowler/issues/3905 still opened and not yet addressed, we will see if the work done for this issue is helpful there.

**Comment by jfagoagas** [comment]
This PR was created to improve the `TelegramBotToken` plugin since it was flagging some AWS ARNs https://github.com/Yelp/detect-secrets/pull/878

**Comment by jfagoagas** [comment]
Hey @jchrisfarris we will merge the above PR once CI passes. We've added a new configuration value to pass one or more regex to exclude secrets from being detected.

Could you please give a try and let us know if this works for you?
