### ISSUE TITLE
Incorrect Description in documentdb_cluster_deletion_protection.metadata.json for DocumentDB

### ISSUE THREAD

**Issue by baecheongho** [toniblyx/prowler#4906]
### Steps to Reproduce

1. Navigate to the documentdb_cluster_deletion_protection.metadata.json file in the Prowler repository: https://github.com/prowler-cloud/prowler/blob/master/prowler/providers/aws/services/documentdb/documentdb_cluster_deletion_protection/documentdb_cluster_deletion_protection.metadata.json

2.Review the description in line 11 of the file.
3.Notice the description states: "Check if Neptune Clusters has deletion protection enabled."

### Expected behavior

The description should accurately describe the check for DocumentDB clusters, not Neptune clusters. It should read:

"Check if DocumentDB Clusters has deletion protection enabled."

### Actual Result with Screenshots or Logs

Actual Description: "Check if Neptune Clusters has deletion protection enabled."
Corrected Description: "Check if DocumentDB Clusters has deletion protection enabled."

This appears to be a simple text entry error.
Upon checking, the check for Neptune clusters exists with the correct descriptions in both the latest master branch and the 4.3.5 release version (neptune_cluster_deletion_protection in 4.3.5 and neptune_cluster_deletion_protection_enabled in older versions).

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

My local workstation.

### OS used

1.Amazon linux and MacOS

### Prowler version

4.3.5(PYPL),4.4(git)

### Pip version

pip 24.2 

### Context

Additional context: This issue was identified by cross-referencing the metadata files for both DocumentDB and Neptune checks in the repository. The Neptune check descriptions are correct and do not need modifications.

**Comment by pedrooot** [comment]
Hi! @baecheongho 
Thanks for the report! I'll ping you once we fix this.

**Comment by pedrooot** [comment]
Here is the PR with the fix -> https://github.com/prowler-cloud/prowler/pull/4909
