### ISSUE TITLE
Prowler doesn't detect RDS Event Notification Subscriptions for all instances

### ISSUE THREAD

**Issue by GauntletWizard** [toniblyx/prowler#4927]
### Steps to Reproduce

I attempted a full scan of our AWS Environment, and I discovered a new result, "rds_instance_event_subscription_security_groups". This is a new result since last I checked. I created a new event subscription.

### Expected behavior

I expect that a RDS Event subscription for that includes all sources (sources unset) and that contains at least the "failure" and "configuration change" event types will be sufficient to pass this test.

### Actual Result with Screenshots or Logs

profile: None;2024-09-04 03:40:38.589752;533266994894;;;;;;prowler-aws-rds_instance_event_subscription_security_groups-533266994894-us-east-1-rds-event-sub;aws;rds_instance_event_subscription_security_groups;Check if RDS Security Group events are subscribed.;;FAIL;RDS security group event category of configuration change is not subscribed.;False;rds;;medium;AwsRdsEventSubscription;arn:aws:rds:us-east-1:533266994894:es:rds-event-sub;rds-event-sub;;;aws;us-east-1;Ensure that Amazon RDS event notification subscriptions are enabled for database security groups events.;Amazon RDS event subscriptions for database security groups are designed to provide incident notification of events that may affect the security, availability, and reliability of the RDS database instances associated with these security groups.;https://docs.aws.amazon.com/securityhub/latest/userguide/rds-controls.html#rds-22;To subscribe to RDS instance event notifications, see Subscribing to Amazon RDS event notification in the Amazon RDS User Guide.;https://docs.aws.amazon.com/securityhub/latest/userguide/rds-controls.html#rds-22;https://www.trendmicro.com/cloudoneconformity/knowledge-base/aws/RDS/rds-db-security-groups-events.html#;https://www.trendmicro.com/cloudoneconformity/knowledge-base/aws/RDS/rds-db-security-groups-events.html#;https://www.trendmicro.com/cloudoneconformity/knowledge-base/aws/RDS/rds-db-security-groups-events.html#;;;;;;;4.4.0

### How did you install Prowler?

Docker (docker pull toniblyx/prowler)

### Environment Resource

Docker container locally

### OS used

Linux (Docker)

### Prowler version

Prowler 4.4.0 (You are running the latest version, yay!)

### Pip version

pip 24.2 from /usr/local/lib/python3.12/site-packages/pip (python 3.12)

### Context

```
Terraform:
+resource "aws_db_event_subscription" "rds" {
+  name      = "rds-event-sub"
+  sns_topic = aws_sns_topic.alerts.arn
+
+  source_type = "db-security-group" # Unset is all
+  # source_ids  = [aws_db_instance.default.identifier]  # Unset is all
+
+  # Just the ones prowler cares about
+  event_categories = [
+    "configuration change",
+    "failure",
+  ]
+}
```

AWS Output:
```
{
    "EventSubscriptionsList": [
        {
            "CustomerAwsId": "533266994894",
            "CustSubscriptionId": "rds-event-sub",
            "SnsTopicArn": "arn:aws:sns:us-east-1:533266994894:bc-alerts-dev",
            "Status": "active",
            "SubscriptionCreationTime": "2024-08-29 22:54:42.894",
            "SourceType": "db-security-group",
            "EventCategoriesList": [
                "failure",
                "configuration change"
            ],
            "Enabled": true,
            "EventSubscriptionArn": "arn:aws:rds:us-east-1:533266994894:es:rds-event-sub"
        }
    ]
}
```

It is probably also worth noting that the "Security Groups" that are monitored here are "RDS security groups", distinct from VPC Security Groups. EC2-Classic was retired on August 15, 2022.

**Comment by vicferpoy** [comment]
Hello @GauntletWizard. We are going to take a closer look at this. Thanks for reporting it.

**Comment by danibarranqueroo** [comment]
Hello!

We are aware of the issue and I'm currently working on that fix in the master branch, but it hasn’t been released yet. I’ll be sure to let you know as soon as it's released so you can test it again and confirm whether the problem has been resolved.

**Comment by danibarranqueroo** [comment]
Hi again, @GauntletWizard! The issue has been resolved. The check now behaves as expected when "failure" and "configuration change" are selected, instead of all. You can test it on the master branch. However, I'll ping you when it's included in the new release.

Thanks for using Prowler and helping us improve! 🚀
