### ISSUE TITLE
Prowler gets stuck / fails when running Lambda check against account - awslambda_function_no_secrets_in_code

### ISSUE THREAD

**Issue by razhamma** [toniblyx/prowler#4947]
### Steps to Reproduce

**Running prolwer using following command:**
```
/usr/local/bin/prowler aws -R arn:$AWSPARTITION:iam::$ACCOUNTID:role/$IAM_CROSS_ACCOUNT_ROLE --compliance aws_well_architected_framework_security_pillar_aws aws_account_security_onboarding_aws aws_audit_manager_control_tower_guardrails_aws aws_foundational_security_best_practices_aws aws_foundational_technical_review_aws aws_well_architected_framework_reliability_pillar_aws cis_3.0_aws -M csv json-ocsf html -f $REGION_LIST ${FINDING_OUTPUT:-} -T 43200 --verbose | tee output/stdout-$ACCOUNTID.txt 1>/dev/null
```

### Expected behavior

A successful Prowler Scan.

### Actual Result with Screenshots or Logs

1- When run `tail -f stdout-<Account-Id>.txt` -> Last check to be seen on the file is `awslambda_function_no_secrets_in_code` with no resources logged.
2- Prowler process gets killed/stopped later on.

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

**One EC2 Instance of type r6i.2xlarge (4 vCPUs and 32GiB RAM)**

### OS used

**Operating System** - Amazon Linux 2023.5.20240819

### Prowler version

Prowler 4.3.5

### Pip version

pip 21.3.1 from /usr/lib/python3.9/site-packages/pip (python 3.9)

### Context

- Facing same issue as https://github.com/prowler-cloud/prowler/issues/4209  
- Prowler scan gets stuck on this check **awslambda_function_no_secrets_in_code** and later on **prowler** process gets stopped.

**Additional Information:**
- **Number of Lambda Functions in the account** = 2249
- **Prowler running on EC2 instance of type r6i.2xlarge(4 vCPUs and 32GiB RAM)**
- **Prowler command is as follow:**
    ```
    /usr/local/bin/prowler aws -R arn:$AWSPARTITION:iam::$ACCOUNTID:role/$IAM_CROSS_ACCOUNT_ROLE --compliance aws_well_architected_framework_security_pillar_aws aws_account_security_onboarding_aws aws_audit_manager_control_tower_guardrails_aws aws_foundational_security_best_practices_aws aws_foundational_technical_review_aws aws_well_architected_framework_reliability_pillar_aws cis_3.0_aws -M csv json-ocsf html -f $REGION_LIST ${FINDING_OUTPUT:-} -T 43200 --verbose | tee output/stdout-$ACCOUNTID.txt 1>/dev/null
    ```
 - **Execution Cycle:** 1 Account 3 Regions 
 
 **Troubleshooting:**
 - If supply following arguments, prowler errors out as un-identified arguments `DEBUG,INFO,WARNING,ERROR,CRITICAL`
    ```
    --log-level {DEBUG,INFO,WARNING,ERROR,CRITICAL} --log-file <file_name>.json
    ```
- Have tried supplying `retries-max-attempts 5` to rule out API throttling but no success.

**Comment by pedrooot** [comment]
Hey! @razhamma could you share the prowler execution adding the `--log-level ERROR`? Thanks!!

**Comment by jfagoagas** [comment]
Hello @razhamma, what is the number of AWS Lambda functions? Take into account that this check downloads the lambda code into memory to analyse it so it can take up time based on the number of lambdas and the size of their codebase.

**Comment by razhamma** [comment]
Hi @jfagoagas ,

Number of Lambdas is 2249.

Might take some time - Completely agree but process shouldn't get killed.

In my case, prowler process is getting killed upon execution of this check. No output reports gets generated either - not even after hours/days.

@pedrooot - I'm currently executing it with `--log-level ERROR` and will share the output.

- `top` result from current ongoing execution:

  ![Screenshot 2024-09-06 at 12 52 22](https://github.com/user-attachments/assets/82b36159-9bbd-4c58-80e2-9a0f6e521e7c)

- Current log from `stdout-<account-id>.txt` file - stuck at same:
![Screenshot 2024-09-06 at 12 52 51](https://github.com/user-attachments/assets/46ad10fa-639f-4135-8092-d884461ad56c)

**Comment by jfagoagas** [comment]
@razhamma could you get the Prowler process' exit code?

**Comment by razhamma** [comment]
Hi @pedrooot - there are only `AccessDenied` errors in the logs.

@jfagoagas prowler process exited with exit code 1.

Initiated scan for 2 accounts this time. 1 got succeeded and one failed. Second was stuck at following and prowler process got killed:

![Screenshot 2024-09-06 at 14 26 25](https://github.com/user-attachments/assets/b4ef36c7-65a5-45ae-86b0-fc31bf884ecc)

**Comment by js37** [comment]
Maybe related to #4209 but I was unable to figure out the problem.

**Comment by toniblyx** [comment]
I bet this is happening due to the large number of lambda functions and the way Prowler handles memory when pulling resources. In particular when using scan secrets on this check it gets a lot of memory and in our experience this check doesn't work well on large number of lambda functions. As a short term workaround, we recommend to disable that check adding the following option `--excluded-checks awslambda_function_no_secrets_in_code`. Additionally, we are working on an important performance improvement that will come to the next minor version (most likely) and we think that will make that check and others to work better and also improve how it handles RAM.

**Comment by razhamma** [comment]
I believe it is not just `awslambda_function_no_secrets_in_code` check. In my case prowler process got killed again upon performing `autoscaling_find_secrets_ec2_launch_configuration` check as well even though I excluded lambda one. Trying to execute prowler again by excluding both of these checks to see if I encounter an issue again.

Btw any reference on what checks follow same evaluation(in memory checks) pattern as of `awslambda_function_no_secrets_in_code` ?

**Comment by jfagoagas** [comment]
> I believe it is not just `awslambda_function_no_secrets_in_code` check. In my case prowler process got killed again upon performing `autoscaling_find_secrets_ec2_launch_configuration` check as well even though I excluded lambda one. Trying to execute prowler again by excluding both of these checks to see if I encounter an issue again.

That's why I was asking about the exit code, for me with the information you provided it does not seem as a memory issue because something killed by memory (Out Of Memory, OOM) gets a 137 exit code.

> Btw any reference on what checks follow same evaluation(in memory checks) pattern as of `awslambda_function_no_secrets_in_code` ?

The following are checks under the `secrets` category:
```
./prowler.py --category secrets --list-checks
                         _
 _ __  _ __ _____      _| | ___ _ __
| '_ \| '__/ _ \ \ /\ / / |/ _ \ '__|
| |_) | | | (_) \ V  V /| |  __/ |
| .__/|_|  \___/ \_/\_/ |_|\___|_|v4.4.0
|_| the handy multi-cloud security tool

Date: 2024-09-09 17:10:00

[autoscaling_find_secrets_ec2_launch_configuration] Find secrets in EC2 Auto Scaling Launch Configuration - autoscaling [critical]
[awslambda_function_no_secrets_in_code] Find secrets in Lambda functions code. - lambda [critical]
[awslambda_function_no_secrets_in_variables] Find secrets in Lambda functions variables. - lambda [critical]
[cloudformation_stack_outputs_find_secrets] Find secrets in CloudFormation outputs - cloudformation [critical]
[cloudwatch_log_group_no_secrets_in_logs] Check if secrets exists in CloudWatch logs. - cloudwatch [medium]
[ec2_instance_secrets_user_data] Find secrets in EC2 User Data. - ec2 [critical]
[ec2_launch_template_no_secrets] Find secrets in EC2 Launch Template - ec2 [critical]
[ecs_task_definitions_no_environment_secrets] Check if secrets exists in ECS task definitions environment variables - ecs [critical]
[ssm_document_secrets] Find secrets in SSM Documents. - ssm [critical]

There are 9 available checks.
```

Could you please exclude all these checks and let us know if the execution works as expected?

Regarding the logs, it is expected to have `Access Denied` from AWS APIs, with that we were looking for some other possible errors within Prowler's execution.

**Comment by jfagoagas** [comment]
Hi @razhamma we are closing this issue since we haven't received any response for more than a month. Please, feel free to reopen it if you are still noticing the same behaviour or if you can provide us with more information about it.

Thanks for using Prowler 🚀
