### ISSUE TITLE
Add new check `lambda_on_eol_runtime`

### ISSUE THREAD

**Issue by bmorrissirromb** [toniblyx/prowler#5002]
### New feature motivation

Lambdas that are deployed on runtimes that are EOL or scheduled to become EOL represent a continuity risk to the business. Prowler should surface these runtimes so that there are not unwelcome surprises when attempting to update a stack.

This issue is particularly acute when dealing with certain older CDK versions that create runtime-version-pinned custom Lambdas that are not simple to change in the code. 

### Solution Proposed

Add a check that looks for Lambdas that are deployed with a runtime that is EOL or will be EOL soon. There may need to be multiple checks here, with severities depending on where the runtime is in its lifecycle.

### Describe alternatives you've considered

Creating a custom Config rule to check for EOL versions.

### Additional context

This check would require dynamically pulling some information from https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html, since EOL data is dynamic and changes over time.

**Comment by MrCloudSec** [comment]
Hi @bmorrissirromb, thanks for reaching us out!

Prowler already has the check `awslambda_function_using_supported_runtimes` that covers the check that you mentioned.
We use the variable `obsolete_lambda_runtimes` to include all EOL runtimes, you can see this variable [here](https://github.com/prowler-cloud/prowler/blob/70a3736073e98742973b0c554a0e55e9728a352c/prowler/config/config.yaml#L80).

Let me know if this check works for you or if it needs any change!

**Comment by bmorrissirromb** [comment]
Proving once again that the fastest way to find an answer on the Internet is to post something incorrect!

Thank you for your help identifying this! I'm glad this exists already.
