### ISSUE TITLE
Request use of botocore.config for to handle API throttling when archiving findings in SecurityHub

### ISSUE THREAD

**Issue by mlmerchant** [toniblyx/prowler#5004]
### Steps to Reproduce

As a security engineer running prowler with the below command:

`prowler AWS --log-level ERROR -M csv html json-asff --ignore-exit-code-3 --security-hub --status FAIL --log-file /foobar/logs.txt --output-directory /foobar`

I expect prowler to archive the findings.

### Expected behavior

I expect prowler to archive the findings in securityhub that were no longer detected in the latest scan.

### Actual Result with Screenshots or Logs

2024-09-11 18:53:36,513 [File: security_hub.py:247]     [Module: security_hub]   ERROR: Client error - - [227]:An error occurred (TooManyRequestsException) when calling the GetFindings operation: Too Many Requests in region us-gov-west-1

Sending findings to AWS Security Hub, please wait...
<redacted positive-number>
Archiving previous findings in AWS Security Hub, please wait...
0 findings archived in AWS Security Hub!

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

Gitlab runner docker container.

### OS used

Ubuntu:latest

### Prowler version

4.3.5

### Pip version

24.0

### Context

Request that prowler make use of 'botocore.config' to handle backoff and retries with the SecurityHub API.'

I believe this change would need to occur at the following location:
https://github.com/prowler-cloud/prowler/blob/master/prowler/providers/aws/lib/security_hub/security_hub.py#L140-L142

```
from botocore.config import Config

# Custom configuration for retries and backoff
config = Config(
    retries={
        'max_attempts': 10,  # Max number of retry attempts
        'mode': 'adaptive'  # or 'standard' for standard exponential backoff
    }
)

# Initialize the client with custom config
enabled_regions[region] = self._session.client(
    "securityhub", region_name=region, config=config
)

```

**Comment by vicferpoy** [comment]
Hey @mlmerchant, thanks for reporting this. 

I've addressed your suggestion internally and we will take care of it as soon as we can. I will leave a note so the team can update with a message here when we fix it.

**Comment by MrCloudSec** [comment]
Hi @mlmerchant, have you tried using the flag `--aws-retries-max-attempts`? You have more information in our docs [here](https://docs.prowler.com/projects/prowler-open-source/en/latest/tutorials/aws/boto3-configuration/). Let us know if that works for you, thanks!

**Comment by MrCloudSec** [comment]
I will close this issue due to lack of activity, feel free to reopen it if you are still encountering this problem, thanks!
