### ISSUE TITLE
Report Status Extended not show in json or security hub

### ISSUE THREAD

**Issue by Norther85** [toniblyx/prowler#5034]
### Steps to Reproduce

prowler aws -z -b --checks ecs_task_definitions_no_environment_secrets -R arn:aws:iam::xxxx:role/infosec -M csv html json-asff

### Expected behavior

I dont see in security hub report.status_extended. The only place i see extended version of logs if i output it in html format. Not sure if it's a bug or i do something wrong, or need additional switch

### Actual Result with Screenshots or Logs

</html>
[ec2-user@ip-10-0-1-54 ~]$ cat output/prowler-output-xxxxxx-20240913152103.html  | grep line
                            <td>Potential secret found in variables of ECS task definition xxxxxwith revision 183 -&gt; Hex High Entropy String on line 18.</td>
                            <td>Potential secret found in variables of ECS task definition geo<wbr />xxxx<wbr />xxxx with revision 137 -&gt; Base64 High Entropy String on line 19, Base64 High Entropy String on line 19.</td>
                            <td>Potential secret found in variables of ECS task definition geo<wbr />xxxx<wbr />xxxxwith revision 494 -&gt; Slack Token on line 27.</td>
                            <td>arn:aws:ecs:ap-northeast-1:xxxxxx:task-definition/xxxxx:348</td>

HTML with report extended

json asff
    "Description": "Check if secrets exists in ECS task definitions environment variables. If a secret is detected, the line number shown in the finding matches with the environment variable \"Name\" attribute starting to count at the \"environment\" key from the ECS Task Definition in JSON format.",
    "Description": "Check if secrets exists in ECS task definitions environment variables. If a secret is detected, the line number shown in the finding matches with the environment variable \"Name\" attribute starting to count at the \"environment\" key from the ECS Task Definition in JSON format.",
    "Description": "Check if secrets exists in ECS task definitions environment variables. If a secret is detected, the line number shown in the finding matches with the environment variable \"Name\" attribute starting to count at the \"environment\" key from the ECS Task Definition in JSON format.",
    "Description": "Check if secrets exists in ECS task definitions environment variables. If a secret is detected, the line number shown in the finding matches with the environment variable \"Name\" attribute starting to count at the \"environment\" key from the ECS Task Definition in JSON format.",

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

ec2 instance

### OS used

amazon linux 2

### Prowler version

 Prowler 4.3.5 (You are running the latest version, yay!)

### Pip version

pip 21.3.1 from /usr/lib/python3.9/site-packages/pip (python 3.9)

**Comment by pedrooot** [comment]
Hey! @Norther85 Thanks for reaching out! 
I'll address this issue with the team and ping you with a solution.
