### ISSUE TITLE
Error in LightSail Service: Potential Miscall of is_resource_filtered Function

### ISSUE THREAD

**Issue by h4r5h1t** [toniblyx/prowler#5043]
### Steps to Reproduce

I've encountered an error in the LightSail service related to the is_resource_filtered function. The issue seems to stem from a potential miscall within the code block below:

```
if not self.audit_resources or is_resource_filtered(
    is_resource_filtered(arn, self.audit_resources)
):
    ports = []
```

The `is_resource_filtered` function appears to be called twice within the same conditional statement. This might lead to unexpected behavior or incorrect filtering results.

### Expected behavior

```
if not self.audit_resources or is_resource_filtered(arn, self.audit_resources):
    ports = []
```

### Actual Result with Screenshots or Logs

N/A

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

1. LightSail

### OS used

Windows

### Prowler version

v4.4.0

### Pip version

pip 22.0.2

**Comment by jfagoagas** [comment]
Hello @h4r5h1t this is a great catch, thank you very much for reporting and opening the PR to fix it 🚀
