### ISSUE TITLE
False Negative "severity downgrade" in check ec2_instance_port_ssh_exposed_to_internet

### ISSUE THREAD

**Issue by jmanduca-psfy** [toniblyx/prowler#5046]
### Steps to Reproduce

1. `prowler aws -c ec2_instance_port_ssh_exposed_to_internet`
2. AWS
3. single/multi account
4. Instances that have an exposed SSH with a public IP in a Public Subnet are being downgraded to High, and marked as being in a Private Subnet

### Expected behavior

EC2 instances in public subnets with the exposed port and public IP should be reported with Severity=Critical

### Actual Result with Screenshots or Logs

EC2 instances in public subnets with the exposed port and public IP are reported with Severity=High, with detail stating "it is placed in a private subnet"

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

7. Workstation

### OS used

5. Ubuntu

### Prowler version

v4.3.5

### Pip version

pip 22.0.2

### Context

The subnet these instances are in has a route table with 0.0.0.0/0 to an IGW (not a NAT gateway). There seems to be a bug in how subnets are determined to be private. I have attached subnet details and route table where these instances are in.
![image](https://github.com/user-attachments/assets/58144508-8d43-48fd-a93f-a5872b3263ab)
![image](https://github.com/user-attachments/assets/7d560142-d339-4b68-9f9a-b0aa32ac22b3)
![image](https://github.com/user-attachments/assets/ade9a5d2-ba1c-4947-9db4-ea15c10dd05e)

**Comment by MrCloudSec** [comment]
Hi @jmanduca-psfy, thanks for reaching us out!

Please, can you execute `--log-level ERROR` in case Prowler is not getting the enough information to determine if the subnet is public?

This is the current logic:

  ```
  if (
        "GatewayId" in route
        and "igw" in route["GatewayId"]
        and route.get("DestinationCidrBlock", "")
        == "0.0.0.0/0"
    ):
```

**Comment by jmanduca-psfy** [comment]
Hey @sergargar , just ran `prowler aws -c ec2_instance_port_ssh_exposed_to_internet --log-level ERROR`. Validated that the subnets are still incorrectly flagged as private.

Here is the full output (don't see any errors):

```
 _ __  _ __ _____      _| | ___ _ __
| '_ \| '__/ _ \ \ /\ / / |/ _ \ '__|
| |_) | | | (_) \ V  V /| |  __/ |
| .__/|_|  \___/ \_/\_/ |_|\___|_|v4.3.5
|_| the handy multi-cloud security tool

Date: 2024-09-16 14:44:05

-> Using the AWS credentials below:
  · AWS-CLI Profile: default
  · AWS Regions:
  · AWS Account: 123412341234
  · User Id: AAAA:jmanduca@domain.com
  · Caller Identity ARN: arn:aws:sts::123412341234:assumed-role/AWSReservedSSO_FullAdminAccess_abc123/jmanduca@domain.com

-> Using the following configuration:
  · Config File: /home/jmanduca/.local/lib/python3.10/site-packages/prowler/config/config.yaml
  · Mutelist File: /home/jmanduca/.local/lib/python3.10/site-packages/prowler/config/aws_mutelist.yaml
  · Scanning unused services and resources: False

Executing 1 check, please wait...
-> Scan completed! |▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉| 1/1 [100%] in 1:01.0

Overview Results:
╭───────────────────┬─────────────────────┬────────────────╮
│ 6.54% (10) Failed │ 93.46% (143) Passed │ 0.0% (0) Muted │
╰───────────────────┴─────────────────────┴────────────────╯

Account 123412341234 Scan Results (severity columns are for fails only):
╭────────────┬───────────┬───────────┬────────────┬────────┬──────────┬───────┬─────────╮
│ Provider   │ Service   │ Status    │   Critical │   High │   Medium │   Low │   Muted │
├────────────┼───────────┼───────────┼────────────┼────────┼──────────┼───────┼─────────┤
│ aws        │ ec2       │ FAIL (10) │          0 │      3 │        7 │     0 │       0 │
╰────────────┴───────────┴───────────┴────────────┴────────┴──────────┴───────┴─────────╯
* You only see here those services that contains resources.

Detailed results are in:
 - JSON-OCSF: /home/jmanduca/output/prowler-output-123412341234-20240916144405.ocsf.json
 - CSV: /home/jmanduca/output/prowler-output-123412341234-20240916144405.csv
 - HTML: /home/jmanduca/output/prowler-output-123412341234-20240916144405.html
```

**Comment by MrCloudSec** [comment]
Thanks for the information @jmanduca-psfy .

Could you execute `aws ec2 describe-route-tables` and insert here the JSON including the information of the subnet you showed us in the screenshot? (Make sure you don't include any sensitive information).

**Comment by jmanduca-psfy** [comment]
Hey @sergargar 

Please see the output below. The route table for the subnet is not **explicitly** associated, just associated by default.

```
jmanduca@______:~$ aws ec2 describe-route-tables --filters Name=route-table-id,Values=rtb-0_____
{
    "RouteTables": [
        {
            "Associations": [
                {
                    "Main": true,
                    "RouteTableAssociationId": "rtbassoc-_______",
                    "RouteTableId": "rtb-0_____",
                    "AssociationState": {
                        "State": "associated"
                    }
                }
            ],
            "PropagatingVgws": [],
            "RouteTableId": "rtb-0_____",
            "Routes": [
                {
                    "DestinationCidrBlock": "172.31.0.0/16",
                    "GatewayId": "local",
                    "Origin": "CreateRouteTable",
                    "State": "active"
                },
                {
                    "DestinationCidrBlock": "0.0.0.0/0",
                    "GatewayId": "igw-c______",
                    "Origin": "CreateRoute",
                    "State": "active"
                }
            ],
            "Tags": [],
            "VpcId": "vpc-2______",
            "OwnerId": "123412341234"
        }
    ]
}

jmanduca@_______:~$ aws ec2 describe-route-tables --filters Name=association.subnet-id,Values=subnet-3______
{
    "RouteTables": []
}
```

**Comment by MrCloudSec** [comment]
Hi @jmanduca-psfy , I think I found the issue: we were only parsing thee first route table.

I have made the fix in the branch `5046-false-negative-severity-downgrade-in-check-ec2_instance_port_ssh_exposed_to_internet`, can you try it again there and let me know if it works? Thanks!

**Comment by jmanduca-psfy** [comment]
@sergargar Just tested it out, looks to be working. Thank you!
