### ISSUE TITLE
EC2 Launch templates doesn't support resource tags

### ISSUE THREAD

**Issue by ghost** [toniblyx/prowler#5060]
### New feature motivation

ec2_launch_template_no_secrets check doesn't support a resource tag to mute specific findings.

current state:
```
 "resources": [
        {
            "cloud_partition": "aws",
            "region": "us-east-1",
            "data": {
                "details": ""
            },
            "group": {
                "name": "ec2"
            },
            "labels": [],
            "name": "lt-0744d2341c2118f70",
            "type": "AwsEc2LaunchTemplate",
            "uid": "arn:aws:ec2:us-east-1:xxxxxxxxxxxx:launch-template/lt-0744d2341c2118f70"
        }
    ],
 ```

### Solution Proposed

Add resource tags to report labels to be used in the mute mechanism.

```
 "resources": [
        {
            "cloud_partition": "aws",
            "region": "us-east-1",
            "data": {
                "details": ""
            },
            "group": {
                "name": "ec2"
            },
            "labels": [
                "Name:test-resource",
                
            ],
            "name": "lt-0744d2341c2118f70",
            "type": "AwsEc2LaunchTemplate",
            "uid": "arn:aws:ec2:us-east-1:xxxxxxxxxx:launch-template/lt-0744d2341c2118f70"
        }
    ],
```

### Describe alternatives you've considered

Without resource tags, the only way to mute specific resources is only wildcard or the list of resource ARNs, which is uncomfortable.

**Comment by MrCloudSec** [comment]
Hi @ivan-morhun, thanks for reaching us out!

I understand that you are having problems with the resource tags, however, we are in progress on adding the missing tags in all AWS resources.

We will let you know when we finish it.

**Comment by ghost** [comment]
Hi @sergargar!

Thanks for your reply.
