### ISSUE TITLE
Add new check `opensearch_domain_fine_grained_access_control_enabled`

### ISSUE THREAD

**Issue by puchy22** [toniblyx/prowler#5094]
### New feature motivation

Implement a check to ensure that Amazon OpenSearch domains have fine-grained access control enabled. This check will help enhance security by verifying that access to OpenSearch domains is controlled at a granular level, allowing for more precise permissions management and reducing the risk of unauthorised access.

References:
- https://docs.aws.amazon.com/securityhub/latest/userguide/opensearch-controls.html#opensearch-7
- https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/opensearch/client/describe_domains.html

### Solution Proposed

Create a new check to ensure that `AdvancedSecurityOptions` is enabled. Things to add:

- Add to the current `OpenSearchDomain` model the necessary attributes in `opensearch_service`.
- Add a check with logic to verify that `AdvancedSecurityOptions` is enabled. [Ref](https://docs.prowler.com/projects/prowler-open-source/en/latest/developer-guide/checks/)
- Add unit tests to ensure the check is working as expected. Cases recommended: no domains, domain with `AdvancedSecurityOptions` enabled and one disabled. [Ref](https://docs.prowler.com/projects/prowler-open-source/en/latest/developer-guide/unit-testing/)

### Describe alternatives you've considered

No alternative.

**Comment by abant07** [comment]
Hey @puchy22 

Would I be able to work on this one?

**Comment by puchy22** [comment]
@abant07 Sure, I assign you the issue. Thanks for your help 💚 🚀
