### ISSUE TITLE
IAM check errors for Chinese Partition

### ISSUE THREAD

**Issue by daftkid** [toniblyx/prowler#5171]
### Steps to Reproduce

1. python3 prowler aws --log-level ERROR

### Expected behavior

Prowler is able to list entities for policy w/o errors within the Chinese partition

### Actual Result with Screenshots or Logs

2024-09-24 16:10:22,858 [File: iam_service.py:659]      [Module: iam_service]    ERROR: cn-northwest-1 -- ClientError[648]: An error occurred (ValidationError) when calling the ListEntitiesForPolicy operation: Invalid ARN partition

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

workstation

### OS used

MacOS

### Prowler version

Prowler 3.16.17

### Pip version

pip 23.1.2

### Context

Trying to run the scan in AWS Chinese partition.

**Comment by MrCloudSec** [comment]
Hi @daftkid, thanks for reaching out!

I understand that you are having problems with the Chinese partition, I will come back with a solution and let you know to try it 😄

**Comment by MrCloudSec** [comment]
@daftkid can you try the above PR, please?

**Comment by daftkid** [comment]
> @daftkid can you try the above PR, please?

Hello @sergargar I confirm I cannot see the issue anymore on the PR branch, thanks.

Will this fix be backported to 3.16.x ?

**Comment by MrCloudSec** [comment]
Yes, we will backport it, thanks!
