### ISSUE TITLE
Error using --resource-tags option after upgrading Prowler to 4.3.7

### ISSUE THREAD

**Issue by ShivaSDP** [toniblyx/prowler#5242]
### Steps to Reproduce

❯❯ prowler.exe --version
Prowler 4.3.7

❯❯ prowler aws --region ap-south-1 --resource-tags Environment=dev Project=DEV

-> Using the AWS credentials below:
.

 **There are no findings in Account xxxxxxxxxx**

### Expected behavior

❯❯ prowler --version
Prowler **4.3.5** (latest is 4.3.7, upgrade for the latest features)

❯❯ prowler aws --region ap-south-1 --resource-tags Environment=dev Project=DEV

-> Using the AWS credentials below:
.

-> Using the following configuration:
.

Executing 383 checks, please wait...

-> Scan completed! |▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉| 383/383 [100%] in 9:42.1 

### Actual Result with Screenshots or Logs

❯❯ prowler aws --region ap-south-1 --resource-tags Environment=dev Project=DEV

-> Using the AWS credentials below:
.

 **There are no findings in Account xxxxxxxxxx**

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

1. EC2 Instance (Ubuntu)
2. Windows Laptop

### OS used

1. Ubuntu 
2. Windows 11

### Prowler version

4.3.7

### Pip version

23.3.1

**Comment by jfagoagas** [comment]
Hello @shivasdp, we are going to review it and we'll back to you once we have an update on it.

Thanks for using Prowler 🚀

**Comment by MrCloudSec** [comment]
Hi @shivasdp, I could not reproduce your error.

Can you execute it again with `--log-level ERROR`, please? Thanks!

**Comment by ShivaSDP** [comment]
I have tested it with below versions -
 4.3.5 (working)
 4.3.6 (not working)
 4.3.7 (not working)
 4.4.0 (working)
 
 Below are the screenshots
 
 4.3.6
 
<img width="1012" alt="image" src="https://github.com/user-attachments/assets/29c9f4d9-021e-44f7-bde3-deafc527b6a8">


4.3.7

<img width="1031" alt="image" src="https://github.com/user-attachments/assets/a701d268-21ef-437c-b791-b3cd51dfd941">

latest, 4.4.0
<img width="923" alt="image" src="https://github.com/user-attachments/assets/90d17767-66d4-4f5c-96d0-7619225ce9b1">

**Comment by ShivaSDP** [comment]
Issue can be closed as it is working fine with the latest version (4.4.0).

**Comment by MrCloudSec** [comment]
Perfect! Glad that it works now 😄
