### ISSUE TITLE
Handle safe exptions list for IP's in `awslambda_function_no_secrets_in_code` check

### ISSUE THREAD

**Issue by kisst** [toniblyx/prowler#5282]
### New feature motivation

Currently non-secret IPv4 addresses trigger the awslambda_function_no_secrets_in_code check.

### Solution Proposed

Add to the default `secrets_ignore_patterns`  a list of safe exceptions which do not raise the alarm, list should contain at least localhost ( 127.0.0.1 ) the metadata API  (169.254.169.254) .

### Describe alternatives you've considered

1) Turn off the check
2) Ignore failing checks
3) Introduce resiliency weakness by using DNS instead of IP
4) Edit the `secrets_ignore_patterns`  per installation

**Comment by MrCloudSec** [comment]
Hi @kisst, have you tried of changing the configurable variable `secrets_ignore_patterns` in the `config.yaml` [here](https://github.com/prowler-cloud/prowler/blob/e99c58405ce08010fd0f3c85c4acc11c5f16bc78/prowler/config/config.yaml#L340)?

**Comment by kisst** [comment]
I listed under the "describe alternatives you've considered" section as number 4) Edit the secrets_ignore_patterns per installation , currently that's the workaround I am using however I believe that in no conditions the metadata APIs IP or localhost can be considered as a secret hence it would make sense to include those on the safe strings default and with that remove a large set of false positives and have an even better and more valuable out of the box experience .

**Comment by MrCloudSec** [comment]
Hi @kisst, you have above the PR solving this issue. However, I was not able to reproduce a FAIL with the localhost IP.
