### ISSUE TITLE
Add flag to disable color output

### ISSUE THREAD

**Issue by ghost** [toniblyx/prowler#5294]
### New feature motivation

When running prowler in some automated environments (e.g. Jenkins) it's too hard to read the tool output because of ANSI escape symbols. If there were a flag, e.g. `--no-color` to disable this behavior it would be great!
![image](https://github.com/user-attachments/assets/ea09da65-f7b9-46fc-bc46-a7067fb13c19)

### Solution Proposed

Add a flag to disable the color output, e.g. `--no-color` 

### Describe alternatives you've considered

There is a Jenkins AnsiColor plugin https://plugins.jenkins.io/ansicolor/

**Comment by MrCloudSec** [comment]
Hi @ivan-morhun, I will discuss it internally with the team and include it in our roadmap since we are working on a new CLI.
I'll let you know whenever we get a solution for this!
