### ISSUE TITLE
Docker image no longer runs contrib/aws/multi-account-securityhub/run-prowler-securityhub.sh in ECS

### ISSUE THREAD

**Issue by jbro-tp** [toniblyx/prowler#5303]
### Steps to Reproduce

1.  Deploy the docker image using this Dockerfile https://github.com/prowler-cloud/prowler/blob/master/contrib/aws/multi-account-securityhub/Dockerfile
2. Run the ECS Task.

### Expected behavior

Expected behaviour is this script will run successfully that is copied over into the docker image https://github.com/prowler-cloud/prowler/blob/master/contrib/aws/multi-account-securityhub/run-prowler-securityhub.sh

### Actual Result with Screenshots or Logs

![Screenshot 2024-10-04 at 11 52 27](https://github.com/user-attachments/assets/aed34b8d-4a96-40d1-bf7e-855d1b3caeea)

### How did you install Prowler?

Docker (docker pull toniblyx/prowler)

### Environment Resource

1. ECS

### OS used

 amazonlinux:2022

### Prowler version

4.4.0

### Pip version

N/A

**Comment by pedrooot** [comment]
Hey Jonathan! We will review your issue with the team and get back to you with a solution, thanks!

**Comment by jbro-tp** [comment]
Thanks Pedro! I can confirm it does work locally.  I can't understand why I see a different behaviour in ECS - I'll keep troubleshooting from my side.

**Comment by pedrooot** [comment]
Great! Thanks

**Comment by jbro-tp** [comment]
Hey @pedrooot I've fixed it, we have on our side some variation of how it works here.  I will close this but I will raise a PR with some changes too :)
