### ISSUE TITLE
Prowler threat detection scan errors with pulling CloudTrail events.

### ISSUE THREAD

**Issue by trzash-6891** [toniblyx/prowler#5341]
### Steps to Reproduce

**Running prowler threat detection scan with the following command**
`prowler aws -f us-east-1 --categories threat-detection -M html --log-level ERROR`

### Expected behavior

Successful scan with an html file.

### Actual Result with Screenshots or Logs

![Screenshot 2024-10-08 at 5 30 56 PM](https://github.com/user-attachments/assets/03c98a99-3bbd-4ab4-841e-a30bbf0c636f)

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

Workstation

### OS used

MacOS

### Prowler version

Prowler 4.4.0

### Pip version

pip 24.2 

### Context

When running the check, I am getting these undescriptive python errors with identifying CloudTrail events with an IAM identity / arn.

**Comment by MrCloudSec** [comment]
Hi @trzash-6891!
That issue was solved in https://github.com/prowler-cloud/prowler/pull/5276 and we will do a release soon with the fixes 😄

**Comment by MrCloudSec** [comment]
@trzash-6891 you can now try it in version 4.4.1!

**Comment by trzash-6891** [comment]
@sergargar Thanks for the update / investigation. Appreciate it.
