### ISSUE TITLE
Potential false positive of new rule AWS organizations_opt_out_ai_services_policy

### ISSUE THREAD

**Issue by dlouzan** [toniblyx/prowler#5394]
### Steps to Reproduce

When running 4.4.0 on one of our AWS accounts, belonging to our parent company AWS organization, we got a failure on the new test `organizations_opt_out_ai_services_policy`, indicating that our organization did not correctly opt-out of sharing data with AWS AI offerings.

I'm trying to find out whether this is a false positive or an actual issue that needs to be reported to our organization (it seems to be the former).

I verified that my user has no rights to access the policies:

```sh
$ aws organizations list-policies --filter SERVICE_CONTROL_POLICY

An error occurred (AccessDeniedException) when calling the ListPolicies operation: You don't have permissions to access this resource.
```

And the prowler code seems to indicate that failure to get the policies will trigger a violation:

<https://github.com/prowler-cloud/prowler/blob/03a26ec507b2b93b6787be4b0516950d6ab3c092/prowler/providers/aws/services/organizations/organizations_opt_out_ai_services_policy/organizations_opt_out_ai_services_policy.py#L22>

Should this be marked by prowler as failed / manual?

### Expected behavior

Is this an actual failure or a false positive?

### Actual Result with Screenshots or Logs

<img width="1426" alt="image" src="https://github.com/user-attachments/assets/c3918f4c-bc52-4e48-bb4b-34aa4195e6c6">

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

Workstation

### OS used

macOS Sonoma 14.7

### Prowler version

Prowler 4.4.0

### Pip version

pip 23.2.1

**Comment by pedrooot** [comment]
Hey @dlouzan thanks for the report! I'll review this issue with the team and we will ping you with a solution.

**Comment by MrCloudSec** [comment]
Thanks for letting us know this issue @dlouzan! The above PR solves it.
