### ISSUE TITLE
Exclude the Aurora cluster reader and writer for the check "Check if RDS instances are protected by a backup plan"

### ISSUE THREAD

**Issue by serhii-ciq** [toniblyx/prowler#5434]
### Steps to Reproduce

This check `Check if RDS instances are protected by a backup plan` should exclude readers and writers and controls only backup plan for the Aurora cluster

Just run the prowler with check `rds_instance_protected_by_backup_plan`

### Expected behavior

No findings for Aurora cluster reader and writer

### Actual Result with Screenshots or Logs

![image](https://github.com/user-attachments/assets/a364d3e7-5e17-41b2-a75a-0ef34222cbff)

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

Workstation, EC2 instance

### OS used

Windows, Amazon Linux

### Prowler version

Prowler 4.4.0 (latest is 4.4.1, upgrade for the latest features)

### Pip version

pip 24.2 (python 3.12)

**Comment by MrCloudSec** [comment]
Hi @serhii-ciq, thanks for letting us know this issue. What types of RDS instance are you expecting Prowler to flag?
