### ISSUE TITLE
"public" definition of resources

### ISSUE THREAD

**Issue by liwadman** [toniblyx/prowler#5454]
### Steps to Reproduce

looking at your code based on some customer questions we've received.

### Expected behavior

Hello. 

re this code here:

https://github.com/prowler-cloud/prowler/blob/778edd5fec7d0cf8ebae6d1471d54fbb18db81ea/prowler/providers/aws/services/iam/lib/policy.py#L112

While this is useful check, it looks to me like you're not checking for aws:SourceArn, aws:SourceOrgId, or aws:SourceOrgPaths which can be used as an alternative to aws:SourceAccount to help protect against the cross-service confused deputy issue.

Also this finding is really for "lack of cross-service confused deputy condition key present" - this does not mean the resource is public. I think that's confusing because that's not how AWS talks about public resources, and implies that there is for sure a way an unauthorized party to access your resource which is usually not the case. 

I can appreciate that nuance may be hard to message, but I think something that's probably easy to do is to identify this as a cross service confused deputy finding, and provide the relevant documentation to the prowler user:

https://docs.aws.amazon.com/IAM/latest/UserGuide/confused-deputy.html#cross-service-confused-deputy-prevention

### Actual Result with Screenshots or Logs

N/a

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

N/A

### OS used

N/A

### Prowler version

N/A

### Pip version

N/A

### Context

AWS receiving some customer outreach around what does this finding mean

**Comment by MrCloudSec** [comment]
Hi @liwadman, I can see that in the code we have the conditions you are asking for https://github.com/prowler-cloud/prowler/blob/778edd5fec7d0cf8ebae6d1471d54fbb18db81ea/prowler/providers/aws/services/iam/lib/policy.py#L254.

Can you give us more information about the check or the use case that is not working as expected?

Thanks!

**Comment by liwadman** [comment]
Gotcha, I can see I was wrong about the test cases.

The question myself and a few other folks who work at AWS have receive is "what does this finding of public mean, and I am I danger?" (paraphrasing)

The finding category for aws:SourceAccount/Arn/OrgId/OrgPaths not being present in an allow with an AWS SP isn't "public". I think a reasonable understanding of the word public is that "Anyone can access this", maybe also from anywhere. That doesn't accurately represent what's on the go here, but I totally agree it's something worth elevating to customers.

I think this should be flagged as a a finding type that's like "resource missing the condition keys for cross-service confused deputy". This does not mean it is possible to confuse a deputy, or there is 'public access' to a resource. I think classifying the finding as such would help a customer understand their potential exposure, and what are the corrective actions.

**Comment by MrCloudSec** [comment]
thanks for the information @liwadman, but which Prowler check are you referring to?

**Comment by jmanduca-psfy** [comment]
It is not one specific check, but any check that uses the `is_policy_public` function to check for public access. Some examples I am dealing with are `ecr_repositories_not_publicly_accessible` , `s3_bucket_public_access` and `s3_bucket_policy_public_write_access`

**Comment by liwadman** [comment]
jamnduca-psfy is correct. It's any check that uses that. What I am saying is that an allow statement in an a resource policy for a service principal without the confused deputy condition keys does not make that resource public, or even potentially affected by a confused deputy issue. It means there is missing confused deputy condition keys present - which generally, is something a customer should take action on.

It's just inaccurate and confusing to classify it as public.

**Comment by MrCloudSec** [comment]
Hi @liwadman @jmanduca-psfy, I understand the problem you are mentioning now, we will review the function and get back to you soon!

**Comment by MrCloudSec** [comment]
Hi @liwadman @jmanduca-psfy, can you try the above PR and give us your thoughts? Thanks.

**Comment by jmanduca-psfy** [comment]
Hey @sergargar , I was able to test it out and the check results make sense, more accurate with the cross account designation vs. Public. Thank you!
