### ISSUE TITLE
Prowler 4.4.1 missing from pypi

### ISSUE THREAD

**Issue by dlouzan** [toniblyx/prowler#5461]
### Steps to Reproduce

Available on docker and github:
- <https://github.com/prowler-cloud/prowler/releases/tag/4.4.1>
- <https://hub.docker.com/layers/toniblyx/prowler/4.4.1/images/sha256-3b89d53281fcfa23c4e620f3bc6a981a62f53e2bef5b2855c410c02bdd7ab542?context=explore>

Missing on pypi: <https://pypi.org/project/prowler/#history>

### Expected behavior

4.4.1 available on pypi

### Actual Result with Screenshots or Logs

<img width="1534" alt="image" src="https://github.com/user-attachments/assets/db1bc281-34f9-409f-9fcf-6adec40469fb">

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

Workstation

### OS used

macOS Sonoma 14.7

### Prowler version

4.4.0

### Pip version

23.2.1

**Comment by MrCloudSec** [comment]
Hi @dlouzan, thanks for letting us know the issue.
We are aware of this problem now and we will let you know when we solve it.

**Comment by MrCloudSec** [comment]
@dlouzan, the version 4.4.1 was just uploaded to PyPi, thanks again for opening the issue!
