### ISSUE TITLE
Add "--organization-id" argument for GCP assessments

### ISSUE THREAD

**Issue by ar3diu** [toniblyx/prowler#5478]
### New feature motivation

For GCP, the easiest way to run prowler is in the Cloud Shell where you are already authenticated to Google Cloud and prowler will use those creds. But if that account has access to multiple organizations then prowler, by default, will scan all projects from all those organizations given no `--project-id` filter. But what if those organizations contain hundreds/thousands of projects and you want  to run prowler just for one of them? Then you will end up with a super long command line containing hundreds/thousands of project ids.

### Solution Proposed

It would be useful to have an argument like `--organization-id` that prowler can use to then list & scan all projects in the given organization id (and accessible by the credentials used).

### Describe alternatives you've considered

Getting a list of project ids for an organization with the following command and pass that list to prowler.
```
gcloud asset search-all-resources --asset-types="cloudresourcemanager.googleapis.com/Project" --scope=organizations/123456789 --format=json | jq -r '.[].additionalAttributes.projectId'
```

or with python:
```
from google.cloud.asset_v1 import AssetServiceClient, SearchAllResourcesRequest

def get_projects_under_org(org_id):
    client = AssetServiceClient()
    request = SearchAllResourcesRequest(
        scope = org_id, 
        asset_types = ["cloudresourcemanager.googleapis.com/Project"],
        read_mask = "additionalAttributes"
    )
    response = client.search_all_resources(request=request)
    projects = []
    for item in response:
        projects.append(item.additional_attributes.get("projectId"))
    return projects
```

**Comment by MrCloudSec** [comment]
Hi @ar3diu, this is a great idea, thanks! However, Prowler now is retrieving all the projects that are accesible through the given credentials [here](https://github.com/prowler-cloud/prowler/blob/master/prowler/providers/gcp/gcp_provider.py#L439). Would not that be the same as the approach you are mentioning?

**Comment by ar3diu** [comment]
@sergargar - given my scenario _(cloud shell, credentials have access to multiple orgs)_, if you wanted to run prowler only on projects in an organization, today you'd have to manually paste the list of project IDs from that organization. Otherwise, prowler will also consider the projects you have access to from other organizations.

**Comment by MrCloudSec** [comment]
Okay @ar3diu, I see what you mean and it makes sense!
We will create this flag, meanwhile, you can use the flag `--list-project-ids` to copy the projects you are interested in.

**Comment by ar3diu** [comment]
Again, hard to know which projects belong to which organization when `--list-project-ids` returns hundreds/thousands of ids. I used the code from my initial message to get project ids for a specific org id and then feed that list to prowler.

**Comment by MrCloudSec** [comment]
Hi @ar3diu, I have included the new flag in https://github.com/prowler-cloud/prowler/pull/5524, let me know if it works for you 😄

**Comment by ar3diu** [comment]
@sergargar - It only gets projects that are located directly under an organization id. But projects can also be located in folders which then can have sub-folders and so on. So you need a way to recursively check in all folders and subfolders for projects. I tried this before but I couldn't find a solution and that's why in my python code above I chose to use the Cloud Inventory.

**Comment by MrCloudSec** [comment]
Okay, it makes sense now! Thanks for the info, I will change it including this.

**Comment by MrCloudSec** [comment]
@ar3diu, I have made the changes to recursively check in all folders and subfolders within the organization, let me know if it supports your use case!

**Comment by ar3diu** [comment]
So, for some reason I get an authentication error when using `--organization-id`:
```
2024-10-28 07:39:41,695 [File: gcp_provider.py:103]     [Module: gcp_provider]   CRITICAL: No Project IDs can be accessed via Google Credentials.

2024-10-28 07:39:41,695 [File: provider.py:231]         [Module: provider]       CRITICAL: GCPNoAccesibleProjectsError[204]: GCPNoAccesibleProjectsError[3002]: No Project IDs can be accessed via Google Credentials.
```
I run prowler in Cloudshell and everything works well when not using this specific arg _(e.g. can access/scan projects in the same organization id)_.
I also tried to re-authenticate but without success.

**Comment by MrCloudSec** [comment]
@ar3diu make sure that the used credentials have the role Cloud Asset Viewer (`roles/cloudasset.viewer`) or Cloud Asset Owner (`roles/cloudasset.owner`) on the organization level. Are you using the same credentials in Prowler and in Cloudshell?
I will add that information in the docs. Let me know if it works!

**Comment by ar3diu** [comment]
Yes, that seems to have been the problem. 
It seems to work ok now. Thanks for implementing this so quickly :raised_hands:
