### ISSUE TITLE
Error when sending findings to SecurityHub: data.Resources[0].Id should NOT be shorter than 1 characters

### ISSUE THREAD

**Issue by jbro-tp** [toniblyx/prowler#5498]
### Steps to Reproduce

 Run the following command prowler aws --log-level ERROR -R arn:"${ACCOUNT_ROLE_ARN}" --security-hub --send-sh-only-fails -f "${REGION}" > /dev/null 2>&1 &  # Suppress output and run in the background

This command is run as part of running Prowler as an ECS task https://github.com/prowler-cloud/prowler/tree/master/contrib/aws/multi-account-securityhub

### Expected behavior

Findings should be sent to AWS Security Hub.

### Actual Result with Screenshots or Logs

<img width="1420" alt="Screenshot 2024-10-22 at 06 52 36" src="https://github.com/user-attachments/assets/132bf3b9-d881-4676-8c4b-fd485744df1f">

### How did you install Prowler?

Docker (docker pull toniblyx/prowler)

### Environment Resource

ECS Fargate

### OS used

Running on Docker image (ECR).

### Prowler version

4.5.0

### Pip version

N/A

**Comment by MrCloudSec** [comment]
Hi @jonathanbro, thanks for letting us now this issue. I will try to reproduce it and come back here with a solution.

**Comment by jfagoagas** [comment]
Hello @jonathanbro we've fixed the issue in the above PR, which is now merged. Thank you!

**Comment by jbro-tp** [comment]
Great news thank you @jfagoagas
