### ISSUE TITLE
False positives for cloudfront_distributions_s3_origin_non_existent_bucket because not all options are considered

### ISSUE THREAD

**Issue by pr3l14t0r** [toniblyx/prowler#5532]
### Steps to Reproduce

Ahoy! I am running prowler in version `4.4.0` and have encountered a lot of false positives for the check `cloudfront_distributions_s3_origin_non_existent_bucket`. 

According to the checks' [code](https://github.com/prowler-cloud/prowler/blob/84ce7a8b52672260b5f7efeb6d4e76a5b61b84a4/prowler/providers/aws/services/cloudfront/cloudfront_distributions_s3_origin_non_existent_bucket/cloudfront_distributions_s3_origin_non_existent_bucket.py#L8), the `origin` is received by a split on `domain_name` and it is just assumed that it has to be an S3 bucket. 

```python
            for origin in distribution.origins:
                bucket_name = origin.domain_name.split(".")[0]
                if not s3_client._head_bucket(bucket_name):
                    non_existent_buckets.append(bucket_name)
```

This is not correct. An origin for a CloudFront distribution resource could also be an ELB, ApiGatetway and even more. The various options of origins are listed in this documentation:
[Use various origins with CloudFront distributions](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/DownloadDistS3AndCustomOrigins.html)

So what happens? If you use ELB for all of your CloudFront Distributions, the check will fail for each resource resulting in a lot of false positives.. 

The command i am running is: 

```bash
prowler aws --log-level WARNING --output-filename "prowler-output-cloudfront" --checks cloudfront_distributions_s3_origin_non_existent_bucket --output-modes csv json-asff json-ocsf --ignore-exit-code-3 --no-banner
```

### Expected behavior

The check `cloudfront_distributions_s3_origin_non_existent_bucket` should validate the origin-type of a CloudFront distribution resource. 

Example: Let's assume the following `domain_name` of an origin: `important-api-12345.production.company.org`.
According to the code

```python
bucket_name = origin.domain_name.split(".")[0]
```

The extracted name would be `important-api-12345` . Since the origin is an ELB, the check would fail because it is just looking for S3 buckets. The check should therefore consider all other documented origin-types. If no S3, ApiGateway, ELB etc. does match the domain's name, the check should fail with something like "No valid resource for configured origin of CloudFront distribution ABCDEFG found".. Or similar.. 

### Actual Result with Screenshots or Logs

Not applicable

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

Docker container locally

### OS used

Debian GNU/Linux 12 (bookworm)

### Prowler version

4.4.0

### Pip version

24.2

**Comment by jfagoagas** [comment]
Hello @pr3l14t0r, we will review it as soon as possible. I sent it to the team to review it.

Thanks for using Prowler 🚀

**Comment by HugoPBrito** [comment]
Greetings @pr3l14t0r.

We have reviewed the code and added a new comprobation in PR #5543 to verify that the origin is an `S3 bucket`, preventing false positives. Now, all `Cloudfront Distributions` with origins in services outside `S3` should return the `PASS` status. Please try this solution and let us know if this works for you.

Thanks for making cloud more secure!

**Comment by pr3l14t0r** [comment]
Heyho @HugoPBrito ! I am soooo sorry that you had to wait so long for my response. I have tested this now running prowler from `master` branch. The check works fine now, at least all the `CloudFront` resources in question do `PASS`. :) 

Thanks for your work and sorry again for my late response. 

You guys are awesome!! ❤️

**Comment by HugoPBrito** [comment]
No problem! Thanks to you, we really appreciate it <3
