### ISSUE TITLE
The compliance flag dosent gives key error when using

### ISSUE THREAD

**Issue by Nirbhay1997** [toniblyx/prowler#5595]
### Steps to Reproduce

Run prowler 4.5.0 with `--complinace` flag

### Expected behavior

The scan should proceed

### Actual Result with Screenshots or Logs

![image](https://github.com/user-attachments/assets/d79d9927-01c9-4721-933f-2f62434ad44e)

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

EKS 

### OS used

Amazon Linux

### Prowler version

v4.5.0

### Pip version

N/A

**Comment by jfagoagas** [comment]
Hello @Nirbhay1997 we are going to take a look to this right now. We will get back to you once we have an update.

Thanks for using Prowler 🚀

**Comment by jfagoagas** [comment]
@Nirbhay1997 we've just detected the issue, we are working on a fix right now. We will push PR with the fix soon.

**Comment by pedrooot** [comment]
Hey! @Nirbhay1997 in this PR -> https://github.com/prowler-cloud/prowler/pull/5601
you can check the solution for this issue. Tell me if this works for you!
