### ISSUE TITLE
CIS 1.8 5.7.2 fails even though seccomp profile is set to runTimeDefault

### ISSUE THREAD

**Issue by misterdohl** [toniblyx/prowler#5803]
### Steps to Reproduce

1. Create a Pod with securityContext.seccompProfile.type: RunTimeDefault
2. Run Prowler
3. Prowler will complain on "Pod <pod name> does not have docker/default seccomp profile enabled."

### Expected behavior

CIS 1.8 5.7.2 states "Remediation: Use securityContext to enable the docker/default seccomp profile in your pod definitions. An example is as below: securityContext: seccompProfile: type: RuntimeDefault"

From the Talos documentation (from version 1.2.0 and above): Talos now runs Kubelet with the CRI default Seccomp Profile enabled.
This can be disabled by setting .machine.kubelet.defaultRuntimeSeccompProfileEnabled to false.

I've checked that its set to true on all nodes.

### Actual Result with Screenshots or Logs

pod manifest
```
kubectl -n kube-system get pod kube-apiserver-controlplane1 -ojsonpath='{.spec.containers[*].securityContext}'

{"allowPrivilegeEscalation":false,"capabilities":{"add":["NET_BIND_SERVICE"],"drop":["ALL"]},"seccompProfile":{"type":"RuntimeDefault"}}
```

prowler json
```
"message": "Pod kube-apiserver-controlplane1 does not have docker/default seccomp profile enabled.",
    "status_detail": "Pod kube-apiserver-controlplane1 does not have docker/default seccomp profile enabled.",
```

### How did you install Prowler?

From brew (brew install prowler)

### Environment Resource

Workstation

### OS used

macOS 15.1

### Prowler version

4.5.3

### Pip version

24.3.1

**Comment by pedrooot** [comment]
Hey! @misterdohl thanks for the ping. Requirement `5.7.2` is associated with the check `core_seccomp_profile_docker_default`. Based on the information you’ve provided, I can see that a modification will be needed to improve it. I’ll let you know as soon as the change is made!

**Comment by MrCloudSec** [comment]
@misterdohl in the PR https://github.com/prowler-cloud/prowler/pull/5814, we fixed this issue by validating the seccomp profile configuration at both pod and container level, let us know if it works for you!

**Comment by misterdohl** [comment]
@MrCloudSec did a pull on PR and launched a scan via poetry, and it seems to mark the pods with seccomp type: runtimedefault OK now. Good job! 🎉
Issue resolved from my perspective 🥇
