### ISSUE TITLE
Adjust root account checks when centralized root account management is active

### ISSUE THREAD

**Issue by cisopaul** [toniblyx/prowler#5804]
### New feature motivation

AWS has recently shipped a feature which allows you to remove the root account from member AWS accounts of an organization (https://aws.amazon.com/blogs/aws/centrally-managing-root-access-for-customers-using-aws-organizations/)

This is a good thing & creates a situation where we don't have to manage credentials or MFA for root accounts.

However this may mean that the checks for root password/MFA could report incorrect status depending on how those checks are done

### Solution Proposed

When centralized root management is in place don't fire the checks for no root password or MFA. Note - it's not clear from the AWS docs if it's possible to test for this state. It may be that the only way of knowing this is for the root password/MFA check to return an error due to no root account.

### Describe alternatives you've considered

Automatically mute findings for root password/MFA if centralized root management is enabled

**Comment by cisopaul** [comment]
It looks like you can pass this managed policy  https://docs.aws.amazon.com/IAM/latest/UserGuide/security-iam-awsmanpol.html#security-iam-awsmanpol-IAMAuditRootUserCredentials during the assume-root operation.

However we'd  want Prowler scan role to ONLY be able to pass this policy & not any of the others. This would require use of https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_iam-condition-keys.html#ck_taskpolicyarn to limit the use of assume-root (which is an additional permission needed if customers are using centralized management of root)

**Comment by jfagoagas** [comment]
Hello @cisopaul, we've been working on a new check, I've just linked it to this feature request.

Thank you!

**Comment by MrCloudSec** [comment]
@cisopaul the check `iam_root_credentials_management_enabled` in PR https://github.com/prowler-cloud/prowler/pull/5801 cover this case, let us know what you think!
