### ISSUE TITLE
CIS 1.8 5.1.2 complain even though ClusterRole dont have access to Secrets

### ISSUE THREAD

**Issue by misterdohl** [toniblyx/prowler#5823]
### Steps to Reproduce

1. In report, Prowler reports  ClusterRole <name> has secret access.
2. kubectl get clusterrole <name> doesnt show it have secret access.

### Expected behavior

I'm guessing this behavior comes from some apiGroups having a wildcard in the resources, but * in apiGroups other than v1/"" shouldn't provide direct access to the v1/Secret object afaik.

### Actual Result with Screenshots or Logs

Prowler output:

`ClusterRole hubble-ui has secret access.`

kubectl get clusterrole hubble-ui -oyaml

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    meta.helm.sh/release-name: cilium
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2024-11-18T14:31:23Z"
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: cilium
  name: hubble-ui
  resourceVersion: "84296702"
  uid: e8687110-319b-4f71-9736-30d1a56fda2f
rules:
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - componentstatuses
  - endpoints
  - namespaces
  - nodes
  - pods
  - services
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cilium.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
```

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

Workstation

### OS used

MacOS 15.1

### Prowler version

4.5.3

### Pip version

24.3.1

### Context

I would presume a better approach is to specifically check after entry "Secret" or wildcard in the core apiGroup when scanning Secret access.

**Comment by MrCloudSec** [comment]
@misterdohl the above PR solves the issue, let us know if that works on your side!

**Comment by misterdohl** [comment]
@MrCloudSec verified that the pr above indeed fixes this issue.

setup an empty kind cluster with the hubble-ui clusterrole
ran prowler 4.5.3 and verified that it warned "hubble-ui clusterrole has access to secrets"
Pulled PR
ran prowler 4.6.0 and verified that hubble-ui wasnt warned on secret access anymore.

Good job! 🎉
