### ISSUE TITLE
Prowler scan stuck on cloudtrail_threat_detection checks

### ISSUE THREAD

**Issue by Micah-Champagne** [toniblyx/prowler#5920]
### Steps to Reproduce

Command: prowler aws --log-level DEBUG. 
Cloud provider: aws
Environment: SecurityAudit and ReadOnlyAccess levels to a single organization. Trying to run it using the security audit credentials. 
Error: Program seems to hang up on cloudtrail_threat_detection_enumeration and cloudtrail_threat_detection_privilege_escalation tests

### Expected behavior

I entered my credentials and started the scan and it worked for a while until test 81 (cloudtrail_threat_detection_enumeration). I thought it was just getting hung up on that one test so i used the -e flag and targeted that test, then it started getting hung up on the cloudtrail_threat_detection_privilege_escalation. I've let it run for 15 minutes and it keeps getting stuck each time.

### Actual Result with Screenshots or Logs

![image](https://github.com/user-attachments/assets/e542e3e2-3459-4ba3-b692-971f87694d94)

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

7. Workstation

### OS used

Ubutnu WSL

### Prowler version

Prowler 4.6.0

### Pip version

pip 24.0

### Context

First time using tool. Tried to read documentation / other issue requests to help fix issue myself.

**Comment by MrCloudSec** [comment]
Hi @Micah-Champagne, the CloudTrail threat detection checks analyze the last 24 hours of events in CloudTrail to identify potential enumeration, LLM hijacking, or privilege escalation attacks. This is why it takes some time to retrieve and process the CloudTrail log events.

That said, we’re working on a fix to ensure these checks are only executed when the `--category threat-detection` argument is explicitly provided. Thanks for bringing this to our attention!
