### ISSUE TITLE
Prowler Scan Freezing During Process

### ISSUE THREAD

**Issue by stenionljunior** [toniblyx/prowler#5928]
### Steps to Reproduce

Command: prowler aws --security-hub
Cloud Provider: AWS
Scenario: I am running Prowler to send findings to AWS Security Hub.

Issue: During the scan, Prowler freezes.

First Test: I ran Prowler on a Lubuntu operating system hosted in Oracle VirtualBox directly on my laptop. In this scenario, the scan always froze during the CloudTrail check.

Second Test: I created an Ubuntu EC2 instance (t2.small) directly in AWS and installed Prowler via pip in a Python venv environment. In this scenario, the scan froze during the MemoryDB check. I noticed the EC2 instance became very slow, and upon checking the monitor, I observed the CPU utilization was at 100%.

### Expected behavior

That the scan completes 100% and the findings are sent to AWS Security Hub.

### Actual Result with Screenshots or Logs

Screenshot of the frozen terminal. The scan did not complete, the terminal is unresponsive, and the scan execution time is not incrementing: 
![image](https://github.com/user-attachments/assets/4cd17710-732f-4be0-a0d4-753d06caa39f)

AWS Monitoring:
![image](https://github.com/user-attachments/assets/dc11bb25-930b-4628-aa19-a00ef4000730)

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

EC2 Instance - t2.small

### OS used

Ubuntu

### Prowler version

Prowler 4.6.0

### Pip version

pip 24.0 (python 3.12)

### Context

I am writing an article about the integration of Prowler and Security Hub. I was using the latest version of the tool when I encountered the issue.

**Comment by jfagoagas** [comment]
Hello @stenionljunior we will review this and get back to you once we have an update. I think the scan will finish but it'll require time to analyse all the resources in your account. 

In the meanwhile, could you please review the following questions:
- Could you execute it again using the `--log-level ERROR` and paste the output here?
- How many resources do you have in your AWS environment?
  - Prowler requires a different amount of CPU and Memory based on the number of resources with a minimum of 2 CPU and 4GiB of RAM memory.
  


Thanks for using Prowler 🚀

**Comment by stenionljunior** [comment]
Hello @jfagoagas! 

After changing the instance to t2.large, the scan finished! Thank you for the feedback.

![image](https://github.com/user-attachments/assets/63c98734-cf32-4607-b725-26e04f87e8e9)

**Comment by jfagoagas** [comment]
That's fantastic, thank you 🚀
