### ISSUE TITLE
rds_service.py error

### ISSUE THREAD

**Issue by garym-krrv** [toniblyx/prowler#5949]
### Steps to Reproduce

1. Running prowler aws -log-level ERROR
2. AWS
3. Single Account

### Expected behavior

To execute without throwing the error

### Actual Result with Screenshots or Logs

2024-11-28 10:20:18,851 [File: rds_service.py:458] [Module: rds_service] ERROR: eu-west-2 -- KeyError[449]: 'SourceType'

We have an postgress RDS 16.3 instance in eu-west-2 and the script is throwing this error

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

2. ECS Fargate task

### OS used

3. Alpine Linux

### Prowler version

4.6.0

### Pip version

na

**Comment by puchy22** [comment]
Hi @garym-krrv,

Could you check if PR #5961 resolves your issue? Let me know if it works for you or if further adjustments are needed.

Thank you for using Prowler!

**Comment by garym-krrv** [comment]
Will do @puchy22

**Comment by puchy22** [comment]
I reopen the issue until @garym-krrv confirms that everything works as expected.

**Comment by garym-krrv** [comment]
Thanks, just tied up with Work. Will get to this today for sure @puchy22

**Comment by garym-krrv** [comment]
Hi @puchy22 , just tested this and I no longer recieve the error. 

Many Thanks.. Closing.
