### ISSUE TITLE
False positive on `wafv2_webacl_with_rules` when when ACL provisioned with AWS Firewall Manager

### ISSUE THREAD

**Issue by ghost** [toniblyx/prowler#6030]
### Steps to Reproduce

1. Depoloy ACL with AWS Firewall Manager including any rule group
2. Run prowler against AWS account where ACL is provisioned with Firewall Manager
3. Prowler will add that ACL as failed because the list of managed rules is empty, but it has AWS Firewall Manager provisioned rules

### Expected behavior

it's expected that ACL is managed centrally and may not have rules added directly

### Actual Result with Screenshots or Logs

![image](https://github.com/user-attachments/assets/bc4da90e-caf6-4748-9fd1-1cef8e4e41f4)

![image](https://github.com/user-attachments/assets/54640d49-5e58-44c6-9801-3c1bd1fe9343)

### How did you install Prowler?

From pip package (pip install prowler)

### Environment Resource

4. EKS

### OS used

1. Amazon Linux 2023

### Prowler version

5.0.0

### Pip version

24.0

**Comment by jfagoagas** [comment]
Hello @ivan-morhun , we will review it as soon as possible and get back to you once we have an update.

Thanks for using Prowler 🚀

**Comment by HugoPBrito** [comment]
Hi @ivan-morhun!

I believe this correction could resolve your issue. Please test it out and let us know if it works for you. If not, let us know as soon as possible.

Thanks for using prowler! 🤘

**Comment by ghost** [comment]
@HugoPBrito Appreciate your help!
Thanks!
