### ISSUE TITLE
False positive alert on firehose_stream_encrypted_at_rest

### ISSUE THREAD

**Issue by serhii-ciq** [toniblyx/prowler#6065]
### Steps to Reproduce

Hi! There is a bug with the check `firehose_stream_encrypted_at_rest`

### Expected behavior

The check should not alert if the Firehose Server-side encryption (SSE)  is enabled

### Actual Result with Screenshots or Logs

![image](https://github.com/user-attachments/assets/d3ad234f-006b-4293-b780-2c9af652a85a)

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

Workstation

### OS used

Windows

### Prowler version

Prowler 5.0.0 (You are running the latest version, yay!)

### Pip version

pip 24.2 (python 3.12)

**Comment by jfagoagas** [comment]
Hello @serhii-ciq, we will review it as soon as possible and get back to you once we have an update.

Thanks for using Prowler 🚀

**Comment by HugoPBrito** [comment]
Hi @serhii-ciq!

I believe this update should resolve your issue. If this is not the case or you encounter any further problems, please don't hesitate to reach out to us.

Thank you for reporting the issue and for choosing Prowler! 🤘

**Comment by serhii-ciq** [comment]
@HugoPBrito I really appreciate your efforts 💪 Thank you so much!
