### ISSUE TITLE
finding_uid is not unique in backup_recovery_point_encrypted and route53_dangling_ip_subdomain_takeover, cloudtrail_multi_region_enabled_logging_management_events

### ISSUE THREAD

**Issue by banv** [toniblyx/prowler#6138]
### Steps to Reproduce

prowler -s backup route53 cloudtrail

The program output CSV file with the same finding_uid like that
prowler-aws-backup_recovery_point_encrypted-<AWS_ACCOUNT_ID>-ap-southeast-1-aps1-ec2-ami-backup-vault
prowler-aws-backup_recovery_point_encrypted-<AWS_ACCOUNT_ID>-ap-southeast-1-aps1-rds-backup-vault
prowler-aws-route53_dangling_ip_subdomain_takeover-<AWS_ACCOUNT_ID>-us-east-1-<RESOURCE_ID>
prowler-aws-cloudtrail_multi_region_enabled_logging_management_events-<AWS_ACCOUNT_ID>-ap-northeast-1-Members

### Expected behavior
The finding_uid must be unique id

### Actual Result with Screenshots or Logs

No Log

### How did you install Prowler?

Cloning the repository from github.com (git clone)

### Environment Resource

8. Other (Local PC)

### OS used

2. MacOS

### Prowler version

Prowler 5.1.0 (You are running the latest version, yay!)

### Pip version

pip 23.3

### Context

It's the same problem with #6105 and I think it may be happen with many check that using for/loop then append report to finding array like [that](https://github.com/prowler-cloud/prowler/blob/4d1c8eae8fbbdedea19ff473faafc9e5c1f1d6df/prowler/providers/aws/services/backup/backup_recovery_point_encrypted/backup_recovery_point_encrypted.py#L8-L20)

**Comment by MrCloudSec** [comment]
Hi @banv, thanks for the heads up! We will work on the fix asap.

**Comment by MrCloudSec** [comment]
@banv I was able to reproduce the error for `backup_recovery_point_encrypted`. Can you give us more info for the rest of the checks, please?

**Comment by MrCloudSec** [comment]
Hi @banv, I just did the PR with the fix, try it if you want and let us know if that fixes the issue. Thanks!
