### ISSUE TITLE
Fix check21: is considering only home region trails

### ISSUE THREAD

**Issue by nayabpatel** [toniblyx/prowler#868]
I have an account which contains the multi-region trail in us-east-1 region while all my services are in eu-central-1 region. While running the validation i ran "./prowler -r eu-central-1 -f eu-central-1 -c check21" command which results in failure. Then I dig the check21 shell script code(specially the below code) wherein it seems it's considering only home region trails.

if [ $TRAIL_REGION != $regx ]; then # Only report trails once in home region
          continue
        fi

Any specific region we are considering only home region trails. As per my understanding if an account has a multi-region trail in any region, the check should pass.

**Comment by toniblyx** [comment]
Thanks for you comment @nayabpatel. This one is a pretty discussed check and you are right, when the scope of Prowler is one region where is not the trail home region and has multi-region enabled it fails as `"No CloudTrail trails were found in the account"`. This is a bug that has to be solved changing the way it goes thru regions when `-f` is used. I'll tag it as bug to work on it but please feel free to send a PR with a fix if you can.

**Comment by nayabpatel** [comment]
Hi  @toniblyx ,

I was getting error while creating a pull request for applying fix of this issue. It seems editing right issue. Error : "Pull request creation failed. Validation failed: You can't perform that action at this time."

**Comment by jfagoagas** [comment]
Hi @nayabpatel you need to fork this project, fix this issue and commit it.

Then, you will be able to open a PR from your forked branch.

**Comment by toniblyx** [comment]
Exactly, try forking and then commit it. If you can please paste here the code that fixes the issue and we will give it a look. Thanks!

**Comment by toniblyx** [comment]
Hi @nayabpatel, did you manage to write the fix? yo can paste it here and I can merge it for you.

Thanks!

**Comment by nayabpatel** [comment]
Sorry for the delay, as i was quite busy in some other stuff. Here is the code  ....


#!/usr/bin/env bash

# Prowler - the handy cloud security tool (c) by Toni de la Fuente
#
# This Prowler check is licensed under a
# Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License.
#
# You should have received a copy of the license along with this
# work. If not, see <http://creativecommons.org/licenses/by-nc-sa/4.0/>.

CHECK_ID_check21="2.1"
CHECK_TITLE_check21="[check21] Ensure CloudTrail is enabled in all regions (Scored)"
CHECK_SCORED_check21="SCORED"
CHECK_TYPE_check21="LEVEL1"
CHECK_SEVERITY_check21="High"
CHECK_ASFF_TYPE_check21="Software and Configuration Checks/Industry and Regulatory Standards/CIS AWS Foundations Benchmark"
CHECK_ASFF_RESOURCE_TYPE_check21="AwsCloudTrailTrail"
CHECK_ALTERNATE_check201="check21"
CHECK_ASFF_COMPLIANCE_TYPE_check21="ens-op.acc.7.aws.iam.1 ens-op.mon.1.aws.trail.1"
CHECK_SERVICENAME_check21="cloudtrail"
CHECK_RISK_check21='AWS CloudTrail is a web service that records AWS API calls for your account and delivers log files to you. The recorded information includes the identity of the API caller; the time of the API call; the source IP address of the API caller; the request parameters; and the response elements returned by the AWS service.'
CHECK_REMEDIATION_check21='Ensure Logging is set to ON on all regions (even if they are not being used at the moment.'
CHECK_DOC_check21='https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrailconcepts.html#cloudtrail-concepts-management-events'
CHECK_CAF_EPIC_check21='Logging and Monitoring'

check21(){
  trail_count=0
  # "Ensure CloudTrail is enabled in all regions (Scored)"
  for regx in $REGIONS; do
    TRAILS_AND_REGIONS=$($AWSCLI cloudtrail describe-trails $PROFILE_OPT --region $regx --query 'trailList[*].{Name:TrailARN, HomeRegion:HomeRegion}' --output text 2>&1 | tr "	" ',')
    if [[ $(echo "$TRAILS_AND_REGIONS" | grep AccessDenied) ]]; then
      textFail "Access Denied trying to describe trails in $regx"
      continue
    fi
    if [[ $TRAILS_AND_REGIONS ]]; then
      for reg_trail in $TRAILS_AND_REGIONS; do
        TRAIL_REGION=$(echo $reg_trail | cut -d',' -f1)       
        trail=$(echo $reg_trail | cut -d',' -f2)
        trail_count=$((trail_count + 1))

        MULTIREGION_TRAIL_STATUS=$($AWSCLI cloudtrail describe-trails $PROFILE_OPT --region $TRAIL_REGION --query 'trailList[*].IsMultiRegionTrail' --output text --trail-name-list $trail)
        if [[ "$MULTIREGION_TRAIL_STATUS" == 'False' ]];then
          textFail "Trail $trail in $regx is not enabled for all regions"
        else
          textPass "Trail $trail in $regx is enabled for all regions"
          break # Atleast one trail is enabled in all regions
        fi

      done
    fi
  done
  if [[ $trail_count == 0 ]]; then
    textFail "No CloudTrail trails were found in the account"
  fi
}

**Comment by nayabpatel** [comment]
Sorry for the delay in response, as i was quite busy in some other stuff. Here is the code(pasting the method only). Also remove / from commented line # "Ensure CloudTrail is enabled in all regions (Scored)", added it just to ignore the effect of #


check21(){
  trail_count=0
  /# "Ensure CloudTrail is enabled in all regions (Scored)"
  for regx in $REGIONS; do
    TRAILS_AND_REGIONS=$($AWSCLI cloudtrail describe-trails $PROFILE_OPT --region $regx --query 'trailList[*].{Name:TrailARN, HomeRegion:HomeRegion}' --output text 2>&1 | tr "	" ',')
    if [[ $(echo "$TRAILS_AND_REGIONS" | grep AccessDenied) ]]; then
      textFail "Access Denied trying to describe trails in $regx"
      continue
    fi
    if [[ $TRAILS_AND_REGIONS ]]; then
      for reg_trail in $TRAILS_AND_REGIONS; do
        TRAIL_REGION=$(echo $reg_trail | cut -d',' -f1)       
        trail=$(echo $reg_trail | cut -d',' -f2)
        trail_count=$((trail_count + 1))

        MULTIREGION_TRAIL_STATUS=$($AWSCLI cloudtrail describe-trails $PROFILE_OPT --region $TRAIL_REGION --query 'trailList[*].IsMultiRegionTrail' --output text --trail-name-list $trail)
        if [[ "$MULTIREGION_TRAIL_STATUS" == 'False' ]];then
          textFail "Trail $trail in $regx is not enabled for all regions"
        else
          textPass "Trail $trail in $regx is enabled for all regions"
          break # Atleast one trail is enabled in all regions
        fi

      done
    fi
  done
  if [[ $trail_count == 0 ]]; then
    textFail "No CloudTrail trails were found in the account"
  fi
}

**Comment by toniblyx** [comment]
thank you @nayabpatel, just for your info, using:

\`\`\`
`code here`
\`\`\`

you can format your code better and helps a bit :D 

Going to test your code, thank you!

**Comment by toniblyx** [comment]
Hi again @nayabpatel, after looking at this in detail I can say that the check is basically working as expected. Let me explain because it needs a bit of a change. In your case you are filtering by region with `-f eu-central-1` and makes automatically prowler forget about any other region but that one, so if you don't have a multi-region cloudtrail enabled in that very same region Prowler must fail and it does. However, it gives you the error:
`FAIL! eu-central-1: No CloudTrail trails were found in the account`
which is not actually accurate and it requires a change to tell user that it is not found in that region.

So I have made a change adding 

```
if [[ $trail_count == 0 ]]; then
    if [[ $FILTERREGION ]]; then
      textFail "$regx: No CloudTrail trails were found in the filtered region" "$regx" "$trail"
    else
      textFail "$regx: No CloudTrail trails were found in the account" "$regx" "$trail"
    fi 
 fi
```

That makes this check now better and provides more comprehensive information to the user.
