### ISSUE TITLE
CSV-Header generation depended of arg order

### ISSUE THREAD

**Issue by gregorschulz** [toniblyx/prowler#871]
When using -M csv,html I get no CSV header, when using -M html,csv the CSV-ouput contains the headers.

Is this by intention?

**Comment by toniblyx** [comment]
Hi @gregorschulz, thanks for the heads up. It is not intentional and has to be fixed.

**Comment by toniblyx** [comment]
Hey @gregorschulz this is now fixed, check it out in branch 2.5.1. Thanks.
