### ISSUE TITLE
BatchImportFindings error 

### ISSUE THREAD

**Issue by ghost** [toniblyx/prowler#872]
Hi I'm Adrian.

I am implementing prowler with quicksight following the [guide ](https://quicksight-security-dashboard.workshop.aws/agenda.html)but apparently when I check the logs, each and every one of the checks gives me the following error:

An error occurred (AccessDeniedException) when calling the BatchImportFindings operation: User: arn:aws:sts::xxxxxx:assumed-role/codebuild-role-Prowler-3/AWSCodeBuild-d901f1d3-06fa-446d-a1d1-dd744db1692b is not authorized to perform: securityhub:BatchImportFindings on resource: arn:aws:securityhub:us-east-1::product/prowler/prowler

ERROR! Failed to send check output to AWS Security Hub

It turns out that the codebuild-role-Prowler-3 role have sufficient permissions to perform that action

![image](https://user-images.githubusercontent.com/61958572/133511044-d60cddb1-8231-47df-8a11-7557641c2b1b.png)

SecurityHubBatchImportFindings:
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "securityhub:BatchImportFindings",
                "securityhub:GetFindings"
            ],
            "Effect": "Allow",
            "Resource": "*"
        }
    ]
}
```

**Comment by toniblyx** [comment]
thanks @Intrusionz3r0, could you please make sure that you are deploying those templates in us-east-1? If not, you have to adapt the prowler options parameter in the 3rd template according to your region. Remember that this integration is tied to a region due to the way Security Hub works.

**Comment by toniblyx** [comment]
Also verify that Prowler integration is enabled in Security Hub integrations in that particular region (that is done by the template 1 but just in case)

**Comment by ghost** [comment]
Hi @tonblyx, the error is resolved.

The problem was that I did not enable AWS Config and Security Hub in the other regions.

Another problem was that the ** codebuild-role-prowler-reinforce-3 ** role did not have enough permissions in other regions

Thank you very much for the advice
