### ISSUE TITLE
Exit status error 3

### ISSUE THREAD

**Issue by ghost** [toniblyx/prowler#878]
Hello @toniblyx , good night, I was executing the script and almost at the end I got the following error:

![image](https://user-images.githubusercontent.com/61958572/134461399-391a02e4-0dfa-4da7-90ca-b565cd1afbf8.png)

What do you think is due?

I would greatly appreciate your answer, anyway I will be investigating doing tests trying to avoid the error so that the execution of CodeBuild ends successfully.

**Comment by toniblyx** [comment]
Hi @Intrusionz3r0, that is due to the exit error handling in Prowler, there are some ways to manage this, look at the recently added feature to branch 2.5.1 that you can use -z and -Z to handle that. More info here https://github.com/toniblyx/prowler/pull/865

**Comment by toniblyx** [comment]
This is duplicated https://github.com/toniblyx/prowler/issues/629
