### ISSUE TITLE
Flag -q shows Check_Results "WARNING" additionally instead of only "FAIL"

### ISSUE THREAD

**Issue by gregorschulz** [toniblyx/prowler#884]
The -q flag doesn't show only the "FAIL"s but also the WARNINGs from the exclusions when using -w whitelist.txt.

Is this by intention?

**Comment by toniblyx** [comment]
Hi @gregorschulz, yes, that is an expected behavior. WARNING is shown when a resource is excluded, it is just to take it into consideration.

**Comment by gregorschulz** [comment]
Ok, but then I would suggest to adjust the documentation for -q:
https://github.com/toniblyx/prowler#show-or-log-only-fails

**Comment by w0rmr1d3r** [comment]
Hi @toniblyx & @gregorschulz !

I did a PR https://github.com/toniblyx/prowler/pull/890 updating the documentation.
Tell me what you think to see if it's clearer that way.

Cheers!

**Comment by toniblyx** [comment]
Thanks for reporting it @gregorschulz and for the enhancements @w0rmr1d3r!!
