### ISSUE TITLE
[Container] 2021/09/27 19:01:52 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: ./prowler $PROWLER_OPTIONS. Reason: exit status 3

### ISSUE THREAD

**Issue by claviston** [toniblyx/prowler#885]
Colleagues I have an error in the build process when I use the Prowler with Cloud-formation.

Can you help me identifying How can I have it fixed? 

![cloudbuild-error](https://user-images.githubusercontent.com/57537626/135104573-b1621232-6cba-4b68-965e-4134ae459f62.jpg)
![cloudbuild-error2](https://user-images.githubusercontent.com/57537626/135104580-f4eaa150-a08e-4145-8a70-c20f94eac596.jpg)
![cloudbuild-error3](https://user-images.githubusercontent.com/57537626/135104583-5bcd55f5-c202-4557-8f5c-131eb9d29a43.jpg)

**Comment by toniblyx** [comment]
This issue is duplicated with https://github.com/toniblyx/prowler/issues/878. Please use the new feature added in the branch 2.5.1 to manage the exit error from Prowler checks. More info https://github.com/toniblyx/prowler/issues/629
