### ISSUE TITLE
Check 7.74 - Duplicate failures being reported

### ISSUE THREAD

**Issue by CenturionGamer** [toniblyx/prowler#886]
The failures from check 7.74 are being duplicated, so it is showing twice as many failures for this check.

**Comment by estemendoza** [comment]
I work with @CenturionGamer and I will give some more context to the issue.

Prowler was executed like this:

`$./prowler -p <profile> -f '<regions>' -b -M json -F <report path>`

It seems that check 7.74 is executed first along with 1.x checks and then it is executed again when 7.x checks are executed

let me know if more info is needed

**Comment by toniblyx** [comment]
ok, that is because it was added to that section. That can be fixed in the next version.
