### ISSUE TITLE
Getting error while running prowler for multiple regions in a account

### ISSUE THREAD

**Issue by anuj1366** [toniblyx/prowler#887]
I am running Prolwer through AWS Code Build for multiple regions in a single AWS account and below command is getting executed:
**-r eu-central-1 -f 'eu-central-1 eu-west-1' -M junit-xml,json-asff -S** 

**Now I am getting below error:**
Access Denied trying to describe regions! Review permissions as described here: https://github.com/toniblyx/prowler/#requirements-and-installation
974 |  
975 | [Container] 2021/09/30 08:48:50 Command did not exit successfully ./prowler $PROWLER_OPTIONS exit status 1
976 | [Container] 2021/09/30 08:48:50 Phase complete: BUILD State: FAILED
977 | [Container] 2021/09/30 08:48:50 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: ./prowler $PROWLER_OPTIONS. Reason: exit status 1

By analyzing the AWS cloudtrail, I have figure out like Prowler is sending filter regions with single quote attached.
![image](https://user-images.githubusercontent.com/91662053/135421267-5040c1d9-8c04-465d-9ca9-782a22703cbc.png)

Could you please suggest how to run Prowler for multiple regions.
Note: I have tried to run the prowler for multiple regions without giving single quote for filter region like below:
**-r eu-central-1 -f eu-central-1 eu-west-1 -M junit-xml,json-asff -S** 
But its considering only eu-central-1.

**Comment by toniblyx** [comment]
Hi @anuj1366, this is a matter of how to escape those quotes in bash. Are you using the CFN template provided in the repo or your own?

**Comment by Kirizan** [comment]
@anuj1366 For codebuild, put the region list in double quotes, not single quotes. Try this command: `-r eu-central-1 -f "eu-central-1 eu-west-1" -M junix-xml,json-asff -S`

**Comment by anuj1366** [comment]
> @anuj1366 For codebuild, put the region list in double quotes, not single quotes. Try this command: `-r eu-central-1 -f "eu-central-1 eu-west-1" -M junix-xml,json-asff -S`

@Kirizan I have already tried to give multiple regions in double quotes but it didn't worked and getting below error.
![image](https://user-images.githubusercontent.com/91662053/135870929-2090fcd7-0d77-4dc1-9ee7-d3b5e5b141e8.png)

**Comment by anuj1366** [comment]
> Hi @anuj1366, this is a matter of how to escape those quotes in bash. Are you using the CFN template provided in the repo or your own?

@toniblyx Yes, I have used the same CFN template provided in the repo (https://github.com/toniblyx/prowler/tree/master/util/codebuild).

I have tried to overriding the default "ProwlerOptions" with below command but nothing worked,
-r eu-central-1 -f 'eu-central-1 eu-west-1' -M junit-xml,json-asff -S
-r eu-central-1 -f "eu-central-1 eu-west-1" -M junit-xml,json-asff -S
-r eu-central-1 -f eu-central-1 eu-west-1 -M junit-xml,json-asff -S

**Comment by toniblyx** [comment]
as a workaround, could you add those regions in this line inside the template? Right here: https://github.com/toniblyx/prowler/blob/3b6bc7fa64a94dfdfb104de6f3d32885c630628f/util/codebuild/codebuild-prowler-audit-account-cfn.yaml#L252 something like 
```
- ./prowler -f 'eu-central-1 eu-west-1' $PROWLER_OPTIONS 
```
Where your prowler options could be `-r eu-central-1 -M junit-xml,json-asff -S` that should make the trick. Can you confirm?

**Comment by toniblyx** [comment]
Provided workaround and no feedback so closing it. Please @anuj1366 feel free to reopen the issue if you have any additional comment.

**Comment by rewanthtammana** [comment]
I'm facing the same issue :(

```bash
[ssm-user@ip-172-30-24-131 prowler]$ ./prowler -f 'eu-west-1' -r 'eu-west-1'
                          _
  _ __  _ __ _____      _| | ___ _ __
 | '_ \| '__/ _ \ \ /\ / / |/ _ \ '__|
 | |_) | | | (_) \ V  V /| |  __/ |
 | .__/|_|  \___/ \_/\_/ |_|\___|_|v2.11.0-21July2022
 |_| the handy cloud security tool

 Date: Wed Aug 10 08:16:10 UTC 2022

 Color code for results:
 -  INFO (Information)
 -  PASS (Recommended value)
 -  WARNING (Ignored by allowlist)
 -  FAIL (Fix required)

 This report is being generated using credentials below:

 AWS-CLI Profile: [INSTANCE-PROFILE] AWS API Region: [eu-west-1] AWS Filter Region: [eu-west-1]
 AWS Account: [.....] UserId: [....]
 Caller Identity ARN: [....................]

 Access Denied trying to describe regions! Review permissions as described here: https://github.com/prowler-cloud/prowler/#requirements-and-installation
```

I'm explicitly specifying one region but why is prowler trying to describe all regions?

**Comment by jfagoagas** [comment]
> I'm explicitly specifying one region but why is prowler trying to describe all regions?

Hi @rewanthtammana, in every Prowler execution we call the `get_regions` function https://github.com/prowler-cloud/prowler/blob/master/include/aws_profile_loader#L63-L75 for two reasons:
1. Validate the regions set as input parameters
2. Extract the available AWS regions

Since you are executing Prowler in an instance, do you allow the `ec2:DescribeRegions` action in the instance role?

Thanks!

**Comment by yerbo1** [comment]
> > Hi @anuj1366, this is a matter of how to escape those quotes in bash. Are you using the CFN template provided in the repo or your own?
> 
> @toniblyx Yes, I have used the same CFN template provided in the repo (https://github.com/toniblyx/prowler/tree/master/util/codebuild).
> 
> I have tried to overriding the default "ProwlerOptions" with below command but nothing worked, -r eu-central-1 -f 'eu-central-1 eu-west-1' -M junit-xml,json-asff -S -r eu-central-1 -f "eu-central-1 eu-west-1" -M junit-xml,json-asff -S -r eu-central-1 -f eu-central-1 eu-west-1 -M junit-xml,json-asff -S

What is the -r flag for? Authentication?
