### ISSUE TITLE
COMMAND_EXECUTION_ERROR: Error while executing command: ./prowler $PROWLER_OPTIONS. Reason: exit status 3

### ISSUE THREAD

**Issue by claviston** [toniblyx/prowler#888]
Any idea how to solve this issue? 
![error build phase](https://user-images.githubusercontent.com/57537626/135480755-5892d5fb-1987-42e1-8fab-902d8e91f565.jpg)

![image](https://user-images.githubusercontent.com/57537626/135480548-83a907c0-03cb-4c7b-b805-2017a97129c4.png)

**Comment by w0rmr1d3r** [comment]
Hello @claviston ,

Could this issue be duplicated with https://github.com/toniblyx/prowler/issues/885 ?

Cheers!

**Comment by toniblyx** [comment]
Exactly, this is not an issue with Prowler but the way that CodeBuild (or Jenkins, etc) work in terms of error or exit status. Prease, review the links provided by Ramon and also check out the branch 2.5.1 and see `-h` for the recently added options `-z` and `-Z`. Those options should make the trick for you.
