### ISSUE TITLE
extra780 it returns false positive because of quote when running container in Windows

### ISSUE THREAD

**Issue by ilutiu** [toniblyx/prowler#903]
Because this check is using --query 'DomainStatus.CognitoOptions.Enabled'  
instead of --query "DomainStatus.CognitoOptions.Enabled", th aws cli  2.2.12 it does not return the value (True / False) but the text 
DomainStatus.CognitoOptions.Enabled

**Comment by toniblyx** [comment]
Thanks for the heads up @ilutiu. Do you mean that using aws cli v2 this command:
```
aws es describe-elasticsearch-domain --domain-name $domain $PROFILE_OPT --region $regx --query 'DomainStatus.CognitoOptions.Enabled' --output text
```
The output is `DomainStatus.CognitoOptions.Enabled` instead of `true` or `false`? But changing the query to double cuotes on `"DomainStatus.CognitoOptions.Enabled"` it works as expected?

**Comment by ilutiu** [comment]
yes, with "DomainStatus.CognitoOptions.Enabled"  it returns True / False

**Comment by toniblyx** [comment]
Sorry but I can't reproduce this issue, I'm using 
```
$ bash --version
GNU bash, version 5.1.8(1)-release (aarch64-apple-darwin20.4.0)
```
with
```
$ aws --version
aws-cli/2.2.47 Python/3.8.8 Darwin/21.1.0 exe/x86_64 prompt/off
```
The outuput for me is exactly the same with single and double quotes. Can you make sure you are using those versions? 

Here are my tests:
```
$ aws es describe-elasticsearch-domain --domain-name test1  --region eu-west-1 --query 'DomainStatus.CognitoOptions.Enabled' --output text
False
$ aws es describe-elasticsearch-domain --domain-name test1  --region eu-west-1 --query "DomainStatus.CognitoOptions.Enabled" --output text
False
```

**Comment by ilutiu** [comment]
Hi,

The issue appears on a linux  container and on windows  with cli v1  

Thanks.

**Comment by toniblyx** [comment]
ok thanks for clarifying, that is not planned to fix at this point, could you use cli v2 or the existing docker image or provided dockerfile? that would fix the problem. https://github.com/toniblyx/prowler/blob/master/util/Dockerfile

**Comment by toniblyx** [comment]
Apparently when the container is running in Windows the response of command 
```
$ aws es describe-elasticsearch-domain --domain-name test1  --region eu-west-1 --query "DomainStatus.CognitoOptions.Enabled" --output text
```
is empty instead of true or false. Can you confirm @ilutiu ?

**Comment by ilutiu** [comment]
Sorry for the misunderstanding. The container is linux (amazon/aws-cli) and I've also tested on windows (not a container).
On both cases I've obtained a false positive and on windows  I've seen that the response of the cli is the text
DomainStatus.CognitoOptions.Enabled instead of bool

**Comment by jfagoagas** [comment]
Hi @ilutiu, could you please fulfil the issue template [here](https://github.com/prowler-cloud/prowler/blob/master/.github/ISSUE_TEMPLATE/bug_report.md), we need more information to address this issue.

Please, include as much debug information as you can, using `bash -x`, because with the information you provide we are not  being able to reproduce your issue.

Thank you!

**Comment by jfagoagas** [comment]
Hi @ilutiu, we are closing this issue because we need more information to reproduce it. 

Please, feel free to reopen it if you can provide more information or if you are experiencing the same issue.

Thank you!
