### ISSUE TITLE
 prowler with cli v2 in a container

### ISSUE THREAD

**Issue by ilutiu** [toniblyx/prowler#905]
Hi,
I've tried to start prowler with cli v2 in a container:

INFO[0034] args: [-c awsv2 --install]                   
INFO[0034] Running: [/bin/sh -c awsv2 --install]        
2021-11-03 11:02:03,951 - awscliv2 - INFO - Installing AWS CLI v2 for Linux
2021-11-03 11:02:03,952 - awscliv2 - INFO - Downloading package from https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip to /tmp/tmpnqtcrd8c.zip
2021-11-03 11:02:04,200 - awscliv2 - INFO - Extracting /tmp/tmpnqtcrd8c.zip to to /tmp/tmpc8vf_l09
2021-11-03 11:02:05,722 - awscliv2 - INFO - Installing /tmp/tmpc8vf_l09/aws/install to /root/.awscliv2
2021-11-03 11:02:06,673 - awscliv2 - INFO - Now awsv2 will use this installed version
2021-11-03 11:02:06,673 - awscliv2 - INFO - Running now to check installation: awsv2 --version
aws-cli/2.3.3 Python/3.8.8 Linux/5.4.0-1045-aws exe/x86_64.debian.9 prompt/off
INFO[0037] Taking snapshot of full filesystem...        
INFO[0041] RUN alias aws='awsv2'                        
INFO[0041] cmd: /bin/sh                                 
INFO[0041] args: [-c alias aws='awsv2']                 
INFO[0041] Running: [/bin/sh -c alias aws='awsv2']      
INFO[0041] Taking snapshot of full filesystem...        
INFO[0043] No files were changed, appending empty layer to config. No layer added to image. 

but I have this error:

ERROR! AWS-CLI (aws command) not found. Make sure it is installed correctly and in your $PATH
/include/aws_profile_loader: line 50: aws: command not found
Any idea why ?

Thanks.

**Comment by toniblyx** [comment]
Why don´t you use the existing Dockerfile and build it from there? https://github.com/toniblyx/prowler/blob/master/util/Dockerfile

From the prowler folder run these commands and build your own image then you can use it as it is explained in the documentation. (use 2.5 or any other tag you want)

To build it:
```
docker build --no-cache -t prowler:2.5 -f util/Dockerfile .
```
to Tag it (whavever version or branch you use):
```
docker tag prowler:2.5 public.ecr.aws/prowler/prowler:2.5
```
then run it following instructions here https://github.com/toniblyx/prowler#usage

yo can also log into the container and run command inside for debug or anything you need:
```
docker run --rm -it --entrypoint bash prowler:2.5
```

**Comment by ilutiu** [comment]
I did use it, but I encountered #903 and tried to use aws cli v2 in the container hoping to get around that false positive with ES.

**Comment by toniblyx** [comment]
Let´s keep just one issue open to fix the same issue for you. Can you confirm if using v2 in that very same Dockerfile fix your issue in windows?

**Comment by ilutiu** [comment]
I've tested with the image amazon/aws-cli and it still returns "es.[extra780] Check if Amazon Elasticsearch Service (ES) domains has Amazon Cognito authentication for Kibana enabled" even if  Cognito authentication for Kibana is enabled

**Comment by toniblyx** [comment]
ok thenk this issue is solved because you can run prowler properly. For a reason we don't know if the container runs in windows it doesn't give you the proper response. Going to reopen #903 and close this one
