### ISSUE TITLE
Update README.md: For Cloud9/Amazon Linux 2 use sudo yum install jq   

### ISSUE THREAD

**Issue by bullittbirant** [toniblyx/prowler#906]
@toniblyx Can you please add "For Cloud9/Amazon Linux 2 use sudo yum install jq  instead of sudo apt or sudo apt-get?"

**Comment by toniblyx** [comment]
This is extracted from the existing README (that is generic and only tries to be specific with some examples):
> AWS-CLI can be also installed it using "brew", "apt", "yum" or manually from https://aws.amazon.com/cli/, but detect-secrets has to be installed using pip. You will need to install jq to get the most from Prowler.

> Make sure jq is installed (example below with "apt" but use a valid package manager for your OS):

> `sudo apt install jq`

Do you mean to change that part per OS or Linux flavour?

**Comment by bullittbirant** [comment]
Since you mentioned Cloud9 as an installation environment, I thought it would be good to mention the specific command for Amazon Linux 2

**Comment by toniblyx** [comment]
This has been added to the branch 2.5.1 that will be master soon.

**Comment by toniblyx** [comment]
Thanks for the feedback @bullittbirant!
