### ISSUE TITLE
Issue with GNU sed on MacOS

### ISSUE THREAD

**Issue by tbondarchuk** [toniblyx/prowler#916]
I'm using gnu sed on macos (`brew install gnu-sed && export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:$PATH"`) but prowler is using bsd sed options (`-i ''`) based on OS discovery, resulting in following errors:

```sh
sed: can't read s/PROWLER_SCORE/64/g: No such file or directory
sed: can't read s/PASS_COUNTER/597/g: No such file or directory
sed: can't read s/TOTAL_RESOURCES/919/g: No such file or directory
sed: can't read s/FAIL_COUNTER/322/g: No such file or directory
sed: can't read s/CHECKS_COUNTER/198/g: No such file or directory
```

I believe that using full path for sed binary would be the easiest fix for this:
```sh
--- a/include/os_detector
+++ b/include/os_detector
@@ -143,7 +143,7 @@ gnu_replace_sed(){
 }
 
 bsd_replace_sed(){
-  sed -i '' $1 $2
+  /usr/bin/sed -i '' $1 $2
 }
 
 # Functions to manage dates depending on OS
 ```
 
 so it'll force prowler to use default bsd sed while user still can use gnu sed from updated PATH.
 
 Can create PR if needed.

**Comment by toniblyx** [comment]
Thanks for let me know @aliusmiles, I´m also user of osx and never had to use gnu-sed that is why I created the functions:

```
gnu_replace_sed(){
  sed -i $1 $2
}

bsd_replace_sed(){
  sed -i '' $1 $2
}
``` 
Out of curiosity, why do you need that? I don't see it as a trend in other users so I don't consider it a needed change there is also the container available to make sure that is working anyway.

**Comment by tbondarchuk** [comment]
@toniblyx I'm using gnu-sed exactly to avoid editing script/oneliners every time sed is used. But I guess most users just use default so prowler's autodiscovery is a really cool feature. 

I just was too lazy to copy-paste aws creds to run docker container and decided to run prowler directly, but that's actually a better way, just need to write oneliner to avoid copy pasting:) Thanks for the suggestion!
