### ISSUE TITLE
sensible versus sensitive in risk messages

### ISSUE THREAD

**Issue by fredski-github** [toniblyx/prowler#925]
need to replace `sensible` for `sensitive` in risk associated with finding message.

- Publicly accessible load balancers could expose `sensible` data to bad actors.
- Vaults accessible to everyone could expose `sensible` data to bad actors

**Comment by toniblyx** [comment]
Thanks @fredski-github, just fixed it in branch 2.6.1 and will be in master as soon as I fix the other bug
