### ISSUE TITLE
check extra776 breaks csv output

### ISSUE THREAD

**Issue by fredski-github** [toniblyx/prowler#926]
was not able to determine how, the CSV report for an account in which check776 was run is malformed. there might be special characters as output of the AWS CLI call causing this.

**Comment by toniblyx** [comment]
Thanks @fredski-github I'm looking at it

**Comment by toniblyx** [comment]
ok, it looks like if it is called directly as check776 instead of extra776 and goes thru a region without resources it breaks it. But using the proper name works fine. I have also fixed the check with resource type and resource id.
