### ISSUE TITLE
Issue with assume role use case 

### ISSUE THREAD

**Issue by cparadkar** [toniblyx/prowler#929]
In case if we try to execute using assume role
e.g. ./prowler -A <account id > -R <role name>

Instead of assume role account, assessmenmt is done the account whose profile is created in system. So assume role use case is failing.

**Comment by toniblyx** [comment]
Closing as duplicated

**Comment by cparadkar** [comment]
Issue is not duplicate

**Comment by cparadkar** [comment]
Please reopen

**Comment by cparadkar** [comment]
./prowler -A 324224971769 -R cp_assume_role this is the command i am using

**Comment by toniblyx** [comment]
Thanks but please you have to provide more context otherwise I can't help

**Comment by cparadkar** [comment]
what more info you want
Can we get connected some how ?

**Comment by cparadkar** [comment]
Will be happy to provide information

**Comment by cparadkar** [comment]
The issue is if I try to execute command with assume role, the assessment is not done on the account where assume role is created. Instead assessment happens on the account where my aws profile is created

**Comment by toniblyx** [comment]
ok, from where are you running prowler? workstation, container, ec2 instance, codebuild? which role and permissions has? (run `aws sts get-caller-identity` to know what initial creds you have). Is that able to assume the role yuo want it to assume in that or other account?

**Comment by cparadkar** [comment]
I am running from my machine's command prompt its mac book. I have all the permissions in AWS.

**Comment by toniblyx** [comment]
-A 123456789012 -R ProwlerRole 

Is probably what you need.

**Comment by abhijeethv** [comment]
We are passing the account ID to -A and the role name to -R. But still not getting the expected resul.

**Comment by toniblyx** [comment]
Closing this one since #933 will take care of it.
