### ISSUE TITLE
Issue with tag/2.2.0 assume role use case 

### ISSUE THREAD

**Issue by cparadkar** [toniblyx/prowler#930]
In case of tag/2.2.0 if we try to execute  assume role use case 
e.g. ./prowler -A <account id > -R <role name>

An error is generated on command line 
An error occurred (AccessDenied) when calling the AssumeRole operation: User: <user arn> is not authorized to perform: sts:AssumeRole on resource: <assume role arn>
This is observed in case of 2.2.0 tag only not happening in 2.6.1 or master

**Comment by toniblyx** [comment]
Thanks @cparadkar, I don't understand if this is duplicated with #929, in any case, why don't you use the lastest version? can you also confirm that your user or role has permissions to assume that given role? btw, I don't see the command you used.

**Comment by toniblyx** [comment]
Also closing this one, the three issues you opened are about the same.
