### ISSUE TITLE
CSV and Json output formats are not consistent in terms of fields and field names

### ISSUE THREAD

**Issue by toniblyx** [toniblyx/prowler#941]
As seen in the screenshot below, CSV and Json outputs are not consistent and they shoudl contain the same fielsds and same field name in both cases. Since ASFF has other requirements in terms of fields, this has no impact to json-asff.

![Screenshot 2021-11-23 at 20 42 13](https://user-images.githubusercontent.com/3985464/143093272-7d8b48b0-aa65-484d-a770-d90ee187928e.png)

**Comment by jfagoagas** [comment]
Included in Prowler roadmap aiming V3.
