### ISSUE TITLE
reading wrong region from AWS config file when using custom profile on sending to AWS Security Hub

### ISSUE THREAD

**Issue by spirovskib** [toniblyx/prowler#942]
I would like to report a bug when running prowler from a custom profile on a different region from the default aws profile and sending information to Security Hub:

I am configuring Prowler to send information to security hub on my us-west-2 based account. 

Since I'm responsible for multiple accounts on different regions i needed to create a separate profile in the .aws/ folder for the prowler scan on us-west-2 based account. 

Profiles:
* `[default]` aws profile is `eu-west-1` based
* target scan profile is `us-west-2` based and called `[ bm_prowler]`

Then I run the command ` prowler -p bm_prowler -q -M json-asff -S -f us-east-2` i get the following error, which complains about eu-west-1 instead of us-east-2:
 
```
An error occurred (AccessDeniedException) when calling the BatchImportFindings operation: User: arn:aws:iam::<redacted>:user/prowler_scanner_user is not authorized to perform: securityhub:BatchImportFindings on resource: arn:aws:securityhub:eu-west-1::product/prowler/prowler
```

I went into `.aws/config` and changed the `region` field for the `[default]` profile to `us-east-2`. The error vanished and i got my results in security hub. 

Here are my aws config and credentials (redacted versions) before the change I described above. 

.aws/config
```
[default]
region = eu-west-1
output = json

[bm_prowler]
region = us-east-2
output = json
```
.aws/credentials
```
[default]
aws_access_key_id = <redacted>
aws_secret_access_key = <redacted>

[bm_prowler]
aws_access_key_id = <redacted>
aws_secret_access_key = <redacted>
```

**Comment by toniblyx** [comment]
Thanks for reporting it @spirovskib, can you try with `prowler -p bm_prowler -q -M json-asff -S -r us-east-2 -f us-east-2` with -r you force where to send default queries and api calls, with -f filter by region. Let me know if that works.

**Comment by toniblyx** [comment]
hey @spirovskib, did you have the chance to test my suggestion above? Please, let us know and reopen the issue if still with issues.
