### ISSUE TITLE
aws cli v2 required for opt-in regions

### ISSUE THREAD

**Issue by j2clerck** [toniblyx/prowler#954]
Hi,

I have noticed a bug when running prowler on new regions (requiring sts v2 token) I have noticed that prowler fails with aws cli v1.

OS: AmazonLinux 2
AWS CLI: aws-cli/1.19.112 Python/2.7.18 Linux/4.14.252-195.483.amzn2.x86_64 botocore/1.20.112
Prowler: 2.6 / 2.7

The fix I found was to use AWS CLI v2 only.

**Comment by toniblyx** [comment]
Thanks @j2clerck, do you have a link or reference to know which regions are those specifically? I'll update templates and documentation accordingly, users need to know the cli v1 limitations.

Thank you!

**Comment by toniblyx** [comment]
Ok, reading documentation here https://awscli.amazonaws.com/v2/documentation/api/latest/reference/iam/set-security-token-service-preferences.html there are two possible solutions to this.
1. Force use aws-cli v2 requires:
   - update installation documentation steps to advise users about it
   - update Dockerfile
   - update all templates with installation process in it like Codebuild and Multiaccount related templates.
2. Test if using `aws iam set-security-token-service-preferences --global-endpoint-token-version v1Token` forces v1Token in all regions including the manually enabled regions but as per documentation it looks like it won't work.

**Comment by j2clerck** [comment]
Hi Toni,

Looking at check29 in particular, I believe the AccessDenied error handling is not generic enough. 
Currently check29 looks at AccessDenied. If AccessDenied is not present in the answer then you iterate on each VPC.   
However EC2 API does not return AccessDenied but rather UnauthorizedOperation or AuthFailure. As these errors are not catched, each word of the error is iterated over when doing the describe-flow-logs operation.

       PASS! ap-east-1: VPC An VPCFlowLog is enabled for LogGroupName: An
       PASS! ap-east-1: VPC An VPCFlowLog is enabled for LogGroupName: error
       PASS! ap-east-1: VPC An VPCFlowLog is enabled for LogGroupName: occurred
       PASS! ap-east-1: VPC An VPCFlowLog is enabled for LogGroupName: (AuthFailure)
       PASS! ap-east-1: VPC An VPCFlowLog is enabled for LogGroupName: when
       PASS! ap-east-1: VPC An VPCFlowLog is enabled for LogGroupName: calling
       PASS! ap-east-1: VPC An VPCFlowLog is enabled for LogGroupName: the
       PASS! ap-east-1: VPC An VPCFlowLog is enabled for LogGroupName: DescribeFlowLogs
       PASS! ap-east-1: VPC An VPCFlowLog is enabled for LogGroupName: operation:
       PASS! ap-east-1: VPC An VPCFlowLog is enabled for LogGroupName: AWS
       PASS! ap-east-1: VPC An VPCFlowLog is enabled for LogGroupName: was
       PASS! ap-east-1: VPC An VPCFlowLog is enabled for LogGroupName: not
       PASS! ap-east-1: VPC An VPCFlowLog is enabled for LogGroupName: able
       PASS! ap-east-1: VPC An VPCFlowLog is enabled for LogGroupName: to
       PASS! ap-east-1: VPC An VPCFlowLog is enabled for LogGroupName: validate
       PASS! ap-east-1: VPC An VPCFlowLog is enabled for LogGroupName: the
       PASS! ap-east-1: VPC An VPCFlowLog is enabled for LogGroupName: provided
       PASS! ap-east-1: VPC An VPCFlowLog is enabled for LogGroupName: access
       PASS! ap-east-1: VPC An VPCFlowLog is enabled for LogGroupName: credentials

A grep -E "(AccessDenied|UnauthorizedOperation|AuthFailure)" would probably allow you to better handle these cases:

       FAIL! ap-east-1: Access Denied trying to describe VPCs

Which means that a refactor like:
`API_ERROR_CODES="(AccessDenied|AuthFailure|UnauthorizedOperation)"` which can be source d and then something like
`if [[ $(echo "$AVAILABLE_VPC" | grep -E "$API_ERROR_CODES") ]]; then`

Output with aws cli v1

       2.9 [check29] Ensure VPC Flow Logging is Enabled in all VPCs - vpc [Medium]
       FAIL! ap-east-1: Access Denied trying to describe VPCs

Output with aws cli v2

       2.9 [check29] Ensure VPC Flow Logging is Enabled in all VPCs - vpc [Medium]
       FAIL! ap-east-1: VPC vpc-29957f40 VPCFlowLog is disabled

You could probably use something like
`AWS_CLI_VERSION=$(/usr/local/bin/aws --version | sed -E 's/^aws\-cli\/(1|2).*/\1/')` to check the version of the AWS CLI and then display a warning.
`WARNING: AWS CLI v1 detected, some checks in opt-in region might return AccessDenied. Please consider upgrading to aws cli v2`

Ultimately aws cli v2 is the way forward, it would be interesting to add it into your roadmap.

**Comment by toniblyx** [comment]
Awesome, great work on the issue @j2clerck, I'll add this to the next version. Thanks!

**Comment by toniblyx** [comment]
The one for error handling has been fixed here https://github.com/toniblyx/prowler/commit/7b848c04c417b44b5fa7db8e4ee9a6e8af79e686

**Comment by toniblyx** [comment]
Version installation and documentation has also been updated in branch 2.7 that will be the next release.
