### ISSUE TITLE
Sending findings to Incorrect region's Security hub

### ISSUE THREAD

**Issue by Akash-bit-ebg** [toniblyx/prowler#957]
Hi,

I would like to report an issue I am facing. I am using below prowler options for check extra763 for eu-central-1 region and I am getting below error. I am not able to figure out even when I am forcing region with -r, why the findings are being sent to us-east-1 region. Can anyone advise please?
 
./prowler -r eu-central-1 -f eu-central-1 -M junit-xml,json-asff -S -c extra763

Error:
User...  is not authorized to perform: securityhub:BatchImportFindings on resource: arn:aws:securityhub:us-east-1::product/prowler/prowler

**Comment by toniblyx** [comment]
Hi @Akash-bit-ebg, apparently your command is correct, using -f option will force to send findings to that region's Security Hub. What version of Prowler are you using? Do you have Prowler enabled as integrator in eu-central-1?

**Comment by Akash-bit-ebg** [comment]
> integrator



> Hi @Akash-bit-ebg, apparently your command is correct, using -f option will force to send findings to that region's Security Hub. What version of Prowler are you using? Do you have Prowler enabled as integrator in eu-central-1?

Hi toniblyx , Thanks for replying. I am using v2.5.0-12 prowler version. I followed the workshop https://quicksight-security-dashboard.workshop.aws/ and deployed resources in eu-central-1 using CFT templates mentioned in the workshop. I did not explicitly enabled Prowler as integrator in eu-central-1. Please advise if I am missing anything. Thanks!

**Comment by toniblyx** [comment]
If you deploy all templates described in the workshop it should be enabled but please, make sure it is in Security Hub in your region by reviewing it manually, also review the command you are running prowler in CodeBuild and try to use the latest version from master which should be 2.6.1-15November2021. Thanks!

**Comment by Akash-bit-ebg** [comment]
> extra763

I checked and Prowler is integrated in eu-central-1, I am also using now latest Prowler version. I tried for a few checks like check 11, check12 the findings are being sent to eu-central-1 security hub, however when I tried for extra763 not sure why findings are getting pushed to us-east-1. Please advise if anything else need to be checked. Thanks a lot!

**Comment by toniblyx** [comment]
Just realized that check 763 has us-east-1 hardcoded... @singergs did that change 6 months ago, I don't remember why since S3 acts as a global service despite buckets are in a particular region. Can you test changing us-east-1 by $REGION in that check?

**Comment by singergs** [comment]
I took a look and I think this is the crux of the issue:
The name space for buckets is global S3 runs in each AWS region.
Since this is causing an issue and looking at it more closely it appears the change should be to remove the us-east-1 and resolve the bucket region location.

**Comment by Akash-bit-ebg** [comment]
okay thanks.. Will try that..

**Comment by toniblyx** [comment]
I think just leaving $REGION in that filed should work and also work in other partitions

**Comment by toniblyx** [comment]
Hey @Akash-bit-ebg please, let me know how it goes to fix it in the next release. Thanks.

**Comment by Akash-bit-ebg** [comment]
> Hey @Akash-bit-ebg please, let me know how it goes to fix it in the next release. Thanks.

Hey @toniblyx, Did not try this yet due to other work commitments. I had cloned https://github.com/toniblyx/prowler.git directly in codebuild to run Prowler. May try later. Thanks!

**Comment by toniblyx** [comment]
I have fixed it in devel branch 2.7 if you want to test it. Please reopen this issue if you need to.
