### ISSUE TITLE
securityhub:BatchImportFindings Issue for Cross Account

### ISSUE THREAD

**Issue by Akash-bit-ebg** [toniblyx/prowler#958]
Hello,

I am trying below test case case
- Enable Security hub in Account A and in region eu-central-1
- Install Prowler in Account A and run code build project to send the findings to Security hub in region eu-central-1
- Install Prowler in another account Account B and run code build project to send the findings to the same Security hub in region eu-central-1

Prowlers in both accounts are running with below command
./prowler -r eu-central-1 -f eu-central-1 -M junit-xml,json-asff -S -c check11

It works fine for Account A, however when Account B tried to send the finding to the same security hub, I am getting below error. 
User...... 
is not authorized to perform: securityhub:BatchImportFindings on resource: arn:aws:securityhub:eu-central-1::product/prowler/prowler

I have setup the policy in Account B as below. I thought as Security hub is region based service this should work but not able to figure out why the error. Is this because under the hood account B is also passed to Security Hub and Security Hub denies requests from any other account? Can anyone please advise if anyone has already tried this test case? Thanks!

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "securityhub:BatchImportFindings"
            ],
            "Resource": "arn:aws:securityhub:eu-central-1::product/prowler/prowler",
            "Effect": "Allow"
        }
    ]
}

**Comment by toniblyx** [comment]
Security Hub is a region based service and you can't send findings to that same security hub. It has to be its own Security Hub. What you are trying to do is not supported by security hub as far as I know.

**Comment by toniblyx** [comment]
You may need this set up https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-accounts.html

**Comment by Akash-bit-ebg** [comment]
> Security Hub is a region based service and you can't send findings to that same security hub. It has to be its own Security Hub. What you are trying to do is not supported by security hub as far as I know.

Thanks for your quick response.. Yes.. that's my point .. Security hub is a region based service and both the Prowlers are running in same region eu-central-1 though from 2 different accounts. As security hub is enabled in eu-central-1 , my understanding was it should accept the findings from both accounts as they are in same region as the security hub. If not, does that mean security hub must be enabled in every account ?

**Comment by Akash-bit-ebg** [comment]
> You may need this set up https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-accounts.html

I had gone through this, however this says to enable security hub in every account including members accounts and our requirement is to enable security hub in just one account in eu-central-1 and run the Prowlers in all accounts to send the findings of eu-central-1 to single security hub for the respective region.

**Comment by toniblyx** [comment]
Unfortunately it is not allowed what you want to do with Security Hub at this point. In order to have a hub and spoke architecture with Security Hub you have to enable it in all accounts.

**Comment by toniblyx** [comment]
Since this is not a Prowler issue but a Security Hub "expected feature", I'm closing it. Please feel free to reopen it or open a new one if you find other issues in this integration. Thanks.
