### ISSUE TITLE
Misleading error message: WARNING! ERROR! Use a valid check name (i.e. check41 or extra71)

### ISSUE THREAD

**Issue by bhardwajhack** [toniblyx/prowler#962]
Hi,

Issue:
If i use numbers of checks in with -c then unable to find invalid check due to misleading error message.
Misleading  message is a check is invalid or not supported : WARNING! ERROR! Use a valid check name (i.e. check41 or extra71)

**Prowler version:** 2.6.1
I have an **invalid check** "check976".
**command :**
```
./prowler  -M json -c check976 -F xyzReport -z
```
**Partial output:**
```
**WARNING! ERROR! Use a valid check name (i.e. check41 or extra71)**
```

**Message should be like:** WARNING! ERROR! Invalid check "check976", Use a valid check name.

**Comment by toniblyx** [comment]
Hello, @bhardwajhack, `check976` is not a valid check name, there is not such a check id like `check976`, is it a typo or are you actually using that check id?

**Comment by bhardwajhack** [comment]
Hi, @toniblyx,

Yes, check976 is invalid. It is intentional to replicate the issue.
I am using prowler with -c with more than 50 checks and I did a typo then prowler resolved in a error [WARNING! ERROR! Use a valid check name (i.e. check41 or extra71)]. But I was unable to find the check id in which i got this error. Error message should have check id to identify the malicious check id.

**Issue: 2**
Recently I found another bug:
For check Id > 7.## prefix 'check' and 'extra' both are allowed?

check Id : 7147 can be written as **check7147** and **extra7147** and prowler will detect the check id and should give the proper result.

Below command is not giving any error. but instead of **check7147** it is checking for **check7142**
```
./prowler  -M json -c check7147
```
Below command is giving proper result.
```
./prowler  -M json -c extra7147
```

**Comment by toniblyx** [comment]
If you paste here yuor command I may be able to help with the typo. In any case, yes, you can use checkNNN or extraNNN for extras as they have the `CHECK_ALTERNATE_xxxx` variable set up on each check file.

**Comment by toniblyx** [comment]
about 7147, there is a bug, see? `CHECK_ALTERNATE_check7147="extra7142"` 

thanks for the heads up, I'm going to fix it now in devel branch 2.7.

**Comment by bhardwajhack** [comment]
@toniblyx

Suggestion: It will be very helpful if the error message contain invalid code.
example: WARNING! ERROR! Invalid check "check976", Use a valid check name (i.e. check41 or extra71)

Thanks for the quick response.
I have fixed it in my local copy of prowler :)

**Comment by toniblyx** [comment]
done, thanks for the suggestion. I did the same to the group option as well.
