### ISSUE TITLE
extra792 - parse error: Invalid numeric literal at line 1, column 4

### ISSUE THREAD

**Issue by caseybecking** [toniblyx/prowler#963]
Check extra792 is giving the error of 'parse error: Invalid numeric literal at line 1, column 4' I'm not sure why this is?

**Comment by caseybecking** [comment]
This issue was solved by removing the --output text in my configuration file, may be worth forcing the output and not assuming json.

**Comment by toniblyx** [comment]
Done, now it forces json in those queries. Thanks!
