### ISSUE TITLE
False positive with checks 41 and 42 when using GRE as IpProtocol ("IpProtocol": "47")

### ISSUE THREAD

**Issue by StephenKing** [toniblyx/prowler#964]
I noticed that the following rules

> [check41] Ensure no security groups allow ingress from 0.0.0.0/0 or ::/0 to port 22
> [check42] Ensure no security groups allow ingress from 0.0.0.0/0 or ::/0 to port 3389

are triggering a FAIL, even though this port is not opened directly.

However, the SG has "only" GRE (protocol 47) open to 0.0.0.0.

I'm wondering, whether this is intended.

<img width="1301" alt="Screenshot AWS Console showing a security group with GRE(47) open from 0.0.0.0/0" src="https://user-images.githubusercontent.com/277561/145481924-6b527b6e-b262-4417-a404-8d2a0e03e839.png">
<img width="1493" alt="Screenshot of prowler output showing check41 FAIL for this SG" src="https://user-images.githubusercontent.com/277561/145481951-cd57e511-dc1a-4ee7-a85a-fd25501ba60b.png">

**Comment by toniblyx** [comment]
Thanks @StephenKing I have reproduced the issue and I can confirm this wrong behavior. I played a little bit narrow down the query but I don't quite get it.
```
aws ec2 describe-security-groups --query 'SecurityGroups[?length(IpPermissions[?((IpProtocol==`tcp` || IpProtocol==`-1`) && (FromPort==null && ToPort==null) || (FromPort<=`22` && ToPort>=`22`)) && (contains(IpRanges[].CidrIp, `0.0.0.0/0`) || contains(Ipv6Ranges[].CidrIpv6, `::/0`))]) > `0`].{GroupId:GroupId}' --profile default --region eu-west-1 --output text
```

Adding `(IpProtocol==`tcp` || IpProtocol==`-1`)` should make the trick, I have created 3 SGs, one like yours (`IpPermissions.IpProtocol==47`), another one with explicit 22 TCP open to the world (`IpPermissions.IpProtocol==tcp`) and another one with all open to all (`IpPermissions.IpProtocol==-1`) but only catches the explicit rule `tcp` not the `-1`. 

Can you play with that query and see how to make it more accurate? Thanks!

**Comment by StephenKing** [comment]
Thanks for the swift feedback!

I compared the number of findings with and without that. Once I use the new query, then it included me this one (a little adjusted.. nobody knows why..) _default_ security group. But that should be flagged as FAIL.

![Screenshot 2021-12-10 at 11 40 32](https://user-images.githubusercontent.com/277561/145561414-87852626-4ac9-4bbe-991e-a91824b67532.png)

**Comment by StephenKing** [comment]
But in general, I confirm that it resolves the problem 👍

**Comment by toniblyx** [comment]
have you tested it with all possible cases? as I mentioned with SGs with any protocol allowed or just SSH allowed to all

**Comment by StephenKing** [comment]
I had checked the modification that you made above and reviewed in one region, how it differs.

But I think above example is showing that the "all open" case isn't caught anymore.

**Comment by toniblyx** [comment]
yep, that condition `` IpProtocol==`-1`` is not working as expected...

**Comment by n4ch04** [comment]
Hi @StephenKing I've been checking this in different regions and checks 41 and 42 detects all open case 
![image](https://user-images.githubusercontent.com/59198746/152790265-65f7acc6-66b2-4e06-b91f-b11585f3a341.png)

![image](https://user-images.githubusercontent.com/59198746/152790497-23a256b5-c5dc-4a14-a208-eea2d1e8a70f.png)
![image](https://user-images.githubusercontent.com/59198746/152790628-c6bf1d28-4652-41fd-80c1-8f078242894c.png)


Could you check it again, it's working fine for me

**Comment by n4ch04** [comment]
Checking right now GRE case, it's returning a false positive

**Comment by jfagoagas** [comment]
@StephenKing Please, check this PR https://github.com/prowler-cloud/prowler/pull/1035

Could you test it agains this branch?

Thanks!

**Comment by n4ch04** [comment]
Since it only needs to detect tcp ports 22 and 3389 it has been added a filter by protocol filtering by tcp

**Comment by StephenKing** [comment]
thanks @jfagoagas for the fix, that looks good to me

**Comment by n4ch04** [comment]
Merging and closing it
