### ISSUE TITLE
Docker usage when access to the output folder is required

### ISSUE THREAD

**Issue by GuyManDude** [toniblyx/prowler#965]
I have Prowler running on Ubuntu.  My command uses the -M flag to get HTML and CSV output files but I cannot find the output folder.

Where would it be please?

**Comment by toniblyx** [comment]
can you describe how did you install prowler and how are you running it exactly? the output folder must be in the same folder from where you run `./prowler`

**Comment by GuyManDude** [comment]
Thanks for the prompt follow-up.   The prowler directory is in the home folder of the user running it.  I am using Docker to run it.  Here is the command I used:

sudo docker run -ti --rm --name prowler --env AWS_ACCESS_KEY_ID --env AWS_SECRET_ACCESS_KEY --env AWS_SESSION_TOKEN toniblyx/prowler:latest -r us-west-2 -n -b -q -g hipaa -M csv,json,html

**Comment by toniblyx** [comment]
Hi @GuyManDude, that's because the output folder is inside the container not in your host so you have to use volumes. Here is an example:
```
docker run -ti --rm -v /tmp/issue965/output:/prowler/output --name prowler \
--env AWS_ACCESS_KEY_ID --env AWS_SECRET_ACCESS_KEY --env AWS_SESSION_TOKEN \
toniblyx/prowler:latest -r us-west-2 -n -b -q -g hipaa -M csv,json,html
```
Then you can go to your local `/tmp/issue965/output` folder and will see those reports created.

**Comment by toniblyx** [comment]
I have added an example to the README.md in the latest commit 0c7adae3cd4c38f93ff878691cc1f1543003e71a

**Comment by GuyManDude** [comment]
Hi Toni.  I tried running your suggested command and I'm just getting a ton of permission denied output like so:

./include/outputs: line 208: ./output/prowler-output-205134639408-20211213180550.csv: Permission denied

Not sure if it's write permissions on the /tmp/issue965 directory and if so how to fix it.

**Comment by toniblyx** [comment]
That seems to be related to your OS or permissions in there. Try to use some folder inside your home folder instead of /tmp to test it.

**Comment by GuyManDude** [comment]
Hi Tony.  I couldn't get it to run without permissions problems.  It appeared to be a problem with the user account creation code so I ended up creating the user manually. 

sudo addgroup -gid 34000 prowler
sudo adduser --shell /bin/sh --ingroup prowler --disabled-password --uid 34000 prowler

Here is the successful run command:
sudo docker run -ti --rm -v /home/prowler:/prowler/output --name prowler --user 34000 --env AWS_ACCESS_KEY_ID --env AWS_SECRET_ACCESS_KEY --env

**Comment by toniblyx** [comment]
Ok thanks for let me know, it seems to be part of the hardening defaults of docker in your operating system.  If it is solved now we can close this issue, can´t we?

**Comment by GrahamLea** [comment]
Just dropping a comment in case it helps anyone who comes through here.

I was getting lots of `Permission denied` errors when trying to run with Docker to create CSV and HTML output files.
My issue was that I was giving `docker` a relative directory (`-v output:/prowler/output`) but it appears that it requires an absolute path (`-v $(pwd)/output:/prowler/output`)
