### ISSUE TITLE
Trused advisor checks fail if the default region in the profile is not the one expected

### ISSUE THREAD

**Issue by prmarino1m** [toniblyx/prowler#967]
depending on the partition ( US gov cloud, standard or china) a different region must be used for trusted advisor checks.
that said the checks for trusted advisor use whatever is set as the default in the profile. this can cause the following errors

For standard AWS the endpoint should be /support.us-east-1.amazonaws.com
For US Gov Cloud the endpoint it should be support.us-gov-west-1.amazonaws.com

the partition can be determind vi a the get_partition_for_region call in boto3 https://boto3.amazonaws.com/v1/documentation/api/latest/reference/core/session.html using the default region then making the calls to the correct endpoint for that partition.

7.26 [extra726] Check Trusted Advisor for errors and warnings - trustedadvisor [Medium]

Could not connect to the endpoint URL: "https://support.us-east-2.amazonaws.com/"

Could not connect to the endpoint URL: "https://support.us-east-2.amazonaws.com/"

Could not connect to the endpoint URL: "https://support.us-east-2.amazonaws.com/"

Could not connect to the endpoint URL: "https://support.us-east-2.amazonaws.com/"

Could not connect to the endpoint URL: "https://support.us-east-2.amazonaws.com/"

Could not connect to the endpoint URL: "https://support.us-east-2.amazonaws.com/"

Could not connect to the endpoint URL: "https://support.us-east-2.amazonaws.com/"

Could not connect to the endpoint URL: "https://support.us-east-2.amazonaws.com/"

Could not connect to the endpoint URL: "https://support.us-east-2.amazonaws.com/"

Could not connect to the endpoint URL: "https://support.us-east-2.amazonaws.com/"

Could not connect to the endpoint URL: "https://support.us-east-2.amazonaws.com/"

Could not connect to the endpoint URL: "https://support.us-east-2.amazonaws.com/"

Could not connect to the endpoint URL: "https://support.us-east-2.amazonaws.com/"

Could not connect to the endpoint URL: "https://support.us-east-2.amazonaws.com/"

Could not connect to the endpoint URL: "https://support.us-east-2.amazonaws.com/"

Could not connect to the endpoint URL: "https://support.us-east-2.amazonaws.com/"

**Comment by toniblyx** [comment]
Thanks for the heads up @prmarino1m, could you please share what command are you using for each case? For those checks pretty tight to a region, in most cases, `-r region` must be used to force where all calls are going. For example, I'm testing it with commercial with no region set up in `~/.aws/config` and I get the same error as you show here. So I have to specify `-r us-east-1` to make it work properly. For GovCloud you have to use `-r us-gov-west-1`. Let me know if it works.

**Comment by jfagoagas** [comment]
Hi @prmarino1m, could you please share what commands are you using for each failing case?

We are investigating it in order to fix it or define the cocrrect way to execute this check.

Thank you!

**Comment by jfagoagas** [comment]
We are closing this issue. Feel free to reopen it if you can provide us more information.

Thank you.

**Comment by prmarino1m** [comment]
@jfagoagas  Sorry for the delayed response here are the options i used in prowler "-M html,csv,text -p <ProfileName> -r us-gov-west-1" that produced this output. Also the default region set in the profile was us-gov-west-1

Also as i pointed out this can be avoided if prowler

**Comment by jfagoagas** [comment]
Thank you @prmarino1m , we're investigating it.

**Comment by toniblyx** [comment]
The way this check extra726 is written it takes region from the command line and if in your case it is getting us-east-2 it is because you probably are running an old version of prowler since that is not even the default commercial region. Please test the latest release or the master repo code with `-M html,csv,text -p -r us-gov-west-1 -f us-gov-west-1` or even for both gov regions `-M html,csv,text -p -r us-gov-west-1 -f 'us-gov-west-1 us-gov-east-1'`. We don't have a way to test GovCloud at this moment so please let us know if that works.

**Comment by MrCloudSec** [comment]
We are closing this issue since we didn't have any feedback. Please, feel free to reopen it if you have any comment.
