### ISSUE TITLE
Custom checks not working as expected

### ISSUE THREAD

**Issue by DB-Vincent** [toniblyx/prowler#968]
Hi all,

I'm having a bit of trouble getting custom checks to work on Prowler v2.7.0-1December2021.

**Issue one:**
I've defined a few custom checks in a directory called 'custom-checks'.
All checks in this directory are part of a custom group called 'custom-group'.

When I execute `./prowler -x ./custom-checks/ -g custom-checks -M html -p baseAccount -r eu-west-1 -A targetAccountId -R targetAccountRole -f eu-west-1`, the command execute successfully, the information gets displayed on the screen and inside the resulting HTML document. The only issue is that the check's information does not get displayed on the screen, which may be just a visual bug but which is very usefull when executing checks.

Screenshot:
![screenshot1](https://user-images.githubusercontent.com/48948316/145998996-af7c11ba-3bf4-4602-922b-4d0567e12f3c.png)

**Issue two:**
When executing the same command, with the `-s` parameter I should be able to get a score (percentage of how many resources passed my checks?), but instead I'm getting 0% consistently as you can see in the following screenshot.
![screenshot2](https://user-images.githubusercontent.com/48948316/145999757-26314a13-5592-4431-bd09-1907f9e8d5a1.png)

Hopefully I can help finding a solution to both these issues.

Kind regards.

**Comment by toniblyx** [comment]
Thanks @DB-Vincent I will test that and let you know what is going on.

**Comment by jfagoagas** [comment]
Hi @DB-Vincent,

I can't reproduce the issue.

Can you provide us more information about it? Also, please test it against branch 2.7 because maybe one of the included fixes will solve it.

Thank you!

**Comment by jfagoagas** [comment]
We are closing this issue. Feel free to reopen it if you can provide us more information.

Thank you.

**Comment by DB-Vincent** [comment]
Hey @jfagoagas,

Sorry for the late response but I've been busy with other assignments.
I've tried it out with the latest code in the 2.7 branch and it looks like the issue has been resolved.

Thank you!
