### ISSUE TITLE
Check 2.3 Bucket - Access Denied assumes set bucket to public

### ISSUE THREAD

**Issue by brendan-s1** [toniblyx/prowler#971]
I feel rule 2.3 _([check23] Ensure the S3 bucket CloudTrail logs to is not publicly accessible)_  should take into consideration Control Tower and the out-of-the-box configuration it comes with.

- Control Tower keeps its cloudtrail s3 bucket in a separate Log Archive account by default, with SCPs which disallow access to any metadata about the bucket except from the Log Archive account. 
- This rule falsely equivalates lack of metadata access with the bucket being set to public.

In my opinion, there should be a medium severity rule for inaccessible buckets, and a high for buckets which are actually set to public.

**Comment by toniblyx** [comment]
Hi @brendan-s1, thanks for the heads up. Currently Prowler doesn't support conditional severity. What could be done though is to detect that use case (Control Tower type of deployments).

**Comment by toniblyx** [comment]
or mark it as warning or info instead?

**Comment by brendan-s1** [comment]
Yeah i mean, honestly, i think `accessdenied` on any resourced based policy type assets deserves its own warning rule itself. Because that could be used as a method for persistence against the owner of the account to hide their activity.

That being said, for this one, i think it should only look for public block off and prioritize it accordingly. If it gets access denied, it is ignored from this rule.

My .02

**Comment by toniblyx** [comment]
hey @brendan-s1, I was thinking about this issue and I wonder if you has seen the whitelist feature. This is a good use case for these kind of check findings, isn't it? Please, let me know your thoughts.

**Comment by brendan-s1** [comment]
@toniblyx - yeah I've considered it. 

As you know - resources policies can be used for both good and evil. If someone was shooting for persistence and stealth, there are very few better ways to do it than reduce a resource policy down to the malicious user and deny everyone else from seeing inside of it. Which is why i feel there should be a separate rule for those types of assets and to investigate those AccessDenied assets.

That in conjunction with a whitelist makes complete sense to me. Because there will be assets with resource policies set to owner only (thereby blocking the prowler role from seeing inside of it..) so having a whitelist for those we expect to deny access makes complete sense.

However, for this particular issue, AccessDenied is assuming a public bucket. Which i guess could make sense if you don't know the status, to assume the worst.

Hmm. This is tough one. To create a special rule for AccessDenied or not?

**Comment by toniblyx** [comment]
Now Prowler mark as INFO when has no permissions to check something.
