### ISSUE TITLE
Unable to run on Windows 

### ISSUE THREAD

**Issue by diyarit** [toniblyx/prowler#985]
Hi there,

I'm trying to run the tool on windows machine but it's not working "not recognizing" the extension any idea how I can make it work?

Thanks in Advance

**Comment by toniblyx** [comment]
Hi @diyarit you need to use Ubuntu on Windows Subsystem for Linux (WSL) https://ubuntu.com/wsl or Cygwin

**Comment by toniblyx** [comment]
I'm going to close this issue if there are no further questions. Feel free to reopen it if you need help.
