### ISSUE TITLE
checks 7.122 and 7.116 fail due to Missing Glue permissions

### ISSUE THREAD

**Issue by Jae-Danner** [toniblyx/prowler#988]
prowler returns these errors:

7.122 [extra7122] Check if Glue ETL Jobs have Job bookmark encryption enabled. - glue [Medium]
An error occurred (AccessDeniedException) when calling the GetSecurityConfiguration operation: User: arn:aws:sts::XXXXXXXXXXXX:assumed-role/ProwlerExecRole/prowler is not authorized to perform: glue:GetSecurityConfiguration because no identity-based policy allows the glue:GetSecurityConfiguration action

7.116 [extra7116] Check if Glue data catalog settings have metadata encryption enabled. - glue [Medium]
An error occurred (AccessDeniedException) when calling the SearchTables operation: User: arn:aws:sts::XXXXXXXXXXXX:assumed-role/ProwlerExecRole/prowler is not authorized to perform: glue:SearchTables on resource: arn:aws:glue:us-east-1:XXXXXXXXXXX

the permssions glue:SearchTables and glue:GetSecurityConfiguration need to be added to the configuration files create_role_to_assume_cfn.yaml and prowler-additions-policy.json located in prowler/iam.

**Comment by jfagoagas** [comment]
HI @Jae-Danner,

With the above message we can't identify what's happening.

Please, try to execute Prowler with the following `bash -x ./prowler -options > debug.log 2>&1` then attach here `debug.log`


Also, complete the following information:

From where are you running Prowler?
 - Resource: [e.g. EC2 instance, Fargate task, Docker container manually, EKS, Cloud9, CodeBuild, workstation, etc.)  
 - OS: [e.g. Amazon Linux 2, Mac, Alpine, Windows, etc. ]
 - AWS-CLI Version [`aws --version`]:
 - Prowler Version [`./prowler -V`]:
 - Shell and version:
 - Others:

**Comment by toniblyx** [comment]
Thanks @Jae-Danner, `glue:SearchTables`  is already in there for next release 2.7 (in a branch so far), we´ll add `glue:GetSecurityConfiguration` as well.

**Comment by toniblyx** [comment]
we can close this one now since has been fixed in PR #995 currently in branch 2.7.
