### ISSUE TITLE
Assume role not working with profile option

### ISSUE THREAD

**Issue by lazize** [toniblyx/prowler#993]
Hi,

I am trying to run prowler on several accounts using assume-role options (-A and -R).  
To debug the issue I added an echo command when it runs `aws sts assume-role` command.  
As you can see below it uses my profile `myprofile` on the first command, but it is missing on the last one.  
Due to this, it is failing to assume the role, because it is using my `default` profile, not the one I set.

PS: I masked my account numbers and user details.

```shell
20:18 $ ./prowler -p myprofile -f 'sa-east-1' -A xxxxxxxx1531 -R ProwlerExecRole
                          _
  _ __  _ __ _____      _| | ___ _ __
 | '_ \| '__/ _ \ \ /\ / / |/ _ \ '__|
 | |_) | | | (_) \ V  V /| |  __/ |
 | .__/|_|  \___/ \_/\_/ |_|\___|_|v2.6.1-15November2021
 |_| the handy cloud security tool

 Date: Tue Jan 18 20:20:44 -03 2022

 Color code for results:
 -  INFO (Information)
 -  PASS (Recommended value)
 -  WARNING (Ignored by whitelist)
 -  FAIL (Fix required)

 This report is being generated using credentials below:

 AWS-CLI Profile: [myprofile] AWS API Region: [sa-east-1] AWS Filter Region: [sa-east-1]
 AWS Account: [xxxxxxxx1531] UserId: [AROAxxxxxxxxxx:yyyyyy]
 Caller Identity ARN: [arn:aws:sts::xxxxxxxx4909:assumed-role/xxxxxxx/xxxxxxxx]

/usr/local/bin/aws --profile myprofile sts assume-role --role-arn arn:aws:iam::xxxxxxxx1531:role/ProwlerExecRole             --role-session-name ProwlerAssessmentSession             --region sa-east-1             --duration-seconds 3600 > /var/folders/7x/pptlnssj6cd91gg_c7wc09v8zptv_f/T/prowler.sts_assumed-XXXXXX.5qgjA8ug 2>&1
1.0 Identity and Access Management - CIS only - [group1] *********** -  []
/usr/local/bin/aws  sts assume-role --role-arn arn:aws:iam::xxxxxxxx1531:role/ProwlerExecRole             --role-session-name ProwlerAssessmentSession             --region sa-east-1             --duration-seconds 3600 > /var/folders/7x/pptlnssj6cd91gg_c7wc09v8zptv_f/T/prowler.sts_assumed-XXXXXX.f1MAMem6 2>&1
       WARNING! Access Denied assuming role arn:aws:iam::xxxxxxxx1531:role/ProwlerExecRole
```

If I run AWS CLI assume-role command with this profile set, it works fine. See it below

```shell
20:46 $ aws --profile myprofile sts assume-role --role-arn arn:aws:iam::xxxxxxxx1531:role/ProwlerExecRole --role-session-name ProwlerAssessmentSession --region sa-east-1 --duration-seconds 3600
{
    "Credentials": {
        "AccessKeyId": "ASIAxxxxx",
        "SecretAccessKey": "b9exxxxx",
        "SessionToken": "IQoJb3xxxxxxxxxxxxxreAeLElvM=",
        "Expiration": "2022-01-19T00:46:57+00:00"
    },
    "AssumedRoleUser": {
        "AssumedRoleId": "AROAxxxxxxxxxx:ProwlerAssessmentSession",
        "Arn": "arn:aws:sts::xxxxxxxx1531:assumed-role/ProwlerExecRole/ProwlerAssessmentSession"
    }
}
```

**Comment by lazize** [comment]
Due to this issue on my environment I found two possible bugs. Please help me to confirm, and if it is the case I can post a PR to fix it.

On file `prowler` at line 641 we have the code below:
```shell
# Gather account data / test aws cli connectivity
getWhoami
if [[ $ACCOUNT_TO_ASSUME ]]; then
  assume_role
fi
```

So when assume-role options is set (-A and -R), variable `$ACCOUNT_TO_ASSUME` will have value and it will go inside this if statement.
`assume_role` function is inside file `include/assume_role`, which will assume role specified using the correct profile configuration.

Here is the first possible bug, inside function `assume_role` it clean variables `PROFILE` and `PROFILE_OPT` at line 82.  
As those variables are empty after the first `assume_role` execution, it will prevent this function to works with profile defined on argument `-p` if invoked again.

```shell
    # The profile shouldn't be used for CLI
    PROFILE=""
    PROFILE_OPT=""
```

Yes, it need to be empty after assume-role, otherwise future executions of AWS CLI will keep using profile option, not assumed role environment variables.

But it needs to keep track of profile variables, so when `assume_role` function is invoke again it will run AWS CLI assume-role command with proper profile variables defined, not an empty ones.

----

On file `prowler` is has a function called `execute_check`.  At the beginning of the function it has the code below.

```shell
# Function to execute the check
execute_check() {

  if [[ $ACCOUNT_TO_ASSUME ]]; then
    # Following logic looks for time remaining in the session and review it
    # if it is less than 600 seconds, 10 minutes.
    CURRENT_TIMESTAMP=$(date -u "+%s")
    SESSION_TIME_REMAINING=$(expr $AWS_SESSION_EXPIRATION - $CURRENT_TIMESTAMP)
    MINIMUM_REMAINING_TIME_ALLOWED="600"
    if [[ $MINIMUM_REMAINING_TIME_ALLOWED > $SESSION_TIME_REMAINING ]]; then
      echo "#### $MINIMUM_REMAINING_TIME_ALLOWED > $SESSION_TIME_REMAINING"
      unset AWS_ACCESS_KEY_ID
      unset AWS_SECRET_ACCESS_KEY
      unset AWS_SESSION_TOKEN
      assume_role
    fi
  fi
```

Notice that I added the line `echo "#### $MINIMUM_REMAINING_TIME_ALLOWED > $SESSION_TIME_REMAINING"` **inside** the if statement. So it should only echo my line when it goes inside the if condition. See my execution below.

```shell
22:35 $ ./prowler -p myprofile -f 'sa-east-1' -A xxxxxxxx1531 -R ProwlerExecRole
                          _
  _ __  _ __ _____      _| | ___ _ __
 | '_ \| '__/ _ \ \ /\ / / |/ _ \ '__|
 | |_) | | | (_) \ V  V /| |  __/ |
 | .__/|_|  \___/ \_/\_/ |_|\___|_|v2.6.1-15November2021
 |_| the handy cloud security tool

 Date: Tue Jan 18 22:57:51 -03 2022

 Color code for results:
 -  INFO (Information)
 -  PASS (Recommended value)
 -  WARNING (Ignored by whitelist)
 -  FAIL (Fix required)

 This report is being generated using credentials below:

 AWS-CLI Profile: [myprofile] AWS API Region: [sa-east-1] AWS Filter Region: [sa-east-1]
 AWS Account: [xxxxxxxx1531] UserId: [AROAxxxxxxx:xxxxxx]
 Caller Identity ARN: [arn:aws:sts::xxxxxxxx4909:assumed-role/xxxxx/xxxxxx]

1.0 Identity and Access Management - CIS only - [group1] *********** -  []
#### 600 > 3598
       WARNING! Access Denied assuming role arn:aws:iam::xxxxxxxx1531:role/ProwlerExecRole
```

Here is the possible second bug. The code executed my `echo` line, even when 600 **is not** greater than 3598.

This explain why on my original post, we see two assume-role executions. When we have assume-role options defined (-A and -R) it will ALWAYS assume-role again inside `execute_check` function. Even when remaining time is bigger than minimum time allowed.

As it uses `>` (greater than) sign, it is comparing both variables as string, not as number. If we change the condition to `-gt` it works as expected. See it below.

```shell
23:11 $ if [[ 600 > 3598 ]]; then echo "TRUE condition"; else echo "ELSE condition"; fi
TRUE condition
23:22 $ if [[ 600 -gt 3598 ]]; then echo "TRUE condition"; else echo "ELSE condition"; fi
ELSE condition
```

**Comment by toniblyx** [comment]
Hi @lazize, we have made few changes in that logic in the devel branch 2.7, could you test it and see if the error still the same?

**Comment by lazize** [comment]
Using branch version 2.7 fixed all issues I pointed originally. So using profile (-p) and assume role (-A and -R) it works as expected and when it needs to renew token, doing assume_role again, it also uses the profile I defined.

To test when it needs to renew token I defined the token time to just 900, so wit will force to renew token often. Like below:
```shell
./prowler -p myprofile -A xxxxxxxx1531 -R ProwlerExecRole -T 900
```

When I run this version with credentials from environment variables and without profile (-p) it fails to run assume_role on the second time. It tries to use credentials from my default profile, not the ones from original environment variables.

The last assume role is using credentials from account final 5262, which is configured under my default profile, but it should be using credentials from account final 4909, as stated on called identity.

Output truncated for brevity.

```shell
13:34 $ ./prowler -A xxxxxxxx1531 -R ProwlerExecRole -T 900
                          _
  _ __  _ __ _____      _| | ___ _ __
 | '_ \| '__/ _ \ \ /\ / / |/ _ \ '__|
 | |_) | | | (_) \ V  V /| |  __/ |
 | .__/|_|  \___/ \_/\_/ |_|\___|_|v2.7.0-6January2022
 |_| the handy cloud security tool

 Date: Wed Jan 19 13:34:18 -03 2022

 Color code for results:
 -  INFO (Information)
 -  PASS (Recommended value)
 -  WARNING (Ignored by whitelist)
 -  FAIL (Fix required)

 This report is being generated using credentials below:

 AWS-CLI Profile: [ENV] AWS API Region: [sa-east-1] AWS Filter Region: [all]
 AWS Account: [xxxxxxxx1531] UserId: [AROAxxxxxx:xxxxxx]
 Caller Identity ARN: [arn:aws:sts::xxxxxxxx4909:assumed-role/xxxxxxxx/xxxxx]

#####  /usr/local/bin/aws  sts assume-role --role-arn arn:aws:iam::xxxxxx1531:role/ProwlerExecRole             --role-session-name ProwlerAssessmentSession             --duration-seconds 900             --region sa-east-1             "" > /var/folders/7x/pptlnssj6cd91gg_c7wc09v8zptv_f/T/prowler.sts_assumed-XXXXXX.HKXLXize 2>"/var/folders/7x/pptlnssj6cd91gg_c7wc09v8zptv_f/T/prowler.sts_assumed-XXXXXX.SY8TcoXf"
1.0 Identity and Access Management - CIS only - [group1] *********** -  []
 Generating AWS IAM Credential Report... -  []
...............
#####  /usr/local/bin/aws  sts assume-role --role-arn arn:aws:iam::xxxxxxxx1531:role/ProwlerExecRole             --role-session-name ProwlerAssessmentSession             --duration-seconds 900             --region sa-east-1             "" > /var/folders/7x/pptlnssj6cd91gg_c7wc09v8zptv_f/T/prowler.sts_assumed-XXXXXX.BwefDvJt 2>"/var/folders/7x/pptlnssj6cd91gg_c7wc09v8zptv_f/T/prowler.sts_assumed-XXXXXX.AW3AFJOT"
       WARNING!  An error occurred (AccessDenied) when calling the AssumeRole operation: User: arn:aws:sts::xxxxxxxx5262:assumed-role/xxxxxx/xxxxx is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::xxxxxxxx1531:role/ProwlerExecRole
```

**Comment by toniblyx** [comment]
Thanks @lazize, let me see if I understood correctly what is going on now with 2.7 branch.

You have 3 accounts involved in this issue. 
- Account A (`*5262`): the account you have locally configured as `default` profile in your aws/credentials file.
- Account B (`*4909`): the account you have locally configured as `myprofile` profile in your aws/credentials file.
- Account C (`*1531`): the account you want to actually scan assuming the role in there. 

When you run prowler as `./prowler -p myprofile -A xxxxxxxx1531 -R ProwlerExecRole -T 900`, when prowler renews session credentials it tries to do so using `default` instead of `myprofile`. Am I correct?

If you see the new logic in file prowler/assume_role, there are two new functions fo backup and restore initial credentials, those functions are making `printenv AWS_ACCESS_KEY_ID` etc, is by any chance your default profile credentials as environment credentials? You can see them by running `env` or `printenv`.

**Comment by lazize** [comment]
@toniblyx  That is correct

> You have 3 accounts involved in this issue.
> 
> Account A (*5262): the account you have locally configured as default profile in your aws/credentials file.
> Account B (*4909): the account you have locally configured as myprofile profile in your aws/credentials file.
> Account C (*1531): the account you want to actually scan assuming the role in there.

Not correct, when I run with profile (-p myprofile) it works fine and renews credential correctly using `-p myprofile`.

> When you run prowler as ./prowler -p myprofile -A xxxxxxxx1531 -R ProwlerExecRole -T 900, when prowler renews session credentials it tries to do so using default instead of myprofile. Am I correct?

But when I run with credential from environment variables, it fails to renew using the original environment variables.

----

Function `restoreInitialAWSCredentials` is used only on some cases, but not in general when function `execute_all` is executed.

This function should be used in the beginning o `assume_role` function. The same way it handles `PROFILE_OPT`. In this way it will always restore original credentials before assume-role.

```shell
assume_role(){

    PROFILE_OPT=$PROFILE_OPT_BAK

```

**Comment by toniblyx** [comment]
Gotcha! Thanks for clarifying! We will see how to fix it, feel free to send a fix if you can make it quicker.

**Comment by lazize** [comment]
@toniblyx my quick fix works fine on my use cases explained in this issue, but I am not sure if it works for all other uses cases.
Is there a way to run some kind of regression test?

**Comment by toniblyx** [comment]
I think the tests you have done are the actual use cases with an additional one that is when the credentials are taken from the resource itself like an instance, container, cloudshell, etc. Using CloudShell is the quickest way to test it. So, on top of my mind, when it comes to testing the assume role capability there are 4 use cases:
1. When initial credentials are ENV variables.
2. When initial credentials are in default profile.
3. When initial credentials are in a non-default profile.
4. When initial credentials are part of the resource profile that runs Prowler (like an EC2 instance, container, CloudShell, Cloud9, CodeBuild, etc.)

**Comment by lazize** [comment]
1. PASS - When initial credentials are ENV variables.
1. PASS - When initial credentials are in default profile.
1. PASS - When initial credentials are in a non-default profile.
1. PASS - When initial credentials are part of the resource profile that runs Prowler (like an EC2 instance, container, **CloudShell**, Cloud9, CodeBuild, etc.)

**Comment by toniblyx** [comment]
Music to my ears :D thanks!
